### ISSUE TITLE
No Readme or example

### ISSUE THREAD

**Issue by wenza** [Grover-c13/PokeGOAPI-Java#1]
Hello,
could you please provide some example how to run your API? Im happy that someone is developing JAVA code for the API and I wont need to use python which Im unable to make working for missing libs. But it would be good to have some README or tutorial with example class to see how I can make it running.
Thank you

**Comment by Grover-c13** [comment]
Hey, its an early WIP, i have posted details on the pokemongo dev reddit: https://www.reddit.com/r/pokemongodev/comments/4t65mh/pokemongo_api_java_01/ with a brief example.

Will be cleaning up and expanding over the next few days.
