### ISSUE TITLE
Pokemon Data From Encounter Result

### ISSUE THREAD

**Issue by CosmoRing** [Grover-c13/PokeGOAPI-Java#100]
Is there any way to add a method to EncounterResult where it returns the pokemon information (WildPokemon and CaptureProbability) so it's possible to judge what to do before trying to catch it? 

Ex: Get the CP from the pokemon so it's possible to use different balls to catch it?

**Comment by jabbink** [comment]
@mjmfighter can you look into this and expand https://github.com/Grover-c13/PokeGOAPI-Java/blob/master/src/main/java/com/pokegoapi/api/map/Pokemon/EncounterResult.java ?

**Comment by mjmjelde** [comment]
Yes I will expand this tonight.  I thought I put a method in there to get the primitive data type, but I guess I missed it.  I will expand it though to get all the data out of it

**Comment by Grover-c13** [comment]
Added in PR #109
