### ISSUE TITLE
item interaction

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#102]
Hello,

how can i drop items on my bag?

this one seems the most probable

go.getBag().removeItem(X,1)

but it doesn't work as expected (i try to remove all pokeballs and leave 100)

**Comment by jabbink** [comment]
`go.getBag().removeItem(ItemId.ITEM_POKE_BALL,1)` does indeed remove 1 pokeball. Tested and works.

If you want to drop everything, except for 100, first get the count, and subtract 100. Drop that amount.

**Comment by ramarro123** [comment]
yeah, of course :)
that's the piece of code, Constant.max(id) will return 100 in case of pokeball...

```

 int max = Constant.max(i.getItemId());
                if (i.getCount() > max) {
                    RecycleInventoryItemResponseOuterClass.RecycleInventoryItemResponse.Result rst = go.getBag().removeItem(i.getItemId(), i.getCount() - max);
                }

```

i'll try to dig a bit more, it seems strange that it doesn't work..

should i execute a 
 go.getPlayerProfile(true);

before the operation? to get fresh data?
i had a similar problem with 
go.getPokebank().getPokemons

that doesn't auto update unless i do a go.GetPlayerProfile(true)

**Comment by ramarro123** [comment]
before server went offline i was able to test it :D 
r.i.P :)
