### ISSUE TITLE
 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by peter6006** [Grover-c13/PokeGOAPI-Java#105]
I got this error when try to run the API in Android Studio:
`java.lang.NoClassDefFoundError: okhttp3.internal.tls.OkHostnameVerifier`
in the line
`OkHttpClient httpClient = new OkHttpClient();`

In my gradle i import the corrects dependencies:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.github.Grover-c13:PokeGOAPI-Java:master-SNAPSHOT'
}
```

And in my other gradle:

```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

I spend like 4 hours finding a solution and came up with nothing, so i ask you for help.

**Comment by Grover-c13** [comment]
We use  com.squareup.okhttp3:okhttp:3.4.0-RC1, so try setting your OkHttp dependency to:     compile 'com.squareup.okhttp3:okhttp:3.4.0-RC1'

**Comment by langerhans** [comment]
Google tells me to try `minifyEnabled true` in your build.gradle.

**Comment by peter6006** [comment]
Nothing, try the 2 solutions, restart Android Studio, clean project and re-build it several times but the same error is there.
Im using Java Jdk 1.8.0_25, try also Java 7 but didnt work either.

EDIT: The problem appears when i add `compile 'com.github.Grover-c13:PokeGOAPI-Java:master-SNAPSHOT'` because i try to create a new project only with "okhttp" and works fine the imports and the `OkHttpClient httpClient = new OkHttpClient();` but i import your project and that error appears (even when i delete the "okhttp" import).
EDIT2: I update Gradle and Android Studio to the latest and still dont work, can anyone create an Android Studio project and test it?

**Comment by Aphoh** [comment]
@peter6006 what gradle version are you using?

**Comment by vmarchaud** [comment]
No news from two days, i expect you to have found the solution at your problem, re-open if its not the case.
