### ISSUE TITLE
ProfileRequest: Wrong RPC ID

### ISSUE THREAD

**Issue by PorkScripts** [Grover-c13/PokeGOAPI-Java#11]
I was having trouble retrieving the profile data and only got it to work after changing Communication.Method.GET_PLAYER_PROFILE to Communication.Method.GET_PLAYER.

I also had to change the fields from required to optional in inventory.proto under PlayerStatsProto and recompile the .java files with protoc.

**Comment by vmarchaud** [comment]
cf author in #9 

> Im swapping all the proto stuff over to proto3 tonight

I imagine the whole proto stuff would work correctly with protobuf 3

**Comment by Grover-c13** [comment]
Hi,

you are correct it is the wrong RPC id, its using GET_PLAYER_PROFILE, should be GET_PLAYER, will correct shortly.

May change names to avoid confusion in future (GET_PLAYER_PROFILE is for public stuff i think, used for Gyms etc).

**Comment by jabbink** [comment]
Oh sorry, my mistake!

Now that PR of mine works, confirmed.
