### ISSUE TITLE
don't see a license on the project

### ISSUE THREAD

**Issue by rohanjain1** [Grover-c13/PokeGOAPI-Java#110]
Guys is there a license on this project?
GPL/Apache/MIT ?
Having the license on the homepage would simplify things for people like me who are eager to play with this. :)
Cheers.

**Comment by langerhans** [comment]
Uhh it's right there: https://github.com/Grover-c13/PokeGOAPI-Java/blob/master/LICENSE.txt

**Comment by rohanjain1** [comment]
D'oh.. sorry my bad, was looking in proj info, didnt check the repo.
