### ISSUE TITLE
go.getMap().encounterPokemon deprecated

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#111]
Hello,

encounterPokemon and
catchPokemon

are deprecated, what should i use instead?

**Comment by stirante** [comment]
Use methods from CatchablePokemon. You have there catchPokemon and encounterPokemon

**Comment by ramarro123** [comment]
mo.getCatchablePokemons() return  a MapPokemon
CatchablePokemon(go, tmp).encounter.catch (more or less) am i right?

a not-totally related, i see that CatchablePokemon take also WildPokemon
what's the difference?

**Comment by Grover-c13** [comment]
WildPokemon/CatchablePokemon are pretty much the same. just distance.
You should be using map.getCatchablePokemon() and related functions.
