### ISSUE TITLE
suggestion: catchPokemon with more options

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#117]
Hi,

i see that catchPokemon support the ability to set certain pokeBall.

it will be great if you add the option for using the berry. Probably it's
already possible simply using the berry before using catchPokemon it's correct?

Also, another great options, will be (if necessary) to add the retry
feature for catchPokemon.

i think that CATCH_MISSED can be retryed, correct?
so, the correct 'flow' to catch a pokemon will be if result == CATCH_MISS catchPokemon();
or it's a final error?

so, my proposal, it's do add a method
`
catchPokemon(pokeBall,berryCt, retryCt)
`

that will use a custompokeball, a certain number of berries, and try for retryCt count.

**Comment by Grover-c13** [comment]
done in latest PR on dev branch #159
