### ISSUE TITLE
suggestion: better handling exceptions

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#118]
Right now, as we know, pokemon go server are.. well.. disappointing 💃 

while login, as opened on prev ticket we can now see

```
E/PokemonGo: Failed to get profile data and update inventory
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
```

that's a e.printStackTrace.

can i suggest to remove all the printStackTrace and replace them with throw new Throwable(something) or even better throw new CustomException, like ServerKaput!

it's useful for custom error handling & logging purpose

**Comment by Hindi** [comment]
Having an exception for wrong credentials would be nice too. The server seem to count the login failures with PTC accounts.

**Comment by jabbink** [comment]
Yeah, after 5 invalid login attempts you get banned for ~30 minutes.

**Comment by vmarchaud** [comment]
done in #220 dont hesite to make new feature request in this issue or reopen one.
