### ISSUE TITLE
PlayerStatsProto issues

### ISSUE THREAD

**Issue by blanketred** [Grover-c13/PokeGOAPI-Java#12]
except the first 4 fields are required 
the rest should be all optional. 

for example, if a player never entered any gym. His response of NumBattleAttackWon NumBattleAttackTotal etc does not exist. I have tested and confirmed.

**Comment by blanketred** [comment]
2nd issue on naming items in your bag. It's really confusing and ugly.

If you need to get item info in your bag, the code would be:
InventoryItemResponseProto item = xxx.parseFrom(yyy)
item.getItem().getItem().getItem() to get itemId
item.getItem().getItem().getCount() to get item qty

my sugguestions would be changing InventoryItemProto {
                optional ItemProto BagItem = 2;
}
and change ItemProto{
        required int32 ItemId = 1;
        required int32 ItemQty = 2;
}

**Comment by blanketred** [comment]
For each protobuff file:

put 
option java_package = "PACKAGENAME";
option java_outer_classname = "CLASSNAME";

in the first 2 lines to save time in add package names after converting to java class

**Comment by vmarchaud** [comment]
cf author in #9 

> Im swapping all the proto stuff over to proto3 tonight

I imagine the whole proto stuff would work correctly with protobuf 3

**Comment by jabbink** [comment]
Yeah, currently preparing a PR that just switches to Protobuf 3 (which everyone else seems to be using) and removing the generated code to clean up the repo.

**Comment by Grover-c13** [comment]
yeah dont ask why i was using proto2 :P

**Comment by jabbink** [comment]
Everything is using proto3 now, so this can be closed.
