### ISSUE TITLE
Pokestops should support the Active Pokemon Attribute

### ISSUE THREAD

**Issue by davidmann4** [Grover-c13/PokeGOAPI-Java#125]
**Intro**
The game offers a feature where you can buff a pokestop to lure pokemons. After you used a Module (the item which boosts a pokestop) Pokemons will show up on a regular. Modules are active for 30 minutes.

**Tech**
After you used a Module on a pokestop the pokestop will get a ActivePokemon Value. See a example below.

``` json
 {  
                    "fortId":"47b4a55ad8c54454940396aaf0601e02.16",
                     "lastModifiedMs":"1469000053563",
                     "latitude":45.030225,
                     "longitude":-93.318969,
                     "enabled":true,
                     "fortType":1,
                     "activePokemon":{  
                        "spawnpointId":"47b4a55ad8c54454940396aaf0601e02.16",
                        "encounterId":"2142514281",
                        "pokedexTypeId":"V0021_POKEMON_SPEAROW",
                        "expirationTimeMs":"1469001133514"
                     }
                  },
                  {  
                     "fortId":"5ec40620884740d98d6969e372156c5c.16",
                     "lastModifiedMs":"1468999658570",
                     "latitude":45.029967,
                     "longitude":-93.319217,
                     "enabled":true,
                     "fortType":1,
                     "activePokemon":{  
                        "spawnpointId":"5ec40620884740d98d6969e372156c5c.16",
                        "encounterId":"1178527421",
                        "pokedexTypeId":"V0013_POKEMON_WEEDLE",
                        "expirationTimeMs":"1469001098512"
                     }
                  },
```

this is something i found in the protobuf files

``` java
message PokemonFortProto {
    string FortId = 1;
    int64 LastModifiedMs = 2;
    double Latitude = 3;
    double Longitude = 4;
    int32 Team = 5;
    int32 GuardPokemonId = 6;
    int32 GuardPokemonLevel = 7;
    bool Enabled = 8;
    ENUM.Holoholo.Rpc.FortType FortType = 9;
    int64 GymPoints = 10;
    bool IsInBattle = 11;
    //unknown ActiveFortModifier = 12;
    Holoholo.Rpc.MapPokemonProto ActivePokemon = 13;
    int64 CooldownCompleteMs = 14;
    ENUM.Holoholo.Rpc.Sponsor.Types.FortSponsor.Sponsor Sponsor = 15;
    ENUM.Holoholo.Rpc.RenderingType.Types.FortRenderingType.RenderingType RenderingType = 16;
 }
```

**Comment by ramarro123** [comment]
try to do

response = stop.getDetails() (where stop ==Pokestop)
tmp = response.getModifier();
this.pokeModifier.get(0).getItemId() ..> return ITEM_TROY_DISK

there are also all other methods like
getExpirationTime,
getPlayerSomethingSomewhere...

i think that's what you need (i use it to detect pokestop in powerup mode)

**Comment by davidmann4** [comment]
Sorry I do not understand your code. I want this infos from a enhanced Pokestop:

``` json
"activePokemon":{  
                        "spawnpointId":"5ec40620884740d98d6969e372156c5c.16",
                        "encounterId":"1178527421",
                        "pokedexTypeId":"V0013_POKEMON_WEEDLE",
                        "expirationTimeMs":"1469001098512"
                     }
```

**Comment by ramarro123** [comment]
of course, you have to put some value on pokestop variable

```
   Pokestop stop = null;
        FortDetails f = stop.getDetails();
        List<FortModifierOuterClass.FortModifier> l = f.getModifier();
        for (FortModifierOuterClass.FortModifier z : l) {
            if (z.getItemId() == ItemIdOuterClass.ItemId.ITEM_TROY_DISK)
            {
                z.getExpirationTimestampMs();
                z.getDeployerPlayerCodename();
            }
        }
```

**Comment by davidmann4** [comment]
Hmm, not sure if we are talking about the same thing active Pokemons are the pokemons hanging around module boosted Pokestops(forts) not gyms

Edit: now I get it pokesstops which have an active module running can be recognized with

```
println("*** Found pokestop ${nearestUnused.first().details.modifier}") 

output:
item_id: ITEM_TROY_DISK
expiration_timestamp_ms: 1469196533466
deployer_player_codename: "Brammetjhuu1"
```

but how do we get the encounterId? I guess it is still missing in the java API

**Comment by jabbink** [comment]
Just to avoid confusion with names: in our protos `FortData` can have a [`FortLureInfo`](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Map/Fort/FortLureInfo.proto)

That one has an encounter ID so should be catchable

**Comment by davidmann4** [comment]
named pokemonData in 

https://github.com/AeonLucid/POGOProtos/blob/1b124cdbdd271a9cd6953949a74db3865a5f42a8/pogo/Networking/Responses/FortDetailsResponse.proto

```

message FortDetailsResponse {
    string fort_id = 1;
    .POGOProtos.Enums.TeamColor team_color = 2;
    .POGOProtos.Data.PokemonData pokemon_data = 3;
    string name = 4;
    repeated string image_urls = 5;
    int32 fp = 6;
    int32 stamina = 7;
    int32 max_stamina = 8;
    .POGOProtos.Map.Fort.FortType type = 9;
    double latitude = 10;
    double longitude = 11;
    string description = 12;
    repeated .POGOProtos.Map.Fort.FortModifier modifiers = 13;
}
```

seems like we only need to add this to 

https://github.com/Grover-c13/PokeGOAPI-Java/blob/181e441effd837a8b38c9268040297bba5ae706c/src/main/java/com/pokegoapi/api/map/fort/FortDetails.java

**Comment by jabbink** [comment]
Seems like @aeonlucid's https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Map/Fort/FortLureInfo.proto does not contain everything shown in https://github.com/Grover-c13/PokeGOAPI-Java/issues/125#issue-167038273 (spawnpoint ID and encounter ID)

**Comment by davidmann4** [comment]
I think there is a encounter disk packet: see https://github.com/Grover-c13/PokeGOAPI-Java/issues/204
