### ISSUE TITLE
Pokemons appear twice in the list returned by getCatchablePokemon

### ISSUE THREAD

**Issue by Hindi** [Grover-c13/PokeGOAPI-Java#132]
> List<CatchablePokemon> list = goMap.getCatchablePokemon();
> This call will return a list of pokemon where each encounter id appear twice.

**Comment by Jari27** [comment]
Second this.

**Comment by LEGENDFF** [comment]
yes, from what it looks like they only differ in expirationTimestampMs.
Example:
CatchablePokemon(api=com.pokegoapi.api.PokemonGo@71b1176b, spawnpointId=47a38d6a76b, encounterId=2820430531495793501, pokemonId=PIDGEY, expirationTimestampMs=1469208706316, latitude=50.68508210960196, longitude=10.914392030576774, encountered=false)
CatchablePokemon(api=com.pokegoapi.api.PokemonGo@71b1176b, spawnpointId=47a38d6a76b, encounterId=2820430531495793501, pokemonId=PIDGEY, expirationTimestampMs=312740, latitude=50.68508210960196, longitude=10.914392030576774, encountered=false)

**Comment by Jari27** [comment]
The first one is an absolute despawn timestamp, the the second is time until despawn. Merge them or remove one?

**Comment by Jari27** [comment]
Added a PR @ #134
