### ISSUE TITLE
CatchResult.getCapturedPokemonId() always returns 0

### ISSUE THREAD

**Issue by Hindi** [Grover-c13/PokeGOAPI-Java#133]
It is impossible to find a catched pokemon in the bag because of this issue.

**Comment by Grover-c13** [comment]
https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Responses/CatchPokemonResponse.proto

was the wrong datatype in the proto, will be fixed when we repin to a later commit of the POGOProtos
