### ISSUE TITLE
Jitpack And Gradle Not Working

### ISSUE THREAD

**Issue by jmrapp1** [Grover-c13/PokeGOAPI-Java#139]
I as well as a few others are trying to reference the project via Jitpack and gradle. It was working fine in the past, but now it seems like a version was changed or duplicated and now it's broken. We are following how to include the dependency [here](https://jitpack.io/#Grover-c13/PokeGOAPI-Java/master-SNAPSHOT). Like I said it was working in the past, but it's not anymore. We want to use gradle so that we don't have to keep updated with the source manually.

**Comment by Marrcroger** [comment]
Likewise

**Comment by vmarchaud** [comment]
like i said on slack : `we need to start versionning and publish it to maven central of smth like that`

**Comment by Marrcroger** [comment]
Using:

Compile 'com.github.Grover-c13:PokeGOAPI-Java:4f5b715380'

Instead worked for me.  
Thanks to https://github.com/omkarmoghe/Pokemap/issues/66

**Comment by jmrapp1** [comment]
Yeah that's what I've been using. Im working on the same project and we all came across that problem.

**Comment by s7092910** [comment]
@vmarchaud Might I suggest bintray for both jcenter and maven central

**Comment by comann** [comment]
Any Update Here?

**Comment by vmarchaud** [comment]
Jitpack already offer these features, you can fix your dependency to a commit or a branch (like @mroge009 last msg show), so this issue shouldnt a problem anymore.
