### ISSUE TITLE
Scope of google Token? "com.pokegoapi.exceptions.LoginFailedException"

### ISSUE THREAD

**Issue by pauloacribeiro92** [Grover-c13/PokeGOAPI-Java#140]
Can you clarify the what scope is needed in google authenticator in order to et the log in token?

My error:

```
com.pokegoapi.exceptions.LoginFailedException
W/System.err:     at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:216)
W/System.err:     at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:69)
W/System.err:     at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:57)
```

Thre line:

```

    if (responseEnvelop.getStatusCode() == 102) {
            throw new LoginFailedException();

```

and yes i have read the FAQ. Im not running this in UI thread.

My android functions: 

To get the token

```

Runnable retrieveTokenRunnable = new Runnable() {
        @Override
        public void run() {
            String scopes = "oauth2:" + Scopes.PROFILE;
            String token = null;

            try {
                Log.d("DBG", "RetrieveTokenTask email: "+mEmail);
                token = GoogleAuthUtil.getToken(getContext(), mEmail, scopes);
                Log.d("DBG", "RetrieveTokenTask token: "+token);
                loginPokemonGo(token);
            }
            catch (UserRecoverableAuthException userRecoverableException) {
                getActivity().startActivityForResult(userRecoverableException.getIntent(),USER_RECOVERABLE_AUTH);
            } catch (IOException e) {
                e.printStackTrace();
            } catch (GoogleAuthException e) {
                e.printStackTrace();
            }
        }
    };
```

To login

```
private void loginPokemonGo(String token){
        Log.d("DBG", "loginPokemonGo token: "+token);
        OkHttpClient httpClient = new OkHttpClient();
        RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo auth = new GoogleLogin(httpClient).login(token);
        PokemonGo go = null;

        try {
            go = new PokemonGo(auth,httpClient);
            Toast.makeText(getContext(), go.getPlayerProfile().toString(), Toast.LENGTH_LONG).show();
            Log.d("DBG", go.getPlayerProfile().toString());
        } catch (LoginFailedException e) {
            e.printStackTrace();
        } catch (RemoteServerException e) {
            e.printStackTrace();
        }

    }
```

**Comment by Grover-c13** [comment]
It needs to use the id_token and not the auth_token, could that be your issue?

**Comment by dtunctuncer** [comment]
i don't understand which scope we have to use

**Comment by Grover-c13** [comment]
Scopes: openid email https://www.googleapis.com/auth/userinfo.email

**Comment by rajulbhatnagar** [comment]
I am not sure why u need to set the scope anywhere if u are using the API.
`//If u dont have the refresh_token persisted yet
RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo auth = new GoogleLogin(httpClient).login();
//persist refresh_token by accessing it using GoogleLoginSecrets.refreshToken
//Subsecquent logins
RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo auth = new GoogleLogin(httpClient).login("Does not matter if u dint store tokenid","persistedrefresh_token")`

This is assuming u using the dev branch as there were API changes for refresh token functionality.

**Comment by vmarchaud** [comment]
He need it to request it in android, just check [how the the google login works](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/auth/GoogleLogin.java) and you will be able to do the same.

**Comment by rajulbhatnagar** [comment]
I dont see why u cant use the API directly in android. I am using it. 
There is also a callback that u can implement to then show the user the validationurl in a chrome custom tab to enter user code. After that u should get the required tokens.

**Comment by langerhans** [comment]
I suppose you're trying to use the native Google sign in that the native client is using. Let me save you from some pain and tell you that you can't. Google Play Services checks the calling package's signature and only if that matches to what's in the API console for that package name, then you'll be able to use the native sign in. And I suppose Niantic won't add your app to their API key ;)

**Comment by pauloacribeiro92** [comment]
yep, that the problem langerhans, thank you
