### ISSUE TITLE
Increase radius of catchable pokemons

### ISSUE THREAD

**Issue by LinkOut** [Grover-c13/PokeGOAPI-Java#146]
There is a way to increase radius of searching pokemons?
List<CatchablePokemon> catchablePokemon = pokemonGO.getMap().getCatchablePokemon();

**Comment by Grover-c13** [comment]
Not really, you will have to change location and do it again.

**Comment by vmarchaud** [comment]
To complete : we already get as much pokemon we can capture via the method `map.getCatchablePokemons()`, PokemonGo servers dont send all pokemon on earth ..

**Comment by timautin** [comment]
Please, can you tell me what is the unit of the radius? Meters, I guess? The max value is 9, isn't it?

**Comment by vmarchaud** [comment]
@timautin We are talking in S2Cell from [google lib](https://github.com/google/s2-geometry-library-java) dont know the actual size of a cell (we are using the level 15 cell btw).

**Comment by timautin** [comment]
OK I see, thanks!
