### ISSUE TITLE
hasLurePokemon() strangeness

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#149]
i probably am using it wrong...

i am doing

```
while (true) {
for (stop : go.getMap().getMapObjects().getPokestops())
   stop.hasLurePokemon();

moveABit();
sleep();
}
```

hasLurePokemon actually "blink" (not every 30 mins as expected, but every 2-3 calls)
it say that a pokestop it's in lure mode, then say that it's not in lure mode, and so on, like crazy.

i have try to disable userCache and change the mapExpire, but it doesn't help.

how am i supposed to use it?

**Comment by Jari27** [comment]
Are you sure you are using the right method, i.e. `hasLure()` vs `hasLurePokemon()`? The latter should blink.

**Comment by ramarro123** [comment]
there is no method hasLure in the current checkout

**Comment by Jari27** [comment]
I thought he'd implementend it himself, that's why. It's not weird that hasLurePokemon blinks...

**Comment by ramarro123** [comment]
can you elaborate a bit more why hasLurePokemon it's normal to blink?

i can see that it have an lureexpiresTimeout, but it should expire in 30 min... what i see it's that it blink at every 4000/5000 milliseconds

**Comment by Jari27** [comment]
hasLurePokemon() shows whether there is a pokemon there (due to a lure). I am assuming you capture those, so they dissapear.

**Comment by ramarro123** [comment]
make sense, so it will be necessary, as you said, to add a method to detect if a lure is active (but haven't lured anytihng yet)

it's always better to stay nearby a pokestop that have a lure, and wait till he lure something i think.

it is possible to see if a pokestop has a valid lure plugged on it apart query it via getDetails?

**Comment by Jari27** [comment]
The data is available but I haven't seen it in the api yet.

Edit: actually I just found `pokestop.getFortData().getLureInfo().` Maybe fiddle around with this?

**Comment by ramarro123** [comment]
pokestop.getFortData().getLureInfo()
return the same data used in hasLurePokemon, so the results will be the same (blinking)

**Comment by Pyr0x1** [comment]
I am checking if a pokestop has a lure module on it in this way and it seems working, even if I don't know what a TROY_DISK is:

```
Collection<Pokestop> pokeStops = go.getMap().getMapObjects().getPokestops();
            for (Pokestop stop : pokeStops) {
                if (stop.getId().equals(Preferences.pokestopId)) {
                    Log.i(TAG, "Found pokestop");
                    List<FortModifier> modifiers = stop.getDetails().getModifier();
                    for (FortModifier modifier : modifiers) {
                        if (modifier.getItemId().equals(ItemId.ITEM_TROY_DISK)) {
                            String message = "Found lure used by " + modifier.getDeployerPlayerCodename() + ", missing " +  (modifier.getExpirationTimestampMs() - System.currentTimeMillis()) / 60000 + " minutes before it vanishes.";
                            Log.i(TAG, message);
                        }
                    }
                }
            }
```

**Comment by jabbink** [comment]
troy disk is the lure petal animation afaik

**Comment by Grover-c13** [comment]
@Pyr0x1 does that behave consistently?

**Comment by Pyr0x1** [comment]
@Grover-c13 I tried it a few times and it was consistent with game, also the time left seemed right.

**Comment by ramarro123** [comment]
but thats not good you are going to do 1 request c each stop... so or there is a caching way to do it or we will get banned for sure :)

**Comment by ramarro123** [comment]
i have try in rome and there are too many pomeatops i am not even able to get all the details at 1 run

**Comment by Pyr0x1** [comment]
@ramarro123 I only made some "manual" experiments and didn't launch the full bot that I had in mind (mainly due to #144 ), but anyway I request details only for the pokestop I need (maybe I forgot to add a break in the snippet that I posted before)

EDIT: I noticed there is no need to get all the details of the pokestop to check the id... modified the snippet

**Comment by ramarro123** [comment]
yeah, i got your point. i still was thinking thwt will be great to gave a bot that go to a point where the lure is active even from 300 meter of distance. i tstill think that in map the lure informstiob its given without extra query .

on the app when i login i got the stop with different gfx color even far away... i eoubt that the app does a call for every stop

**Comment by Pyr0x1** [comment]
I don't really know the criteria by which the list of given pokestops is returned by the API, probably only the ones in a certain range, so even if all are queried for details it is not too heavy to handle. In my case that list for the coordinates I need counts 102 elements, I don't know how it is in your case.

**Comment by ramarro123** [comment]
well, it's not matter of my user case, i am trying to make it work in a more general way.

what i can do, at the moment, it's to store all the pokestop on a set, and wrap with something that return the same hashCode for the same pokestop (ie using ID as hashing code)

In that way, i can use the wrapper class as a singleton for pokestop, and create a sort of caching, doing query only when need.

It's not a big problem, but if there is a standard and more lightway to get pokestop information (expecially the lure info) it will be great.

At the moment it's of no usage, since we can't catch lured pokemon in any case :( :( 
[https://github.com/Grover-c13/PokeGOAPI-Java/issues/151]

**Comment by Pyr0x1** [comment]
Hmm, I am not sure I understood your problem... I query for the list of pokestops, but I get the details only of the one I am interested in, because I noted its id. I don't understand what you are doing with hashing and stuff.

Anyway, I would be happy to have a bot that notifies me when somebody uses a lure module on the pokestop I am interested in.

**Comment by ramarro123** [comment]
i think that this issue it's becaming very big already :D hope that the devs will be able to read them all :)

anyway, to make a long story short, it's exactly what i am trying to achive, get a nofity when somebody use a lure module on pokestop, so i can move in that direction.

i want to monitor 500/1000 pokestops at the same time, and making 500/1000 query every 3-6 mins it's a terrible idea.

if the lure information it's send out when the map begin serialized, it will be great to be able to fetch them

**Comment by Pyr0x1** [comment]
Ah, I see your problem now. I only want to monitor one pokestop, while you want to monitor many, that's why...
