### ISSUE TITLE
CatchablePokemon from fortData

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#151]
on CatchablePokemon constructor (with fortData param), the spawnPointId it's set to null.

i think that this constructor will be used to catch pokemon lured on fort, but it won't work
cos enconuter will throw null pointer (spawnpoint = null)

also, if i try to catch without encounter (that i doubt it's the correct way, but just in case)
there is a barrier with if (encountered == false) blablal, so it won't work.

**Comment by jabbink** [comment]
Won't raise a null pointer exception.

Not sure if it works. No lured pokestops around here, hence why the entire code is not called anywhere. Feel free to test it.

**Comment by ramarro123** [comment]
actually, i try it and i got a nullpointer :) 

let me cut & paste exception, give me 2 mins i have lured  poketsops here :D

**Comment by jabbink** [comment]
Oh yeah, I see it, the generated code is fubar

```
      /**
       * <code>optional string spawn_point_id = 2;</code>
       */
      public Builder setSpawnPointId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
```

The field is optional (but I don't know if not setting it actually works) but it checks for null...

**Comment by jabbink** [comment]
But if you're near a lure now, quickly try commenting both `.setSpawnPointGuid(getSpawnPointId())` and `.setSpawnPointId(getSpawnPointId())` to see if capturing the pokemon then works, because I fear it doesn't.

**Comment by ramarro123** [comment]
on my way with my laptop :D hehehe

commenting from encounter right?

**Comment by ramarro123** [comment]
another things that make very hard to test this one it's that issue.
https://github.com/Grover-c13/PokeGOAPI-Java/issues/149

i have modify the program to stay in front of the pokestop that i know it's lured, and wait even if it say hasLured == false... wonder why it doesn't report correctly the state of this stop.
....

FIY, after removing the method, encounterPokemon return not success

**Comment by vmarchaud** [comment]
Linked to [this issue](https://github.com/AeonLucid/POGOProtos/pull/103) i guess
