### ISSUE TITLE
Import project to workspace

### ISSUE THREAD

**Issue by Chriko2502** [Grover-c13/PokeGOAPI-Java#155]
Dear all,
I really like the work and want to help developing it! But sadly/embarrassingly I am failing at importing the source to Eclipse or NetBeans... Perhaps a small howto for this in the wiki? :)
Thanks a lot!

**Comment by mluigi** [comment]
I use IntelliJ Idea, it imports directly through the build.gradle, and automatically downloads the dependencies.
As for Eclipse or NetBeans, search for import through gradle

**Comment by vmarchaud** [comment]
Follow to readme, you will get all dependencies, after go to Build path > Configure Build Path > Source > Add Folder > Select `build/generated/source/proto/main/java` > Finish and the last errors will go away.

If its not working, retry from start, its working for me.

**Comment by AbandonedCart** [comment]
http://stackoverflow.com/a/10730545/461982

> add
> `apply plugin: "eclipse"`
> in your build.gradle and run
> `gradle eclipse`

That will only import it as a Java project (not Android) and you will still need to add the folder.
