### ISSUE TITLE
egg report 0 for getEggKmWalkedStart

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#160]
Hi,

an egg with
getEggIncubatorId != null (the correct id of the incubation)
and with
getEggKmWalkedTarget = 5 (the correct km that i have to wait)
report
getEggKmWalkedStart = 0 (that should be, in my case 2.4 at the moment)

every eggs return getEggKmWalkedStart = 0, in incubator or not

**Comment by stirante** [comment]
Check also getEggIncubatorId().isEmpty(). Eggs you get with getEggs() are the ones not in incubator.

**Comment by ramarro123** [comment]
at the moment it's possible to incubate eggs (with isEmpty for instance, to check if the incubator it's free)

but, it's not possible to hatch an egg when it reach time_ready (it won't happen automatically)

if i open the app,get the hatched stuff then i can incubate other eggs

**Comment by vmarchaud** [comment]
i'm currently investing for this bug.

**Comment by vmarchaud** [comment]
@ramarro123 after investing this bug, its seems that no data for the actual distance is being sent by the server in egg proto, but they do in the incubator proto, i added method to retrieve it in my last PR.

**Comment by ramarro123** [comment]
oky, so better to remove the other method as well to avoid confusion? or to wrap it to make it do a getHatchery, find the one used and return the already done job?

**Comment by vmarchaud** [comment]
will do when i will be sure how to exactly get the distance done with this egg

**Comment by vmarchaud** [comment]
After looking for information directly in the network call of the official app, i dont see any way for computing the actual distance, the incubator proto just contain their start/end, not the current progress. 
Waiting another implementation to get this information to add it to our.

**Comment by vmarchaud** [comment]
closing in favor of #227
