### ISSUE TITLE
Feature request: CatchablePokemon CP

### ISSUE THREAD

**Issue by evaldasguogis** [Grover-c13/PokeGOAPI-Java#162]
Unless I missed something, at the moment there is no way to know CP (and other stats) of a catchable pokemon.
It would be nice to have to know pokemon CP when capture starts, and use berries/better pokeballs based on that.

**Comment by mjmjelde** [comment]
CapturePokemon do not have CP.  You only can get the CP after you have encountered them.

Once you have encountered them and got the EncounterResult back, you can do `EncounterResult.getWildPokemon().getPokemonData().getCp()`  You may want to check that the WildPokemon has PokemonData first by calling `EncounterResult.getWildPokemon().hasPokemonData()` or errors could happen
