### ISSUE TITLE
FeatureRequest: UPGRADE_POKEMON

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#163]
it's possible to deploy upgrade() as well as evolve() method?

eventually, even having the query things can be nice, like upgrade cost in candy & powder or required level (upgrade follow certain rules that i don't know, but i got a message like 'you can't upgrade your pokemon cos your level it's too low)

**Comment by FabianTerhorst** [comment]
evolve is already in the proto.https://github.com/AeonLucid/POGOProtos/blob/3682394bf5c10ac5ebdfcb06cd7f0f7479afc7a5/src/POGOProtos/Networking/Responses/EvolvePokemonResponse.proto  https://github.com/AeonLucid/POGOProtos/blob/3682394bf5c10ac5ebdfcb06cd7f0f7479afc7a5/src/POGOProtos/Networking/Requests/Messages/EvolvePokemonMessage.proto

**Comment by Grover-c13** [comment]
I think he is referring too powering up the pokemon (i think upgrade pokemon is the name of the proto)

**Comment by Grover-c13** [comment]
#182 done, will not work until AeonLucid/POGOProtos has accepted PR to fix an int issue (right now upgrading pokemon will return pokemon doesnt exist or something similiar).
