### ISSUE TITLE
GoogleAuth with own client id

### ISSUE THREAD

**Issue by thejavatar** [Grover-c13/PokeGOAPI-Java#164]
**Description:**
It would be great if I could use the API with my own Google Client ID

**Expected behavior:**
GoogleAuth uses user's defined CLIENT ID

**Actual behavior:**
GoogleAuth uses always the same CLIENT ID, potentially a security breach?

Happy to make necessary changes in the code.

**Comment by mjmjelde** [comment]
Wut?  You can't use your own Google Client ID.  Your own Client ID doesnt not have authorization over the PokemonGO oauth.  This would be a big security breach.  This is why we have to use the Google Client ID of the PokemonGO App

**Comment by vmarchaud** [comment]
You definitely should read about [how things work](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2) before make PR without correctly understanding whats going on.

**Comment by thejavatar** [comment]
Ah, never mind. I think I have spent too much time on the sun today catching magikarps. I don't know why but for some reason I told myself that this authentication is supposed to be the authentication to my application instead of Pokemon Go... Hence I was suprised I have to use some default pair of id and key... It took me a while to realize that I'm talking nonsense. Def need more sleep less coffee.

Sorry for the confusion and thanks for the great library.

**Comment by FabianTerhorst** [comment]
@thejavatar can you close this issue?
