### ISSUE TITLE
fix open TODO in catchablePokemon ( module boosted spots)

### ISSUE THREAD

**Issue by davidmann4** [Grover-c13/PokeGOAPI-Java#167]
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/api/map/pokemon/CatchablePokemon.java#L118

needs to be

this.spawnPointId = proto.getId();

I am currently stuggling setting everything up on my machine so I can test. you guys use intellij?

**Comment by davidmann4** [comment]
hmm was able to make a jar and use this 

had ENCOUNTER_NOT_FOUND 

so will not work aswell

**Comment by Grover-c13** [comment]
the fort id and spawnPointId are different i think, will confirm sometime today
