### ISSUE TITLE
Legal Issues, thoughts?

### ISSUE THREAD

**Issue by firaskafri** [Grover-c13/PokeGOAPI-Java#17]
Here are some of the legal terms that could be related to the API, thoughts?

(iii) Use, or facilitate the use of, any unauthorized third-party software (e.g. bots, mods, hacks, and scripts) to modify or automate operation within the Service whether for yourself or for a third party.
(v) Download quantities of content to a database for any reason;
(vi) Decompose, disassemble, or reverse engineer any part of any Service, or otherwise use a Service for any purpose other than those provided for by us and in conjunction with the operations of the Service;
(vii) Develop functionally similar products or services to any Service;
(xiii) Attempt to circumvent any restriction in any Service based upon age, geography, or other restriction imposed by us.

**Source**: http://www.pokemon.com/us/terms-of-use/

**Comment by Grover-c13** [comment]
hope for the best

**Comment by firaskafri** [comment]
@Grover-c13 sure, but I'm trying to raise an important point to avoid having problems in the very near future. I believe at some point they will release an official API, and I believe it will be limited and restricted due to the fact that there are already way too many ways for them to monetize the game and they want to be first to experiment with it before releasing the API for the public to play with it.

**Comment by Grover-c13** [comment]
ill keep going til im told to stop, which is hopefully never. This is just a hobby for me in the end, i think however players using tools using APIs/Reverse engineer should be aware that they could get banned/legal trouble for breaching the ToS.

Other then that lets hope people make some cool stuff and they are all like "hey this is cool, lets not throw lawyers at it"

**Comment by firaskafri** [comment]
@Grover-c13 can you please give me your email address?

**Comment by Grover-c13** [comment]
can i ask why?

**Comment by firaskafri** [comment]
Just want to propose an idea to you and pick your brains on something
related since you're someone who's already deep in this.

**Comment by Grover-c13** [comment]
If you want to talk please come to Pokemon GO Reverse Engineering slack,
https://www.reddit.com/r/pokemongodev/comments/4skbwo/pokemon_go_reverse_engineering_live_discussion/
