### ISSUE TITLE
APi should use standard logger lib for logger instead of the custom com.pokegoapi.util.Logger

### ISSUE THREAD

**Issue by NargiT** [Grover-c13/PokeGOAPI-Java#171]
**Description:**
The librarie does not use any standard logging system. It should use at least java.util.logging and let the application decide how to handle it.

**Steps to reproduce:**
1. Run the application
2. The console logs using com.pokegoapi.util.Logger (not a java standard)

**Expected behavior:**
Should allow the end user to log the level of the log (DEBUG, INFO, WARN, ERROR) and controle the granularity of logging

**Actual behavior:**
Custom information is display, no way to control the granularity

**Stacktrace (If it's a crash):**
No crashe

**Version:**
master-SNAPSHOT (at least from revision 5a7fcc4)

**Comment by ramarro123** [comment]
my 2 cents... the lib (packet) it's already 3mb and there are quite a few libs.

if you want to implement something of standard, just use java.util.logging without slf4j facade, it should be better imho

**Comment by NargiT** [comment]
Sounds good for me, as long as I can use slf4j bridge :)

**Comment by Jari27** [comment]
I think Log isn't implemented fully yet. It seems there is indeed no way to log with a desired granularity, but I hardly think a working Log has been a priority for the past few days.

@Grover-c13 What is your idea on this?

**Comment by Grover-c13** [comment]
Doesnt really bother me, at the end of a day a logger logs. So if people think using the standard logger would be better thats fine. @Aphoh what do you think

**Comment by Aphoh** [comment]
IMO there is enough logging functionality for this library. If you want to use sl4j you can implement the Logger interface and set your Logger as the logging instance. This helps maintain better compatibility with android. If there are more logging features you would like please either describe them or make a pr.

**Comment by Aphoh** [comment]
@NargiT @Sadye any requests for logging functionality? If not I will close the issue.

**Comment by Jari27** [comment]
I'd like a granularity, but that's it.

**Comment by Aphoh** [comment]
@Sadye what do you mean? We already include a log level and the name of the class in the log.

**Comment by Jari27** [comment]
It's currently impossible to define at what level you want messages, e.g.
`Log.setLevel(Level.VERBOSE);`

**Comment by Aphoh** [comment]
@Sadye 
Edit: I see what you mean. I will implement this now and submit a PR.

**Comment by NargiT** [comment]
Hello sorry the late reply. My point was that I want to manage granularity of logging by package name. 
@Aphoh : not sure I understand what you meant by "If you want to use sl4j you can implement the Logger interface and set your Logger as the logging instance."
