### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by alawing** [Grover-c13/PokeGOAPI-Java#183]
I dont know why cannot I build through the README file, could you help me?

$ ./gradlew assemble
:PokeGOAPI-Java:extractIncludeProto FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':PokeGOAPI-Java:extractIncludeProto'.
  
  > Could not expand ZIP '/home/ec2-user/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/3.0.0-beta-3
  > /ed8c2f9a63cfa770292f8173fd0172bdaa014fe3/protobuf-java-3.0.0-beta-3.jar'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.46 secs

**Comment by Grover-c13** [comment]
have you done a git submodule init and git submodule update?

**Comment by alawing** [comment]
yes I did git submodule update --init first

**Comment by langerhans** [comment]
So did you try what gradle suggests and ran it with `--info` or `--stacktrace` which you could have added to this isse if you wouldn't have removed the issue template?

**Comment by alawing** [comment]
Here is the result of --info

$ ./gradlew build bundle --info
Starting Build
Settings evaluated using settings file '/home/ec2-user/PokemonGoBot/lib/PokeGOAPI-Java/settings.gradle'.
Projects loaded. Root project using build file '/home/ec2-user/PokemonGoBot/lib/PokeGOAPI-Java/build.gradle'.
Included projects: [root project 'PokeGOAPI-Java']
Evaluating root project 'PokeGOAPI-Java' using build file '/home/ec2-user/PokemonGoBot/lib/PokeGOAPI-Java/build.gradle'.

---

## Detecting the operating system and CPU architecture

os.detected.name=linux
os.detected.arch=x86_64
os.detected.classifier=linux-x86_64
All projects evaluated.
Selected primary task 'build' from project :
Selected primary task 'bundle' from project :
Tasks to be executed: [task ':extractIncludeProto', task ':extractProto', task ':generateProto', task ':compileJava', ta
sk ':processResources', task ':classes', task ':jar', task ':sourcesJar', task ':assemble', task ':checkstyleMain', task
 ':extractIncludeTestProto', task ':extractTestProto', task ':generateTestProto', task ':compileTestJava', task ':proces
sTestResources', task ':testClasses', task ':checkstyleTest', task ':test', task ':check', task ':build', task ':bundle'
]
:extractIncludeProto (Thread[main,5,main]) started.
:extractIncludeProto
:extractIncludeProto (Thread[main,5,main]) completed. Took 0.132 secs.

FAILURE: Build failed with an exception.
- What went wrong:
  Could not open cache fileSnapshots.bin (/home/ec2-user/PokemonGoBot/lib/PokeGOAPI-Java/.gradle/2.13/taskArtifacts/fileSn
  apshots.bin).
  
  > java.io.FileNotFoundException: /home/ec2-user/PokemonGoBot/lib/PokeGOAPI-Java/.gradle/2.13/taskArtifacts/fileSnapshots
  > .bin (Permission denied)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 8.71 secs

**Comment by langerhans** [comment]
`(Permission denied)`

There you go. This is an isse with your gradle setup. Gradle can't access the file mentioned. Make sure your user has access to this file/directory.
