### ISSUE TITLE
Are lure pokemons supported yet?

### ISSUE THREAD

**Issue by Jari27** [Grover-c13/PokeGOAPI-Java#186]
Are lure pokemons supported yet?

Code still has `//TODO check correctness`.
See `com.pokegoapi.api.map.Map` and `com.pokegoapi.api.map.pokemon.CatchablePokemon`.

Has anyone used it and/or checked it?

**Comment by davidmann4** [comment]
does not work

**Comment by davidmann4** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/issues/125

**Comment by davidmann4** [comment]
also https://github.com/Grover-c13/PokeGOAPI-Java/issues/167

**Comment by davidmann4** [comment]
why did you closed the issue? well I will open a new one

**Comment by Jari27** [comment]
It was a simple question, not really an Issue. 

An issue should, imho, be worded like: bug: fix lurepokemon
