### ISSUE TITLE
Code to accept levelups, achievements, hatch pokemon?

### ISSUE THREAD

**Issue by swiftveteran** [Grover-c13/PokeGOAPI-Java#188]
These features would help usability as well as increase the leveling rate. Currently, you have to log in and you get spammed with levelup/achievement/hatch messages. Sorry if this is not the correct way to open an issue for features.
- [x] accept levelups
- [x] accept achievements
- [x] hatch pokemon

**Comment by stirante** [comment]
Hatching already is implemented. There is queryHatchedEggs in Hatchery I think. The rest can be done just by sending CheckAwardedBadgesMessage which I think is quite simple.

**Comment by vmarchaud** [comment]
From what i tested, rewards for level up are actually automated in the backend, they give the reward directly in your inventory, so its seems useless to send the request.

**Comment by swiftveteran** [comment]
@vmarchaud That wasn't the case for me. When I logged into a leveled account it spammed with achievements, levelups, and hatch messages for a very long time.

**Comment by jabbink** [comment]
> its seems useless to send the request.

How to catch a bot without fancy algorithms: check if they marked their full screen popup levelup warnings as read.

**Comment by vmarchaud** [comment]
Yeah @jabbink what about faking the analytics sent to their third parties .....

`That wasn't the case for me. When I logged into a leveled account it spammed with achievements, levelups, and hatch messages for a very long time.`
Dump your response from the network they always return "ALREADY_REWARDED", even just after you leveled up.

**Comment by swiftveteran** [comment]
@vmarchaud You're not wrong, but it still spams the Android client UI...is there no way around that?

**Comment by FabianTerhorst** [comment]
@swiftveteran maybe this is the default behavior for achievements you missed while the app was closed.

**Comment by stirante** [comment]
Well, If you want it quick there you go:

``` java
    public static void checkBadgesAndStuff() throws LoginFailedException, RemoteServerException {
        CheckAwardedBadgesMessageOuterClass.CheckAwardedBadgesMessage msg = CheckAwardedBadgesMessageOuterClass.CheckAwardedBadgesMessage.newBuilder().build();
        ServerRequest serverRequest = new ServerRequest(RequestTypeOuterClass.RequestType.CHECK_AWARDED_BADGES, msg);
        api.getRequestHandler().sendServerRequests(serverRequest);
        //here you marked everything as read
        CheckAwardedBadgesResponseOuterClass.CheckAwardedBadgesResponse response;
        try {
            response = CheckAwardedBadgesResponseOuterClass.CheckAwardedBadgesResponse.parseFrom(serverRequest.getData());
        } catch (InvalidProtocolBufferException e) {
            throw new RemoteServerException(e);
        }
        //do something with response
    }
```

But I'm sure it will be in this API soon

**Comment by vmarchaud** [comment]
@swiftveteran Just send the request to the backend every 10 minutes and it will get rid of the notifications.

**Comment by jabbink** [comment]
> Yeah @jabbink what about faking the analytics sent to their third parties .....

Upsight? That's literally external analytics that is perfectly valid not to respond to, eg by youronlinechoices.eu and local adblockers (or hosts file patches; etc)

**Comment by vmarchaud** [comment]
@jabbink Why you want to make believe the server that the api is the official client so, thats impossible ???

**Comment by ramarro123** [comment]
the proposed code
checkBadgesAndStuff()
doesn't work...

it will return success but if i login i still got all the badge animations  & prizes for levelup.

prizes aren't collected from the bot

**Comment by stirante** [comment]
Yeah, you're right. Just checked. You also need to actually equip these badges. I'll try to fix it. Just give me 10 minutes

**Comment by ramarro123** [comment]
i think that there is also the LevelUpRewards things to be considered right?

**Comment by stirante** [comment]
http://pastebin.com/0zAidCpw

Fixed code. Can't test it right now as i don't have any badges to receive.

**Comment by ramarro123** [comment]
i'll test it tomorrow, tnx!
