### ISSUE TITLE
Implementation in Android, "real case" use?

### ISSUE THREAD

**Issue by Maufeat** [Grover-c13/PokeGOAPI-Java#19]
Hey,

is there someone already trying to get this working on Android Studio or on android in general? With an demo app maybe. Just for confirmation and may get attention to this a bit more.

**Comment by firaskafri** [comment]
Yes, soon will make our modifications public with a code that makes a bit more sense for Android.

**Comment by Grover-c13** [comment]
There are a few branches trying to make it more android compatible (java6, drop apache http) which will be merged as soon as feasible, Android compatibility is one of the goals of the API.

**Comment by firaskafri** [comment]
@Grover-c13 can you name a few?

**Comment by Grover-c13** [comment]
This is the main one we are going to merge at this current moment, although currently not functional:
https://github.com/Aphoh/PokeGOAPI-Java/

**Comment by jabbink** [comment]
@firasalkafri now available as #25

**Comment by halsafar** [comment]
I would say I have a fully functional Android port of this working.  I was going to push it up today but the servers are down so I cannot actually verify it is working with todays updates of POGOProtos and this API.  Sounds like someone is already on it?

**Comment by Grover-c13** [comment]
As far as im aware, this branch is currently android compatible.

**Comment by jabbink** [comment]
With #48 it will require JDK 7 instead of 6, though.

From what I've heard that will limit Android to version 4.4 and newer.

**Comment by Grover-c13** [comment]
Closing
