### ISSUE TITLE
Pokéstop don't loot anything

### ISSUE THREAD

**Issue by iSach** [Grover-c13/PokeGOAPI-Java#191]
**Description:**
When I try to make a pokestop loot, it doesn't drop anything.

Code used:

``````
                        StringBuilder sbb = new StringBuilder();
                        sbb.append("```Pokéstops looted:" + "\n");
                        for (Pokestop pokestop : go.getMap().getMapObjects().getPokestops()) {
                            if(pokestop.canLoot()) {
                                PokestopLootResult result = pokestop.loot();
                                System.out.println(result);
                                if(!result.wasSuccessful()) continue;
                                sbb.append("  ").append(pokestop.getDetails().getName()).append(":").append("\n");
                                sbb.append("    EXP dropped: ").append(result.getExperience()).append("\n");
                                sbb.append("    Items: ").append("\n");
                                for(ItemAwardOuterClass.ItemAward item : result.getItemsAwarded()) {
                                    sbb.append("      ").append(item.getItemCount()).append("x ").append(TextUtil.beautifyString(item.getItemId().name()) + "\n");
                                }
                            }
                        }
                        sbb.append("```");
                        getMessageChannel().sendMessage(sbb.toString());
``````

Example output:

```
Pokéstops looted:
  Ladu:
    EXP dropped: 0
    Items: 

```

Also checked inventory, no new items, and also checked EXP.

**Steps to reproduce:**
1. Pokestop.loot();

**Expected behavior:**
Receiving Items and Experience.

**Actual behavior:**
No Items nor any EXP dropped.

**Version:**
0.1.15

**Comment by LEGENDFF** [comment]
looks like you are soft banned

**Comment by iSach** [comment]
I can still connect through my phone

**Comment by iSach** [comment]
@LEGENDFF Oh, it means I'm banned from API?

What's the goal of an API if we can get banned from it?

**Comment by LEGENDFF** [comment]
softban = unable to spin pokestops, pokemons flee after first attack etc., for a certain time after moving too fast

**Comment by iSach** [comment]
@LEGENDFF Ah okay so it's just like an Anti-Spam?
I thought I was really banned from game, thanks :)

**Comment by LEGENDFF** [comment]
Yea its an anti cheat measure by the game server.
If you set your location close to a pokestop near your location, while having the app closed for a few seconds, your code should work though

**Comment by iSach** [comment]
Do you know how long it lasts?

**Comment by vmarchaud** [comment]
@iSach There isnt a fix timer, maximum 1 hour i would say, but average should be 10 minutes.

**Comment by iSach** [comment]
@vmarchaud okay, thanks. Can it lead to a definitive ban?

**Comment by vmarchaud** [comment]
No one as my knowledge has been definitely banned but you definitely should be using an alt account with anything that break niantic's ToS (hint : we are with this api).
PS : close the issue as its not an actual issue with the api.

**Comment by iSach** [comment]
Okay, thanks :)

**Comment by RobertMcCoy** [comment]
iSach, I know you have closed this issue, but have you gotten this working? My code compiled incorrectly if I try to do a for loop on the items, it's like it's not recognizing the ItemAwardOuterClass.ItemAward portion, even with the proper imports.

**Comment by iSach** [comment]
@RobertMcCoy Yes, my code is fully working when not being soft-banned.

Her is the class of my Discord Bot containing all the features of Pokémon Go I made yet with the API. (Go somewhere, SHowing bank, inv, stops nearby, pokémons nearby, player stats, catching a pokémon and making a stop loot).

**Comment by FabianTerhorst** [comment]
@iSach you are going to share the discord bot?

**Comment by iSach** [comment]
@FabianTerhorst Oh sorry, forgot to include the link. yes, it's open-source:
http://github.com/iSach/Samaritan

**Comment by RobertMcCoy** [comment]
@iSach Ah, I was a missing an API import for items, so the ItemAward object was not being compiled properly. Thanks for the link, neat stuff!

**Comment by iSach** [comment]
@RobertMcCoy you're welcome :p
