### ISSUE TITLE
I can't compile it :/

### ISSUE THREAD

**Issue by coolnickname** [Grover-c13/PokeGOAPI-Java#192]
Whenever I try to compile it I get an error saying POGOProtos can't be found.

log:
http://pastebin.com/viMP6SjS

**Comment by vmarchaud** [comment]
As its wrote on the readme you should `git submodule update --init` ...

**Comment by LEGENDFF** [comment]
put https://github.com/AeonLucid/POGOProtos/tree/ff99b436a34f0db79e3f1db805811f083405aecd into src/main/resources/protobuf

**Comment by coolnickname** [comment]
@vmarchaud My Git said it wasn't a valid parameter, and since I didn't use Git to clone it I just... It makes much more sense now.
