### ISSUE TITLE
Build error - Generate proto failed (filename too long)

### ISSUE THREAD

**Issue by froglordsixtynine** [Grover-c13/PokeGOAPI-Java#193]
Execution failed for task ':generateProto'.

> java.io.IOException: Cannot run program "C:\Users_____.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc
> \3.0.0-beta-3\71e76cad4f9b30aab172c44035d343c5bab47815\protoc-3.0.0-beta-3-windows-x86_64.exe": CreateProcess error=206,
>  The filename or extension is too long

Not caused by your code, of course, but is there a workaround for this?

**Comment by Jari27** [comment]
Move it to `C:\PokeGOAPI-Java` ?

**Comment by froglordsixtynine** [comment]
Thanks, worked

**Comment by Aphoh** [comment]
As it seems the issue has been solved, I am closing it. It will be reopened if it has not been solved.

**Comment by luisa123456** [comment]
Long Path Tool can help you to remove blocked files or too long path files. You can easily fix file errors with this software.

**Comment by Stepan222** [comment]
This can be fixed using "Long Path Tool Program" 
Just rename the file using this software and the issue will be resolved.
