### ISSUE TITLE
All pokemon catch results in CATCH_FLEE

### ISSUE THREAD

**Issue by willsherwood** [Grover-c13/PokeGOAPI-Java#194]
I am a level 5 within the game and using the following code to find and catch pokemon. However, I am not losing any pokeballs when I log into the game on my phone after hte fact and every single pokemon gets "CATCH_FLEE". Console output:

> Pokemon in area:3
> Encounted:RATTATA
> Attempt to catch:RATTATA CATCH_FLEE
> Encounted:GASTLY
> Attempt to catch:GASTLY CATCH_FLEE
> Encounted:ZUBAT
> Attempt to catch:ZUBAT CATCH_FLEE

Code:

```
go.setLocation(/* real loc with pokemon */);
            List<CatchablePokemon> catchablePokemon = go.getMap().getCatchablePokemon();
            System.out.println("Pokemon in area:" + catchablePokemon.size());

            for (CatchablePokemon cp : catchablePokemon) {
                // You need to Encounter first.
                EncounterResult encResult = cp.encounterPokemon();
                // if encounter was succesful, catch
                if (encResult.wasSuccessful()) {
                    System.out.println("Encounted:" + cp.getPokemonId());
                    CatchResult result = cp.catchPokemonWithRazzBerry();
                    System.out.println("Attempt to catch:" + cp.getPokemonId() + " " + result.getStatus());
                }
            }
```

Any advice? Thanks a lot.

**Comment by swiftveteran** [comment]
You got soft-banned for warping. It will go away in ~5 minutes.

**Comment by Aphoh** [comment]
As it seems the issue has been solved, I am closing it. It will be reopened if it has not been solved.
