### ISSUE TITLE
INFO: branch question

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#197]
Hi,

there is any info on how the two main branch will be used?

master it's quite a lot behind development, and i see that now pogoproto have finally merge the pull request to fix hatch & powerup pokemons, thus i guess that this 2 modify can go to master...

but still, want to know how is the expected development cycle, just to know :)

**Comment by Grover-c13** [comment]
right now its probably going to be make a bunch of features > check stable > merge into master, probaby every few days. Id say maybe tonight or tomorrow for the first update. We will start versioning as well
