### ISSUE TITLE
[Suggestion] Split sample and library into two different modules

### ISSUE THREAD

**Issue by FabianTerhorst** [Grover-c13/PokeGOAPI-Java#201]
Currently the examples are in a folder inside the library. With gradle you can split the lib and the sample in two different modules. When you would like this i could create a pr for this behavior.

**Comment by rajulbhatnagar** [comment]
I think thats a good idea.

**Comment by Grover-c13** [comment]
yeah go for it

**Comment by vmarchaud** [comment]
Done ;)
