### ISSUE TITLE
[Request Feature] Farm Module Pokestops

### ISSUE THREAD

**Issue by davidmann4** [Grover-c13/PokeGOAPI-Java#204]
**Intro**
The game offers a feature where you can buff a pokestop to lure pokemons. After you used a Module (the item which boosts a pokestop) Pokemons will show up on a regular. Modules are active for 30 minutes.

**Tech**
After you used a Module on a pokestop the pokestop will get a ActivePokemon Value. See a example below.

> disk_encounter
> check to see if the fort has 'lure_info'
> if it has then attempt a disk_enounter
> and if encounter status 1 then try to catch pokemon
> just a heads up not 100% times will you find a successful encounter with lure'd forts mostly you will get it but not always
> working python code:
> https://github.com/j-e-k/pgoapi/blob/master/pgoapi/pgoapi.py#L421

**Comment by vmarchaud** [comment]
Linked to [this issue ](https://github.com/AeonLucid/POGOProtos/pull/103) and duplicate of #151
