### ISSUE TITLE
[BUG] getItemsAwarded returns empty list sometimes

### ISSUE THREAD

**Issue by Jari27** [Grover-c13/PokeGOAPI-Java#208]
**Description:**
Sometimes `lootResult.getItemsAwarded()` returns an empty list, even though the the call was succesful (`lootResult.wasSuccesful() == true && lootResult.getExperience() > 0`).

**Steps to reproduce:**

```
if (pokestop.canLoot()) {
    PokestopLootResult lootResult = pokestop.loot();
    if (lootResult.wasSuccessful()){
    System.out.print(lootResult.getItemsAwarded().isEmpty());
}

```

**Expected behavior:**
Should always print `false` or nothing, because spinning a pokestop succesfully always gives items.

**Actual behavior:**
Prints `true` in about 66% of the cases.

**Version:**
commit f91890

**Comment by stirante** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/api/map/fort/PokestopLootResult.java#L36

Probably Full Inventory

**Comment by Jari27** [comment]
You're right! It never happens after I've just caught a pokémon. 

I'm closing this then.
