### ISSUE TITLE
[BUG] Build error in Java code

### ISSUE THREAD

**Issue by Jari27** [Grover-c13/PokeGOAPI-Java#213]
**Description:**
Building the project failed

**Steps to reproduce:**

```
clone repro,
cd into repro
./gradle build bundle
```

**Expected behavior:**
Should build.

**Actual behavior:**
Build failed

**Stacktrace (If it's a crash):**

```
C:\<snip>\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\map\Map.java:465: error: cannot find symbol
                                .setSpawnPointId(catchablePokemon.getSpawnPointId())
                                ^
  symbol:   method setSpawnPointId(String)
  location: class Builder
C:\<snip>\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\player\PlayerProfile.java:92: error: cannot find symbol
                team = Team.values()[playerResponse.getPlayerData().getTeamValue()];
                                                                   ^
  symbol:   method getTeamValue()
  location: class PlayerData
C:\<snip>\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\map\pokemon\CatchablePokemon.java:343: error: cannot find symbol
                                        .setSpawnPointId(getSpawnPointId())
                                        ^
  symbol:   method setSpawnPointId(String)
  location: class Builder
C:\<snip>\PokeGOAPI-Java\src\main\java\com\pokegoapi\api\pokemon\Pokemon.java:232: error: incompatible types
                return proto.getDeployedFortId();
                                              ^
  required: String
  found:    int
```

**Version:**
Most recent, pulled a minute ago.

**Comment by FabianTerhorst** [comment]
You builded the development branch?

**Comment by vmarchaud** [comment]
README > `git submodule update --init`

**Comment by Jari27** [comment]
@FabianTerhorst  Yes
@vmarchaud  Done that. It was actually `git submodule update`

**Comment by vmarchaud** [comment]
@Sadye the log saying that you havent generated the proto java file, so you may havent init the submodule at the correct version.
Retry from 0.

**Comment by FabianTerhorst** [comment]
@vmarchaud without that the error would be looking like this `error: package POGOProtos.Networking.Envelopes does not exist`.
@Sadye looks like you have a outdated version of the proto files.

**Comment by Jari27** [comment]
Hmm weird. It says this:

```
:extractIncludeProto UP-TO-DATE
:extractProto UP-TO-DATE
:generateProto UP-TO-DATE
```

Is there a force update command for git?

**Comment by vmarchaud** [comment]
Could you retry from the git clone to see if its the proto have been updated ?

EDIT : work for me using the instruction in readme.

**Comment by Jari27** [comment]
I'd really like to just just override this part:

```
:extractIncludeProto UP-TO-DATE
:extractProto UP-TO-DATE
:generateProto UP-TO-DATE
```

instead of starting from zero.

So far I've tried: `git submodule update -f` and
`git submodule deinit --all -> git submodule update --init`

Neither works, i.e. both say that my files are up to date.

**Comment by vmarchaud** [comment]
normal behavior on this one, you should remove the generated file `rm -rf build/generated` and deinit and init should re-generate them.

**Comment by Jari27** [comment]
Did that. I got the following:

```
:extractIncludeProto UP-TO-DATE
:extractProto UP-TO-DATE
:generateProto
:compileJava -> ERROR
```

Then I removed the entire build folder:

```
:extractIncludeProto
:extractProto UP-TO-DATE
:generateProto
:compileJava - ERROR
```

I don't get it anymore :(

**Comment by Jari27** [comment]
Alright so I found the issue: 

my POGOProtos is at commit eeccbb. It doesn't want to update any further.

```
git submodule update -f
Submodule path 'src/resources/protobuf': checked out 'eeccbb121b126aa51fc4eebae8d2f23d013e1cb8'
```

**Comment by vmarchaud** [comment]
Thats why i told you to restart from 0 :)

**Comment by Jari27** [comment]
I might just have to do that. So weird the submodule doesn't update further though.

**Comment by vmarchaud** [comment]
Got this problem last night, just retry and it worked so yeah.
Closing since its solved

**Comment by Jari27** [comment]
Fixed it. The HEAD was detached and I had to manually pull.

**Comment by Jari27** [comment]
Also thank you :+1:
