### ISSUE TITLE
Proto now has a Hypno family id.

### ISSUE THREAD

**Issue by kyleshrader** [Grover-c13/PokeGOAPI-Java#223]
Please uncomment hypno from

https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/api/pokemon/PokemonMetaRegistry.java#L168

He is now in the proto.

**Comment by a4andy** [comment]
Also, is there a reason why MANKEY is missing in the meta.put(...) list? Just got a NullPointerException right now

**Comment by vmarchaud** [comment]
Can someone make a PR for these ?

**Comment by kyleshrader** [comment]
#233

**Comment by Grover-c13** [comment]
Fix in the meta PR i did tonight #246

**Comment by Sheigutn** [comment]
@Grover-c13 Although there's an enum constant named FAMILY_HYPNO, Hypno should be in FAMILY_DROWZEE if I'm not wrong.

**Comment by kyleshrader** [comment]
This is a bug.... API shows hypno having no candy and drowzee having...

**Comment by kyleshrader** [comment]
I believe the rejected PR #233  would have fixed this.
