### ISSUE TITLE
[BUG] Incubator returns wrong kmWalked and kmTarget

### ISSUE THREAD

**Issue by Jari27** [Grover-c13/PokeGOAPI-Java#227]
**Description:**
When checking how far I still had to walk for my egg to hatch the function getKmWalked() and getKmTarget returned nonsene

**Steps to reproduce:**

```
for (EggIncubator incubator : api.getInventories().getIncubators()){
    Log.d(TAG, String.format("Incubator is in use: %b. (%.2f/%.2f km) ", incubator.isInUse(), incubator.getKmWalked(), incubator.getKmTarget()));
}
```

**Expected behavior:**
`getKmWalked()` returns something between 0.0 and 10.0
`getKmTarget()` returns either 2.0, 5.0 or 10.0

**Actual behavior:**
`[   LOGIN|D] Incubator is in use: true. (24.22/29.22 km)`

Only thing I can imagine is that it is a sum of all previously walked distances and the same for target. In this case that would be that this incubator (it's the special one) has hatched 2x10km, 1x5km, 2x2km eggs. Still doesn't explain where the 0.22km comes from. A proto error maybe?

**Comment by vmarchaud** [comment]
After testing, i always got these data, the official may computing the wanted data with these but i dont know how. (tested with mitmproxy-node avec i got exactly same data)

Will keep open this one and close the older one since its much more documented.

**Comment by ushort** [comment]
Look for `kmDistanceToHatch_` inside `_PokemonSettingsOuterClass_`

:egg:

**Comment by vmarchaud** [comment]
Done in #240 , got the same value in the official app and with the implemented call.
Will get merged soon, closing this issue ! (reopen if you got a problem)
