### ISSUE TITLE
com.pokegoapi.main.Request 404 Not found

### ISSUE THREAD

**Issue by vmarchaud** [Grover-c13/PokeGOAPI-Java#23]
Has you can read, someone deleted it, its gonna be easier if someone can re-push it again ;)
PS : gonna submit a PR to add how to build/install the api to the readme, might push it with it.

**Comment by langerhans** [comment]
A new mechanism for this was pushed but it seems the commit was incomplete. So not sure if it's supposed to stay. If you revert your branch by two commits you'll have a working base again.

**Comment by vmarchaud** [comment]
Yeah i was trying to understand why the master branch is used to this kind of rewrite.

**Comment by langerhans** [comment]
Agree, would be a good idea to at least have a master/develop workflow or just do **everything** in PRs.

**Comment by vmarchaud** [comment]
I dont even know if its usefull to finish the work and submit the PR or the author has already finish but not pushed ...

**Comment by jabbink** [comment]
Will revert `master` to a working state and move those 2 commits to a branch so @Grover-c13 can fix it tomorrow.

**Comment by jabbink** [comment]
Fixed
