### ISSUE TITLE
getExpirationTimestampMs returning wrong number

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#231]
**Description:**
getExpirationTimestampMs() seems to not actually be returning how many miliseconds before the pokemon expires? I recently have been getting values that are excess of 1 hour.
http://imgur.com/a/WFQBI screenshot of when I breakpoint the call in the CatchablePokemon class

**Steps to reproduce:**
1. Get catchablepokemon
2. Call getExpirationTimestampMs

**Expected behavior:**
Should be getting actual value

**Actual behavior:**
Getting non correct value. Ex in screenshot, its +24K minutes

**Version:**
Latest commit in version: 3543350b60cab02a235539cf397f5f9e1ef5eb8c

**Comment by FrozenDroid** [comment]
`pogo.getMap().getMapObjects().getWildPokemons().forEach(wildPokemon -> {
        wildPokemon.getTimeTillHiddenMs();
    });`
This will do what you want, I think?
The function you're mentioning is not supposed to return what you're expecting it to.

**Comment by ghost** [comment]
@FrozenDroid Oh did not know, what does getExpirationTimestampMs() do?

**Comment by FrozenDroid** [comment]
@jmew Not sure, actually :P

**Comment by FrozenDroid** [comment]
@jmew Actually, it's probably the epoch timestamp at which time the Pokemon will expire.

**Comment by ghost** [comment]
@FrozenDroid Ah I see. Whats weird is that I was using getExpirationTimestampMs() for a week before i pulled latest changes today and it gave me the #of MS till exipry from current time just perfectly fine before. Thanks for the help :)

**Comment by ghost** [comment]
@FrozenDroid Oh its not actually a UNIX timestamp. Anyone know what it is? I would like some way to store the "time till pokemon disappears" in the actual Pokemon/CatchablePokemon class themselves, so that I can easilly get the expiration time for a specific pokemon without having to iterate through all the map objects

**Comment by FrozenDroid** [comment]
@jmew are you sure it's not? It's in milliseconds so you have to divided by 1000 to get the timestamp.

**Comment by ghost** [comment]
Whoops forgot that unix time stamp was GMT. That's what was causing the issue. Thanks :)
