### ISSUE TITLE
Just hit pokestops

### ISSUE THREAD

**Issue by pock2793** [Grover-c13/PokeGOAPI-Java#232]
Will setting the catch prob to 0 have it ignore pokemon and just hit stops?

**Comment by kyleshrader** [comment]
-You wish to modify your local code to only tag pokestops? You can comment out tasks you dont want to perform in the .../tasks/TaskController.java-

edit: ignore me... i thought i was reading something in another repo... nvm.. :disappointed:

**Comment by pock2793** [comment]
im using the pre compiled jar

**Comment by Grover-c13** [comment]
?

**Comment by pock2793** [comment]
ignore this i thought this was another repo too lol
