### ISSUE TITLE
Correct inUse for incubators

### ISSUE THREAD

**Issue by jabbink** [Grover-c13/PokeGOAPI-Java#237]
**Description:**
The property `inUse` is not set correctly in the API, it returns `false` at all times right now.

**Expected behavior:**
Return `true` when an incubator is occupied.

**Actual behavior:**
Always not in use

**Proposed fix:**
Remove the `inUse` field and add this function

``` java
    public boolean isInUse() {
        return getKmTarget() > pgo.getPlayerProfile().getStats().getKmWalked();
    }
```

Maybe add some error handling to make sure the playerProfile and stats are actually set.

**Comment by Jari27** [comment]
Isn't this the wrong way around? I think the incubator is in use if `getKmTarget() > pgo.getPlayerProfile().getStats().getKmWalked();`

**Comment by jabbink** [comment]
yes, indeed the wrong way around. Copypasted the sample code from one of my projects, that filters unused incubators. Fixing the top comment.
