### ISSUE TITLE
Wrong IncubatorResponse hatchEgg() failed

### ISSUE THREAD

**Issue by NullP0interEx** [Grover-c13/PokeGOAPI-Java#242]
**Description:**
IncubatorResponse from hatchEgg(EggPokemon egg) is always "ERROR_POKEMON_EGG_NOT_FOUND"

**Steps to reproduce:**

Use a free incubator & egg and then:
incubator.hatchEgg(eggPokemon);

**Expected behavior:**
The Egg should stored in the incubator.

**Actual behavior:**
RequestResult is: ERROR_POKEMON_EGG_NOT_FOUND

**Comment by vmarchaud** [comment]
Working for me, could you send us your code ?

**Comment by NullP0interEx** [comment]
```
for (EggIncubator incubator : bot.getGo().getInventories().getIncubators())
                if (!(incubator.getKmTarget() >= bot.getGo().getPlayerProfile().getStats().getKmWalked())) {
                    for (EggPokemon eggPokemon : bot.getGo().getInventories().getHatchery().getEggs()) {
                        if (eggPokemon.getEggIncubatorId() == null || eggPokemon.getEggIncubatorId().isEmpty()) {
                            long id = eggPokemon.getId();
                            boolean is = eggPokemon.isIncubate();
                            UseItemEggIncubatorResponseOuterClass.UseItemEggIncubatorResponse.Result result = incubator.hatchEgg(eggPokemon);
                            if (result == UseItemEggIncubatorResponseOuterClass.UseItemEggIncubatorResponse.Result.SUCCESS) {
                               // OK
                                break;
                            } else
                                log("Egg: " + result + " Failed!");
                        }
                    }
                }
```

**Comment by vmarchaud** [comment]
Could you please use the balise code or putting it into a pastebin, it isnt readable here.

**Comment by vmarchaud** [comment]
Okay i got the same problem, investing ...

**Comment by Sadye** [comment]
I've been having the same troubles :(

**Comment by stirante** [comment]
Protos to blame. They changed in proto files uint64 to fixed64 so for pokemon ids it's better but not for egg ids. Change in EggIncubator.proto fixed64 to uint64 and in UseItemEggIncubatorMessage.proto

**Comment by vmarchaud** [comment]
Protos isnt the blame, its us who made this changed, so its us to blame.

**Comment by NullP0interEx** [comment]
@vmarchaud can you push a fix? :)

**Comment by vmarchaud** [comment]
You misunderstood, the error come from the proto, but we asked for these, wait for the protos repo to update.

**Comment by NullP0interEx** [comment]
ahh, i understand... I thought you have maybe access to the repo. 
Thx

**Comment by vmarchaud** [comment]
Fixed in dev branch.
