### ISSUE TITLE
Couldn't download the last version of the jar

### ISSUE THREAD

**Issue by mlabouardy** [Grover-c13/PokeGOAPI-Java#251]
Failed to resolve: com.github.Grover-c13:PokeGOAPI-Java:0.2

**Comment by Lasek** [comment]
I recommend change it to
`com.github.Grover-c13:PokeGOAPI-Java:ee28406d5a0f87dc2b16429f7b19e31fbac30a95`

**Comment by mlabouardy** [comment]
@Lasek doesnt work :(

**Comment by jdagnogo** [comment]
i have the same issue

**Comment by Lasek** [comment]
Typed

```
repositories {
    maven { url "https://jitpack.io" }
}
```

in build.gradle?

Now I tested with ee28406d5a0f87dc2b16429f7b19e31fbac30a95 and works for me.

**Comment by jdagnogo** [comment]
@Lasek yes I did, but it didnt work:

```
buildscript {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by ghost** [comment]
Set in dependencies this: compile 'com.github.Grover-c13:PokeGOAPI-Java:Development-SNAPSHOT'

**Comment by Aphoh** [comment]
The latest version may actually be broken guys...
https://jitpack.io/com/github/grover-c13/pokegoapi-java/0.2/build.log

Edit: This should work, however
`compile 'com.github.grover-c13:pokegoapi-java:master-f21ab72705-1'
`

**Comment by mlabouardy** [comment]
until the problem is solved, i built the jar manually and I added it to the build path

**Comment by vmarchaud** [comment]
Wrong link @Aphoh , there is the good one : https://jitpack.io/#Grover-c13/PokeGOAPI-Java/0.2
Working well if you do the same thing as explained in jitpack.
