### ISSUE TITLE
Write a document's API

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#253]
Feature Request:
Write a document similar to this(http://static.zerorobotics.mit.edu/docs/tutorials/ZR_user_API.pdf) to make the API more accessible

**Comment by Jari27** [comment]
The javadoc is supposed to be this.

**Comment by ghost** [comment]
Nobody does it ?

**Comment by vmarchaud** [comment]
Javadoc is within the code, we dont have any external doc, and i dont think its in the roadmap to do this next days. But i dont think someone will not make a pdf like this.

**Comment by jabbink** [comment]
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html

**Comment by spantin** [comment]
Here's a javadoc html export https://drive.google.com/open?id=0BynWaZ4k64aXaWs0N3ZtblIxaGc

**Comment by Aphoh** [comment]
That being said even with exporting the javadoc a small outline of the APIs available would be very nice. If we could make a wiki with a list of the currently supported and unsupported calls, we can leave the user to find the classes and look at the method implementations for those calls.

**Comment by jaavant** [comment]
yea would appreciate having javadocs instead of going through github files trying to find a method and maybe seeing comments above it.
