### ISSUE TITLE
Creating an auth and pokemongo object

### ISSUE THREAD

**Issue by jaavant** [Grover-c13/PokeGOAPI-Java#256]
**Description:**

In example CatchPokemonAtAreaExample.java  the auth is declared and then initialized to null but never used. Also PokemonGo Object is instantiated by the second given line of code. Whats the point in declaring auth in this snippet?

```
RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo auth = null; 
PokemonGo go = new PokemonGo(new PtcCredentialProvider(http, ExampleLoginDetails.LOGIN,ExampleLoginDetails.PASSWORD), http);


```

In example FightGymExample.java  it creates an auth and PokomonGO in a different way.

```
CredentialProvider auth = new PtcCredentialProvider(http, ExampleLoginDetails.LOGIN, ExampleLoginDetails.PASSWORD);
PokemonGo go = new PokemonGo(auth, http);

```

I'm curious as what is the proper way of doing this, or is both ways correct?

**Comment by Jari27** [comment]
Both are correct, but the first one is outdated.

I personally prefer the second way, but it's your choice.

**Comment by ramarro123** [comment]
actually, what you have posted, is exactly the same... one it's not an outdated version of the other, they are exactly the same...

in the first example, you declare an auth object and it's not used at all...
in the second the auth it's the same object that you pass in the 1st example directly to the class constructor
