### ISSUE TITLE
Authentication in Android?

### ISSUE THREAD

**Issue by wsun19** [Grover-c13/PokeGOAPI-Java#260]
Hi, I have the API set up and I'm just trying out one of the basic examples. When I get my code I get:

> 07-26 17:19:22.967 9257-9359/william.mod.poketracker I/System.out: D/GoogleCredentialProvider: 1800
> 07-26 17:19:22.967 9257-9359/william.mod.poketracker I/System.out: D/GoogleCredentialProvider: Get user to go to:https://www.google.com/device and enter code:DUME-LECJ

So should I be redirecting my users to a WebView, and have them enter that code? If so, I should save the refresh token from onTokenIdReceived(), right? Or is there a library to handle this?

For reference, this is the current status of my code:

```
public class MainActivity extends AppCompatActivity {

    private static final String LOG_TAG = MainActivity.class.getSimpleName();
    GoogleCredentialProvider.OnGoogleLoginOAuthCompleteListener listnr;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        listnr = new GoogleCredentialProvider.OnGoogleLoginOAuthCompleteListener() {
            @Override
            public void onInitialOAuthComplete(GoogleAuthJson googleAuthJson) {
                Log.d(LOG_TAG, "onInitialOauthComplete " + googleAuthJson);
            }

            @Override
            public void onTokenIdReceived(GoogleAuthTokenJson googleAuthTokenJson) {
                Log.d(LOG_TAG, "onTokenIdReceived " + googleAuthTokenJson);
            }
        };
        new getPoke().execute();
    }

    private class getPoke extends AsyncTask<Void, Void, Void>{
        @Override
        protected Void doInBackground(Void... params){

            try{

                OkHttpClient httpClient = new OkHttpClient();
                PokemonGo go = new PokemonGo(new GoogleCredentialProvider(httpClient, listnr),httpClient);

                // set location
                go.setLocation(-32.058087, 115.744325, 0);

                List<CatchablePokemon> catchablePokemon = go.getMap().getCatchablePokemon();
                Log.v(LOG_TAG, go.getPlayerProfile().toString());
                Log.d(LOG_TAG, "Pokemon in area:" + catchablePokemon.size());

                for (CatchablePokemon cp : catchablePokemon) {
                    // You need to Encounter first.
                    EncounterResult encResult = cp.encounterPokemon();
                    // if encounter was succesful, catch
                    if (encResult.wasSuccessful()) {
                        Log.d(LOG_TAG, "Encounted:" + cp.getPokemonId());
                        CatchResult result = cp.catchPokemonWithRazzBerry();
                        Log.d(LOG_TAG, "Attempt to catch:" + cp.getPokemonId() + " " + result.getStatus());
                    }

                }
            } catch (Exception e){
                Log.d(LOG_TAG, e.toString());
            }


            return null;
        }
    }
}
```

**Comment by AbandonedCart** [comment]
This is confusing, partially because the JavaDoc does not have a clear explanation of the flow and the README has leftover explanations from the previous method. It doesn't help that it is all done in a single step that cannot be performed on the UI thread. Since it is no longer realistic to simply port [the login](https://github.com/Grover-c13/PokeGOAPI-Java/commit/34138099dadf1a813e1a52c44aa1141f33b78189#diff-a3e679b3c0a5286805b20b44ef929733L120) to the app manually, you will need to take a few extra steps.

You will want to have a WebView available and set up BEFORE launching the login process. This way you can post the site URL to it without any issues about doing so while in a background thread. It would be best to put the code the user has to enter into the clipboard. The user can then paste it into the WebView when the page prompts for it.

**Comment by EdbertChan** [comment]
Yes, you should have users enter in the code at that link. I do not know what "Refreshtoken" is in reference to.

You should try to at least look into the function and read it first.

**Comment by AbandonedCart** [comment]
@EdbertChan refresh token is referring to the token used as a "pin" to send when requesting a refreshed token, which is a new token without requiring the entire auth process because the last expired. That would also have been found by reading the function.

**Comment by JohnTendik** [comment]
I'm getting a "GoogleCredentialProvider" unresolved error. Does anyone know why this might be?

**Comment by JohnTendik** [comment]
nevermind I had to update the repo

**Comment by vmarchaud** [comment]
You can use the android oauth flow from google play services to get a refresh token and login you with it or use another google provider, readme is updated from today change.
Closing (reopen if you had more questions)
