### ISSUE TITLE
[Feature Rquest] Limit which MapObjects to fetch

### ISSUE THREAD

**Issue by s7092910** [Grover-c13/PokeGOAPI-Java#261]
I'm not sure if this is possible or not.

**Description:**
When fetching MapObjects, allow developers to decide what MapObjects they require. If the MapObject type is not required, don't fetch it from the Niantic Servers. 

**Example Case:**
If a developer only wants the catchable pokemon, the API should only fetch the catchable pokemon from the Niantic Servers instead of including gym locations and pokestop locations.

**Comment by langerhans** [comment]
GetMapObjectsMessage does not have any parameters to limit this. So there is no way I can think of right now to do this.

edit: well in theory I think the S2 level can somehow "filter" what is returned, but not in a granularity that would be useful I think.

**Comment by Aphoh** [comment]
If I understand correctly this is not possible (although it would be nice). Closing the issue unless something new comes up.
