### ISSUE TITLE
[Feature Rquest] Remove fetching of player data in contructor of PokemonGo.java

### ISSUE THREAD

**Issue by s7092910** [Grover-c13/PokeGOAPI-Java#263]
**Description:**
There shouldn't be fetching of data when creating a PokemonGo object. As not everyone is going to be using that information. Effectively causing unnecessary network requests.

**Comment by Psifour** [comment]
The default branch now includes 900ms of sleeps during this process. While the information is nice to have quick access to I would much prefer to have snappy logins and grab those (as needed) when I am done logging all accounts and doing their startup routines.

**Comment by vmarchaud** [comment]
The majority of our users are using data directly after the construction of the instance, thats why we have done that. But you are right, we shouldnt do this for everyone, maybe that we will implement another constructor that doesnt fetch data directly.

**Comment by Grover-c13** [comment]
Done #388
