### ISSUE TITLE
How to get more pokemons by changing width?

### ISSUE THREAD

**Issue by saurabhjaluka** [Grover-c13/PokeGOAPI-Java#267]
**Description:**
I was looking for getCatchablePokemons given the lat, lon and alt, I see I can only find for a very small area. I want to fetch more, lets pokemons in 1 or 2 miles radius. Then I saw one function getMapObjects(int width), where I can modify the width so I changed it to >9 but I don't see any pokemons coming up.
**Steps to reproduce:**
1. pokemonGo.getMap().getMapObjects(9).getCatchablePokemons(); give me few pokemons
   but when I give width greater than 9 
   pokemonGo.getMap().getMapObjects(12).getCatchablePokemons(); I don't see anything

**Expected behavior:**
If I increase the width, it should return me more pokemons covering more cells

**Actual behavior:**
Observed width > 9 gives 0 pokemons

**Comment by mjmjelde** [comment]
Not possible.  This is a limitation with the game, not the api.  You can only get the catchable pokemon within 1 step of you.  The width on gameObjects is more related to getting pokestops and gyms.  The max value is 9 for getMapObjects()

Edit:  To get pokemon within 1-2 miles of you, you will have to move your position and get the pokemon again and keep looping that till you get the distance you want
