### ISSUE TITLE
What happened to logging into PTC with a token?

### ISSUE THREAD

**Issue by MrPat** [Grover-c13/PokeGOAPI-Java#270]
I've been logging into PTC with a username/password and getting a token from that login. Then I used the token to login afterwards. Today I updated my library and now I can get the PTC login token but there doesn't seem to be a method to login with it. Google still has one but the PTC doesn't. Either that or it was moved to a place that I haven't looked. Anybody know what happened to it? Thanks.

**Comment by vmarchaud** [comment]
Both has been removed (login via access_token, google has login via refresh token), feel free to make a PR to add them to new system, but keep in mind that the token cant be refreshed so the lib will stop running after 15min.
