### ISSUE TITLE
Memory leak somewhere 

### ISSUE THREAD

**Issue by Paul776** [Grover-c13/PokeGOAPI-Java#273]
I'm using the API in an Android project and after about 250h time I call the API the (libc) as a fatal error

This piece of code is submitted in an executor service of 4 thread. nothing problematic about this.

```
OkHttpClient http = new OkHttpClient();
    try {
      PokemonGo pokemonGo = new PokemonGo(authInfo, http);
      pokemonGo.setLatitude(lat);
      pokemonGo.setLongitude(lon);
      pokemonGo.setAltitude(0);
      List<CatchablePokemon> pokemons = pokemonGo.getMap().getCatchablePokemon();
      return pokemons;
  } catch (..)
```

If I submit about 250 of these task at some point I have a fatal crash, 

> A/libc: FORTIFY_SOURCE: FD_SET: file descriptor >= FD_SETSIZE. Calling abort().
> FORTIFY_SOURCE: FD_SET: file descriptor >= FD_SETSIZE. Calling abort().
> A/libc: FORTIFY_SOURCE: FD_SET: file descriptor >= FD_SETSIZE. Calling abort().
> A/libc: FORTIFY_SOURCE: FD_SET: file descriptor >= FD_SETSIZE. Calling abort().
> W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
> W/Google Maps Android API: GLHudOverlay deprecated; draw(): no-op
> W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
> W/google-breakpad: Chrome build fingerprint:
> W/google-breakpad: 4.0
>  W/google-breakpad: 4
>  W/google-breakpad: cc44b2ab-e93c-4e93-9038-0dd354d5b4b4
> W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
> A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 17238 (pool-5-thread-2)

Note that If I remove the API code from the task, the app never crashes, this is how I have isolated the problem to be some problem in the API where .close is not called properly

**Comment by vmarchaud** [comment]
You should remove the httpClient from the thread execution, it cost in memory to instantiate one.

**Comment by Paul776** [comment]
True that was a copy past for the example, http is only created once
Note as well as I'm seeing this issue with the version I build around the 21 of July as I cannot really use the current version with thread at the moment

**Comment by Grover-c13** [comment]
could you get a heap dump?

**Comment by Paul776** [comment]
Trying now

**Comment by vmarchaud** [comment]
@Paul776 any news ?

**Comment by Grover-c13** [comment]
I think this may of been the map cache, cant 100% confirm without heap dump but will close since havent heard back
