### ISSUE TITLE
[Request] Serializable

### ISSUE THREAD

**Issue by Paul776** [Grover-c13/PokeGOAPI-Java#274]
It would be nice if all your object were Serialisable.

And.. you guy should override for ALL your object equals and hashcode.. atm it is a bit of a pain to put these object in Set etc..

**Comment by vmarchaud** [comment]
Already discuted in #137, important class like Pokemon already have equals override, if you want to implement them, feel free to make a PR, but from the old discussion we will not implement all of our object with serializable.
