### ISSUE TITLE
setFavoritePokemon(true) -> ERROR_POKEMON_NOT_FOUND

### ISSUE THREAD

**Issue by stefan-karger** [Grover-c13/PokeGOAPI-Java#280]
**Description:**
setFavoritePokemon(true) always results in a ERROR_POKEMON_NOT_FOUND result for every pokemon that I try

**Steps to reproduce:**
1. call setFavoritePokemon(true)
2. there is no step2 

**Expected behavior:**
the Pokemon will be starred

**Actual behavior:**
the Pokemon is not starred

**Stacktrace (If it's a crash):**
no crash just a result:ERROR_POKEMON_NOT_FOUND

**Version:**
latest dev branch (commit/f281522ab51e44f18225b27bacb35aec7fa82b54)

**Comment by Grover-c13** [comment]
can you git submodule update and test

**Comment by stefan-karger** [comment]
did that and rebuild -> no files changed -> still the same error :(

**Comment by Grover-c13** [comment]
Ok soon as PTC is back up will check

**Comment by jabbink** [comment]
Is online now.

**Comment by Grover-c13** [comment]
https://github.com/AeonLucid/POGOProtos/pull/99/

Has to be uint64, the server doesnt seem to like it as fixed64
