### ISSUE TITLE
[question] new mock time class

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#283]
What's the purpose of it?

apart mocking time of course ;)

it will be nice to have a use case, just to better understand the power of this new facility

**Comment by vmarchaud** [comment]
People used to modify their OS time, so the refresh token doesnt work, so @jabbink decided a make a patch for this.

**Comment by jabbink** [comment]
Yes, exactly that, you'd still need to implement a different time source then, eg. NTP or grabbing the Date header from the login request and add that as an offset. At least with this patch it's possible to use a different time source.
