### ISSUE TITLE
Feature Request: Way to get metadata for whole family

### ISSUE THREAD

**Issue by devinsba** [Grover-c13/PokeGOAPI-Java#286]
I would be nice to have a way to get the metadata for a whole family. I currently have made the meta list public for working locally but thats obviously not a good solution. I may take a crack at this once I finish the feature I am working on but I figured I would report this a low hanging fruit if someone is new to things

**Comment by Grover-c13** [comment]
can you list the information you want per family

**Comment by Grover-c13** [comment]
Closing because i dont really understand what youre requesting, if you provide more details please reopen.
