### ISSUE TITLE
Disable API base logger

### ISSUE THREAD

**Issue by Xstoudi** [Grover-c13/PokeGOAPI-Java#289]
Hey !
Can you add the possibility to totaly disable the API logging ?

Thanks !

**Comment by igoticecream** [comment]
Make a dummy implementation of the Logger interface and call Log.setLogger(dummy)

**Comment by Jari27** [comment]
It will still run the logger when you create an api object, because there's it logs when you've attained a static token.

You can't override that, I think.

**Comment by Aphoh** [comment]
All you have to do is Log.setLevel(Level.ASSERT) and you'll only get errors that truly break the library.

@Sadye You can't currently override that, but you could set the level before calling that function to ASSERT and then set it back to DEBUG or VERBOSE afterwards.

**Comment by Grover-c13** [comment]
#409
