### ISSUE TITLE
How to add this .jar to Android Studio?

### ISSUE THREAD

**Issue by David6390** [Grover-c13/PokeGOAPI-Java#291]
Im triying to execute the example but i can't. 
I added the .jar to the libs folder.
Added compile files('libs/pokego.jar') to my gradle file.

Everything compile and execute with no problem, i put the code for google account and this come up:

Caused by: java.lang.NoClassDefFoundError: POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass$RequestEnvelope$AuthInfo

Anyone know what is going on?, i tried cleaning and rebuilding project with no success.

**Comment by Aphoh** [comment]
Either use jitpack (https://jitpack.io/#Grover-c13/PokeGOAPI-Java/0.2) or clone the source and build the jar yourself. If you choose the latter option don't forget git submodule update --init.

**Comment by vmarchaud** [comment]
We added some explaination on how to import the api into a project in the readme, should be enough to help you.
