### ISSUE TITLE
GoogleCredentialProvider

### ISSUE THREAD

**Issue by adobeSlash** [Grover-c13/PokeGOAPI-Java#293]
Since this morning I get the following error : GoogleCredentialProvider: Get user to go to:null and enter code:null

Anyone else ?

**Comment by keunsy** [comment]
me too ， Looking for a solution

**Comment by spbisya** [comment]
The same error, suppose received json was incorrect. I logged some code and got this
`"error" : "invalid_client"` I think the mistake is in the updated client_id in GoogleLogin class

**Comment by john086** [comment]
I have the same error  Get user to go to:null and enter code:null

**Comment by okynk** [comment]
I try create my own google `CLIENT_ID` and put on the code, and it seems everything working fine..
so I guess, the main problem is on the `CLIENT_ID`

**Comment by john086** [comment]
ok i trying

**Comment by Grover-c13** [comment]
do not change the client id, its a static value that needs to be used so the app can authenticate. You may be able to get pass the auth stage but it should not work in game.

**Comment by okynk** [comment]
that's right, when I try to go in the game, they kicked me out. lol

**Comment by john086** [comment]
yes i understand it, i receive response  with code 401 Unauthorized and all data of authjson is null

**Comment by spbisya** [comment]
I have tried another login method:
`go = new PokemonGo(new PtcCredentialProvider(httpClient,"login@gmail.com","pass"),httpClient);`
Then I've received `Error LoginFailedException **Failed to fetch token**`
Any other variants to get authorized?

**Comment by Grover-c13** [comment]
Ptc is for pokemon trainer account logins and not gmail accounts.

**Comment by Grover-c13** [comment]
GoogleAuthCredentialProvider is now implemented and tested (uses gpsoauth which pretends to act like a phone using googe player services instead of direct oauth flows)  #265

**Comment by thejavatar** [comment]
While GoogleAutoCredentialProvider is great I guess some users would prefer to stick to the previous _token based_ solution. Is that still taken into consideration?

[EDIT]
Btw. great job, providing the fix in such a timely fashion. Thanks!

**Comment by thejavatar** [comment]
Unfortunately this will also fail when 2-step verification is enabled on the Google Account.

**Comment by davinkevin** [comment]
I will like to be able to use the two-step authentication... 😢

**Comment by Grover-c13** [comment]
Not much we can do about it right now sorry

**Comment by davinkevin** [comment]
Ok, thanks...

**Comment by vmarchaud** [comment]
From what i understood, Niantic disabled access via token that we used, i dont think there is other way to login, but we will search for them.
But today, you should use the PTC login or Google via Play Services.

**Comment by Grover-c13** [comment]
#316 adds a new oauth with user interaction

**Comment by daf82hvfe2sfd** [comment]
No need to disable 2 step authentication. Create an app password for your gmail account and enter that without spaces. I just logged in using that method instead of my regular password and it works.

**Comment by john086** [comment]
i receive Response{protocol=h2, code=403, message=, url=https://android.clients.google.com/auth}

**Comment by thejavatar** [comment]
@daf82hvfe2sfd Unfortunately for me, the most important would be to have a separate password for the gmail account and for pokemon-go / application that will use this api.
