### ISSUE TITLE
GoogleCredentialProvider: Get user to go to:null and enter code:null

### ISSUE THREAD

**Issue by jsl303** [Grover-c13/PokeGOAPI-Java#301]
It worked fine, but all of sudden, I started getting this message.
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null
Waiting for the code null to be put in null
Google works fine, Pokemon Go server works fine.
Any solution?
Thanks!

**Comment by Grover-c13** [comment]
something has changed in Niantics developer console, please use GoogleAutomaticAuth provider for now or implement your own oauth flow.

**Comment by jsl303** [comment]
Could you provide some code sample on how to use GoogleAutomaticAuth 
provider?

Thank you!

**Comment by Grover-c13** [comment]
> ```
>       Time time = new SystemTimeImpl();
>         GoogleAutoCredentialProvider cre = new GoogleAutoCredentialProvider(http, "username", "password", time);
>         PokemonGo go = new PokemonGo(cre, http, time);
> ```

**Comment by jsl303** [comment]
Thank you! Where is GoogleAutoCredentialProvider? 
"GoogleAutoCredentialProvider cannot be resolved to a type." 
PokeGOAPI-Java doesn't seem to have it. It's another library I need to 
download? Also, I assume username and password are for my google account?

**Comment by Grover-c13** [comment]
Its currently only on the development branch and not master, and yes your google username and passwords

**Comment by jsl303** [comment]
Thank you! Awesome. That worked!
However, now I have Attempt to catch:GOLDEEN CATCH_ERROR.

**Comment by jsl303** [comment]
GoogleAutoCredentialProvider also stopped working now. I get 
"com.pokegoapi.exceptions.RemoteServerException: 
com.google.protobuf.InvalidProtocolBufferException: Contents of buffer 
are null"

**Comment by vmarchaud** [comment]
@jsl303 This error is thrown because of the official servers sending imparsable data, wait few hours to retry.
