### ISSUE TITLE
time in GoogleAutoCredentialProvider

### ISSUE THREAD

**Issue by jabbink** [Grover-c13/PokeGOAPI-Java#303]
Sorry, on mobile now, but there's a major bug in https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/auth/GoogleAutoCredentialProvider.java

It uses System.currentTimeMillis().

Please refactor to accept an instance of `Timr` in the constructor and deprecate the old constructor.

**Comment by Grover-c13** [comment]
fixed #305
