### ISSUE TITLE
GoogleAuthJson returning null values

### ISSUE THREAD

**Issue by iSach** [Grover-c13/PokeGOAPI-Java#304]
**Description:**
GoogleAuthJson returns null for both URL and Code.

**Expected behavior:**
D/GoogleCredentialProvider: Get user to go to: http://google.com/device and enter code:ABCD-EFGH

**Actual behavior:**
D/GoogleCredentialProvider: 0
D/GoogleCredentialProvider: Get user to go to:null and enter code:null

**Version:**
0.2

**Comment by tguerin** [comment]
Oauth endpoint returns 401, It seems the client id is not valid anymore.

**Comment by Grover-c13** [comment]
Niantic have changed something in their developer console, not a quick fix. Please use GoogleAuoCredentialProvider instead.

**Comment by benjy3gg** [comment]
for me the autocredentialprovider doesnt work too:
Gpsoauth.TokenRequestFailed -> BadAuthentication
