### ISSUE TITLE
Library error while building

### ISSUE THREAD

**Issue by spbisya** [Grover-c13/PokeGOAPI-Java#308]
**Description:**
I tried to build the lib from development branch and now while building my android app I have some mistakes

**Steps to reproduce:**
1. Build the lib and add it to your project, than try to build the .apk

**Actual behavior:**
Build crashes

**Stacktrace (If it's a crash):**
http://pastebin.com/J3ekR9QM

**Version:**
0.2

**Comment by Grover-c13** [comment]
svarzee/gpsoauth-java#1

**Comment by vmarchaud** [comment]
centralized issue in #326
