### ISSUE TITLE
error when google login using googleautocredential 

### ISSUE THREAD

**Issue by okynk** [Grover-c13/PokeGOAPI-Java#312]
**Description:**
when i tried to login via google using the googleautocredentialprovider, it crashed 
this error only happen when I run the app using AWS-EC2

**Steps to reproduce:**
1. in AWS-EC2 instance
2. login google using autocredential

**Expected behavior:**
login to pokemon go

**Actual behavior:**
crashed 

**Stacktrace (If it's a crash):**
http://pastebin.com/vQDyXVEt

**Version:**
latest from development branch

I guess it's because the Gpsoauth lib? but I don't know which one the main problem..

**Comment by Grover-c13** [comment]
svarzee/gpsoauth-java#4

**Comment by benjy3gg** [comment]
@okynk are you able to get a token?

**Comment by okynk** [comment]
@benjy3gg if I ran the app on my pc, yes I could get a token. But when i ran the app on an AWS instance, it crahsed.

@Grover-c13 thanks. so the fastest solution is I need to change the gpsoauth source and change this lib dependencies from jitpack to local lib right?

**Comment by vmarchaud** [comment]
@okynk Yep, or you can use our new provider with google, thats work almost the same that the last one, @Grover-c13 just pushed it few minutes ago.

**Comment by vmarchaud** [comment]
centralized issue in #326
