### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Sectorbob** [Grover-c13/PokeGOAPI-Java#315]
**Description:**
Attempting to build with gradlew, but for some odd reason I am getting compilation errors. I am on the LATEST revision and have made no modifications

**Steps to reproduce:**
1. git cloned the repo
2. ran ./gradlew bundle

**Expected behavior:**
I would assume compilation would be successful and put out a jar

**Actual behavior:**
I get compilation errors as seen in the link below

**Stacktrace (If it's a crash):**
[stacktrace](http://pastebin.com/v2cXtJ82)

**Version:**
[latest commit](https://github.com/Grover-c13/PokeGOAPI-Java/commit/8730a67808797a22f79fd1eed53853ea8abb2ab8)

**Comment by Grover-c13** [comment]
You need to git submodule init, git submodule update beforehand.

**Comment by vmarchaud** [comment]
There is readme, if you read it, you can read that you need to `git submodule update --init` before building.

**Comment by Sectorbob** [comment]
worked like a charm. thank you so much
