### ISSUE TITLE
Possibly un-deprecate methods without Time

### ISSUE THREAD

**Issue by pvanassen** [Grover-c13/PokeGOAPI-Java#319]
Just a suggestion, because the Time interface was added for mocking it is not required. The default implementation is right for most people. Because the old constructors are deprecated it may be lots of people now mimic the deprecated line in their code. 

I get why the Time interface was added but maybe the deprecation of the old methods is a bit too much.

**Comment by vmarchaud** [comment]
Yep, already thought of that on slack, we started to remove them on the dev branch, tell me where we forgot some please

**Comment by pvanassen** [comment]
Updated by branch, Got the changes now. Good job

**Comment by pvanassen** [comment]
Found one, GoogleUserCredentialsProvider has no constructor with just Http client and refresh token. It always requires Time.

**Comment by vmarchaud** [comment]
@pvanassen Yeah i got the commit in local, will push in few minutes ;)

**Comment by vmarchaud** [comment]
commited ;)
