### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by spbisya** [Grover-c13/PokeGOAPI-Java#320]
**Description:**
Trying to build with the latest version of the lib.

**Steps to reproduce:**
1. compile 'com.github.Grover-c13:PokeGOAPI-Java:1ff0e55'
2. Build the app

**Actual behavior:**
It fails

**Stacktrace (If it's a crash):**

```
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class
```

**Version:**
commit 1ff0e55

**Comment by vmarchaud** [comment]
Its because you added two times the same lib into your build file, we are building the jar with all dependency that are needed for the lib to work.
So you should just remove them and keep only our API.

**Comment by spbisya** [comment]
But I added your lib only once. Here is the part of my .gradle file.

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.google.android.gms:play-services-maps:9.2.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.github.Grover-c13:PokeGOAPI-Java:1ff0e55'
}
```

And there are no libs in /libs folder
