### ISSUE TITLE
About lured pokemons (possible solution)

### ISSUE THREAD

**Issue by igoticecream** [Grover-c13/PokeGOAPI-Java#321]
Hello guys, this is an issue of POGOProtos itself but i'd like to discuss it here first.

As we know, there's is not a way to catch lured pokemons (Go to Map.java and check out getCatchablePokemon).

I'm currently using a bot based on an api wrote on c# and i noticed it actually catch lured pokemons. Checking out rocket api and their protos files, i found this:

On message PokemonFortProto, the number 13 points to MapPokemonProto (https://github.com/Maufeat/Pokemon-Go-Rocket-API/blob/master/PokemonGo/RocketAPI/Proto/MapObjectsResponse.proto#L83)

While on POGOProtos's protos the #13 points to FortLureInfo (https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Map/Fort/FortData.proto#L44)

Maybe this's the reason why CatchablePokemon malforms with FortData.

What you think? I'm right? Should i make a pull request to POGOProtos?

**Comment by vmarchaud** [comment]
You should make an issue to discuss it with the POGOProto's guys, but if its work for your C# protos, yes, it should come from here.
(closing since i think that the right place for this issue is in the POGOProtos repos ^^)

**Comment by igoticecream** [comment]
Ok it works, i tested the modified proto and compiled the api and it actually detect lured pokemons. So let's wait the pull request gets merged https://github.com/AeonLucid/POGOProtos/pull/103 and i'll pull some changes i made so getCatchablePokemons includes lured ones.

**Comment by vmarchaud** [comment]
Thanks for helping us with our implementation 👌

**Comment by igoticecream** [comment]
Was going to submit a pull request but someone figure out first.

I can confirm it works

https://github.com/Grover-c13/PokeGOAPI-Java/pull/344

**Comment by ramarro123** [comment]
:)
