### ISSUE TITLE
GoogleAutoCredentialProvider issues centralized

### ISSUE THREAD

**Issue by vmarchaud** [Grover-c13/PokeGOAPI-Java#326]
- java 7 isnt supported : [merged](https://github.com/svarzee/gpsoauth-java/pull/1)
- stackoverflow with regex : [merged](https://github.com/svarzee/gpsoauth-java/pull/4)

Please use the new [google provider](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/examples/GoogleUserInteractionExample.java) (token based) in replacement while waiting for fix. 

UPDATE : need to test their release and will bump our version after.

**Comment by SonnyX** [comment]
When running GoogleAutoCredentialProvider:

```
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:90)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:112)
    ... 4 more
```

**Comment by vmarchaud** [comment]
@SonnyX Not related, that come from the PokemonGo servers that are sending garbage.

**Comment by Jazed** [comment]
Niantic changed things in their API. API is broken atm.

**Comment by benjy3gg** [comment]
but the GoogleUserCredentialsProvider should work?

**Comment by ushort** [comment]
@benjy3gg it is working, at least for me. the problem are api requests like updating profile, catching pokemon, etc..

**Comment by benjy3gg** [comment]
i only need getMap(), does that work?

**Comment by ushort** [comment]
@benjy3gg nope that requests map objects using api so just wait until its fixed :p

**Comment by benjy3gg** [comment]
but its only bugged when using google auth?

**Comment by DrakeSharp** [comment]
Ptc auth, google auth and game are separate things

**Comment by benjy3gg** [comment]
yeah i know
thats why i ask. because in my app, with ptclogin i can call getMap() perfectly right now, only googleaautoauth doesnt work

**Comment by benjy3gg** [comment]
btw is there a slack or discord channel?

**Comment by vmarchaud** [comment]
Please, this issue is only for GoogleAutoCredential, not a chat about Pogo's servers having trouble, if you want there is a slack that you can chat on, all info are on the readme.

EDIT : added link to slack invitation

**Comment by okynk** [comment]
@vmarchaud fyi
https://github.com/svarzee/gpsoauth-java/commit/92c084f06168a3bdc745b3e35472b7a2b8ba342b
https://github.com/svarzee/gpsoauth-java/commit/5dcde304896da3a826817edfcfc7eca538c970f5
i guess this issue fixed ?

**Comment by AbandonedCart** [comment]
Apparently, albeit in an excessive attempt to perform what the two pulls did with minimal overhead.
Also broken. Hangs build at `Configuring > 1/1 projects > Resolving dependencies ':compile'`

**Comment by john086** [comment]
Any news on GoogleAutoCredentialProvider  ? Is only available login with GoogleUserCredentialProvider ?

**Comment by vmarchaud** [comment]
I gonna test the new version later, to see if its working correctly or not.
If its working i will bump the version on the dev branch.

**Comment by john086** [comment]
Great.

**Comment by 4ndro1d** [comment]
Can someone tell me what is the most actual approach for Google login? And can someone set up a proper example? I would be sooo happy :dancers:

**Comment by vmarchaud** [comment]
Closing since it has been merged.
