### ISSUE TITLE
[Request] First login settings

### ISSUE THREAD

**Issue by bolds07** [Grover-c13/PokeGOAPI-Java#330]
Are there any way to deal with the first login settings programatically?
I mean, select skin color, clothes, name, and check that first agreement

If I create a new account, the bot doesn't see any pokestop or catchable pokemon until I go manually throught this first settings

Probably this is not on the roadmap of the API if someone can give me a tip about how to decript the packages and figure by myself the protocol I would be very glad

**Comment by Lasek** [comment]
I didn't test it but check
`go.getPlayerProfile().getAvatar()`
when go is object of PokemonGo. You can use set methods for set eyes, hat, hair.

**Comment by JohnTendik** [comment]
I've heard you can skip the account creation details if you use PT account instead of google account. 

There is also a updatePlayer method 

https://jitpack.io/com/github/Grover-c13/PokeGOAPI-Java/a2828da60d/javadoc/

**Comment by vmarchaud** [comment]
You need to send requests needed to pass throught the tutorial, [like wrote here ](https://docs.google.com/spreadsheets/d/1Xv0Gw5PzIRaVou2xrl6r7qySrcmOKjQWLBjJA73YnJM/edit#gid=0) we didnt planned to implement them for now (for different reasons), if someone want to implement them, feel free to make a PR.

PS : the `updateProfile()` method is used to retrieve latest data from PokeGo servers

**Comment by bolds07** [comment]
I've tried again and now it is working.

**Comment by jay8ee** [comment]
Can you clarify what you did to get this working?
