### ISSUE TITLE
GoogleUserCredentialProvider NoClassDefFoundError

### ISSUE THREAD

**Issue by john086** [Grover-c13/PokeGOAPI-Java#334]
i tryed to use GoogleUserCredentialProvider  but at runtime have this error 

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pokegoapi/auth/GoogleUserCredentialProvider;

Any idea 
**Version:**
last commit

**Comment by Grover-c13** [comment]
Are you using master branch? master currently does not have it only Development

**Comment by john086** [comment]
I use development , now i resolve it... can close
