### ISSUE TITLE
Error Login

### ISSUE THREAD

**Issue by jchunly** [Grover-c13/PokeGOAPI-Java#337]
hi i am trying to connect to the api and gives me error when I want to sign on the line...

PokemonGo go = new PokemonGo(new PtcCredentialProvider(http, ExampleLoginDetails.LOGIN,
ExampleLoginDetails.PASSWORD), http);

the username and password are correct and tells me it can not retrieve the token, there is another way that I can connect.?

**Comment by vmarchaud** [comment]
What error the example is giving to you ?
There is a way to login via google [here](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/examples/GoogleUserInteractionExample.java).

**Comment by jchunly** [comment]
om.pokegoapi.exceptions.LoginFailedException: Failed to fetch token
07-29 13:19:58.087 26461 26480 D   Julian com.jchunly.pokenotificator2          at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:219)
07-29 13:19:58.087 26461 26480 D   Julian com.jchunly.pokenotificator2          at com.pokegoapi.auth.PtcCredentialProvider.<init>(PtcCredentialProvider.java:101)

I changed the login username and password for my password

in the jar file  cant import GoogleUserCredentialProvider

sorry dor my english. i am spanish

**Comment by bolds07** [comment]
Use a browser to try to login at https://sso.pokemon.com/sso/login

if you are not able to login probably your account was banned, I dont know why but some of my accout got banned and I was receiving this same error

**Comment by vmarchaud** [comment]
Yeah try another account, for sure the problem isnt the lib but your account or the PTC servers.

**Comment by jchunly** [comment]
estoy intentando conectarme con GoogleUserCredentialProvider

ya hos comento. gracias por la ayuda
