### ISSUE TITLE
Error getting Map Objects

### ISSUE THREAD

**Issue by joerndyherrn** [Grover-c13/PokeGOAPI-Java#340]
**Description:**
Using the method
`go.getMap().getMapObjects().getPokestops()`
results an error.

**Expected behavior:**
The method should return a list of pokestops on the map.

**Actual behavior:**
An error is the result.

**Stacktrace (If it's a crash):**
http://hastebin.com/inuyalicin.avrasm

**Version:**
Latest (dcaa793)

**Comment by vmarchaud** [comment]
@Zwoerni2000 This error is linked to the fact that Niantic introduced a rate-limit last night, the api isnt handling this yet so you'll need to wait between each request you want to make.
We are working on this #335 but it will take time to make a full operational system.

**Comment by joerndyherrn** [comment]
Thanks for the fast answer, I'll wait :+1:
