### ISSUE TITLE
Thread dies while getting gym info getGymMembers()

### ISSUE THREAD

**Issue by 4ndro1d** [Grover-c13/PokeGOAPI-Java#343]
**Description:**
I am trying to fetch data about a specific gym in my neighborhood. I login using new GoogleUserCredentialProvider.

**Steps to reproduce:**

```
if (poGo != null) {
            poGo.setLocation(48.3097431, 14.2821328, 0);
            try {
                List<Gym> gyms = poGo.getMap().getGyms();
                for (Gym gym : gyms) {
                    if (gym.getName().equals(gymNameAEC)) {

                        AECInfo info = new AECInfo();
                        info.setInBattle(gym.getIsInBattle());
                        info.setTeamColor(gym.getOwnedByTeam().toString());
                        info.setGymLevel(gym.getGymMembers().size());

                        if (listener != null)
                            listener.AECInfoUpdated(info);

                        continue;
                    }
                }
            } catch (LoginFailedException | RemoteServerException e) {
                e.printStackTrace();
            }
        }
```

**Expected behavior:**
I should retrieve the amount of Pokemon inside this gym. It was working before changing to the new GoogleAuth

**Actual behavior:**
Thread dies at this line:  `info.setGymLevel(gym.getGymMembers().size());`

**Stacktrace (If it's a crash):**
com.pokegoapi.exceptions.RemoteServerException
    at com.pokegoapi.api.gym.Gym.details(Gym.java:118)
    at com.pokegoapi.api.gym.Gym.getName(Gym.java:127)
    at alldev.aec.PokeGoHelper.getAECGym(PokeGoHelper.java:125)
    at alldev.aec.PokeGoHelper.run(PokeGoHelper.java:62)
    at java.lang.Thread.run(Unknown Source)

**Comment by 4ndro1d** [comment]
Might not be realted to the method getgymMember(), but to #275

**Comment by 4ndro1d** [comment]
Also not related to #275 but to the for loop I am using? Is gym.getName() calling the server every time in the loop?

**Comment by Grover-c13** [comment]
the name is stored, so its only calling once.  Could the gym have 0 members at the time and is being wrapped by the remote server exception?

**Comment by Grover-c13** [comment]
OH actually, probably the rate limiting by Niantic now, as it will make an extra call to get the Gym details after constructing when calling the related methods (getGymMembers()), please put a sleep of 300ms after getGyms().

We are working on a more ideal solution

**Comment by 4ndro1d** [comment]
I had to add a sleep in each iteration of my loop to avoid it, so I assume .getName() indeed does a server call each time? Looking forward to your solutions

**Comment by Grover-c13** [comment]
yeah sorry just checked, it does too. but once either getName/getGymMembers is called it should be stored on the local object per gym.

**Comment by 4ndro1d** [comment]
Also 300ms weren't sufficient. I went for 500ms, which slows the whole process down pretty much. Just did a little work around and hope that the position in the list doesn't change soon ;D

aec = gyms.get(18);
            if (!aec.getName().equals(gymNameAEC)) {
// do for loop to search
