### ISSUE TITLE
exception in GoogleUserCredentialProvider

### ISSUE THREAD

**Issue by jchunly** [Grover-c13/PokeGOAPI-Java#345]
Hi. Here my code. where token is the string returned by the web Authenticating google .
all code is inside a asytask

OkHttpClient http = new OkHttpClient();
        try{
           GoogleUserCredentialProvider provider = new GoogleUserCredentialProvider(http);
           Scanner sc = new Scanner(token);
           String access = sc.nextLine();
           provider.login(access);
           PokemonGo go = new PokemonGo(provider, http);
        }catch(LoginFailedException e){
            Log.d("Julian","Fallo en el login",e);
        }catch(RemoteServerException e){
            Log.d("Julian","Fallo en el servidor ",e);
        }

Upon reaching the line of pokemon go gives me the following exception .

 com.pokegoapi.exceptions.LoginFailedException: invalid_request
07-29 17:24:41.759 1239 1357 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.auth.GoogleUserCredentialProvider.refreshToken(GoogleUserCredentialProvider.java:159)
07-29 17:24:41.759 1239 1357 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.auth.GoogleUserCredentialProvider.getAuthInfo(GoogleUserCredentialProvider.java:232)
07-29 17:24:41.759 1239 1357 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.api.PokemonGo.getAuthInfo(PokemonGo.java:93)
07-29 17:24:41.759 1239 1357 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.main.RequestHandler.resetBuilder(RequestHandler.java:253)
07-29 17:24:41.759 1239 1357 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.main.RequestHandler.resetBuilder(RequestHandler.java:238)
07-29 17:24:41.759 1239 1357 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.main.RequestHandler.<init>(RequestHandler.java:60)
07-29 17:24:41.759 1239 1357 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:74)

**Comment by jchunly** [comment]
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
07-29 17:54:23.459 5487 5679 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
07-29 17:54:23.459 5487 5679 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
07-29 17:54:23.459 5487 5679 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
07-29 17:54:23.459 5487 5679 D     Julian com.jchunly.pokenotificator2          at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:76)
07-29 17:54:23.459 5487 5679 D     Julian com.jchunly.pokenotificator2

**Comment by vmarchaud** [comment]
You are tying to make too much requests at the same time, just sleep between request.
(for the second strackrace you got)

**Comment by vmarchaud** [comment]
Verify that you are on the latest version of our dev branch, i cant reproduce the problem.

**Comment by medusalix** [comment]
I can reproduce this, I'm not able do call any of the api's methods.

**Comment by jchunly** [comment]
hello may be that all problems have it is that I am intentanto accessed from developing android ???

I can not download the code as the import of da muchisimos code errors with what I have doubts that this code is not adapted to android.

where you could unburden a jar file of the updated library with codes ?

**Comment by medusalix** [comment]
I don't think this is related to Android. I'm developing a standard application and I get this exception.

**Comment by Aphoh** [comment]
@jchunly https://translate.google.com?

**Comment by jchunly** [comment]
I use it. Thank you

**Comment by adobeSlash** [comment]
@vmarchaud  do you know when you are going to release or merge the dev branch with master ?

**Comment by jchunly** [comment]
Hi, I'm testing and I realize that when I try to connect with the same token that gives me the web of google gives me error.

I have to ask every time a new token?
or I have to make a refreshtoken and save it for later connections result?

**Comment by jchunly** [comment]
it increasingly using a different token, it gives me error on the server.
It is possible to download a jar file with the current code because I have one but not the GoogleUserCredentialProvider class and I have to add manually.
If I download all code and add in the project it gives me many mistakes.

a greeting. and thanks for the help.

**Comment by medusalix** [comment]
@jchunly You could use [Jitpack](https://jitpack.io/#Grover-c13/PokeGOAPI-Java/Development-SNAPSHOT), which automatically compiles the code from the Github repo.

**Comment by adobeSlash** [comment]
it's not the dev branch isn't it ?

**Comment by medusalix** [comment]
Yeah, I was just editing it :smile:

**Comment by adobeSlash** [comment]
so @jchunly you have to fork it. 
Just click on fork from the main page, top left

**Comment by vmarchaud** [comment]
testing now.

**Comment by medusalix** [comment]
@adobeSlash It is the dev branch, I edited the link to point to the _Development-SNAPSHOT_ branch.
That's what I'm currently using.

**Comment by vmarchaud** [comment]
lol i didnt see that @svarzee already pushed it, you should be able to get the update by choosing the [last build](https://jitpack.io/#Grover-c13/PokeGOAPI-Java/ef8079b328) over jitpack.

**Comment by vmarchaud** [comment]
So, are we agree that the issue is revolved on the dev branch ?

**Comment by medusalix** [comment]
No, I am using the dev branch and I'm not able to login.

If I login without a token, I get no exception util I call any of the api-functions.

**Comment by FabianTerhorst** [comment]
Im able to sign in with the google login. The only think im not using is the java Scanner object. And android devs should now that this isn´t available for android (obviously).

**Comment by bolds07** [comment]
This is not an issue...

I'm at dev branch, can login with google token, and with ptc login/password

if you can't login right now it's because server is unstable

**Comment by medusalix** [comment]
EDIT: It's working now. Really seems to be a server problem :smile:

Can be CLOSED now :+1:

**Comment by jchunly** [comment]
hola. vuelvo a comentar en este post para decir un detalle del cual me he dado cuenta.

desde esta api no se puede iniciar sesion de google de una cuenta que tenga verificacion en dos pasos. ese era el problema que me estaba dando. lo probe con una cuenta que no tiene verificacion en dos pasos y funciono perfectamente.

una gran enhorabuena a los creadores de la api por tan gran labor. sigo probando casas... un saludo.
