### ISSUE TITLE
[Enhacement] reduce update calls

### ISSUE THREAD

**Issue by bolds07** [Grover-c13/PokeGOAPI-Java#348]
**Description:**
As niantic is limiting the number of received requests i think the api should rationalize the update calls [as everything is cached anyway]. Indeed I think after of create objects the update should only be invoked by user.

Anyway some methods have previsible effects that could save update request as:

pokemon.transfer
pokemon.evolve
renamePokemon
setFavourite

(all those methods are calling updateinventories at the end)

By the way the method catchPokemon send as many requests as pokeballs without any interval

PS. I would like to help with a branch but these lombok annotations break my eclipse, i cant compile nothing with it

**Comment by vmarchaud** [comment]
We are re-writing the api to be able to handle the rate-limit without user having to write specific code, see #335 .
You can make a PR if you want to fix stuff before we get things working.
PS : Google how to install lombok with Eclipse, its pretty simple.

**Comment by Jari27** [comment]
> PS : Google how to install lombok with Eclipse, its pretty simple

Literally download it and run it, then add lombok.jar as an external library.
