### ISSUE TITLE
Feature Requests Activate ITEM_INCENSE_ORDINARY

### ISSUE THREAD

**Issue by jsl303** [Grover-c13/PokeGOAPI-Java#353]
Is there a way to activate ITEM_INCENSE_ORDINARY using the api? Also can you reset the expiration timer? That would be awesome.
Thanks!

**Comment by jaxnb** [comment]
Yes, +1. While you wait,
http://hastebin.com/huzaqakaho.avrasm
This will activate one.

**Comment by vmarchaud** [comment]
like #314 ?

**Comment by jsl303** [comment]
Yes. I assume useItem() is not merged to development yet?

**Comment by Grover-c13** [comment]
Merged now.
