### ISSUE TITLE
Android Studio fails

### ISSUE THREAD

**Issue by segura2010** [Grover-c13/PokeGOAPI-Java#354]
I added the dependencie to gradle, but when i try to compile the app, it gives me the following error:

```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

I read i should enable 'multiDexEnabled' in gradle file, so i did, and now I get the following error:

```
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/squareup/moshi/AdapterMethodsFactory$1.class
```

Anyone knows how to fix it??

**Comment by mzmyslow** [comment]
Try adding in gradle in android:
 `dexOptions {
incremental true
javaMaxHeapSize "4g"
}`
Btw. Did you execute `./gradlew clean` in your project folder ?

**Comment by pdc52** [comment]
Also having this issue, above did not fix.

**Comment by mzmyslow** [comment]
I recommend to check the link: http://stackoverflow.com/questions/16608135/android-studio-add-jar-as-library

**Comment by pdc52** [comment]
Enabling multidex and using the packaging options listed in #362 resolved the issue for me 👍

**Comment by David6390** [comment]
having the same issue but with:

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: svarzee/gps/gpsoauth/AuthToken.class

**Comment by mzmyslow** [comment]
Just download the newest version of API.

**Comment by David6390** [comment]
Which one do you recommend? im using Development-SNAPSHOT

**Comment by mzmyslow** [comment]
@David6390 I also use development. I had the same issue, but they fixed on Friday.

**Comment by David6390** [comment]
I have to be doing something wrong...

I did what it says in #362 also using latest development and get the duplicate entry error with "svarzee/gps/gpsoauth/AuthToken.class"

**Comment by segura2010** [comment]
I have tried and still have the error, now with "svarzee/gps/gpsoauth/AuthToken.class", like @David6390 .

At the moment I am using an old version (0.2) and it works fine, so while it works I wont try to update to the latest version.

I dont know where the problem was introduced :(

**Comment by FabianTerhorst** [comment]
try 

``` groovy
allprojects {
    repositories {
        jcenter()
    }
  }

  dependencies {
    compile 'com.pokegoapi:PokeGOAPI-library:0.3.4'
  }
```
