### ISSUE TITLE
PTC Login

### ISSUE THREAD

**Issue by 607ch00** [Grover-c13/PokeGOAPI-Java#356]
Hi, I'm working on porting the PTC login class over to the PHP version  and I get an error when trying to retrieve the ticket, was hoping someone here might have a hint as to why I can't get make submit the login successfully?

POST /sso/login?service=https%3A%2F%2Fsso.pokemon.com%2Fsso%2Foauth2.0%2FcallbackAuthorize HTTP/1.1 User-Agent: niantic 
Content-Type: application/x-www-form-urlencoded
Host: sso.pokemon.com 
lt=LT-8825043-gAYLPdGPGmyZNBn63F7uo3FHyXfbha&execution=e1s1&_eventId=submit&username=redacted&password=redacted
HTTP/1.1 500 Internal Server Error 
Date: Sat, 30 Jul 2016 09:27:50 GMT 
Server: PWS/8.1.38 
Transfer-Encoding: chunked 
X-Px: nc h0-s6.p1-yyz ( h0-s2043.p9-jfk), nc h0-s2043.p9-jfk ( origin>CONN)
Cache-Control: max-age=5
Content-Type: text/html;
charset=UTF-8
Access-Control-Allow-Origin: https://www.pokemon.com
Access-Control-Allow-Credentials: true
Vary: Accept-Encoding
Connection: keep-alive

**CAS is Unavailable**
There was an error trying to complete your request. Please notify your support desk or try again.

**Comment by vmarchaud** [comment]
You should check over [this repo](https://github.com/NicklasWallgren/PokemonGoAPI-PHP/tree/master/src/Authenticators), already implemented a php version and from what i saw its working. 
And our java implementation is [right there](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/auth/PtcCredentialProvider.java), you can check the difference between your code and ours.

**Comment by 607ch00** [comment]
Thanks, must be the http library I'm using. Tried a different one and I got it working!
