### ISSUE TITLE
Not sure how to include this as a maven dependency

### ISSUE THREAD

**Issue by thedewpoint** [Grover-c13/PokeGOAPI-Java#36]
Can you update the documentation to show which maven dependency I should include in my project.

Thank you

**Comment by Grover-c13** [comment]
Hi,

we have jitpack that you should be able to use with maven: 
https://jitpack.io/#Grover-c13/PokeGOAPI-Java/master-SNAPSHOT

**Comment by thedewpoint** [comment]
Awesome thanks so much
