### ISSUE TITLE
bag.getItemsCount() Doesn't Update?

### ISSUE THREAD

**Issue by jsl303** [Grover-c13/PokeGOAPI-Java#361]
Whenever I loot a poke stop, I have this code:
System.out.println(res.getItemsAwarded().size()+" items received, total "+bag.getItemsCount()+" items");
However, I get this:
3 items received, total 147 items
4 items received, total 147 items
3 items received, total 147 items
4 items received, total 147 items
4 items received, total 147 items
3 items received, total 147 items
I did not spend any balls or potions between.

**Comment by vmarchaud** [comment]
Yes, currently you need to update the inventory to retrieve the news items, we didnt update the cache that we have in memory.

**Comment by jsl303** [comment]
How do you update the inventory?

**Comment by vmarchaud** [comment]
check [here](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/api/inventory/Inventories.java#L94)

**Comment by jsl303** [comment]
Great, thanks! update() worked!
