### ISSUE TITLE
Android Studio | Duplicate file exception 

### ISSUE THREAD

**Issue by Ivolutio** [Grover-c13/PokeGOAPI-Java#362]
**Description:**
I have been trying to get he API working in my Android Studio project, but it keeps giving me this error (see "Actual Behaviour"). The previous versions did work, but those don't have the  GoogleUserCredentialProvider class, which the example in the readme uses (which I've been trying to use). 

**Steps to reproduce:**
1. Click 'run 'app''
2. Wait

**Expected behavior:**
A succesfull build of the apk

**Actual behavior:**
The build fails with the following error:

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK google/protobuf/struct.proto
    File1: C:\Users\USER\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protobuf-java\3.0.0-beta-3\ed8c2f9a63cfa770292f8173fd0172bdaa014fe3\protobuf-java-3.0.0-beta-3.jar
    File2: C:\Users\USER\.gradle\caches\modules-2\files-2.1\com.github.Grover-c13\PokeGOAPI-Java\Development-SNAPSHOT\8f92629f10b5a44f9ce68834b543a2732b833773\PokeGOAPI-Java-Development-SNAPSHOT.jar
```

**Version:**
Latest snapshot, via Jitpack `com.github.Grover-c13:PokeGOAPI-Java:Development-SNAPSHOT`

**Comment by FabianTerhorst** [comment]
Can you post your App build.gradle file

**Comment by Ivolutio** [comment]
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.ikstream.android.pokefinder"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.github.Grover-c13:PokeGOAPI-Java:Development-SNAPSHOT'
}

```

**Comment by cesco89** [comment]
try this:
`packagingOptions {
        exclude 'META-INF/maven/com.squareup.moshi/moshi/pom.properties'
        exclude 'META-INF/maven/com.squareup.moshi/moshi/pom.xml'

```
    exclude 'META-INF/maven/com.google.protobuf/protobuf-java/pom.xml'
    exclude 'META-INF/maven/com.google.protobuf/protobuf-java/pom.properties'
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE.txt'
    exclude 'META-INF/maven/com.squareup.okio/okio/pom.xml'
    exclude 'META-INF/maven/com.squareup.okio/okio/pom.properties'

    exclude 'META-INF/maven/com.squareup.okhttp3/okhttp/pom.properties'
    exclude 'META-INF/maven/com.squareup.okhttp3/okhttp/pom.xml'

    exclude 'META-INF/maven/com.annimon/stream/pom.properties'
    exclude 'META-INF/maven/com.annimon/stream/pom.xml'

    exclude 'META-INF/maven/net.iharder/base64/pom.xml'
    exclude 'META-INF/maven/net.iharder/base64/pom.properties'

    pickFirst 'gpsoauth.properties'
    pickFirst 'google/protobuf/any.proto'
    pickFirst 'google/protobuf/field_mask.proto'
    pickFirst 'google/protobuf/plugin.proto'
    pickFirst 'google/protobuf/compiler/plugin.proto'
    pickFirst 'google/protobuf/api.proto'
    pickFirst 'google/protobuf/descriptor.proto'
    pickFirst 'google/protobuf/wrappers.proto'
    pickFirst 'google/protobuf/type.proto'
    pickFirst 'google/protobuf/struct.proto'
    pickFirst 'google/protobuf/timestamp.proto'
    pickFirst 'google/protobuf/source_context.proto'
    pickFirst 'google/protobuf/duration.proto'
    pickFirst 'google/protobuf/empty.proto'




}`
```

i'm compiling with this version:
`compile 'com.github.Grover-c13:PokeGOAPI-Java:2b05b2638d'`

**Comment by Ivolutio** [comment]
That worked. Thank you very much! It also works with the Development-SNAPSHOT version :smile:

**Comment by coder04** [comment]
I am trying to run my project but whenever i run it i get this error

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK AUTHORS
	File1: C:\Program Files\Android\Android Studio\gradle\m2repository\com\android\tools\external\lombok\lombok-ast\0.2.3\lombok-ast-0.2.3.jar
	File2: C:\Program Files\Android\Android Studio\gradle\m2repository\com\android\tools\external\lombok\lombok-ast\0.2.3\lombok-ast-0.2.3.jar

**Comment by AbandonedCart** [comment]
I am getting some weird corruption in the posted content, so hopefully it's only me.

@coder04 This was an issue with two separate imports containing the same file. Your issue is with an external library that may have duplicate contents or was imported twice. See https://github.com/Grover-c13/PokeGOAPI-Java/issues/924
