### ISSUE TITLE
Logging in with PTC yields strange excpetion

### ISSUE THREAD

**Issue by slycoderr** [Grover-c13/PokeGOAPI-Java#364]
When I call the following code:

```
OkHttpClient client = new OkHttpClient();
RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo` authInfo = new PTCLogin(client).login("user", "pass");
PokemonGo go = new PokemonGo(authInfo, client);
```

the constructor for Pokémon Go crashes with the following error: 

{"Index: 20, Size: 10"}

Stacktrace:

   at com.pokegoapi.main.RequestHandler.sendServerRequests()
   at com.pokegoapi.api.PokemonGo.getPlayerAndUpdateInventory(PlayerProfile )
   at com.pokegoapi.api.PokemonGo.getPlayerProfile(Boolean forceUpdate)
   at com.pokegoapi.api.PokemonGo.getPlayerProfile()
   at com.pokegoapi.api.PokemonGo..ctor(AuthInfo auth, OkHttpClient client)

**Comment by vmarchaud** [comment]
You are using the master branch that havent been updated for a week now almost, please use the dev branch.

**Comment by slycoderr** [comment]
Hmm I cloned the repo and compiled the source. Same issue occurs. I did convert the jar to a dll with ikvm if that is relevant.

**Comment by vmarchaud** [comment]
The PTCLogin class doesnt exist on the dev branch, so you are not on the dev branch for sure.

**Comment by slycoderr** [comment]
I used the sample and was able to compile this:

```
            var client = new OkHttpClient();
            var prov = new PtcCredentialProvider(client, "user", "pass");
            var go = new PokemonGo(prov, client);
```

Is this the correct usage?

**Comment by vmarchaud** [comment]
Yes.

**Comment by slycoderr** [comment]
<img width="258" alt="capture" src="https://cloud.githubusercontent.com/assets/5349436/17271661/9adcb4a0-564f-11e6-9123-14ee7f2ec101.PNG">

I'm fairly certain im on the dev branch, ill keep messing with it.

**Comment by vmarchaud** [comment]
Dont know your IDE, be i'm sure of what we commited last week, or even check on github the code, the dev branch example are up to date.
