### ISSUE TITLE
Can't get any informations from .getMap().getMapObjects()

### ISSUE THREAD

**Issue by bitcasst** [Grover-c13/PokeGOAPI-Java#365]
**Description:**
I'm trying to show information from .getMap().getMapObject and I always have a list with 0 element.

**Steps to reproduce:**
1. Connect using PtcCredentialProvider (username, password)
2. Set location (setLocation(longitude, latitude, altitude))
3. Try to get nearbyPokemons (getMap().getMapObjects().getNearbyPokemons())
4. get an empty list

**Expected behavior:**
I should have atleast 1 pokemon in the list (I tried with couples of location. I always get 0 result. But, if I try with the app I see pokemon at this exact location)

**Actual behavior:**
I get an empty list

**Stacktrace (If it's a crash):**
N/A

**Version:**
SHA: 6cec95d127f41b8809be4907ef9fe2c0567eb33b (30-07-2016)

**Other info:**
.getPlayerProfile().getStats().getPokemonsCaptured() is working.

**Comment by vmarchaud** [comment]
Try to use `getMap().getCatchablePokemons()` and tell me if its working ?

**Comment by SippieCup** [comment]
I have been investigating this for a few hours now, its similar to a softban. However rather than having Pokemon Flee or Pokestops not work, the server will just tell you there is nothing around.

It could also be due to a change in the server architecture by Niantic, they could be sharding locations much more aggressively and causing caching issues for people who teleport.

https://github.com/SwipeX/PokeMate/issues/221#issuecomment-236373938

**Comment by bitcasst** [comment]
@vmarchaud 
I have the same results with : 
getCatchablePokemons:0
getSpawnPoints:0
getDecimatedSpawnPoints:0
getGyms:0
getNearbyPokemons:0
getPokestops:0
getWildPokemons:0

**Comment by bitcasst** [comment]
@SippieCup interesting.. I'll keep investigating.. thanks!

**Comment by bolds07** [comment]
Server is unstable, everybody using this api shall have an extra account, when your tests fail on your official account you test the extra accoount... this will reveal any ban or account related problem

I was having this situation on 80 accounts i've during today... so i created a new one and realized the problem wasn't with me

**Comment by bitcasst** [comment]
I just created a new account to test it. I have the same issue. Also, I should have mentioned that it never worked for me.

I'm not trying to do anything special here's a short example of what I'm trying to do.
http://pastebin.com/A7YaNrvK

**Comment by bolds07** [comment]
@bitcasst As I said I'm having the same situation on 81 accounts today... so the problem isn't you is the server. if you want to check you can let this query in a loop and see that at some moment it suddenly works

**Comment by jian-yang** [comment]
I have the same issue. ...

**Comment by bitcasst** [comment]
I just realised I inverted my lat / long coord. I was trying to find pokemon on Antartica... Well there's none at this place.
