### ISSUE TITLE
[Question] pokemon.transferPokemon have a limit

### ISSUE THREAD

**Issue by bolds07** [Grover-c13/PokeGOAPI-Java#366]
**Description:**
Sometimes i get successively UNSET return from transferPokemon method... the pokemon isn't in a gym and i always wait 3 secods between calls, but the method continues returning unset [and pokemon is transfered] and usually it happens simultaniously for lots of pokemons at same user.

So, the question is, are there any limit for amount pokemons i can transfer at once? does anyone have idea about this problem?

**Comment by Lasek** [comment]
I can't reproduce this problem. How big is the amount of pokemon to transfer? I tested with 40 and it works.

**Comment by bolds07** [comment]
indeed im not doing a batch transfer, i just keep runing the bot, capturing and replacing the worst pokemons, and at some moment the transfer start return unset for every try

**Comment by bolds07** [comment]
I got the problem...

The thing is if you try to create a Pokemon instance with PokemonData got from a CatachablePokemon [after you catch it] you will get an unusable instance because the Pokemon.data.id was not seted yet.

The solution is to set the pokemon id in pokemonData with the value got in catchPokemonResult getCapturedPokemonId

I tested and it works and in this way you dont need to update the pokemonBank just to transfer any pokemon you caught.

THE PROBLEM is that PokemonData class is automatic generated from protobuf files, and it doesn't have a set method to id attribute [i needed to use reflection to test]

I will open an enhancement to add id

**Comment by vmarchaud** [comment]
You are using it wrong, you must refresh the inventory and after transfering it.
