### ISSUE TITLE
[Question][Android] Getting "Protocol message contained an invalid tag (zero)" after Login

### ISSUE THREAD

**Issue by cesco89** [Grover-c13/PokeGOAPI-Java#367]
i successfully loggen in using google token and stored the refreshtoken, anyway, after this message:
`D/GoogleUserCredentialProvider: Refreshed Token
D/RequestHandler: Authenticated with static token`

i get always this one from ProtoBuf:
`com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).`

Here is the code (inside an asynctask):
` try {
        CredentialProvider auth = new GoogleUserCredentialProvider(httpClient,  PrefsUtils.getRefreshToken(getActivity()));
        go = new PokemonGo(auth, httpClient);
        go.getPlayerProfile().getUsername();

```
  } catch (LoginFailedException e) {
    e.printStackTrace();
  } catch (RemoteServerException e) {
    e.printStackTrace();
  } `
```

Is there a possible solution i'm missing? 

i'm using the latest build available from jitpack:
`compile 'com.github.Grover-c13:PokeGOAPI-Java:2b05b2638d'`

thanks!

**Comment by vmarchaud** [comment]
Niantic introduced a rate-limit, you must be sending request too fast, please sleep between them or wait for #360 OR #357 to be merged.
