### ISSUE TITLE
Problem with INCUBATOR_ALREADY_IN_USE after eggs hatched

### ISSUE THREAD

**Issue by davinkevin** [Grover-c13/PokeGOAPI-Java#369]
**Description:**
If I try to put an egg in an incubator previously used, I got this error `INCUBATOR_ALREADY_IN_USE` in the `hatchEgg` method. It seems the fact I don't trigger the animation in the app doesn't free the incubator.

**Steps to reproduce:**
1. Put an egg in a incubator
2. Walk until the `e.getEggKmWalked() < e.getEggKmWalkedTarget()` where e is the egg
3. Try to put a new egg in the incubator

**Expected behavior:**
I should have an new egg in the incubator.

**Actual behavior:**
The system says nothing (not even an exception), The `UseItemEggIncubatorResponse#toString()` let appears a `INCUBATOR_ALREADY_IN_USE` string. 

**Stacktrace (If it's a crash):**
No stackTrace, just a capture of the response where I got the error
![image](https://cloud.githubusercontent.com/assets/1970922/17271801/1b5ce704-5686-11e6-92b2-e8eb657e9917.png)

**Version:**
2b05b2638d8abdca7f717d14db49b461c63308c0

**Code:**

```
public List<EggPokemon> incubate() {
        List<EggIncubator> emptyIncubator = List
                .ofAll(go.getInventories().getIncubators())
                .filter(i -> !i.isInUse());

        List<EggPokemon> newlyIncubatedEggs = List.empty();

        for (EggIncubator eggIncubator : emptyIncubator) {
            List<EggPokemon> availableEgg = List.ofAll(go.getInventories().getHatchery().getEggs())
                    .filter(REMOVE_READY_EGG)
                    .sorted(EGG_POKEMON_COMPARATOR)
                    .filter(ARE_NOT_INCUBATING)
                    .reverse();

            if(availableEgg.isEmpty())
                return newlyIncubatedEggs;

            EggPokemon egg = availableEgg.get(0);

            newlyIncubatedEggs = newlyIncubatedEggs.push(egg);
            RetryUtils.retry(() -> eggIncubator.hatchEgg(egg)); //This operation didn't fail but didn't change the egg in the incubator.
        }

        return newlyIncubatedEggs;
    }
```

**Comment by vmarchaud** [comment]
Before re-using hatchEgg with another egg, you must ask the servers to confirm the hetch using `getHatchery().queryHatchedEggs()` and hatch a new egg into the incubator.

**Comment by davinkevin** [comment]
Sorry, I didn't found this... thanks for the answer 😄
