### ISSUE TITLE
spawnPoints / decimatedSpawnPoints

### ISSUE THREAD

**Issue by DominikTrenz** [Grover-c13/PokeGOAPI-Java#37]
Just for clarification:
I assume spawnpoints are the coordinates where it is possible that pokemons spawn, am i right? What's the difference between spawnPoints and decimatedSpawnPoints?

**Comment by jabbink** [comment]
As far as we know, this isn't entirely certain.

Last I heard/guessed was spawn being a potential spawn (XM in Ingress) and decimated would be a "depleted" spawn that is no longer valid and only sent so a potential client can remove it from the list/UI?

For now, just use the information of Wild/Nearby/Catchable pokemon to realiably find Pokemon.
