### ISSUE TITLE
Usage Example Incorrect

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#371]
In the README.md, the Usage Example does not seem to reflect how to use the API correctly, and has general errors as well. For instance:
- OkHttpClient variable is declared as "httpClient", but is used as "http" in the example code
- GoogleUserCredentialProvider is not a class that actually exists, however GoogleCredentialProvider, is. 
- GoogleCredentialProvider does not have a LOGIN_URL field
- GoogleCredentialProvider instances do not have a constructor that takes a string

Unfortunately, this is as far as I was able to get before I stopped. The example code only uses PTC login methods, and google auth code is commented out, but when uncommented, generates compile errors, due to listner not being defined. This creates a couple of gaps in knowledge of how to use the API.
- I do not know what the URL to obtain an auth token from
- I do not know where to provide the GoogleCredentialProvider with the auth token when/if i get it
- I know that i am supposed to implement the GoogleCredentialProvider listener myself, but I am not sure how i am supposed to react to these events.

I can only assume that onTokenIdReceived will be called when the servers give us the auth token for future use, but i'm not sure what onInitialOAuthComplete does.

I am fairly lost here :S Can we please get an updated README.md?

**Comment by Jasper-ketelaar** [comment]
I think you're working from an outdated version. I have GoogleUserCredentialProvider etc..

**Comment by medusalix** [comment]
Yes, you have to choose the _Development_ branch.

**Comment by vmarchaud** [comment]
I take always the time to update the readme after ALL major apis update just after pushing it, please verify next time.
