### ISSUE TITLE
HatchedEgg#getId() returns nonsenical data

### ISSUE THREAD

**Issue by Jasper-ketelaar** [Grover-c13/PokeGOAPI-Java#373]
HatchedEgg.getId() returns a value that is negative and nonsensical. 
Example value: -192030004

**Comment by vmarchaud** [comment]
The negative arent truly real, its just that :

We are using fixed64 -> unsigned long
Java dont support support printing unsigned long (you can make operation with it but you cant print it without going overflow)

So if you want to print them, you should either :

use java 8 :
- Long.toUnsignedLong(var) or Long.parseUnsignedString(str)
- use a lib that could handle this for you (dont know if it exist)
- write your own functions to do it.

**Comment by Jasper-ketelaar** [comment]
Then how do I get a PokémonId instance from the long value? I tried using forNumber but it doesn't work.

**Comment by vmarchaud** [comment]
You cant, the getId() from Pokemon object is a unique id, no other pokemon has the same.
There is a method : getPokemonId() that return the type of Pokemon that you are searching for

**Comment by Jasper-ketelaar** [comment]
I see. So the only way to find out which pokemon was hatched is by checking recent pokemon?

**Comment by vmarchaud** [comment]
Nope there is a method Hatchery.queryHatchedEggs that will ask the server :)

**Comment by Jasper-ketelaar** [comment]
I know I'm using Hatchery.queryHatchedEggs but the data returned doesn't contain pokemon id except for that unique ID you mentioned :/

**Comment by vmarchaud** [comment]
you need to queryHatchedEggs, update the inventory, and the id of the HatchedEgg should correspond to a pokemon in your inventory.
