### ISSUE TITLE
RequestHandler uses non-deamon threads

### ISSUE THREAD

**Issue by noxone** [Grover-c13/PokeGOAPI-Java#378]
**Description:**
The class com.pokegoapi.main.RequestHandler contains a ExecutorService created by Executors.newFixedThreadPool(1). This leads to a non-daemon thread preventing the normal application shutdown.

**Steps to reproduce:**
Just log in successfully... the thread will then be there.

**Expected behavior:**
The thread should be a daemon thread.

**Version:**
using jar packed by jitpack from push 3df35da

**Comment by jjordantb** [comment]
Perhaps I'm misunderstanding something but I don't see why you would want it to be a daemon thread...? Make them daemon and it won't shutdown properly.

**Comment by Aphoh** [comment]
What exactly do you mean when you say normal application shutdown? Shouldn't the application close all threads in the process like normal?

**Comment by svarzee** [comment]
I've observed the same issue but I'd rather have PokemonGo implement Closeable

**Comment by Jari27** [comment]
@Aphoh If the `public void main()`method exits, it doesn't close the requesthandler thread if it's not a daemon.

**Comment by Aphoh** [comment]
Ideally the RxJava pr will get merged and we wont have to worry about crazy threading stuff. I'm not too experienced in threading (android and rx is my specialty) so I can't speak much to this issue.
@Grover-c13 Do you have any thoughts?

**Comment by Grover-c13** [comment]
Yeah ive noticed this issue too. Will fix sometime, probably as @Sadye suggests

**Comment by pvanassen** [comment]
The Runnable in the threadpool should stop if it receives an interruptedexception which happens at shutdown. On my app, when I send a shutdown signal, the thread indeed stops itself within a few seconds.

**Comment by Jari27** [comment]
Whoever is currently working with this, take a look at this.

[http://stackoverflow.com/questions/13883293/turning-an-executorservice-to-daemon-in-java](http://stackoverflow.com/questions/13883293/turning-an-executorservice-to-daemon-in-java)

**Comment by pvanassen** [comment]
Basically the same as starting a thread manually. Wasn't using any of the extra methods of the executor anyways.

**Comment by Jari27** [comment]
If you start a thread manually you can do `myThread.setDaemon(true)`

**Comment by pvanassen** [comment]
@Sadye Check https://github.com/Grover-c13/PokeGOAPI-Java/pull/392/commits/d13b8e1f0a0da1dcda2b0478da31643e4f0c5362
It's already in Development

**Comment by Jari27** [comment]
So this should be closed then.

@Grover-c13 
@jabbink 
@Aphoh 
@vmarchaud

**Comment by Grover-c13** [comment]
Yes ty
