### ISSUE TITLE
[Enhancement] add setId method in PokemonData class

### ISSUE THREAD

**Issue by bolds07** [Grover-c13/PokeGOAPI-Java#379]
**Description:**
I was trying to transfer a recent caught pokemon without update the pokemonBank 
PokemonData data = encResult.getWildPokemon().getPokemonData();
Pokemon p = new Pokemon(this.api, data);
p.transferPokemon();

The code above doesn't work because the pokemonId in data class isn't seted yet. The way to make it works is setting data.id with the result of catchPokemon().getCapturedPokemonId() (it works I tested)

THE PROBLEM is PokemonData class is automatic generated from protobuf files, and it have no setId method

**Comment by vmarchaud** [comment]
Nope, these files are generated by protobuf, we cant change them.
You should use the raw RequestHandler to send a custom packet to make it evolve and set the pokemonId from here, check the README.md for an example on how to send request with RequestHandler.

**Comment by bolds07** [comment]
Well, i dont know how is the mechanism to generate the java from protobuf, maybe there is a way to make the compiler to create getters and setters for all attributes.

Anyway is possible bypass this situation with Reflection [in my code]

or just copy paste, the actual api code to transfer the pokemon...

I was justsuggesting a better way
