### ISSUE TITLE
Importing Project into Intellij

### ISSUE THREAD

**Issue by jjordantb** [Grover-c13/PokeGOAPI-Java#381]
I've been trying to get this to work for hours and idea's docs are terrible for gradle, and I can't f*****\* take it anymore.
1. Fork Project
2. File -> New -> Project From Version Control -> Github
3. Enter your master password
4. Paste in the clone link "https://github.com/jjordantb/PokeGOAPI-Java.git"
5. Clone
6. "Unlinked Gradle project" popup -> Import Gradle Project
7. "Import Project from Gradle" window pops up
8. Select Use auto-import
9. Project imports
10. Attempt to Build -> Rebuild Project
11. Get 100 errors saying POGOProtos does not exist. (protobuff library isn't recognized)

Things I've tried:
- Building from command line
- Clean building from command line
- ./gradlew idea
- updating git sub-repos
- every other import option
- updating gradle
- updating intellij
- refreshing gradle libraries
- invalidating cache and restarting
- deleting .iml and .idea 

Running ubuntu 16.04 64bit, oracle java 8, gradle 2.14.1

I give up, someone help please, I'm begging. I hope this is enough information.

**Comment by FabianTerhorst** [comment]
you don´t read the readme? git submodule update --init

**Comment by jjordantb** [comment]
"updating git sub-repos" i did it

**Comment by mashurex** [comment]
What version of IDEA are you running? I'm running the latest and it worked for me immediately. I cloned from the command line and and then created a new project from existing sources.

**Comment by jjordantb** [comment]
Latest version of 2016.2, ill try it by cloning it through command line and then importing it

**Comment by mashurex** [comment]
Also, you'll want to install the Lombok plugin if you haven't already.

**Comment by mashurex** [comment]
I wonder if it's because you need to do a git submodule update --init and IDEA probably doesn't do it.

**Comment by meher19** [comment]
i'm running in the same environnement, after the "git clone" or "git pull" you have to run "git submodule update --init"
After this i built the gradle projet in Intellij and that's worked for me. I'm using Intellij Ultimate 2016.1.3

**Comment by FabianTerhorst** [comment]
@meher19 for me this worked as well. Im using android studio 2.2 p6.

**Comment by jjordantb** [comment]
I did install the lombok plugin.

I,
"git clone https://github.com/jjordantb/PokeGOAPI-Java.git"
"git submodule update --"
Then import it into intellij, and it's still not working. I'm going to try and mess around with my gradle install

**Comment by FabianTerhorst** [comment]
pokegoapi-java is providing a own gradle wrapper-

**Comment by jjordantb** [comment]
Wish I new what I did, but it works now. Pretty sure pulling through idea was the biggest of a series of problems.
