### ISSUE TITLE
No Pokemon in Latest Commit?

### ISSUE THREAD

**Issue by jsl303** [Grover-c13/PokeGOAPI-Java#382]
catchablePokemon = map.getCatchablePokemon();
catchablePokemon.size()  is always 0.
How do you use the latest commit properly?
I read you don't need to insert sleeps anymore.
How do you check how many commands in the queue?
Lastly, what are all the ...async functions?
Thanks!

**Comment by Grover-c13** [comment]
async means it doesnt block, you provide a callback when the response is ready.

Im looking into the pokemon issue now

**Comment by jsl303** [comment]
Thanks!

How do I make sure I don't overload the request queue in the latest commit?

**Comment by Grover-c13** [comment]
the api should handle it for you

**Comment by jsl303** [comment]
How does it exactly handle it?
Suppose if I send inventory.update(), pokestop.loot(), or map.getCatchablePokemon() every ms. Does it filter out and ignore unnecessary requests? 
Then how do I make sure certain commands are executed?
Thanks!

**Comment by Grover-c13** [comment]
It wont ignore anything (that would be awful :P), basically there are now async calls that return futures you can use, while all the old methods use wrappers that wait for the async call. The request handler is on its own thread and schedules things.

**Comment by Grover-c13** [comment]
Pokemon should appear now in PR #386
