### ISSUE TITLE
Feature Request Travel Function with Interpolated Points

### ISSUE THREAD

**Issue by jsl303** [Grover-c13/PokeGOAPI-Java#384]
Can we have a function where we can specify a destination coordinate and a speed or time instead of teleporting instantly? Api can travel to the destination while sending the interpolated points between the current and the destination to the server.
public void travel(double latitude, double longitude, double speed)
public void travel(double latitude, double longitude, long time)
The second function will automatically calculate and use the speed that will get you to the destination at the specified time.
This would be awesome! Thanks always!

**Comment by FabianTerhorst** [comment]
This is out of scope for this Library. It's a Java Library for Pokémon go, not a Pokémon go bot.
