### ISSUE TITLE
pokestop.canLoot() always reports true?

### ISSUE THREAD

**Issue by jsl303** [Grover-c13/PokeGOAPI-Java#385]
Does lootability doesn't guarantee you'll receive something?
pokestop.canLoot() reports true even though I just looted.
Then result.getItemsAwarded().size is 0.
At least I get size of 0 way more frequently than the previous commit.
Thanks!

**Comment by Jari27** [comment]
You need to force-update the map first, I think.

**Comment by Grover-c13** [comment]
are you checking the result of the loot? could your bag be full?

**Comment by jsl303** [comment]
I have this before loot.

stops = map.getMapObjects().getPokestops();

How would you force update the map?
Thanks!

**Comment by Grover-c13** [comment]
when you test next please print out the Result of the PokestopLootResult object 

> ie: pokestop.loot().getResult()

**Comment by jsl303** [comment]
The result says out of range, but canLoot() returns true.

**Comment by jsl303** [comment]
I check if (stop.inRange() & stop.canLoot()) before looting. However, 
result still indicates cooling off or out of range.

**Comment by FabianTerhorst** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/map/fort/Pokestop.java#L102 there is a range check now.
