### ISSUE TITLE
getCatchablePokemon returns empty/not a full list of pokemon

### ISSUE THREAD

**Issue by TheLushpen** [Grover-c13/PokeGOAPI-Java#394]
I'm getting pokemons by PokemonGo.getMap().getCatchablePokemon. But it returns empty/not a full list of pokemon. How to get it all? Sorry for stupid question.

**Comment by Grover-c13** [comment]
Are you on master branch?

**Comment by LinkOut** [comment]
They changed api or someting?   Or maybe the delay between requests, under a certain time they might ignore?

**Comment by TheLushpen** [comment]
I use compile 'com.github.Grover-c13:PokeGOAPI-Java:0.2'

**Comment by Grover-c13** [comment]
Yeah they introduced several changes server side, request limiting, restricting amount of cells sent etc, which broke the number of pokemon showing up. Most these issues have been fixed on dev branch. We will push 0.3 up to master hopefully tomorrow.

**Comment by TheLushpen** [comment]
Thanks
