### ISSUE TITLE
Creation of PokemonGo class instance throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by romanzes** [Grover-c13/PokeGOAPI-Java#395]
**Description:**
Creation of PokemonGo instance throws IndexOutOfBoundsException

**Steps to reproduce:**
1. Run this code on **Android**:

``` java
OkHttpClient httpClient = new OkHttpClient();

GoogleUserCredentialProvider provider = new GoogleUserCredentialProvider(httpClient);

provider.login("working token here");
PokemonGo go = new PokemonGo(provider, httpClient);
```

**Expected behavior:**
This code should run without errors

**Actual behavior:**

Exception occurs

**Stacktrace (If it's a crash):**

> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err: java.lang.IndexOutOfBoundsException: Beginning index larger than ending index: 0, -1621147904
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.google.protobuf.ByteString.checkRange(ByteString.java:1215)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.google.protobuf.ByteString.copyTo(ByteString.java:595)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.google.protobuf.CodedInputStream.tryRefillBuffer(CodedInputStream.java:1101)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:1035)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:139)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at POGOProtos.Networking.Responses.GetPlayerResponseOuterClass$GetPlayerResponse.<init>(GetPlayerResponseOuterClass.java:62)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at POGOProtos.Networking.Responses.GetPlayerResponseOuterClass$GetPlayerResponse.<init>(GetPlayerResponseOuterClass.java:36)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at POGOProtos.Networking.Responses.GetPlayerResponseOuterClass$GetPlayerResponse$1.parsePartialFrom(GetPlayerResponseOuterClass.java:549)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at POGOProtos.Networking.Responses.GetPlayerResponseOuterClass$GetPlayerResponse$1.parsePartialFrom(GetPlayerResponseOuterClass.java:544)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:197)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at POGOProtos.Networking.Responses.GetPlayerResponseOuterClass$GetPlayerResponse.parseFrom(GetPlayerResponseOuterClass.java:185)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:95)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:78)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:81)
> 07-31 16:31:40.376 6560-6560/ru.romanzes.pokemongocheat W/System.err:     at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:100)

**Version:**
[The version of the lib you used]
https://github.com/Grover-c13/PokeGOAPI-Java/commit/2e7a99f5c0cba11ce1c7a9ac8d872b32b357170d

**Comment by loicortola** [comment]
New version was rolled out last night with a deprecation of the distance-to-pokemon feature.
The API must have changed...
Anyone digged into the protobuf parsers?

**Comment by vmarchaud** [comment]
protobuf cant parse the response, might come from the proto, wait for #486 to be fixed to re-test.
