### ISSUE TITLE
PokemonScannerExmple

### ISSUE THREAD

**Issue by zhuhuogeng** [Grover-c13/PokeGOAPI-Java#398]
**Description:**
[Short description of the issue observed. If this is a feature request you can modify the template as required.]

**Steps to reproduce:**
1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the lib you used]

**Comment by Grover-c13** [comment]
are you asking for an example of pokemon scanner?

**Comment by zhuhuogeng** [comment]
是的，我尝试过自己写一个，但是我不知道怎么去扫描指定区域的所有精灵。
像这个网站一样https://pokevision.com/#/@-34.916767,138.595291 https://pokevision.com/#/@-34.916767,138.595291

**Comment by FabianTerhorst** [comment]
The Range for the Pokémon returned by the api isn't as big as pokevision.
