### ISSUE TITLE
Lucky eggs

### ISSUE THREAD

**Issue by weewoo-meow** [Grover-c13/PokeGOAPI-Java#402]
Add method to use lucky eggs at ItemBag

**Expected behavior:**
The API sends to the Niantic server that the "player" used a lucky egg

**Actual behavior:**
The method is not implemented.

**Version:**
Probally #368

**Comment by vmarchaud** [comment]
[Implemented](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/api/inventory/ItemBag.java#L201) on dev branch
