### ISSUE TITLE
Api gets stuck at cp.catchPokemon(pokeball)

### ISSUE THREAD

**Issue by jsl303** [Grover-c13/PokeGOAPI-Java#406]
The latest commit sometimes gets stuck at cp.catchPokemon(pokeball).
Can't seem to track down the cause. it just hangs at catchPokemon(pokeball) function.
I went back to previous commit dad8a4a, and it doesn't have the problem.

**Comment by Grover-c13** [comment]
on the very very latest commits? #404 #405

**Comment by jsl303** [comment]
Thanks! You guys are so fast! Love it. I see there are more commits.

I just pulled down commit 82fefdb62fce9aaaf80ca26e97640dc4f416f73a.
Testing now. I'll report back.

**Comment by a4andy** [comment]
Also having the same issue with latest commit 82fefdb

**Comment by jsl303** [comment]
I'm on commit 82fefdb62fce9aaaf80ca26e97640dc4f416f73a.

This one seems to get stuck less, but still get stuck on once in a while.

result = cp.catchPokemon(pokeball);

**Comment by jsl303** [comment]
I have been testing it for a while, and it definitely gets stuck at cp.catchPokemon(pokeball);.
Not all the time, but once in a while.
Also, after you catch all the pokemons in catchablePokemon, and refresh the following in the same spot,
catchablePokemon = map.getCatchablePokemon();
size = catchablePokemon.size();
It sometimes returns 1, and when you try to catch, nothing's there.
It happens enough that I think something weird is happening in the queue.
Also, the cpu usage is pretty high. None of these issues happen in the previous commits before sync future. I went back and check.
Could you investigate what might cause these after  the commit dad8a4a?
Thank you as always!

**Comment by jsl303** [comment]
I just pulled commit 4f85be14c63d5329e2a7edf283e2aa96c984bf07.
This one sometimes goes into infinite loop where catchablePokemon.size() is always 1, and there's nothing to encounter.

**Comment by jsl303** [comment]
Apparently pokemon that you already caught still remains in go.getMap().getCatchablePokemon().
Then the cp.encounterPokemon().getStatus() returns ENCOUNTER_ALREADY_HAPPENED.
Is there way to remove caught pokemons from the getCatchablePokemon()?
Or, should I keep refreshing getCatchablePokemon() and ignore ENCOUNTER_ALREADY_HAPPENED?

**Comment by Grover-c13** [comment]
Weird, thought i had fixed that issue

**Comment by Grover-c13** [comment]
are you 100% sure you have pulled?

**Comment by jsl303** [comment]
I'm pretty sure. I just ran git-rev-parse, and it says I'm on 4f85be1.

**Comment by jsl303** [comment]
Here's my code and result in case I missed something.
while (true) {
List<CatchablePokemon> catchablePokemon = go.getMap().getCatchablePokemon();
size = catchablePokemon.size();
System.out.println("Catching " + size + " Pokemons");
for (CatchablePokemon cp : catchablePokemon) {
EncounterResult encResult = cp.encounterPokemon();
System.out.println(encResult.getStatus());
if (!encResult.wasSuccessful()) continue;
PokemonId id = cp.getPokemonId();
System.out.println("Encountered:" + id);
CatchResult result = cp.catchPokemon();
String status= result.getStatus().name();
System.out.println("Attempt to catch: " + id + " " + status);
}
}
Catching 1 Pokemons
ENCOUNTER_SUCCESS
Encountered:PIDGEY
ASYNC CATCH CALL
ASYNC CATCH CALL
Attempt to catch: PIDGEY CATCH_SUCCESS
Catching 1 Pokemons
ENCOUNTER_ALREADY_HAPPENED
Catching 1 Pokemons
ENCOUNTER_ALREADY_HAPPENED
Catching 1 Pokemons
ENCOUNTER_ALREADY_HAPPENED
...........

**Comment by jsl303** [comment]
Commit cca2a1cf still has this problem.

**Comment by FabianTerhorst** [comment]
Why it should"t?

**Comment by jsl303** [comment]
After catching all the pokemons in catchablePokemon, shouldn't go.getMap().getCatchablePokemon().size() report 0 unless there's new pokemon?

**Comment by Grover-c13** [comment]
yes it should, unless the cache timer had expired between the catch and the getCatchablePokemon

**Comment by SippieCup** [comment]
Application is getting stuck with this output: `CatchPokemon   [02:56:09] MAGIKARP Catch Result`

Related Code:

```
context.setConsoleString("CatchPokemon", "[" + new SimpleDateFormat("HH:mm:ss").format(new Date()) + "] " + target.getPokemonId() + " Catch Result");
CatchResult catchResult = target.catchPokemon(pokeball);
context.setConsoleString("CatchPokemon", "[" + new SimpleDateFormat("HH:mm:ss").format(new Date()) + "] " + target.getPokemonId() + " After Catch Result");
```

**Comment by jsl303** [comment]
Is this related?
Encountered PIDGEY: ENCOUNTER_SUCCESS
A/CatchablePokemon: Got an error or unrecognized catch attempt
A/CatchablePokemon: Proto:CatchResult(captureAward=null, response=null, status=CATCH_ERROR, failed=true)
Attempt to catch: CATCH_ERROR

**Comment by vmarchaud** [comment]
issue is much more detailed on #446
