### ISSUE TITLE
Difference between Nearby, wild and catchable Pokemon?

### ISSUE THREAD

**Issue by sarbajitsaha** [Grover-c13/PokeGOAPI-Java#407]
**Description:**

As the title suggests, what exactly is the difference between Nearby, wild and catchable Pokemon?

I am guessing catchable pokemon refers to those which are near us and those which we can catch without moving, but I am not sure about the nearby and wild pokemon.

**Comment by Jari27** [comment]
I believe wild is the moving grass you sometimes see. Nearby: no clue.

**Comment by xunnanfu** [comment]
Nearby is similar to in game, where it shows you what is nearby. Niantic servers now sends back very minimal information regarding them.

WildPokemon contains all the information for a pokemon. This includes CP, IV, and moves.

Catchable pokemon can change state. You start off with only knowing the location, expiry, and which pokemon. But once you encounter it, you get a WildPokemon back from the server, with randomized CP, IV, and moves.

**Comment by vaibhavthapliyal** [comment]
I am still not clear on the difference. I get zero results in the catchable pokemon request but I get one result in the nearby pokemon list. What would this mean?

**Comment by xunnanfu** [comment]
When you make a request for catchable pokemon given a location, the servers returns ones that are very close to you within the specified catchable range.

Nearby pokemon means it is something within a range larger than catchable range.

**Comment by sarbajitsaha** [comment]
So that means if someone wants to catch a pokemon, only catchable pokemon will work? Because I tried the nearby one, and thought it did return the names its distance was fixed at 200m.

**Comment by Grover-c13** [comment]
Wild pokemon & Catchable = both catchable,
Nearby = used on the radar in game, can only get type and dsitance, right now the server just returns 200m to reduce server load (and because they have disabled the radar)
