### ISSUE TITLE
High CPU Usage in Async Commit

### ISSUE THREAD

**Issue by jsl303** [Grover-c13/PokeGOAPI-Java#408]
Compared to dad8a4a ,  82fefdb has much higher cpu usage. Almost 10% cpu usage difference in task manager.

**Comment by Grover-c13** [comment]
Was probably the async to blocking, can you try on updated dev wtih RXjava?

**Comment by Jari27** [comment]
Still having this problem, even with the new RxJava version (3 threads -> 33% cpu)

**Comment by pvanassen** [comment]
Can you provide a thread dump when this occurs? I cannot reproduce it myself unfortunately.

**Comment by FabianTerhorst** [comment]
Cant reproduce.
