### ISSUE TITLE
[QUESTION] Static wait vs max requests per seconds?

### ISSUE THREAD

**Issue by Jari27** [Grover-c13/PokeGOAPI-Java#412]
**Description:**
Currently in the code there's a static wait of 350 ms between requests, or if there are no requests just a repeated 350 ms wait. [Link](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/src/main/java/com/pokegoapi/main/RequestHandler.java#L276)

What are long term plans for this? Calculating how many requests have been done in the past `n` seconds and then (depending on the result) immediately sending a request if available or waiting for the second to pass. (this could be done with a queue I reckon, where the last 3 requests are stored and their time. Some `Thread.sleep(1)` and popping and pushing should then give the desired outcome).

I'm very happy it works right now, but just wondering. It seems so inefficient.

**Comment by FabianTerhorst** [comment]
You want to create a pr?

**Comment by Jari27** [comment]
I might do that sometime in the future. Not too confident as of now, since I've never worked with either Futures or Observables.

**Comment by vmarchaud** [comment]
Dont need to work with async stuff, you just need to store when the latest request has been send and wait if itsnt more than 200ms ago.

**Comment by Jari27** [comment]
I'll get working on it then.

**Comment by FabianTerhorst** [comment]
@vmarchaud are you sure the wait time should be 200ms? Maybe try if a lower time is possible as well.

**Comment by Jari27** [comment]
I thought it was 3 requests/second, which is what I'm using now. Any input on what the actual rate is?

**Comment by kaaas** [comment]
I debugged a bit into the request/second ratio... 

Especially when updating the map objects (i'm doing a scan of my neighbourhood to build my own pokemon map) I noticed that only requests with a delaly of ~3.5-5 seconds from the last request are answered properly by the server. I do get an answer for each request, but it doesnt contain any information (no pokestops, no pokemon, etc.), which means I need to wait ~3.5-5 seconds before changing position and submitting a new GET_MAP_OBJECTS request... 

Anyone else have similar observations? Anyone knows how niantic throttles their api (by connection, client, ip, token)?

**Comment by FabianTerhorst** [comment]
5sec is the new default wait for scans thats true.

**Comment by kaaas** [comment]
hmm thats bad... is it possible to do parallel requests without using multiple accounts/tokens?

**Comment by FabianTerhorst** [comment]
no you won´t get good results every time. Parallel is only possible with multiple account now. I think there has done that, because of the server stability.

**Comment by Jari27** [comment]
I can't get this to work. Anyone else wanting to step in?

**Comment by FabianTerhorst** [comment]
Post your Code with the 6sec wait.

**Comment by Jari27** [comment]
EDIT: now that I look at it I see a big error already. 

```
public void run() {
    List<AsyncServerRequest> requests = new LinkedList<>();
    LinkedList<Long> sentRequestTimestamps = new LinkedList<>();
    AuthTicketOuterClass.AuthTicket authTicket = null;
    while (true) {
        Log.v("debug", "Removing useless timestamps");
        // first we remove timestamps longer than a second ago (using Iterator to facilitate removing)
        for (Iterator<Long> it = sentRequestTimestamps.iterator(); it.hasNext(); ) {
            long timestamp = it.next();
            if (System.currentTimeMillis() > timestamp + 1000) {
                Log.v("debug", "Removed timestamp " + (System.currentTimeMillis() - timestamp));
                it.remove();
            }
        }
        // then we check if the remaining timestamps satisfy the rate limiting by Niantic
        // i.e. less than 3 requests per second as of 27/07/2016
        while (sentRequestTimestamps.size() >= 3){
            Log.v("debug", "Sleeping cause more than 3 recent requests.");
            try {
                Thread.sleep(10);
            } catch (InterruptedException e) {
                throw new AsyncPokemonGoException("System shutdown", e);
            }
        }
        if (workQueue.isEmpty()) {
            continue;
        }
        // rest of method
    }
}
```

**Comment by pvanassen** [comment]
The reason for not using a ring buffer is because you can batch multiple requests into one. The assumption made is, there's a continues flow of requests comming into the RequestHandler. The only speedup possible is the one suggested earlier, if no request was fired off the last 300-350 ms, one could be fired off right away, saving some millis. 

The next requests will have to wait before being batched netting out in not much of a speed gain under a bit of load.
