### ISSUE TITLE
NearbyPokemon fetch geocoordinates unavailable? 

### ISSUE THREAD

**Issue by Rifat-Rashid** [Grover-c13/PokeGOAPI-Java#414]
**Description:**
Is there a way to fetch the geocoordinates of the various Pokemon objects (wild, nearby, catchable)? Neither of the NearbyPokemon or CatchablePokemon classes have any return void for latitude or longitude. In short, is there a way to retrieve the geocoordinates of the pokemon with the use of this API?  

**Version:**
[0.0.1]

**Comment by Grover-c13** [comment]
nearby doesnt provide coordinates only distance, we cant do anything about that. Wild/Catchable should show them, and will appear in the CatchablePokemon (map.getCatchablePokemon()) and through the Wild/Catchable protos (map.getMapObjects().getCatchable()/getWild())
