### ISSUE TITLE
Login with refresh token, invalid grant

### ISSUE THREAD

**Issue by john086** [Grover-c13/PokeGOAPI-Java#415]
**Description:**
I try login with refresh token saved previous.

**Expected behavior:**
Login without copy and paste token

**Stacktrace (If it's a crash):**
http://pastebin.com/QtLB6smq

**Version:**
last version

**Comment by Grover-c13** [comment]
is the refresh token from GoogleUserCredential and not auto?

**Comment by john086** [comment]
Now working fine, :+1:
