### ISSUE TITLE
Imitate official app behaviour

### ISSUE THREAD

**Issue by jabbink** [Grover-c13/PokeGOAPI-Java#42]
The official app often does requests like this

> <Your request> + GetHatchedEggs, GetInventory, CheckAwardedBadges, DownloadSettings

Should we replicate this in the API or should be let users of the API do this per application?

Also, the official app requests map objects every 1-5(? correct number is in the reply of DownloadSettings afaik) seconds, replicate this in the API or let others figure this out?

**Comment by vmarchaud** [comment]
i think its better to let user the choice of which request they want to send, not all users would want to make multiple request like that, better make the minimum request.

**Comment by adobeSlash** [comment]
Do you think than they can choose to use this as a verification method to auto-ban people ?

**Comment by vmarchaud** [comment]
They can do whatever they want, actually there is more low low level stuff that doesnt have been cracked yet + nobody make call like official app does so they already know who is using a custom lib and who isnt. So yes, they can use this to ban account if they wanted to

**Comment by Aphoh** [comment]
@vmarchaud I thought the whole idea of this issue was that we should try to imitate the official app so that they can't discern our app from the official one

**Comment by vmarchaud** [comment]
@Aphoh Actually, even if we wanted, it would be impossible since there a lot of fields of envelope that we doesnt even know what they are (talking about unknown6 for example), people had tried to understand what was these but at my knowledge, couldnt find anything.

PS : For me the whole issue is about choosing if we try to do this or not, like imply the question asked by jabbink : 

> Should we replicate this in the API or should be let users of the API do this per application?

**Comment by FabianTerhorst** [comment]
#667 this is on our list to combine these calls.

**Comment by ramarro123** [comment]
667 speak about login flow, will you combine even other requests to mimic official app? 

if so, better to add a note on 667?
