### ISSUE TITLE
LoginFailedException not thrown to the user

### ISSUE THREAD

**Issue by Hindi** [Grover-c13/PokeGOAPI-Java#427]
**Description:**
LoginFailedException was printed but not thrown outside the api right after trying to login. Did I miss any check when trying to login in?

**Steps to reproduce:**
Try to login with PTC until you get "com.pokegoapi.exceptions.LoginFailedException: Invalud Auth status code recieved"

**Expected behavior:**
LoginFailedException should be thrown to the user so that he can  handle it properly

**Actual behavior:**
No exception is raised leading the user to nullPointerExceptions

**Stacktrace (If it's a crash):**

> com.pokegoapi.exceptions.LoginFailedException: Invalud Auth status code recieved, token not refreshed?
>   at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
>   at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
>   at java.lang.Thread.run(Thread.java:745)
> 
> Exception in thread "Thread-29" java.lang.NullPointerException
>   at client.modules.ClientInventory.getItemCount(ClientInventory.java:158)
>   at client.modules.ClientInventory.canEncounter(ClientInventory.java:181)
>   at ai.state.AIStateSeekGoal.update(AIStateSeekGoal.java:44)
>   at ai.AIController.update(AIController.java:98)
>   at client.Client.update(Client.java:140)
>   at client.Client.run(Client.java:98)
>   at java.lang.Thread.run(Thread.java:745)

**Version:**
Latest commit d1cd3f9

**Comment by Grover-c13** [comment]
The login auth issues should be fixed, shouldnt you be handling throwing the exception to the user once thrown to your app? or am i misunderstanding something
