### ISSUE TITLE
SpawnPoints not work

### ISSUE THREAD

**Issue by ivoavido** [Grover-c13/PokeGOAPI-Java#431]
**Description:**

GetSpawnPoints() method return always an empty list

**Comment by Grover-c13** [comment]
can you give me the lat long of the problem area so i can check to see if there are spawn points in range?

**Comment by FabianTerhorst** [comment]
double lat = 48.847533008980086;
 double lng = 2.3301315307617188;

there are from middle of paris

**Comment by ivoavido** [comment]
That's the execution code:

---

double lat = 39.367369;
double lng = 16.225263;
double alt = 1;
int range = 9;

OkHttpClient httpClient = new OkHttpClient();
PokemonGo go = new PokemonGo(new PtcCredentialProvider(httpClient,username,password),httpClient);
go.setLocation(lat, lng, alt);
List<Long> cells = go.getMap().getCellIds(lat, lng, range);
MapObjects mapObjects = go.getMap().getMapObjects(cells);
mapObjects.getSpawnPoints();  // Always empty collection

---

Thanks.

**Comment by vmarchaud** [comment]
You should verify that you arent asking to fast (there is a limit for GetMapObjects requests now) and check #486 too. Shouldnt come from the api itself, people used it without problem so.
