### ISSUE TITLE
Build fails: checkstyle fail

### ISSUE THREAD

**Issue by Cydhra** [Grover-c13/PokeGOAPI-Java#437]
**Description:**
The gradle build fails with an exception, claiming that the checkstyle failed:
com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask : Unsupported major.minor version 52.0

I do not use gradlew normally, so I am completly unable to tell, wether I made a mistake in the build process, I simply followed the instructions.

**Steps to reproduce:**
1. Follow the build instructions in your readme.
2. Fails.

**Expected behavior:**
Build should success and produce jar at build/ folder.

**Actual behavior:**
Build fails.

**Stacktrace (If it's a crash):**
(It is the default pretty much nonsense stack trace of gradle. I think the only useful information is what I gave in description. If you still need it, I will give it, but it does not seem very useful.

**Version:**
The cloned version, since the build fails for the 0.3 release (cannot compile with "gradlew build" and the build instructions state to clone the repository, "gradlew :library:build" fails anyways in the release, since the project library isn't found.)

**Comment by Cydhra** [comment]
Ok, just an update: with -x checkstyleMain the build process succeeds. I don't know whether the built lib was available before, because apparently the lib is called "library.jar" unlike the stated name in description. To repeat myself: I am a complete noob to gradle, I dunno, whether the state Issue exists or is my fault, so I await response.

**Comment by Jari27** [comment]
Did you read the readme and follow it? If I clone from nothing the build works (using java 8).

**Comment by Cydhra** [comment]
Yes, as I stated multiple times: I followed the readme. Using Java 8.

**Comment by Jari27** [comment]
Are you sure your java_home var is set correctly? Also check your path var.

**Comment by Cydhra** [comment]
Yes I double checked it, since I also tried the process with jdk 1.7, just to be sure.

**Comment by FabianTerhorst** [comment]
read this and fix it http://stackoverflow.com/a/11239128/2824115 . Unrelated to this library can be closed.

**Comment by Cydhra** [comment]
Well, I am not using eclipse and there is no runtime, just an compile time. But I assume it has something to do with my jdk installation. It worked by skipping CheckStyleMain, so I guess it is not an issue to this library.
