### ISSUE TITLE
Commit cca2a1c finds pokemon only once after running.

### ISSUE THREAD

**Issue by jsl303** [Grover-c13/PokeGOAPI-Java#438]
In Commit cca2a1c, go.getMap().getCatchablePokemon() only seems to find pokemons only once after launching. After catching pokemon, I have to terminate and rerun in order to find more.

**Comment by FabianTerhorst** [comment]
this commit doesn´t changed the logic. You have to wait 5sec after every scan since the server update.

**Comment by jsl303** [comment]
If I run my same code with commit 82fefdb6, it finds pokemons without 
any problem except getting stuck at cp.catchPokemon() once in a while.
In cca2a1c, are you suggesting to run Thread.sleep(5000) before 
catchablePokemon = go.getMap().getCatchablePokemon();?
Thanks,

**Comment by FabianTerhorst** [comment]
There are logic changes from @jabbink in this commit.

**Comment by FabianTerhorst** [comment]
from #426

**Comment by FabianTerhorst** [comment]
does this is breaking the scan in your app?

**Comment by jsl303** [comment]
Well, it finds once in the beginning. Then it breaks.
I'm not sure exactly what the sequence is supposed to be. Here's my code for catching loop.
This code works fine in commit  82fefdb except it hangs once in  a while at cp.catchPokemon();. In  cca2a1c , it only finds once in the beginning, and I have to terminate and rerun in order to find more. It'd be great if you could write a catching loop in the example.

```
    while (true) {
        int size = 0;
        while (size == 0) {
            Thread.sleep(1000);
            catchablePokemon = go.getMap().getCatchablePokemon();
            size = catchablePokemon.size();
        }
        System.out.println("Catching " + size + " Pokemons");
        for (CatchablePokemon cp : catchablePokemon) {
            PokemonId id = cp.getPokemonId();
            EncounterResult encResult = cp.encounterPokemon();
            System.out.println("Encountered: " + id + " " + encResult.getStatus());
            if (!encResult.wasSuccessful()) continue;
            CatchResult result = cp.catchPokemon();
            System.out.println("Attempt to catch: " + id + " " + result.getStatus());
        }
    }
```

**Comment by stefan-karger** [comment]
you need to change the sleep time to 5000 or otherwise it will only work once

**Comment by stefan-karger** [comment]
and you may also need to add a Thread.sleep(5000) after encounterPokemon() and catchPokemon() for the same reason, but I'm not 100% sure about that one

**Comment by FabianTerhorst** [comment]
I only know that 5 seconds is the minimum for scanning. Many people are saying there are using 6 seconds to be 100% sure.

**Comment by Grover-c13** [comment]
The api currently implements this (it will use cached object for 5 seconds and request new one), im looking into an issue with the cache of catchable pokemon now, but looks like its running fine for me.

**Comment by FabianTerhorst** [comment]
Is the wait before or after the first request?

**Comment by Grover-c13** [comment]
it will use a fresh copy on the first request, then store it, and then any call for the next 5 seconds will return the cache copy, and then will request a new copy again for calls after that 5 seconds.

**Comment by FabianTerhorst** [comment]
I thought about saving 50 pokemongo object references that are using 50 different accounts so that i can send a request every 0,1seconds.

**Comment by jsl303** [comment]
If the api returns cache copy, wouldn't my loop eventually get a new scan every 5 seconds? It shouldn't break forever until restart though.

**Comment by Grover-c13** [comment]
Yes you are correct, unless there is a flaw in the cache logic. Can you give me the long/lat so i can do some testing at that area to see if i can reproduce?

**Comment by jsl303** [comment]
I'm just doing Central Park, New York.

**Comment by pvanassen** [comment]
There's a flaw in the cache logic. 
If you call getCatchablePokemon for the first time, everything works. cachedCatchable is set to something not null. 
If you after this, do any call on getting the map and the timeout has expired, map objects are reloaded and cache timeout is reset. If you then get catchable pokemon, timeout is not expired and cachedCatchable is not null, so cachedCatchable is returned which by this time most likely is empty. 

Setting cachedCatchable to null in the getMapObjectsAsync call will solve this.

**Comment by Grover-c13** [comment]
yeah i think i did this in the latest PR, let me check

**Comment by pvanassen** [comment]
Here's a PR if it's still broken

**Comment by Grover-c13** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/blob/0d9857633b92ebce4c7c8bc5c1b52bb891999b74/library/src/main/java/com/pokegoapi/api/map/Map.java#L98

https://github.com/Grover-c13/PokeGOAPI-Java/blob/0d9857633b92ebce4c7c8bc5c1b52bb891999b74/library/src/main/java/com/pokegoapi/api/map/Map.java#L378

yep did it

**Comment by pvanassen** [comment]
Awesome

**Comment by Grover-c13** [comment]
Could you test and comment @jsl303

**Comment by jsl303** [comment]
I can't build it for some reason.
Execution failed for task ':library:generateProto'.

> java.io.IOException: Cannot run program "C:\Users\user.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\
> 3.0.0-beta-3\71e76cad4f9b30aab172c44035d343c5bab47815\protoc-3.0.0-beta-3-windows-x86_64.exe": CreateProcess error=206,
> The filename or extension is too long.
> I never had this problem before in previous commits.
> Any thought on why this happens?

**Comment by FabianTerhorst** [comment]
The error message is there.

**Comment by jsl303** [comment]
Yes, but how do you make this file name shorter? And what is this file?

**Comment by FabianTerhorst** [comment]
move your project to the desktop or when you are on windows to C://

**Comment by jsl303** [comment]
This finding pokemon only once in the beginning definitely got fixed! 
Awesome job! Thank you!

catchPokemon(pokeball) still hangs sometimes though. If it hangs, I have 
to terminate and rerun.
Also seeing pokemon already caught in the getCatchablePokemon() happens 
far less. I've seen only a couple of times in few hours.
I filed those issues separately. Should I comment on them indicating 
still happening?
I'm on commit aa6c5d92bfe3455282ee176ad653b2924f21ddc1.
Thanks!

**Comment by a4andy** [comment]
Ditto, same thing happening still on latest commit, random hanging on catchPokemon()

**Comment by Grover-c13** [comment]
can you check on latest commits

**Comment by vmarchaud** [comment]
Working great on latest commit 4 days ago (before niantic broke it all), re-open if you still have issue with it in future.
