### ISSUE TITLE
Unresolve Dependency

### ISSUE THREAD

**Issue by DaveBben** [Grover-c13/PokeGOAPI-Java#440]
**Description:**
Trying to enter any of the builds from jitpack into Android studio, leaves me with an unresolved dependency.

**Steps to reproduce:**
1. Add to dependency:  compile 'com.github.Grover-c13:PokeGOAPI-Java:0.3'

**Expected behavior:**
Sync from repository

**Actual behavior:**
Error:(30, 13) Failed to resolve: com.github.Grover-c13:PokeGOAPI-Java:0.3
<a href="openFile:A:/Dropbox/Android_Projects/AutoCollect/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the lib you used]

**Comment by FabianTerhorst** [comment]
#436 will stop this type of bugs.

**Comment by vmarchaud** [comment]
Should be working now using jcenter.
