### ISSUE TITLE
Method catch pokemon

### ISSUE THREAD

**Issue by john086** [Grover-c13/PokeGOAPI-Java#445]
**Description:**
When i try to call catch methon always response with catchstatus 3 escaped

Can you help me?

**Steps to reproduce:**
1. Get encoutered pokemon
2. Get catchable pokemon
3. Catch pokemon

**Version:**
Last commit

**Comment by Grover-c13** [comment]
how many catch attempts and did you by chance get the catch probability?

**Comment by john086** [comment]
This is example 

status: ENCOUNTER_SUCCESS
capture_probability {
  pokeball_type: ITEM_POKE_BALL
  pokeball_type: ITEM_GREAT_BALL
  pokeball_type: ITEM_ULTRA_BALL
  capture_probability: 1.0
  capture_probability: 1.0
  capture_probability: 1.0
}

This escape , i try one catch

**Comment by FabianTerhorst** [comment]
Maybe softban?

**Comment by john086** [comment]
I don't known it s possible?

**Comment by sarbajitsaha** [comment]
Try visiting a pokestop and see if you gain any experience; if not, then its probably softban. They usually last for a few hours though.

**Comment by john086** [comment]
No i try now work from Pokémon app, from my app give always  escaped

**Comment by john086** [comment]
I update api with last commit and use this method catchPokemonWithBestBall() ,now work fine :+1:
