### ISSUE TITLE
catch pokemon loop forever

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#446]
doing a simple 
            CatchResult result = pokemon.catchPokemon(PokemonHelper.ball(pokemon,api.getInventories().getItemBag()), -1, PokemonHelper.berry(pokemon,api.getInventories().getItemBag()));

can cause a loop that will output on console

ASYNC CATCH CALL

wth a debug i can see that
CATCH_ERROR
is returned during catch and the api loop there

```

                            if (response.getStatus() != CatchStatus.CATCH_ESCAPE
                                    && response.getStatus() != CatchStatus.CATCH_MISSED) {
                                api.getInventories().updateInventories();
                                return new CatchResult(response);
```

the pokemon it's a "normal" encounter type, and it's of course encountered.

```
api = {PokemonGo@2200} 
pokemonId = {PokemonIdOuterClass$PokemonId@2299} "SNORLAX"
expirationTimestampMs = 1470150910268
encounterKind = {CatchablePokemon$EncounterKind@2300} "NORMAL"
encountered = {Boolean@2301} "true"
```

the strange things it's that i got

```
result = {ByteString$LiteralByteString@2197} "<ByteString@742fa311 size=0>"
 bytes = {byte[0]@2316} 
 hash = 0
```

and

```
response = {CatchPokemonResponseOuterClass$CatchPokemonResponse@2198} ""
 status_ = 0
 missPercent_ = 0.0
 capturedPokemonId_ = 0
 captureAward_ = null
 memoizedIsInitialized = 1
 unknownFields = {UnknownFieldSet@2312} ""
 memoizedSize = -1
 memoizedHashCode = 0
```

i think that the api should handle this case, probably this pokemon it's too powerful to be catched :)

**Comment by Grover-c13** [comment]
ty for all the details
