### ISSUE TITLE
POGOProtos not found

### ISSUE THREAD

**Issue by iSach** [Grover-c13/PokeGOAPI-Java#449]
**Description:**
I'm trying to modify the API (I forked it, etc)
But it doesn't find POGOProtos and generates tons of errors.

**Steps to reproduce:**
1. Fork Project
2. Git Clone it.
3. Open It.

**Expected behavior:**
No errors

**Actual behavior:**
https://puu.sh/qnkIp/8936cafbc2.png
Errors, can't find POGOProtos.

**Stacktrace (If it's a crash):**
https://puu.sh/qnkIp/8936cafbc2.png

**Version:**
0.3

**Comment by FabianTerhorst** [comment]
you initialized the submodule?

**Comment by iSach** [comment]
Yes
https://puu.sh/qnl0B/f1489ea16d.png

**Comment by FabianTerhorst** [comment]
this wasn´t the right screenshot. Go into library src resources.

**Comment by FabianTerhorst** [comment]
and open the folder there

**Comment by stirante** [comment]
Just mark build/generated/source/proto/main/java as source directory in project structure->modules

At least it works for me. Also do 'gradle build' first.

**Comment by stirante** [comment]
Also it might have changed since i'm on a bit old commit right now. But the generated sources should be somewhere in build folder after you build everything with gradle.

**Comment by iSach** [comment]
@FabianTerhorst https://puu.sh/qnlo1/5028295e5e.png

protobuf is empty

**Comment by FabianTerhorst** [comment]
shouldn´t be empty^^. You realy initialized the submodule?

**Comment by iSach** [comment]
@stirante I have no "build" folder, and can't have one as it shows errors when I "gradle build"

**Comment by iSach** [comment]
@FabianTerhorst What do you exactly mean by "Initialized submodule"? When I imported the project, I selected it

**Comment by FabianTerhorst** [comment]
git submodule update --init

**Comment by iSach** [comment]
Thanks, not empty anymore.
https://puu.sh/qnlDQ/434695edef.png
Though, still can't find :/

**Comment by FabianTerhorst** [comment]
because gradle task is generating them.

**Comment by iSach** [comment]
@FabianTerhorst Ah, okay thanks a lot! Bothering you a last time ^^
Many getters seem being not able to be found. I think it's a issue with the annotations. Would you know why?

**Comment by FabianTerhorst** [comment]
You have to install a plugin. Its called lombok.

**Comment by iSach** [comment]
I'm closing the issue.
Thanks again for the fast and good help!

**Comment by FabianTerhorst** [comment]
https://plugins.jetbrains.com/plugin/6317
