### ISSUE TITLE
svarzee GPS package duplicate error in Android Studio when making APK

### ISSUE THREAD

**Issue by duyngn** [Grover-c13/PokeGOAPI-Java#450]
**Description:**
Unable to build APK in Android Studio due to duplicate library references leading to a Jar merge error.  Error points to svarzee.gps.gpsoauth package.

**Steps to reproduce:**
Try to build an app APK using PokeGOAPI-Java (via gradle) in Android Studio with or without proguard.

**Expected behavior:**
Should not have conflict.  I inspected the external libraries and PokeGOAPI-Java package does in fact contain the offending svarzee GPS package.  Maybe PokeGOAPI-Java shouldn't embed other packages?

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebug'.

> java.io.IOException: Can't write [C:\android_workspace\MyTestApp\app\build\intermediates\transforms\proguard\debug\jars\3\1f\main.jar] (Can't read [local\directory.gradle\caches\modules-2\files-2.1\com.github.Grover-c13\PokeGOAPI-Java\0.3\c114d5d76764ebc685bec19d1e4072b720c84ea8\PokeGOAPI-Java-0.3.jar(;;;;;;*_/_.class)] (Duplicate zip entry [PokeGOAPI-Java-0.3.jar:svarzee/gps/gpsoauth/AuthToken.class]))

**Version:**
release 0.3

**Comment by FabianTerhorst** [comment]
multidex enabled?

**Comment by duyngn** [comment]
Yep.  It won't build without multidex.

**Comment by FabianTerhorst** [comment]
and when you use `compile 'com.pokegoapi:PokeGOAPI-library:0.3.2'` 

with

```
 maven {
url "http://dl.bintray.com/grover-c13/maven"
}
maven {
url "https://jitpack.io"
}
```

**Comment by duyngn** [comment]
Yes. my build.gradle looks like this.(where pokegoapi is concerned)

repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
   compile 'com.github.Grover-c13:PokeGOAPI-Java:0.3'
}

EDIT: It used to work fine in version release 0.2 and the master:SNAPSHOT

**Comment by FabianTerhorst** [comment]
try the setup i posted above

**Comment by duyngn** [comment]
Ok. I will try those as soon as I can.(couple hours...)
I also edited the main post to escape some characters to show the entire error output.

**Comment by FabianTerhorst** [comment]
when this is not fixing the error you have to wait a few hours until bintray is releasing the gps package port to jcenter.

**Comment by duyngn** [comment]
Ok. Just tried.  Not working.  Though what's wrong with my repository syntax?  It works for everything else and is how document indicates.

**Comment by duyngn** [comment]
Just an update:

I double checked the main page of this repo and the JitPack instruction indicates to use:

allprojects {
        repositories {
            maven { url "https://jitpack.io" }
        }
    }

dependencies {
            compile 'com.github.Grover-c13:PokeGOAPI-Java:0.3'
    }

I put the repo chunk into the project scope's build.gradle.
I put the dependencies chunk into my app module's build.gradle.

It's now throwing this:
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForDebug'.

> java.io.IOException: Can't write [/user/Desktop/Bitbucket/pokemon-notifier/app/build/intermediates/transforms/proguard/debug/jars/3/1f/main.jar] (Can't read [/Users/user/.gradle/caches/modules-2/files-2.1/com.github.Grover-c13/PokeGOAPI-Java/0.3/c114d5d76764ebc685bec19d1e4072b720c84ea8/PokeGOAPI-Java-0.3.jar(;;;;;;*_/_.class)] (Duplicate zip entry [PokeGOAPI-Java-0.3.jar:com/annimon/stream/AbstractSpinedBuffer.class]))

**Comment by FabianTerhorst** [comment]
and when you use jcenter from above?

**Comment by duyngn** [comment]
jcenter() is already present in the repositories section in the project scope's build.gradle, so i assume t's doing the same thing.

**Comment by FabianTerhorst** [comment]
compile 'com.pokegoapi:PokeGOAPI-library:0.3.2'  maven {
url "http://dl.bintray.com/grover-c13/maven"
}

**Comment by Danm72** [comment]
@FabianTerhorst are those maven urls mentioned in the readme? They should be!

**Comment by FabianTerhorst** [comment]
@Danm72 there are not needed when bintray accepted the publish request. This can take up to 24hours.

**Comment by duyngn** [comment]
@FabianTerhorst So I need not take any actions with the current gradle config and it should resolve itself?  (as long as I have jcenter() as the repo)

**Comment by FabianTerhorst** [comment]
My GPS build got approved from bintray so its now hosted on jcenter.

**Comment by FabianTerhorst** [comment]
When #448 is merged and @Grover-c13 updated the bintray package it should work.

**Comment by duyngn** [comment]
So... I'm still getting a ton of "Duplicate zip entry" while trying to build APK.  I can start adding exclusions in gradle... or are we looking at a possible fix coming soon to make it compatible with Android Studio?

**Comment by duyngn** [comment]
Update: Fixed.

Looks like the readme is updated with the new gradle config.
compile 'com.pokegoapi:library:0.3'

All is well now.  Thanks!
