### ISSUE TITLE
Scan map by radius

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#456]
Hi folks,

Is anybody working on get MapObjects by radius? If then, which strategies are you using?
- Generate the neighbours coordinates from a LatLong given + perform an api call for each coordinates.
- Generate the CellIds from a LatLong given and perform a single api call with this CellIds.

Thanks in advance!

**Comment by Jari27** [comment]
`myApi.getMap().getMapObjects(int width)` is almost exactly what you are looking for. Why not take a look into that?

**Comment by FabianTerhorst** [comment]
@Sadye maybe he knows that the limit is a width of 9

**Comment by Jari27** [comment]
That's based on what the server can reasonably return right? You'll need to 'walk around' to request more cells.

**Comment by ghost** [comment]
So if I make a single request with a list of CellIds based on the different coordinates of the "walk around" the response I obtain does not correspond to this?

In other words, do I need to perform several requests?

**Comment by Jari27** [comment]
No basically the server only responds if the cellids you request are reasonable (i.e. close enough and not too much).

So if you go above a certain radius, you'll have to send multiple requests. (this is beyond basic functionality for the api).

The requests are like: at position 1: request surrounding cells. Move to position 2. At position 2: request surrounding cells... etc etc

**Comment by ghost** [comment]
Nice, got it! Do you know which is this maximum distance? Is it a width of 9? 
If then, if we use this parameter we should pass values <= 9

**Comment by Jari27** [comment]
<snip snarky comment>

 I don't know what the maximum is on the server side. Does anyone else?

**Comment by FabianTerhorst** [comment]
9

**Comment by FabianTerhorst** [comment]
myApi.getMap().getMapObjects() is using 9 by default btw.

**Comment by ghost** [comment]
Thank you guys!

**Comment by vmarchaud** [comment]
Resolved.
