### ISSUE TITLE
How to use google email and password to login

### ISSUE THREAD

**Issue by lzj0718** [Grover-c13/PokeGOAPI-Java#461]
How to use google email and password to auto login?

**Comment by a4andy** [comment]
`PokemonGo(new GoogleAutoCredentialProvider(httpClient, username, password), httpClient);`

**Comment by lzj0718** [comment]
thanks ,How to get the attribute  latitude,longitude and expirationTimestamp by nearby Pokemon ？

**Comment by a4andy** [comment]
Read the readme, shows you how to get nearby catchable pokemon.

**Comment by lzj0718** [comment]
Thanks，but I use the api  go.getMap().getCatchablePokemon() ,the method return 0 size List<CatchablePokemon>.  I had set location by go.setLocation(37.7879938, -122.4074374,0);

**Comment by FabianTerhorst** [comment]
@lzj0718 the radius is very small. You should try more different locations.

**Comment by lzj0718** [comment]
OK,Thanks!  I want to know the attribute  cp and level  of catchablePokemon ,How can I get it?

**Comment by DrakeSharp** [comment]
encounter it, then cast EncounterResult

**Comment by lzj0718** [comment]
I import the jar by moven. and I write the pom.xml content with  
<dependency>
        <groupId>com.github.Grover-c13</groupId>
        <artifactId>PokeGOAPI-Java</artifactId>
        
        <version>a273fd71e4</version>
    </dependency>

the version "a273fd71e4" is latest submission，but error "Missing artifact svarzee.gps:gpsoauth:jar:0.3".

if the version is "0.3" ,Can run correctly.

**Comment by FabianTerhorst** [comment]
@lzj0718 you have to add jcenter() to your repositorys

**Comment by eatyours0up** [comment]
@lzj0718 I'm having the same issue

**Comment by AbandonedCart** [comment]
https://bintray.com/bintray/jcenter (Click the "Set me up" wrench icon in the top right)

or

https://jitpack.io/#maven
group: com.github.svarzee
artifact: gpsoauth-java
tag: v0.3.0

should be enough to get it working in Maven

**Comment by eatyours0up** [comment]
@LoungeKatt Got it!, thanks

**Comment by eatyours0up** [comment]
Could someone explain to me how to increase my radius? I've used multiple latitude and longitude but I'm still getting 0 pokemon nearby. I'm able to get the players inventory, etc. so I know im able getting data back

**Comment by AbandonedCart** [comment]
@eatyours0up https://github.com/Grover-c13/PokeGOAPI-Java/issues/486

It is usually better to try to find a similar issue, or post a new one if there are none that are similar. It makes it easier for people with the same issue or an answer to find it.

**Comment by eatyours0up** [comment]
thanks

**Comment by vmarchaud** [comment]
Revolved.
