### ISSUE TITLE
How to map returned Pokemons with names

### ISSUE THREAD

**Issue by meher19** [Grover-c13/PokeGOAPI-Java#462]
Hello,

this is my question : 
I found the pokemon names in this file : https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/classes/production/PokeGOAPI-Java/pokemon_names.properties

Now, how to map returned pokemons from method getCatcheablePokemons() with the integer ids in the properties file, i looked for a similar id in the PokemonData object but nothing.

Thanks.

**Comment by a4andy** [comment]
I am assuming this method will get you the pokemon's number. 
`cp.getPokemonId().getNumber();`

**Comment by john086** [comment]
You can check class DisplayPokenameExample.java

**Comment by meher19** [comment]
@a4andy : thank you, i will look at this attribute.
@john086 : i saw it, but this example is just displayng names from the properties file, it's not mapping with results returned from Niantic servers.

I have another related question : how i can get pokemon image, do this api provides an image library that we can map with each pokemon ? else how to do ?

Thanks.

**Comment by john086** [comment]
@meher19  no is niantic server name , if i open app "Pokemon go" in Diary i see exactly the same name :+1:

**Comment by meher19** [comment]
@john086 : ok ! but this not responds to my last question...

**Comment by john086** [comment]
@meher19  for image i don't know

**Comment by Grover-c13** [comment]
we dont provide images, you can use various restful apis for it.
