### ISSUE TITLE
Getting empty CatchablePokemon List

### ISSUE THREAD

**Issue by David6390** [Grover-c13/PokeGOAPI-Java#463]
Im getting empty list of CatchablePokemon when i do the following:
go.getMap().getMapObjects(9).getCatchablePokemons()

It is strange cause there are Pokemon where im looking for. Also no Exceptions, only empty list.

**Version:**
Im using "com.pokegoapi:library:0.3"

**Comment by Grover-c13** [comment]
Niantic changed the time between getMapObjects again from 5 to 10 seconds :|

**Comment by David6390** [comment]
Really? Im doing like 25 calls to getCatchablePokemons(), is there any solution to this?

**Comment by Grover-c13** [comment]
ive updated the API to address it. 0.3.3 onwards

**Comment by David6390** [comment]
Do i have to do something special in my code? or it is handled by the API?

**Comment by Grover-c13** [comment]
handled by the API, it will retain a copy of map objects for 10 seconds and then on the next request get a fresh copy.

**Comment by David6390** [comment]
Ok thanks!

EDIT: when i make the calls, they go all in a loop with no time to wait between them, im still getting no pokes. But if i add a 10 seconds sleep, it works as expected.

Does it mean that i have to manage the time between calls myself?

**Comment by FabianTerhorst** [comment]
@David6390 its your loop. You have to wait 10sec inside the loop.
