### ISSUE TITLE
Catch Pokemon called double

### ISSUE THREAD

**Issue by Cyperghost** [Grover-c13/PokeGOAPI-Java#471]
Wenn i try to catch a pokemon with the function
`CatchablePokemon.catchPokemon();`
The AsyncServerRequest called the function after success catch again.
When success the Result object have this values

>  status: CATCH_SUCCESS
>      captured_pokemon_id: 12510444585850155229
>      capture_award {
>      activity_type: ACTIVITY_CATCH_POKEMON
>      activity_type: ACTIVITY_CATCH_EXCELLENT_THROW
>      activity_type: ACTIVITY_CATCH_CURVEBALL
>      xp: 100
>      xp: 100
>      xp: 10
>      candy: 3
>      candy: 0
>      candy: 0
>      stardust: 100
>      stardust: 0
>      stardust: 0
>      }

In the second step the value

> status: CATCH_FLEE{
>      status_ = 3
>      missPercent_ = 0.0
>      capturedPokemonId_ = 0
>      captureAward_ = null
>      memoizedIsInitialized = 1
>      unknownFields = {UnknownFieldSet@2258} ""
>      memoizedSize = -1
>      memoizedHashCode = 0
>      }

But the pokemon successfully in my poke bank.

**Comment by Cyperghost** [comment]
I see that this CatchResult have this values, but why the value failed is true? 

`CatchResult(captureAward=null, response=null, status=CATCH_SUCCESS, failed=true)`

**Comment by Grover-c13** [comment]
Hopefully fixed in the latest commit before PR #472
