### ISSUE TITLE
getMap().getCatchablePokemon() returns 0 often

### ISSUE THREAD

**Issue by ashgh** [Grover-c13/PokeGOAPI-Java#476]
This method often returns 0 for me with the latest changes. Are there other requirements to get this call to work? I am making sure my location is updated before the call and I am letting 1 second go by before making this call. For reference, I am navigating downtown San Diego.

**Comment by Jari27** [comment]
`getCatchablePokemon()` uses `MapObjects`. Wait atleast 10s between calls to solve this.

**Comment by ashgh** [comment]
10s seems kind of long to wait. Is the alternative to subscribe to the async version?

**Comment by FabianTerhorst** [comment]
@ashgh you have to wait 10seconds before starting the next request. The request itself don´t need 10seconds.

**Comment by ashgh** [comment]
@FabianTerhorst so I have to wait 10s before each request that uses MapObjects. Could I theory cache getMap().getMapObjects() and refresh that every 10 seconds instead?

**Comment by mgorski-mg** [comment]
@ashgh it works like you said. It is cached and refresh when you call it and the last refresh was more than 10s.

**Comment by ashgh** [comment]
@mgorski-zlatan oh ok, so it's already being cached and updated. so really if the call returns 0 pokemon, there isn't anything you can really do except wait 10 seconds for it to refresh?

**Comment by Jari27** [comment]
It's not being updated automatically, you still have to make a request that queries mapobjects.

**Comment by ashgh** [comment]
@Sadye right, I have a thread that queries every second already. so as long as the request is being made, it will get updated every 10 seconds, is that right?

**Comment by mgorski-mg** [comment]
That's right. If you are querying every 1s, it will send network request every 10s.

**Comment by Jari27** [comment]
@ashgh Take care that you are still receiving bullshit empty responses if something is wrong. Might want to catch those.

**Comment by PokeAlert** [comment]
Are guys sure this is a throttling issue ? Looks to me something changed in the proto ?

**Comment by mgorski-mg** [comment]
unfortunately you're right :( something is changed, probably in mapcell proto

**Comment by Paul776** [comment]
https://github.com/PocketMobsters/PokeMobBot/commit/eb1c6abff719db20d652e32f781931c7a6b0f544

**Comment by aaiezza** [comment]
Yea,  this looks broken to me like as of a couple hours ago.

**Comment by vmarchaud** [comment]
please refer to #486
