### ISSUE TITLE
okhttp3

### ISSUE THREAD

**Issue by jchunly** [Grover-c13/PokeGOAPI-Java#480]
the imports for okhttp3 are not available in the version of the library 0.3.4 ????

**Comment by ivankoma** [comment]
If you are importing as a library, use PokeGOAPI-library-all-0.3.0.jar.

**Comment by jchunly** [comment]
thanks

**Comment by jchunly** [comment]
please upload library 0.3.0 in jfrog bintray

**Comment by FabianTerhorst** [comment]
Can you post your build.gradle

**Comment by jchunly** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.+'

```
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}
```

}

allprojects {
    repositories {
        jcenter()
    }
}
