### ISSUE TITLE
Failed to receive contents from server

### ISSUE THREAD

**Issue by ivankoma** [Grover-c13/PokeGOAPI-Java#481]
**Description:**
Since 1 hour ago you cannot anymore login using this API. 

**Steps to reproduce:**
1. Call `go = new PokemonGo(new PtcCredentialProvider(httpClient, "username", "pass"), httpClient);`

**Expected behavior:**
Successful login.
**Actual behavior:**
`Exception: com.pokegoapi.exceptions.RemoteServerException: Failed to receive contents from server`

**Version:**
PokeGOAPI-library-all-0.3.0.jar

More informations on:

https://www.reddit.com/r/pokemongodev/comments/4w0jum/all_ptcgoogle_logins_failing_from_api/
https://www.reddit.com/r/pokemongodev/comments/4w0mtr/getting_0_pokemon_upserted_in_last_few_minutes/

There are some fixes on Github:
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/3403?issuecomment=237372013#issuecomment-237372013
https://github.com/NECROBOTIO/NecroBot/commit/35339c3f527e7f934ae5fae6a7c7aa45e246be32

**Comment by aaiezza** [comment]
So the API probably changed. I am able to login both PTC and Google on my phone and in the API.

I am also able to use my potions (I'm assuming other items as well) and discard items. However, even after I update my location, I am unable to retrieve any pokéstops or catchablePokémon.

**Comment by jay8ee** [comment]
Yes this seems to be the case. All the major Pokemon GO based github projects seem to be discussing it. The protobuffer layouts changed about an hour ago.

**Comment by iGio90** [comment]
MapCells proto structure has changed. It's a tuple now! They are already on it

**Comment by aaiezza** [comment]
Sooo how do we make new ones with the updated info? Wait for a leak?

**Comment by NoBullPleb** [comment]
There's a discussion happening here on the subject : https://www.reddit.com/r/pokemongodev/comments/4w0jum/all_ptcgoogle_logins_failing_from_api/

**Comment by vmarchaud** [comment]
please refer to #486
