### ISSUE TITLE
Android shows error "number of method references in a .dex file exceed 64K"

### ISSUE THREAD

**Issue by ricechenghk** [Grover-c13/PokeGOAPI-Java#483]
**Description:**
When I add PokeGOAPI-library:0.3.4 in my Android Studio, it shows me this error.
Error:The number of method references in a .dex file cannot exceed 64K.
But I just include only necessary dependencies...

**Steps to reproduce:**
Change the build.gradle with following dependencies and run the project
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.google.android.gms:play-services-location:9.2.1'
    compile 'com.google.android.gms:play-services-maps:9.2.1'
    compile 'com.netflix.rxjava:rxjava-android:0.20.6'
    compile 'com.tbruyelle.rxpermissions:rxpermissions:0.7.0@aar'
    compile 'com.pokegoapi:PokeGOAPI-library:0.3.4'
}

**Version:**
PokeGOAPI-library:0.3.4

**Comment by FabianTerhorst** [comment]
You have to enable multidex. The generated protofile has 56k methods.

**Comment by DaveBben** [comment]
Also,  if you're using Google Play Services,  make sure that you're aren't importing the whole library into the dependencies. Only what you need.

**Comment by mgorski-mg** [comment]
or just use proguard to shrink unused code ;)

**Comment by FabianTerhorst** [comment]
@mgorski-zlatan you don´t want to enable proguard on debug build. This is increasing the build time.

**Comment by mgorski-mg** [comment]
It depends, I prefer to do it. But it depends of the time of the build. Obviously if it make build last very long, you're right it is better to enable multidex on debug version.

**Comment by FaintPixels** [comment]
In your Manifest file put:
`<application
        ...  
        android:name="android.support.multidex.MultiDexApplication">` 

In your gradle build file put: 
`defaultConfig {
        ...  
        multiDexEnabled true
    }`

Finally in your dependencies add:
    compile 'com.android.support:multidex:1.0.1'

Think that's everything you need to do... good luck!

**Comment by FabianTerhorst** [comment]
@jabbink Can be closed.

**Comment by FabianTerhorst** [comment]
We could at to the faq that the app needs multidex when someone want to create a pr for this.

**Comment by aaiezza** [comment]
Sooo are we all done here? The only real issue at hand (#486) is blocked and nobody is really saying anything.

I wish I could help but I'm only half way through [this page](https://developers.google.com/protocol-buffers/docs/javatutorial).

**Comment by AbandonedCart** [comment]
In most cases, it only requires MultiDex when using it with Google Play Services. It would be better to slim down the API and use parameters over all of the individual methods for each variance of a call. I started working on that, but it is extremely late in the game to get anywhere quickly :/

**Comment by FabianTerhorst** [comment]
there is nothing we can Slim down. The protofiles have 56k methods and the protobuf Library itself has 10k methods.

**Comment by FabianTerhorst** [comment]
Niantic solved this by using the protos in the native Library.

**Comment by AbandonedCart** [comment]
@FabianTerhorst "It would be better to slim down the API and use parameters over all of the individual methods for each variance of a call"

To better explain this, see https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/map/pokemon/CatchablePokemon.java

You could convert the entire collection of WithRazzBerry calls to a boolean and the sorting of which ball to use to an int and remove about 15 methods.

**Comment by FabianTerhorst** [comment]
but this wouldn't prevent multidex.

**Comment by AbandonedCart** [comment]
@FabianTerhorst Depending on how you implement it, maybe not. It's a long way from a PR, so no need to concern yourself with it right now.

**Comment by FabianTerhorst** [comment]
we need the proto files. These files are filling the whole limit.

**Comment by AbandonedCart** [comment]
That's not entirely true. I successfully avoided MultiDex until the last few days. That is including Google Play Services and my proprietary code. As I said before, you needn't worry about it until the API is functional and the feasibility can be revisited based on how much is required for that alone.
