### ISSUE TITLE
go.getMap().getMapObjects() returns all lists empty.

### ISSUE THREAD

**Issue by rahulsom** [Grover-c13/PokeGOAPI-Java#484]
**Description:**
Calling `getMapObjects()` returns a bunch of lists - `getWildPokemons()`, `getSpawnPoints()`. However all lists are empty. 

**Expected behavior:**
These methods returning lists should return non empty lists.

**Version:**
0.3.0

**Comment by mjmjelde** [comment]
All API's are broken with an update from Niantic today.  You will just have to wait till it all gets fixed

**Comment by TheLushpen** [comment]
But game works fine.

**Comment by Nihisil** [comment]
@TheLushpen because bots don't send all information to the servers. It will take some time to figure out what to fix. You can check discussion here: https://github.com/AeonLucid/POGOProtos/issues/131

**Comment by Grover-c13** [comment]
The game had an update

**Comment by TheLushpen** [comment]
Thanks
