### ISSUE TITLE
Niantic server update problem

### ISSUE THREAD

**Issue by meher19** [Grover-c13/PokeGOAPI-Java#485]
I suggest to merge all issues caused by the last Niantic server update in this topic.

You can see the explanation of the problem and last updates about research to resolve it here : 
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

Someone tried to resolve the problem among developers of this API ?

**Comment by LoungeKatt** [comment]
The key used to access the API was predefined, but now it is being authenticated on the device.

You need to decompile the binaries in IDA and recreate the method used to generate the key.

**Comment by john086** [comment]
Now the api cannot be used ?

**Comment by stefan-karger** [comment]
not for now. here are the most important updates: https://github.com/AeonLucid/POGOProtos/issues/131

**Comment by LoungeKatt** [comment]
@Tsunamii Thanks for flagging this post in the discussion about a C&D letter to quote a post already on the linked reddit. Might as well have called Niantic with your contact info.

**Comment by FabianTerhorst** [comment]
we can build an android library that is using the official .so files. Then the api would work again.

**Comment by john086** [comment]
@FabianTerhorst  what do you mean? can you give more detail ?

**Comment by David6390** [comment]
@FabianTerhorst Is that possible?

**Comment by mgorski-mg** [comment]
I'll try to do that. Give me some time.

**Comment by FabianTerhorst** [comment]
@john086 yes it is. Its needs a complete different library.

**Comment by vmarchaud** [comment]
please refer to #486
