### ISSUE TITLE
gym list empty

### ISSUE THREAD

**Issue by 4ndro1d** [Grover-c13/PokeGOAPI-Java#489]
**Description:**
List is empty when requesting

**Steps to reproduce:**

poGo.setLocation(48.3097431, 14.2821328, 0);
List<Gym> gyms = poGo.getMap().getGyms();

**Comment by Grover-c13** [comment]
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/
soz :(

**Comment by vmarchaud** [comment]
please refer to #486

**Comment by 4ndro1d** [comment]
I upgraded to to version 0.4.0 but the issue persists?

**Comment by Grover-c13** [comment]
Hmm is your account working fine in the game?

**Comment by 4ndro1d** [comment]
wp, no. As the only thing I did was requesting gym infos about one specific arena I rly didn't expect it to be banned :D Sry I bothered you

**Comment by 4ndro1d** [comment]
Okay so I created a new account which is definetly not banned and I still get the same error. Got a new token as well

**Comment by Grover-c13** [comment]
Same story in game? you may be IP banned https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/

**Comment by 4ndro1d** [comment]
The freshly created account is not banned (I just caught the starter Pokemon and then switched back to my main account on the same phone and same network)

**Comment by Grover-c13** [comment]
But does the new account get map objects? there are specific kinds of bans (no map objects etc). not sure if starter pokemon apply for map object data.

**Comment by 4ndro1d** [comment]
I already switched back to my maina ccount and got rid of tzhe other on my phone. Map objects not visible result from an IP ban which is def. not the case as my main account is totally working fine atm. And I don't see why a fresh account would be banned immediatly atm

**Comment by 4ndro1d** [comment]
http://imgur.com/r6fwOQ4 everythimg working fine on new account

**Comment by Grover-c13** [comment]
Does getting pokestops with the API work?

**Comment by 4ndro1d** [comment]
Need to figure out how to fetch them. But e.g. `poGo.getInventories().getIncubators().size()` is working.
I am starting to think my Eclipse Buildpath may have some problem. Will try to wrap it in a new project first

**Comment by 4ndro1d** [comment]
Well yeah, now I'm back to #565
