### ISSUE TITLE
UnmodifiableCollection.addAll error when getting MapObjects

### ISSUE THREAD

**Issue by Aphoh** [Grover-c13/PokeGOAPI-Java#49]
Stacktrace:
java.lang.UnsupportedOperationException
W/System.err:     at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:932)
W/System.err:     at com.pokegoapi.api.map.MapObjects.addDecimatedSpawnPoints(MapObjects.java:54)
W/System.err:     at com.pokegoapi.api.map.Map.getMapObjects(Map.java:127)
W/System.err:     at com.pokegoapi.api.map.Map.getMapObjects(Map.java:86)
W/System.err:     at com.pokegoapi.api.map.Map.getMapObjects(Map.java:74)
W/System.err:     at com.pokegoapi.api.map.Map.getMapObjects(Map.java:43)

Occurs when calling PokemonGo.getMap().getMapObjects(lat, long)

**Comment by jabbink** [comment]
This was a _tiny_ :hushed: bug introduced by bec2926 and has been fixed in #46
