### ISSUE TITLE
This project is in violation of the Apache License.

### ISSUE THREAD

**Issue by iphydf** [Grover-c13/PokeGOAPI-Java#490]
https://github.com/google/s2-geometry-library-java/blob/master/src/com/google/common/geometry/S2LatLng.java is Copyright by Google and under the Apache License 2.0, which states that you can't remove the copyright notice and the license notice. You can't simply relicense other people's code, so now you are in violation of copyright law. Please restore the original license and copyright notice.

**Comment by iphydf** [comment]
To be clear, the files in question are under https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/google/common/geometry.

**Comment by FabianTerhorst** [comment]
http://www.apache.org/licenses/GPL-compatibility.html

**Comment by Grover-c13** [comment]
Hi @iphydf,

Thanks for posting.

this wasnt intentional and was just auto generated in IntelliJ. (as far as im aware the original license shouldnt of been removed if they had them in there, it would of been just under it). 

Will clean it up sometime and probably move it to its own repo

**Comment by FabianTerhorst** [comment]
maybe jcenter upload?
