### ISSUE TITLE
Signature has been implemented in python

### ISSUE THREAD

**Issue by Paul776** [Grover-c13/PokeGOAPI-Java#492]
The extra signature field has been reversed and implemented in python
https://github.com/keyphact/pgoapi/blob/master/pgoapi/rpc_api.py#L69

Are some of you already working in porting this to java ?

(Note you need the encrypt.dll which hasn't been release yet)

**Comment by vmarchaud** [comment]
updated #486 : 

> Update : https://github.com/keyphact/pgoapi
> please make a PR if someone want to implement it.
> Currently no maintainer is working on this at my knowledge
