### ISSUE TITLE
Add ability to send device fingerprint and sensor data

### ISSUE THREAD

**Issue by jabbink** [Grover-c13/PokeGOAPI-Java#497]
**Description:**
Behave like a real device and allow setting a device fingerprint + sensordata.

**Comment by FabianTerhorst** [comment]
we could add a android module for that that can access this os apis.

**Comment by jsl303** [comment]
Should we all wait until this gets implemented, or is it safe to use?

**Comment by FabianTerhorst** [comment]
@jsl303 i don´t know if there ban accounts thats not sending the right device infos.

**Comment by vmarchaud** [comment]
@jsl303 As wrote in the readme, its never safe and never have been, if you already used the lib before, Niantic should know that you arent using the official app.

**Comment by jabbink** [comment]
They haven't perm banned anyone yet.

Also: even when you implement this feature (max 5 lines of code), detection of this API (or any other atm) is very easy as the requests don't look like the real app (or does this API already bundle requests into a single envelope?)

**Comment by pvanassen** [comment]
Yes it bundles requests if you use it properly

**Comment by s7092910** [comment]
@FabianTerhorst It would probably be best to put some provider interfaces. That way depending on the platform, the developer can fill in those fields in the providers.

**Comment by FabianTerhorst** [comment]
@s7092910 that was the way we would use. First add an interface to the library. Second add an module that is providing an interface for an platform.

**Comment by ramarro123** [comment]
@pvanassen  can you elaborate the
"it bundles requests if you use it properly"
sentence?

i see that almost everywhere there is AsyncHelper.toBlocking calls, making hard for me to think that it will bundle anything :)

**Comment by pvanassen** [comment]
Using the blocked calls is not using it properly :). If you use the async calls directly and build your app on the principles of Reactive programming, you will achieve parallelism, and requests will get bundled. 

Or you can have multiple threads going on for one player and do the blocking calls. This will do the same but can be a bit harder.

**Comment by ramarro123** [comment]
ah so, it will be cool they are deprecated :)

**Comment by FabianTerhorst** [comment]
Closed, because you can set the sensorinfos and deviceinfos now.
