### ISSUE TITLE
Accounts have to accept TOS before using API?

### ISSUE THREAD

**Issue by MrPat** [Grover-c13/PokeGOAPI-Java#500]
**Description:**
Pokemon Go accounts now have to accept the TOS before the API will work. Someone has made a Python script that will accept automatically, but I'm not sure how to port it to Java. Anyone capable of porting the script? It's really short but I'm not great with Python.

Accept TOS script https://github.com/scottstamp/pgoapi/blob/master/scripts/accept-tos.py

If this has been done already let me know and I'll close the issue, but I haven't seen any commits about it.

**Comment by Jazed** [comment]
#504
