### ISSUE TITLE
New release for new api

### ISSUE THREAD

**Issue by itsfolf** [Grover-c13/PokeGOAPI-Java#502]
When there will be a new release with the new api?

**Comment by SippieCup** [comment]
Its done.

**Comment by itsfolf** [comment]
There's nothing new in https://github.com/Grover-c13/PokeGOAPI-Java/releases

**Comment by ivankoma** [comment]
`git pull`
New api works.

**Comment by itsfolf** [comment]
I'm looking for the .jar

**Comment by itsfolf** [comment]
It's somewere or do I need to compile?

**Comment by itsfolf** [comment]
ops, sorry

**Comment by broach** [comment]
Clone, checkout Development, build project per the instructions, use jar.

If you're using it for android, you'll need to add an upstream from #501 and merge it.

**Comment by vmarchaud** [comment]
All information is in the readme, please read it.

**Comment by ivankoma** [comment]
@checkplys 
`git pull, 
git submodule update --init, 
gradlew.bat, 
gradlew build`

@broach 
I didn't do that, and everything works for me. How?
