### ISSUE TITLE
Question about radius

### ISSUE THREAD

**Issue by ivankoma** [Grover-c13/PokeGOAPI-Java#503]
What is the default radius for `go.getMap().getCatchablePokemon()` in meters? 

Can we change it?

Is that the same distance as distance in PoGo game?

**Comment by vmarchaud** [comment]
Its the same radius as in game, you cant change it since its server sided.

**Comment by ivankoma** [comment]
What about radius in meters? I want to create a circling algorithm to scan area around you as in `PokemonGoMap`.

In nobody knows the answers then tomorrow I will figure it out by walking outside.

**Comment by vmarchaud** [comment]
@ivankoma Should be around 200 meters but not sure.

**Comment by ivankoma** [comment]
Ok thanks, I will find out tomorrow.

**Comment by eraofchaos** [comment]
Hi,
You have all Server settings:
settings {
  fort_settings {
    interaction_range_meters: 40.0
    max_total_deployed_pokemon: 10
    max_player_deployed_pokemon: 1
    deploy_stamina_multiplier: 2.0
    far_interaction_range_meters: 1000.0
  }
  map_settings {
    pokemon_visible_range: 70.0
    poke_nav_range_meters: 201.0
    encounter_range_meters: 50.0
    get_map_objects_min_refresh_seconds: 5.0
    get_map_objects_max_refresh_seconds: 30.0
    get_map_objects_min_distance_meters: 10.0
    google_maps_api_key: "xxxx"
  }
  inventory_settings {
    max_pokemon: 1000
    max_bag_items: 1000
    base_pokemon: 250
    base_bag_items: 350
    base_eggs: 9
  }

Section: "map_settings". 
   CatchablePokemons - 201 meters
  You can catch them in 50 meters radius, PKO shows them in 70 meters radius..

Have fun!
