### ISSUE TITLE
GetMaps returns empty object?

### ISSUE THREAD

**Issue by JohnTendik** [Grover-c13/PokeGOAPI-Java#505]
Hey guys, I don't want to be a nuisance or anything but I'm having issues with the GetMaps method. 

Everything works in the API including getinventory, getplayerprofile etc, except for getmap. 

compile 'com.pokegoapi:PokeGOAPI-library:0.3.4'

Am I doing something wrong, did the API change at all? I tried waiting 5 seconds between requests, even at the initial request which seems excessive xD 

Thanks in advanced, and thanks for all the hard work! :+1:

**Comment by Jazed** [comment]
Having same issue here, looks like API isn't updated yet.

**Comment by gionata-bisciari** [comment]
Hi had the same issue and I was using a google refresh token to login, I deleted it and refreshed login and now all works fine!

**Comment by JohnTendik** [comment]
nice!! I'm going to try that out and see if I get any results :o

**Comment by gionata-bisciari** [comment]
I hope Essert been helpful :)

**Comment by Jazed** [comment]
PTC doesn't work for me.

EDIT: Just tried Google and generated new token still returns 0, after calling it 5 seconds after authenticating.

```
go.getMap().getMapObjects().getPokestops().size()
```

Is it working for you guys? if so could you show your implementation? @gionata-bisciari

**Comment by gionata-bisciari** [comment]
I'am using google access like in readme example, then I simply set go.setLocation(lat, lon, alt) and finally I call go.getMap().getMapObjects().getPokestops()

**Comment by Jazed** [comment]
I'm doing the exact same using the latest repo clone. 0.0 yet returns 0.

**Comment by gionata-bisciari** [comment]
Did you cloned Development or master branch?

**Comment by Jazed** [comment]
I cloned the dev branch, I'll reclone it and retry.

**Comment by gionata-bisciari** [comment]
Let us know if it works

**Comment by Jazed** [comment]
I've re-cloned and it seems to be going better now, however what is the new alternative for OkHttpClient? It's giving me a red line and doesn't give any suggestions as to what I should import.

**Comment by gionata-bisciari** [comment]
Great. Why we need an alternative?

**Comment by Jazed** [comment]
EDIT: Got it, looks like I needed the "all" generated .jar instead of just the library.

Thanks for the help :)

**Comment by Jazed** [comment]
Mind attaching your pogoapi.lib here?

**Comment by DrBrad** [comment]
Im having the same issue using this line compile 'com.pokegoapi:PokeGOAPI-library:0.3.4' in the gradle... Nothing shows on get map even with a 5 second after log in...

**Comment by Jazed** [comment]
@DrBrad Try this:

```
git clone --recursive -b Development https://github.com/Grover-c13/PokeGOAPI-Java.git &&
cd PokeGOAPI-Java && ./gradlew build
```

Then the lib should be found in: 

```
PokeGOAPI-Java\library\build\libs\PokeGOAPI-library-all-0.3.0.jar
```

**Comment by DrBrad** [comment]
Alright ill try that but isn't the update 0.3.4?

**Comment by Jazed** [comment]
Well that's the version that builds from the Dev branch, so I wouldn't know if theres anything above that builds from it.

**Comment by DrBrad** [comment]
What JDK is required for this because I'm getting this error...

Could not find tools.jar. Please check that /usr/lib/jvm/java-7-openjdk-amd64 contains a valid JDK installation.

**Comment by Jazed** [comment]
I had that error as well, you should google around and check for classpaths correctly. Was really annoying to fix.

**Comment by DrBrad** [comment]
I'm gonna try JDK 8 then ill Google. Thank you for your help @Jazed

**Comment by DrBrad** [comment]
For anyone else having this issue and is using Ubuntu this worked. Just  enter: sudo apt-get install default-jdk

**Comment by FabianTerhorst** [comment]
@DrBrad : @Grover-c13 has to publish version 0.4.0.

**Comment by DrBrad** [comment]
@FabianTerhorst That or possibly you could use the commit by jabink.

**Comment by FabianTerhorst** [comment]
@DrBrad i uploaded 0.4.0 on my own jcenter profile.

**Comment by DrBrad** [comment]
@FabianTerhorst How do you do that?

**Comment by FabianTerhorst** [comment]
@DrBrad i created the feature for the jcenter upload, because of that i tested this first and created and account for that with the package. This package got jcenter upload permisson from bintray.

**Comment by ivoavido** [comment]
I have imported the 0.4.0 library in my project, but I still get an empty MapObjects (gyms, pokestops and nearby Pokemons).

**Comment by ulyssessouza** [comment]
@andreaparise92 I finally got it working...
Take a look at:
https://github.com/Grover-c13/PokeGOAPI-Java/pull/516

**Comment by ivoavido** [comment]
@ulyssessouza Thanks

**Comment by FabianTerhorst** [comment]
Looks like this is solved with the default device info
