### ISSUE TITLE
Every pokemon fleeing

### ISSUE THREAD

**Issue by Jazed** [Grover-c13/PokeGOAPI-Java#506]
I am currently not softbanned however whenever I try to catch a pokemon, it will always flee. My guess is due to incorrect values such as spin, etc which were removed by Niantic.

**Comment by pvanassen** [comment]
This is a known server issue: https://twitter.com/PokemonGoApp/status/761301330967326720

**Comment by Jazed** [comment]
Right, so the API should be updated to remove sending those bonuses.

**Comment by DrBrad** [comment]
@Jazed It could also be caused by "teleportation". Meaning that you change you lat/lon and change it to an unreasonable amount within a time that is unreasonable to get to said location by car/plane.

**Comment by Jazed** [comment]
I will do more tests tomorrow, but it doesn't look like it as it happens in between pokestops and it isn't soft banned at that point.

**Comment by vmarchaud** [comment]
Working great for me, should come from your utilisation of the API.

**Comment by SippieCup** [comment]
This happened to me when writing poke mate. The `CatchResult` object would sometimes return as unsuccessful when it did catch the pokemon.

I do believe it was fixed, but its probably related.

**Comment by Jazed** [comment]
Do you need to wait 10 seconds between encounters or catches?

**Comment by Jazed** [comment]
@vmarchaud Can you show me sample code of a successful catch? still having trouble.

**Comment by Jari27** [comment]
This works:

```
List<CatchablePokemon> CatchablePokemons = api.getMap().getCatchablePokemon();
for (CatchablePokemon cp : CatchablePokemons) {
    if (!cp.isEncountered()) {
        EncounterResult er = cp.encounterPokemon();
        if (er.wasSuccessful()) {
            CatchResult cr = cp.catchPokemon();
            if (cr.isFailed()) {
            // fail catch
            } else {
            // succes catch
        } else {
        // fail encounter
    }
}
```

**Comment by Jazed** [comment]
@Sadye Using the above code I get a fail encounter. Cloned last dev branch.

**Comment by Jazed** [comment]
There we go, thanks :)
