### ISSUE TITLE
Getting the amount of candy of a PkMn ID

### ISSUE THREAD

**Issue by DiogoRNeves** [Grover-c13/PokeGOAPI-Java#51]
Are you planning on implementing this, or is it there and I'm missing it? 

It would be very useful as in validating wether a Pokémon can evolve or not before requesting it to the server and to calculate the optimum amount of Pokémon to transfer (and then transfer them).

And congrats on the work so far!

**Comment by Grover-c13** [comment]
Not currently implemented, will be sometime.

**Comment by DiogoRNeves** [comment]
Thanks.

**Comment by Grover-c13** [comment]
This is now implemented using a getCandy() method on a Pokemon object #59

**Comment by DiogoRNeves** [comment]
You're the best. Thanks man! Keep it up!
