### ISSUE TITLE
getCatchablePokemon method still returning 0 results

### ISSUE THREAD

**Issue by meher19** [Grover-c13/PokeGOAPI-Java#513]
i updated api dependency to use the last version (0.3.4), but this method still return no results, i'm pretty sure in the location where i execute this methos there is many pokemons !

This is related to the closed issue : #486

Maybe i missed something to make it work again ?

**Comment by FabianTerhorst** [comment]
@Grover-c13 has to upload 0.4.0 to jcenter.

**Comment by meher19** [comment]
so the jcenter library still not updated ?

**Comment by FabianTerhorst** [comment]
Not right now.

**Comment by meher19** [comment]
ok, can you update this topic when it's done ?

Thanks.

**Comment by loicortola** [comment]
Hi @FabianTerhorst 
Great job out there on the comments and setSignature() implementation.
I am using your fork while @Grover-c13 is still working on the release, and am experiencing the same issues as @meher19 .
No error, no pokemons.

I double checked that the valid SensorInfo and DeviceInfo was set correctly and put into signature.
I feel like I'm missing something... Thoughts?

**Comment by FabianTerhorst** [comment]
@loicortola there released a new version 0.33.0 for the android app. But the server behavior shouldn´t change. You are getting the right profile name returned?

**Comment by FabianTerhorst** [comment]
So are other requests working like pokestops?

**Comment by loicortola** [comment]
Nope, all 0.

**Comment by Luigik2806** [comment]
I am testing on android, i used the 0.4.0 version and I get an empty list of catchable pokemons too

**Comment by FabianTerhorst** [comment]
@Luigik2806 me too, you are getting pokestops, right?

**Comment by FabianTerhorst** [comment]
I have tested it now and im getting pokemon back when im setting the device info. Take a look at #516 for sample code.

**Comment by Luigik2806** [comment]
```
SensorInfo sensorInfo = new SensorInfo();
sensorInfo.setAngleNormalizedY(0);
go.setSensorInfo(sensorInfo);
```

This code doesn't work, `SensorInfo()` is private and `go.setSensorInfo(sensorInfo);` doesn't exist, if I remove this 3 lines I still get an empty list

**Comment by mgorski-mg** [comment]
@Luigik2806 because it's only on PR.

**Comment by meher19** [comment]
I updated the dependency to 0.4.0, it's worked for me without adding the DeviceInfo and SensorInfo staff, what's the utility of this lines ?

**Comment by FabianTerhorst** [comment]
Can you check if you get something back with the same Code from #516 in the comments.

**Comment by FabianTerhorst** [comment]
when not should you create a new account.

**Comment by meher19** [comment]
By adding DevideInfo it's still working, but i can't add SensorInfo because i can't find this class in the latest dependecy version.

**Comment by FabianTerhorst** [comment]
You have to use my fork from the #516 to test this

**Comment by meher19** [comment]
Which dependecy i have to use to import your fork from Gradle ?

**Comment by Luigik2806** [comment]
Now I have tested both method, adding depency 'com.pokegoapi:PokeGOAPI-library:0.4.0-alpha1' and putting the code and its dependecy. Still get empty list...., I'm finding catchablePokemon in Parco Sempione, Milan, so I am sure that there are some catchable pokemons

**Comment by FabianTerhorst** [comment]
You have to Clone the fork and generate the jar.

**Comment by Luigik2806** [comment]
Ok, this is strange maybe...but same code in eclipse works in android studio dont
P.S. I used your fork

**Comment by mackenzieg** [comment]
@FabianTerhorst How can you implement the SensorInfo part without using your pr? I am using reflection to set the values and all that but the only problem is setting the SensorInfo.

```
    try {

        SignatureOuterClass.Signature.SensorInfo sensorInfo = SignatureOuterClass.Signature.SensorInfo.newBuilder().build();
        Field field = sensorInfo.getClass().getField("angleNormalizedZ_");
        field.setAccessible(true);
        field.setInt(sensorInfo, 0);
    } catch (Exception e) {
        e.printStackTrace();
    }
```

**Comment by FabianTerhorst** [comment]
@mackenziejgoodwin its merged now, you can use the latest commit.

**Comment by mackenzieg** [comment]
@FabianTerhorst Despite the update I am still getting zero pokemon and zero pokestops...

Example:

```
    List<CatchablePokemon> pokemons = getBot().getPokemonGo().getMap().getCatchablePokemon();
    System.out.println(pokemons.size() + " Pokemon");
    if (pokemons != null) {
        if (pokemons.size() > 0) {
            CatchablePokemon catchablePokemon = pokemons.get(0);

            EncounterResult encounterResult = catchablePokemon.encounterPokemon();
            if (encounterResult.getCaptureProbability().getCaptureProbabilityCount() <= Config.getCatchChanceUseRazzberry())
                ; //TODO use razzberrry
            CatchResult catchResult = catchablePokemon.catchPokemon(Pokeball.POKEBALL);
            if (catchResult.getStatus().equals(CatchPokemonResponseOuterClass.CatchPokemonResponse.CatchStatus.CATCH_SUCCESS)) {
                System.out.println(Ansi.ansi().fg(Ansi.Color.GREEN).a("Caught a " + catchablePokemon.getPokemonId().name() + "!"));
            } else {
                System.out.println(Ansi.ansi().fg(Ansi.Color.GREEN).a("Error Catching pokemon " + catchablePokemon.getPokemonId().name() + "... Fled?"));
            }
        }


        Walk.setLocation(this.getBot());
    }
```

**Comment by FabianTerhorst** [comment]
you setted the Default device infos?

**Comment by mackenzieg** [comment]
@FabianTerhorst 

```
    DeviceInfo deviceInfo = DeviceInfo.DEFAULT;
    pokemonGo.setDeviceInfo(deviceInfo);

    SensorInfo sensorInfo = new SensorInfo();
    sensorInfo.setAngleNormalizedZ(0);
    pokemonGo.setSensorInfo(sensorInfo);
```

**Comment by FabianTerhorst** [comment]
and without the sensorinfos, because im using for default now a ios device and i don´t know the sensor infos for ios.

**Comment by FabianTerhorst** [comment]
looks like niantic requires more infos now, because at the morning i got catchable pokemon back now with the same request im only getting pokestops back

**Comment by FabianTerhorst** [comment]
Im getting 1 back everytime when i change the location a little bit.

**Comment by FabianTerhorst** [comment]
At this place there isn´t more then one so its ok.

**Comment by mackenzieg** [comment]
@FabianTerhorst What is your location because no matter what location I set it returns 0.
My Code: https://github.com/mackenziejgoodwin/PokemonGoBot/blob/master/src/main/java/com/pokemongobot/PokemonGoBot.java
https://github.com/mackenziejgoodwin/PokemonGoBot/blob/master/src/main/java/com/pokemongobot/tasks/CatchPokemon.java

**Comment by FabianTerhorst** [comment]
```
        double lat = 48.847533008980086;
        double lng = 2.3301315307617188;
        go.setLocation(lat,lng, 0);
```

When you don´t get some back create a new account.

**Comment by mackenzieg** [comment]
@FabianTerhorst I created a new account (found out my other account was softbanned) and it still doesn't find any pokemon or stops.

**Comment by FabianTerhorst** [comment]
@mackenziejgoodwin you don´t even find 94 stops on the lat lng i provided and you are using 3g?

**Comment by mackenzieg** [comment]
@FabianTerhorst Indeed. Here is some debug output...

```
System.out.println(pokemonGo.getMap().getMapObjects().toString());
MapObjects(nearbyPokemons=[], catchablePokemons=[], wildPokemons=[], decimatedSpawnPoints=[], spawnPoints=[], gyms=[], pokestops=[], complete=false, api=com.pokegoapi.api.PokemonGo@7f77e91b)
```

Appears to not see anything on the map... weird.
It does pull the inventory properly though

```
           List<Pokemon> s = pokemonGo.getInventories().getPokebank().getPokemons();
        String t = "";
        for(Pokemon pokemon : s) {
            t += pokemon.getPokemonId().name();
        }
        System.out.println(t);
        SQUIRTLE
```

**Comment by FabianTerhorst** [comment]
Can you test 3g when not wait 24hours and try again could be a local ip ban.

**Comment by mackenzieg** [comment]
@FabianTerhorst Made another account, tried using a proxy and changing ip, still nothing.

**Comment by FabianTerhorst** [comment]
you tried the catch example?

**Comment by olegshulyakov** [comment]
@mackenziejgoodwin your MapObjects has **_complete=false_** thats why there is nothing near you.
Try to debug your code to see when it is updated and when you are using it.

**Comment by meher19** [comment]
I tried to use the last sources of the library to test it, but when i import the jar to my project, i have this compile error : 

```
Error:(58, 54) Gradle: error: cannot access MessageOrBuilder
class file for com.google.protobuf.MessageOrBuilder not found
Error:(60, 80) Gradle: error: cannot access GeneratedMessage
class file for com.google.protobuf.GeneratedMessage not found
```

I tried to add com.google.protobuf plugin to my gradle build file, but this not resolves my problem..

**Comment by meher19** [comment]
Update : 
I resolved the problem by adding this dependecy to gradle build : 
`compile 'com.google.protobuf:protobuf-java:2.4.1'`

But now, when i instanciate GoogleAutoCredentialProvider, i have this exception : 
`java.lang.NoClassDefFoundError: Failed resolution of: Lsvarzee/gps/gpsoauth/Gpsoauth;`

**Comment by mackenzieg** [comment]
@meher9 
You need to download the dependencies.
git submodule update --init

See here: https://github.com/mackenziejgoodwin/PokemonGoBot/blob/master/update.bat

**Comment by meher19** [comment]
@mackenziejgoodwin 
i already updated the dependecies
