### ISSUE TITLE
API stops returning pokemon after amount of time.

### ISSUE THREAD

**Issue by jay8ee** [Grover-c13/PokeGOAPI-Java#515]
I noticed that the API stops returning Pokemon after about an hour of successful scanning. No exceptions are thrown, just zero Pokemon returned from getCatchablePokemon.

My java code is respecting the API limit, as I understand it you shouldn't call getCatchablePokemon more than once every 10 seconds.

I've been using latest from the dev branch.

**Comment by gdespres** [comment]
Maybe you're blacklisted by Niantic !

**Comment by jay8ee** [comment]
If that's the case then why does restarting the API fix the issue?

**Comment by mgorski-mg** [comment]
@jay8ee do you change cellWidth?
Because when I changed it to 9, I stoped returning map objects after some time.

**Comment by jay8ee** [comment]
I'm using the default set by the library, which is currently 3.

**Comment by jay8ee** [comment]
I was taking a look at the change @jabbink made 867e972e828412b45ad3482365f05cdda1023977. Could be related? I assume before this google tokens weren't refreshing?

**Comment by jabbink** [comment]
Yes, before that you would just get kicked out after 1.5 hours and everything would crash. I did confirm with a few people though that their instance of the API with Google login did work for 8+ hours just now (including catching pokemon).

**Comment by jabbink** [comment]
There might be a problem right here:

https://github.com/jabbink/PokeGOAPI-Java/blob/2aec73d2d3e4dec4838276f7bbe6eaf63fb555ff/library/src/main/java/com/pokegoapi/util/Signature.java#L34-L34 in the case `internalSendServerRequests` was called from here https://github.com/jabbink/PokeGOAPI-Java/blob/e1d2d15320f363da89ae09b411fce0e7ba672066/library/src/main/java/com/pokegoapi/main/RequestHandler.java#L221-L221

Then there is _one_ request that uses the wrong authentication I guess, but all subsequent use the correct one again.

**Comment by jay8ee** [comment]
I grabbed the changes you made to the Google refresh token and now it seems to search just fine. Many thanks for the help.

**Comment by jabbink** [comment]
Wait, you weren't using the newest version from `Development` when you made this issue?
