### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by Rimander** [Grover-c13/PokeGOAPI-Java#517]
I cant use https://github.com/AeonLucid/POGOProtos

Errors:
`
Signature.java:64: error: cannot find symbol
        builder.addUnknown6(uk6);
`

`error: no suitable constructor found for ServerRequest(RequestType,UseItemReviveMessage)
        ServerRequest serverRequest = new ServerRequest(RequestType.USE_ITEM_REVIVE, reqMsg);`

**Comment by kyr0** [comment]
Yes, confirmed. Don't work for me neither.

Also unk22 has been renamed in the protos to unknown22. 
So setUnk22() is also wrong. It should be setUnknown22() now.

See: https://github.com/AeonLucid/POGOProtos/commit/eca2d143059c51ac20f566d96a933e4b0b823b58

setUnknown6() also isn't generated by protoc based on the new proto definitions. This is because the term "repeated" has been removed in this commit:

https://github.com/AeonLucid/POGOProtos/blob/014fed5148df85a89a2c06f55e8b6a4919a15778/src/POGOProtos/Networking/Envelopes/RequestEnvelope.proto#L16

Also the method setUnknown1() is missing; it looks like it's because they renamed the field from unknown1 to encrpyted_signature:

https://github.com/AeonLucid/POGOProtos/commit/0a3a48cf9136e94757b994636478f5dce405a6a0#diff-93b5ab0ea93383f11531e2f778ec1ff2L9

So as a quick fix, you can apply the following patch:

```
   public static void setSignature(PokemonGo api, RequestEnvelopeOuterClass.RequestEnvelope.Builder builder) {
    if (builder.getAuthTicket() == null) {
        //System.out.println("Ticket == null");
        return;
    }
    byte[] uk22 = new byte[32];
    new Random().nextBytes(uk22);

    long curTime = api.currentTimeMillis();

    byte[] authTicketBA = builder.getAuthTicket().toByteArray();

    SignatureOuterClass.Signature.Builder sigBuilder = SignatureOuterClass.Signature.newBuilder()
            .setLocationHash1(getLocationHash1(api, authTicketBA, builder))
            .setLocationHash2(getLocationHash2(api, builder))
            .setUnknown22(ByteString.copyFrom(uk22))
            .setTimestamp(api.currentTimeMillis())
            .setTimestampSinceStart(curTime - api.startTime);

    SignatureOuterClass.Signature.DeviceInfo deviceInfo = api.getDeviceInfo();
    if (deviceInfo != null) {
        sigBuilder.setDeviceInfo(deviceInfo);
    }


    for (RequestOuterClass.Request serverRequest : builder.getRequestsList()) {
        byte[] request = serverRequest.toByteArray();
        sigBuilder.addRequestHash(getRequestHash(authTicketBA, request));
    }

    // TODO: Call encrypt function on this
    byte[] uk2 = sigBuilder.build().toByteArray();
    byte[] iv = new byte[32];
    new Random().nextBytes(iv);
    byte[] encrypted = Crypto.encrypt(uk2, iv).toByteBuffer().array();
    Unknown6OuterClass.Unknown6 uk6 = Unknown6OuterClass.Unknown6.newBuilder()
            .setRequestType(6)
            .setUnknown2(Unknown2.newBuilder().setEncryptedSignature(ByteString.copyFrom(encrypted))).build();
    builder.addUnknown6(uk6);
}
```

And add the "repeated" term in RequestEnvelope.proto:

```
repeated .POGOProtos.Networking.Envelopes.Unknown6 unknown6 = 6;
```

**Comment by Rimander** [comment]
Thank you,
When you update the API¿

**Comment by FabianTerhorst** [comment]
I can add this to #516

**Comment by FabianTerhorst** [comment]
but we don´t change the protofiles so we can´t add the repeatable.

**Comment by kyr0** [comment]
Yep, maybe ask the guys over there; the comment in the commit doesn't look like that the implication was clear to them...

**Comment by FabianTerhorst** [comment]
but setUnknown6 should be the same

**Comment by kyr0** [comment]
Well, it should... just when I remove the "repeated" I get:

Error:(64, 10) error: cannot find symbol method addUnknown6(Unknown6)

**Comment by FabianTerhorst** [comment]
you can use setUnknown6(builder)

**Comment by FabianTerhorst** [comment]
you are using gradle on your project?

**Comment by kyr0** [comment]
Oh, yes; eagle eye! :) 👍 

[EDIT: REMOVED]; compiles.

**Comment by FabianTerhorst** [comment]
you can try if compile 'com.pokegoapi:PokeGOAPI-library:0.4.0-alpha1' is working for you.

**Comment by FabianTerhorst** [comment]
with 

``` groovy
repositories {
    maven {
        url  "http://dl.bintray.com/fabianterhorst/maven" 
    }
}
```

**Comment by kyr0** [comment]
Well, I'm having an unrelated issue here, because I'm running on Android:
java.lang.ClassNotFoundException: Didn't find class "net.jpountz.xxhash.XXHash32JavaSafe" on path

**Comment by FabianTerhorst** [comment]
@kyr0 thats an known bug.

**Comment by kyr0** [comment]
Side-note: I already integrated https://github.com/Grover-c13/PokeGOAPI-Java/pull/501 locally
