### ISSUE TITLE
Android and DeviceInfo

### ISSUE THREAD

**Issue by hugorosario** [Grover-c13/PokeGOAPI-Java#518]
Now that we have to set the DeviceInfo and I am developing for Android, I would like to match the DeviceInfo with the same values that the official client is sending and I am not really sure what some of the values should be.

I am using this to populate the DeviceInfo object : 

```
            pogo = new PokemonGo(provider, httpClient);
            DeviceInfo info = new DeviceInfo();
            info.setAndroidBoardName(Build.BOARD);
            info.setAndroidBootloader(Build.BOOTLOADER);
            info.setDeviceBrand(Build.BRAND);
            info.setDeviceId(Settings.Secure.getString(mContext.getContentResolver(), Settings.Secure.ANDROID_ID));
            info.setDeviceModel(Build.PRODUCT);
            info.setDeviceModelBoot(Build.BOARD);
            info.setDeviceModelIdentifier(Build.ID);
            info.setFirmwareBrand(Build.PRODUCT);
            info.setFirmwareFingerprint(Build.FINGERPRINT);
            info.setFirmwareTags(Build.TAGS);
            info.setFirmwareType(Build.TYPE);
            info.setHardwareManufacturer(Build.MANUFACTURER);
            info.setHardwareModel(Build.MODEL);
            pogo.setDeviceInfo(info);
```

Most of the fields are self-explanatory but there are some that give me doubts like :
- DeviceModelBoot (what should that be?)
- FirmwareBrand vs DeviceBrand?

I know that the API works with whatever you put on this fields but I want to send exactly what the official client is sending to avoid getting flagged when they check the logs...

**Comment by FabianTerhorst** [comment]
The pr is opened right now for a better documentation. https://github.com/FabianTerhorst/PokeGOAPI-Java/blob/3f819eaee6dee46b1304fcfc45e15f5dbe7be6f0/library/src/main/java/com/pokegoapi/api/device/DeviceInfo.java
