### ISSUE TITLE
Signature.java uses unimplemented POGOproto methods

### ISSUE THREAD

**Issue by RomanTheLegend** [Grover-c13/PokeGOAPI-Java#519]
**Description:**
I'm using the latest protobus files (from https://github.com/AeonLucid/POGOProtos)
and seems like Signature.java is using methods that are not implemented in protobufs:

  method setUnk22(com.google.protobuf.ByteString)
  method setUnknown1(com.google.protobuf.ByteString)
  method addUnknown6(POGOProtos.Networking.Envelopes.Unknown6OuterClass.Unknown6)
  **Steps to reproduce:**
1. Get latest protobufs (https://github.com/AeonLucid/POGOProtos)
2. Compile them
3. Plug them into project

**Stacktrace (If it's a crash):**
C:\Dev\TestPokeMaps\src\com\pokegoapi\util\Signature.java
Error:(41, 33) java: cannot find symbol
  symbol:   method setUnk22(com.google.protobuf.ByteString)
  location: class POGOProtos.Networking.Envelopes.SignatureOuterClass.Signature.Builder
Error:(63, 67) java: cannot find symbol
  symbol:   method setUnknown1(com.google.protobuf.ByteString)
  location: class POGOProtos.Networking.Envelopes.Unknown6OuterClass.Unknown6.Unknown2.Builder
Error:(64, 24) java: cannot find symbol
  symbol:   method addUnknown6(POGOProtos.Networking.Envelopes.Unknown6OuterClass.Unknown6)
  location: variable builder of type POGOProtos.Networking.Envelopes.RequestEnvelopeOuterClass.RequestEnvelope.Builder

**Version:**
PokeGOAPI-Java commit f62049c 

**Side comment**
It would be good if you give a link to protobufs you're using in Readme file

**Comment by AbandonedCart** [comment]
See https://github.com/Grover-c13/PokeGOAPI-Java/pull/516

**Comment by kyr0** [comment]
Also https://github.com/Grover-c13/PokeGOAPI-Java/issues/517 for a quick fix

**Comment by AbandonedCart** [comment]
The "quick fix" involves editing the protos and is actually a lot longer than a cherry-pick, but was quick at the time

**Comment by kyr0** [comment]
> The "quick fix" involves editing the protos

No, it doesn't. Better read the comments ;)  By using setUnknown6(...) no proto file has to be changed.
