### ISSUE TITLE
How to refresh data without recreating another client?

### ISSUE THREAD

**Issue by mortyccp** [Grover-c13/PokeGOAPI-Java#520]
I need to refresh data to fetch the latest pokemon, and I can't find any api to do refresh data apart from recreating the client with the same credential provider. Is there any way to do that?

**Comment by DrakeSharp** [comment]
Don't know what you want exactly but maybe:
Inventory:        go.getInventories().updateInventories(true);
Catchable:        go.getMap().getCatchablePokemon();

**Comment by mortyccp** [comment]
Thank you. updateInventories is what I am looking for.
