### ISSUE TITLE
Cannot compile project

### ISSUE THREAD

**Issue by rah-0** [Grover-c13/PokeGOAPI-Java#524]
This project is so badly explained, I cant manage to get get it running without errors: 

1 So the first thing i did was to download the project
2 Then I went to the folder location with command prompt and I wrote: gradlew.bat :library:build
3 After that i get a lot of errors like: C:\Users\MyUser\PokeGOAPI-Java-Development\library\src\main\java\com\pokegoapi\api\gym\Battle.java:18: error: package POGOProtos.Data.Battle.BattleActionOuterClass does not exist
import POGOProtos.Data.Battle.BattleActionOuterClass.BattleAction;

Are you kidding me? There is no way to compile this? There are over 500 errors, including code errors. 
And what is this PokeGOAPI-library-all-0.X.X.jar? There is no way of getting this JAR no matter what you do. 

Can someone explain the damn process of deploying properly without errors?

**Comment by Grover-c13** [comment]
Did you git submodule update --init as per the readme?

**Comment by rah-0** [comment]
Did git submodule update --init
Then ./gradlew :library:build

Got some warnings but no errors, now i have the ALL jar, 
can this be used in any editor? Or is it gradle dependant?

**Comment by vmarchaud** [comment]
Please follow the readme, there are all indication on how to compile AND how to use the project.
