### ISSUE TITLE
disable log

### ISSUE THREAD

**Issue by bolds07** [Grover-c13/PokeGOAPI-Java#531]
I would like to know how to disable this log, because i'm also using system output as log api is sending lot of mesages as: 

V/CatchablePokemon: Pokemon caught/or flee 

totally useles to me, and as i run a batch of threads is almost impossible to check the real data that i'm looking for

**Comment by Jari27** [comment]
Put somewhere in your code (as early as possible) `Log.setLevel(Level.NONE)`.

**Comment by Jari27** [comment]
Can you close the issue if it worked?

**Comment by vmarchaud** [comment]
Re-open if it isnt the case but from your reaction it should.
