### ISSUE TITLE
Feature: Being able to transfer a pokemon newly captured

### ISSUE THREAD

**Issue by davinkevin** [Grover-c13/PokeGOAPI-Java#532]
**Description:**
If I want to automatically transfer a pokemon after having caught it, I have to force update the inventory because if I don't, the method `getPokemonById` return null... so the transfer operation lead to a NullPointerException.

I think, a method `transferPokemon` available in the in CatchablePokemon could be useful.

**Steps to reproduce:**
1. Catch a pokemon with method `CatchResult result = cp.catchPokemon` where `cp` is a `CatchablePokemon`
2. Try to transfer the pokemon with `go.getInventories().getPokebank().getPokemonById(result.getCapturedPokemonId())).transferPokemon();`

**Expected behavior:**
Transfer the pokemon

**Actual behavior:**
Trigger a NullPointerException because the pokemon isn't in the inventory

**Version:**
Dev on commit f62049cc382a4f280c49b06b3e726304dbf07381

**Comment by bolds07** [comment]
That is possible to do with java reflection. [or in a even worse way with lots of redundant code]

I've already wrote about this thing #379 but it was closed and said that is out of escope

what you need to do is:

```
try {
                    Field f = data.getClass().getDeclaredField("id_");
                    f.setAccessible(true);
                    f.set(data, result.getCapturedPokemonId());
                }
                catch (IllegalArgumentException | IllegalAccessException | NoSuchFieldException | SecurityException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                Pokemon p = new Pokemon(this.api, data);
```

where data is the wildpokemon.getdata()
result is the return of catchPokemon method
and api is the pokemonGo object
