### ISSUE TITLE
getCpAfterEvolve() from #495 returns the wrong value

### ISSUE THREAD

**Issue by cesco89** [Grover-c13/PokeGOAPI-Java#533]
As said, the method getCpAfterEvolve() in file PokemonDetails.java return a number with 6 digits.
Example: 
Actual CP = 337
CP after Powerup = 349
CP After Evolution = 386239

Can someone help me to figure out a workaround for this? 
thanks :D

**Comment by Jari27** [comment]
@pvanassen

**Comment by mgorski-mg** [comment]
It was a problem in evolution formula - it should use cp multiplier not pokemon lvl.
https://github.com/Grover-c13/PokeGOAPI-Java/pull/538
More info: https://www.reddit.com/r/pokemongodev/comments/4t7xb4/exact_cp_formula_from_stats_and_cpm_and_an_update

**Comment by cesco89** [comment]
@mgorski-zlatan Great! Thanks!

**Comment by pvanassen** [comment]
It it fixed?

**Comment by mgorski-mg** [comment]
not merged yet, but yes it's fixed

**Comment by mgorski-mg** [comment]
@cesco89, now it is merged, if it is working for you, please close this issue :)
