### ISSUE TITLE
getPokemons().size() returns wrong value

### ISSUE THREAD

**Issue by francesco-tran** [Grover-c13/PokeGOAPI-Java#535]
**Description:**
Hello,
I just tried logging into my google account and print getPokebank().getPokemons().size().
On my account I have 189 pokemons, the list returned has only 180 pokemons.

**Version:**
I'm using version 0.4.0

**Comment by steathy** [comment]
that's 9 pokemon eggs you are talking about

**Comment by Grover-c13** [comment]
Pokebank does not include eggs

**Comment by francesco-tran** [comment]
Gotcha, thanks
