### ISSUE TITLE
Feature: Return the user level.

### ISSUE THREAD

**Issue by TheEpTic** [Grover-c13/PokeGOAPI-Java#537]
**Description:**
It would be awesome if we were able to pull the user's level. Possibly `PlayerProfile#getLevel`

**Comment by Recolance** [comment]
You can do this already..

**Comment by TheEpTic** [comment]
I can't find any documentation on this nor can I find it in the code. Could you reference me? Thanks

**Comment by Recolance** [comment]
account.getPlayerProfile().getStats().getLevel();

**Comment by TheEpTic** [comment]
Ah... I see. Now I feel stupid.

Thank you :]
