### ISSUE TITLE
Gradle build

### ISSUE THREAD

**Issue by Recolance** [Grover-c13/PokeGOAPI-Java#539]
https://gyazo.com/f7e50d49f1fc938d3c8ee0f789f6f396

Really not sure here.. Anyone know? Keeps failing to build

**Comment by AbandonedCart** [comment]
Probably because you are using the wrong command. You want `:library:build` not `generateProto`

**Comment by Recolance** [comment]
I ran exactly what is in the build sources section of the git page.

https://gyazo.com/52ca88f08594ae02ad592a566e4ea7d5

See what I typed in. Which is why I am confused.

**Comment by AbandonedCart** [comment]
Try running `./gradlew clean` since it looks like the issue is in a cache folder. That or try moving the source closer to the root directory (ie. C:/) to avoid adding extra subdirectories to the path.

**Comment by Recolance** [comment]
Unfortunately this didn't work either. 

I built this a few days ago, I just wanted an updated jar.

**Comment by AbandonedCart** [comment]
You probably need the updates for the new protos. 
You can either wait for a merge or get them from the PR

**Comment by Grover-c13** [comment]
206 is filename too long, which os are you on?

**Comment by Recolance** [comment]
Managed to build it, really not sure exactly what I did, but it built. Thanks for the help guys!

Windows 7-64bit
