### ISSUE TITLE
AsyncPokemonGoException

### ISSUE THREAD

**Issue by Recolance** [Grover-c13/PokeGOAPI-Java#542]
Currently experiencing this error everytime I try to access playerProfile().getStats();
https://gyazo.com/73cefaf853857c511cf519ee21a64921

It's practically random but happens more time then not. Sometimes it decides to return properly, and most of the time it just throws an error.

This is the code I am using that is throwing the error: http://hastebin.com/idulohodok.coffee

**Comment by IronPepper3964** [comment]
I just wanted to say "me too"

I have the same issue when running getMap().getNearbyPokemon(); and similar methods.

I can't find a rhyme or reason: just about 50-75% of the time it fails to call the functions with com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred.

I saw an earlier issue was closed suggesting the user was temporarily banned, but I can have a successful call, failed call, and another successful call within a minute.

**Comment by clangdev** [comment]
I am currently looping over "critical" API-Calls until they give positive response. Pretty odd but works for me..

while (!optimizePokemon(p));

within boolean optimizePokemon(Pokemon p); I either return true or false if I hit that Exception and just wait 300ms.

**Comment by nacheteam** [comment]
This seems a little bit weird to me because if I execute my java program in Linux it gives me this error each 4 minutes or less. I have got also a windows system in my laptop and if I execute it in windows it does not gives me this error. It is exactly the same code and I'm executing it in NetBeans on both systems.

**Comment by IronPepper3964** [comment]
I have been using Android Studios with a Nexus 5 Emulator on Windows 10.

**Comment by FabianTerhorst** [comment]
You still got the error? Looks server related, because of null response.

**Comment by Nyazuki** [comment]
Any update on this? I am on a mac. #629

**Comment by FabianTerhorst** [comment]
you are getting this exception also on the sample?

**Comment by Nyazuki** [comment]
@FabianTerhorst thought so since you marked my issue as the dup on this, but it is more like https://github.com/Grover-c13/PokeGOAPI-Java/issues/593 I think.

**Comment by FabianTerhorst** [comment]
You are getting null result. #593 is getting 53 Status Code.

**Comment by FabianTerhorst** [comment]
getStats doesn´t execute a network request anymore.
