### ISSUE TITLE
How to access refreshToken in GoogleAutoCredentialProvider ?

### ISSUE THREAD

**Issue by ricechenghk** [Grover-c13/PokeGOAPI-Java#549]
I am now using GoogleAutoCredentialProvider for login and would like to store refreshToken for next time login. But seems it is not accessible.

**Comment by vmarchaud** [comment]
Just [here](https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/auth/GoogleUserCredentialProvider.java#L51), you can access it with`provider.getRefreshToken()`
