### ISSUE TITLE
I didn't find gyms, pokestop and pokemon

### ISSUE THREAD

**Issue by michibat01** [Grover-c13/PokeGOAPI-Java#550]
It doesn't find me gyms , pokestop and pokemon despite there being over, but I can access all of the backpack items.

Authentication:Google
Version:4.0.0

Sorry for my english

**Comment by vmarchaud** [comment]
You might be softbanned, please retry with another account/ip or wait few hours before retrying, and you shouldnt teleport in game if you dont want to be softbanned.

**Comment by michibat01** [comment]
I have already tried, but do not show changes, always set the same position to avoid softban
@vmarchaud

**Comment by michibat01** [comment]
I Have tried with the official client and with the same ip and work!

**Comment by FabianTerhorst** [comment]
you tried to set the device infos? `new PokemonGo();... go.setDeviceInfo(DeviceInfo.DEFAULT);` ?

**Comment by michibat01** [comment]
no, it may affect ? @FabianTerhorst

**Comment by FabianTerhorst** [comment]
@michibat01 just try. It could.

**Comment by FabianTerhorst** [comment]
And update to the latest commit to use it properly.

**Comment by michibat01** [comment]
PokemonGo class has not setDeviceInfo @FabianTerhorst

**Comment by FabianTerhorst** [comment]
"And update to the latest commit"

**Comment by michibat01** [comment]
sorry I had'nt seen, i'm trying @FabianTerhorst

**Comment by michibat01** [comment]
Very very thank you, it work @FabianTerhorst
