### ISSUE TITLE
Wild Pokemons

### ISSUE THREAD

**Issue by dtunctuncer** [Grover-c13/PokeGOAPI-Java#56]
I can get neaby gyms and pokestops but there is a issue with wild pokemons do you guys aware of that ?

**Comment by Grover-c13** [comment]
can you expand a bit more.

**Comment by dtunctuncer** [comment]
getMapObjects method returns neaby map objects, There isn't any error with gyms and pokestop I successfuly get them but when it comes to neaby pokemons around given location api return arraylist size zero. I haven't got any pokemon data so far. Sorry for my bad english I hope I explained myself correctly.

ps i have the lastest master relaese

**Comment by shpen** [comment]
Can you show us what your getMapObjects() call looks like?

**Comment by dtunctuncer** [comment]
PokemonGo go = new PokemonGo(auth,http);
            go.setLocation(41.0742066,29.00472,0);
            PlayerProfile profile = go.getPlayerProfile();
            Toast.makeText(this, profile.getUsername(), Toast.LENGTH_SHORT).show();

```
        Map map = go.getMap();
        MapObjects mapObjects = map.getMapObjects();
```

**Comment by shpen** [comment]
Looks fine to me. Try getting map objects at a different location. Maybe there just aren't any pokemon nearby?

**Comment by Grover-c13** [comment]
I just tested and WildPokemon is working in the latest commit. WildPokemon are the actual catachable pokemon, where Nearby Pokemon are all the pokemon in the area.
