### ISSUE TITLE
Feature request: deploy pokemon to gym

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#560]
**Description:**
API call to put a pokemon into the gym

**Steps to reproduce:**
1. Get gym object
2. Call method to deploy pokemon into the gym

**Expected behavior:**
Whenever is possible (gym owned by same team, location available) the pokemon is deployed into the gym as guard

**Actual behavior:**
Currently no method is available to do that from gym object

**Comment by mackenziejgoodwin** [comment]
@aacdevelop 

        StartGymBattleResponseOuterClass.StartGymBattleResponse battleResponse;
        StartGymBattleMessageOuterClass.StartGymBattleMessage.Builder builder = StartGymBattleMessageOuterClass.StartGymBattleMessage.newBuilder();

        for (int i = 0; i < team.length; i++) {
            builder.addAttackingPokemonIds(team[i].getId());
        }


        List<PokemonDataOuterClass.PokemonData> defenders = gym.getDefendingPokemon();
        builder.setGymId(gym.getId());
        builder.setPlayerLongitude(api.getLongitude());
        builder.setPlayerLatitude(api.getLatitude());
        builder.setDefendingPokemonId(defenders.get(0).getId()); // may need to be sorted

        ServerRequest serverRequest = new ServerRequest(
            RequestTypeOuterClass.RequestType.START_GYM_BATTLE, builder.build());
        api.getRequestHandler().sendServerRequests(serverRequest);


        try {
            battleResponse = StartGymBattleResponseOuterClass.StartGymBattleResponse.parseFrom(serverRequest.getData());
        } catch (InvalidProtocolBufferException e) {
            throw new RemoteServerException();
}

**Comment by FabianTerhorst** [comment]
I don´t find the related request inside the protos. Maybe you want to take a look or add a pr to the proto repo?

**Comment by Gegy** [comment]
`Gym#deployPokemon`
