### ISSUE TITLE
gym.getOwnedByTeam() not available?

### ISSUE THREAD

**Issue by 4ndro1d** [Grover-c13/PokeGOAPI-Java#565]
**Description:**
For the project I am doing I need to know which team color the gym is assigned to. But it seems you guys removed the gym.getOwnedByTeam() method?

**Steps to reproduce:**

```
poGo.setLocation(48.3097431, 14.2821328, 0);
List<Gym> gyms = poGo.getMap().getGyms();
gyms.get(0).gym.getOwnedByTeam();
```

**Actual behavior:**
Compiler doesn't recognize the method

**Version:**
0.4.0

**Comment by FabianTerhorst** [comment]
Its inside the library. https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/gym/Gym.java#L70
