### ISSUE TITLE
`FATAL EXCEPTION: main` when Internet connection drops

### ISSUE THREAD

**Issue by ivankoma** [Grover-c13/PokeGOAPI-Java#569]
**Description:**
Sometime my cellular network drops if there is bad coverage and if in that moment `go.setLocation(lat, lon, alt);` is called app will crash.

What is the easiest way to check if connection to Niantic servers still exists (user is still logged)?

**Steps to reproduce:**
1. Connect to PTC
2. `go.setLocation(lat, lon, alt);`
3. Disable Internet
4. `go.setLocation(lat, lon, alt);` and app will crash

**Stacktrace (If it's a crash):**

```
beginning of crash
FATAL EXCEPTION: main
Process: com.example.me.pokemon, PID: 17041           
W/ActivityManager:   Force finishing activity com.example.me.pokemon/.MainActivity
```

**Version:**
0.3.0, Android 6.0

**Comment by FabianTerhorst** [comment]
You have to catch all exceptions with a try catch.

**Comment by ivankoma** [comment]
Yea, that actually did the trick. I though that solution was more complicated.
