### ISSUE TITLE
CATCH_ERROR in every single try

### ISSUE THREAD

**Issue by nacheteam** [Grover-c13/PokeGOAPI-Java#571]
**Description:**
The trouble is that my program has worked nicely for 2 hours, then I stopped it and launched it again. In this new launch the program always gives me catch_error. I'm using this code:

```
  List<CatchablePokemon> catchablePokemon = go.getMap().getCatchablePokemon();

  if(catchablePokemon.size()>0){

    System.out.println("\nPokemon in area:" + catchablePokemon.size());

    for (CatchablePokemon cp : catchablePokemon) {
      // You need to Encounter first.
      EncounterResult encResult = cp.encounterPokemon();
      // if encounter was succesful, catch
      if (encResult.wasSuccessful()) {
        int pokemon_cp = encResult.getPokemonData().getCp();
        System.out.println("Encounted:" + cp.getPokemonId() + " with cp: " + pokemon_cp);
        CatchResult result = cp.catchPokemon(Pokeball.MASTERBALL, 2);
        System.out.println("Attempt to catch:" + cp.getPokemonId() + " " + result.getStatus());
        if(!result.isFailed())
        {
          number_of_pokemons++;
          System.out.println("Numero de pokemons: " + number_of_pokemons);
        }
        //removeBadPokemons();
      }

    }
  }
```

Which is just part of the example code about auto-capture of pokemons but changing the pokeball to masterball and adding 2 as the limit. At first try I wasn't specifing the ball to use when trying to catch the pokemon.

**Steps to reproduce:**

Just use the catching function with masterball and a limit.

**Expected behavior:**
You should be trying to catch the pokemon with 2 masterballs in this case and if it isn't possible try with a pokeball.

**Actual behavior:**
You always obtain catch_error in the encounter.

**Version:**
0.4.0

**Comment by FabianTerhorst** [comment]
Catch error is happening when an item is missing. In your Case the masterball is missing.

**Comment by FabianTerhorst** [comment]
You checked if you have enought normal pokeballs?

**Comment by nacheteam** [comment]
That's exactly what I was going to post right now. When I don't have normal pokeballs this error is displayed but my question now is if I do have masterballs and I have set the limit on 2, why do I get catch error all times? Does it checks if you have normal pokeballs before trying to catch the pokemon with the masterballs?

**Comment by nacheteam** [comment]
Because at least some of the pokemons should have been caught with the masterballs before reaching the limit of 2, right? I tried like 15 pokemons.

**Comment by FabianTerhorst** [comment]
you don´t have masterballs. You got maybe one in the entire game.

**Comment by kyle1128** [comment]
Check ur inventorie b4 catch, drop potions when cnt gt 15, loot pokestop to top up balls

**Comment by kyle1128** [comment]
Use normal ball except encouter low catch possiblity cp like less than 0.25 with normal ball

**Comment by AbandonedCart** [comment]
Or let the user select the ball themselves.
(You could then fall back from that, or simply warn when there are none)

**Comment by nacheteam** [comment]
Nice thank you all!
