### ISSUE TITLE
your account is banned exception

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#572]
after the last commit, i got the infamous "you are banned" exception.

trying from the mobile work (both catch pokemon & fight at gym)
what's happened?

**Comment by FabianTerhorst** [comment]
your account got banned?

**Comment by FabianTerhorst** [comment]
Before this commit you just got nothing back anyway with this Status Code.

**Comment by Grover-c13** [comment]
Status code 3 doubles for invalid request/banned, so if sending some invalid requests you will get this. If you can login and play properly you are not banned

**Comment by AbandonedCart** [comment]
You should only take this message into account when performing an initial login, so long as you are confident your login code is accurate. The best way to handle this would be separating the try/catch block for login or setting some sort of boolean breakpoint for after the login is complete.

**Comment by kyle1128** [comment]
My google ac got banned for more that 24hr. 
I was using 0.3.x i guess
My bot was not doing any tp, it was walking at about 6km/hr with a set of abt 30 coord
Currently, after google auth, it returns a playerProfile obj with null for all fields.

**Comment by ramarro123** [comment]
if i play on the device, the account it's valid and working, wonder what's happeed, probably was already on this 'status' but without the check i haven't noticed it before :)

**Comment by oorakci** [comment]
#577

**Comment by FabianTerhorst** [comment]
#667
