### ISSUE TITLE
Getting Lured Pokemons

### ISSUE THREAD

**Issue by Valerien1** [Grover-c13/PokeGOAPI-Java#573]
Hello!

With the current API is there a way to retrieve lured Pokemon around me?

Thanks!

**Comment by kaiyan910** [comment]
not sure it is correct or not but I can get the lure pokemon

``` java
for (Pokestop pokestop : pokemonGo.getMap().getMapObjects().getPokestops()) {
    if (pokestop.inRange() && pokestop.hasLure()) {
        FortDataOuterClass.FortData data = pokestop.getFortData();
        if (data.hasLureInfo()) {
            CatchablePokemon lurePokemon = new CatchablePokemon(pokemonGo, data);
        }
    }
}
```

**Comment by stirante** [comment]
I think @Valerien1 wants to get pokemons from incense. I don't think there is possibility withing API right now. Incense pokemon are retrieved through special request GetIncensePokemonMessage. Also they need to be encountered with special request IncenseEncounterMessage.
Right now I wrote some kind of code for that but it's not really pretty and not tested enough.
http://pastebin.com/CwKhJhw4

Also encounterPokemon for incense pokemon is different and should look kinda like this:
http://pastebin.com/NsHM0w08

And from what I found catching them is the same as normal pokemon.

And last thing is there is no possibility right now to check if you have active incense/lucky egg/some other effects within API, but in protos you can check AppliedItems.

**Comment by relyks** [comment]
I was trying to do the exact same thing for a pokestop, and my code ended up very similar to @kaiyan910. Does getActivePokemonId() do anything?

``` java
Collection<Pokestop> pokestops = go.getMap().getMapObjects().getPokestops();
                            if (pokestops.size() > 0) {
                                for (Pokestop pokestop : pokestops) {
                                    if (pokestop.inRange() && pokestop.hasLure()) {
                                        System.out.println("Lure on Pokestop: " + pokestop.getDetails().getName());

                                        System.out.println("Time remaining: " + pokestop.getFortData().getLureInfo().getLureExpiresTimestampMs());
                                    }
                                    PokemonId pokemon_id = pokestop.getFortData().getLureInfo().getActivePokemonId();
                                    if (!pokemon_id.equals(PokemonId.MISSINGNO)) {
                                        System.out.println("Lured pokemon: " + GetPokemonName(pokemon_id));
                                    }
                                }
                            }
```

**Comment by FabianTerhorst** [comment]
getActivePokemonId() is inside the pokemon go protos. Its inside the library, because its there as well. https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Map/Fort/FortLureInfo.proto#L9

**Comment by FabianTerhorst** [comment]
Thats the same fortdata class thats used for the gym.

**Comment by FabianTerhorst** [comment]
pokestop getCatchable pokemon would be a possible addition to this. Like @kaiyan910´s code snippet.

**Comment by FabianTerhorst** [comment]
getCatchablePokemonAsync is doing  `for (Pokestop pokestop : mapObjects.getPokestops()) {
                    if (pokestop.inRangeForLuredPokemon() && pokestop.getFortData().hasLureInfo()) {
                        catchablePokemons.add(new CatchablePokemon(api, pokestop.getFortData()));
                    }
                }`
