### ISSUE TITLE
Modifying Existing Request

### ISSUE THREAD

**Issue by rdegelo** [Grover-c13/PokeGOAPI-Java#574]
Hello, first thank you for this wonderful lib.

I'm using this lib in conjunction with Xposed framework to intercept the messages send by the Pokemon Go App to the server.

Everything is working, but after some time the modified requests stops working.
if I don't modify, it works every time. Even if I decode and reencode it.

My guess is that the unknown6 or some encryption stops working after some time.
(Actually I'm not dealing with signing or encryption)
Currently I'm parsing the envelope and modifying the requests using a new builder and then converting to byte array again and redirecting to the network.

Can you guide me on how to resign the Request/Envelope, or if you have any clue of what is going on?
Note that I don't initiate the connection or login with the API. All I have is the requests and envelope.
However I can try to get more info if you want.

Thanks!

**Comment by FabianTerhorst** [comment]
Can you post some code?

**Comment by rdegelo** [comment]
Sure, please check my code below:
param[5] is the buffer that Pokemon GO is sending to the server
param[7] is the buffer size.

```
ByteBuffer buffer = (ByteBuffer)param.args[5];
if(buffer != null) {
    byte[] rawBuf = new byte[buffer.limit()];
    newBuffer.get(rawBuf);

    final RequestEnvelopeOuterClass.RequestEnvelope envelope = RequestEnvelopeOuterClass.RequestEnvelope.parseFrom(rawBuf);
    RequestEnvelopeOuterClass.RequestEnvelope.Builder envelopeBuilder = envelope.toBuilder();

    int i = 0;
    for(RequestOuterClass.Request r : envelope.getRequestsList()) {
        if(r.getRequestType() == RequestTypeOuterClass.RequestType.CATCH_POKEMON) {
            RequestOuterClass.Request.Builder requestBuilder = r.toBuilder();

            CatchPokemonMessageOuterClass.CatchPokemonMessage catchMessage = CatchPokemonMessageOuterClass.CatchPokemonMessage.parseFrom(r.getRequestMessage());

            double recticleSize = test(120, 195);

            CatchPokemonMessageOuterClass.CatchPokemonMessage newMessage = CatchPokemonMessageOuterClass.CatchPokemonMessage.newBuilder(catchMessage)
                                    .setSpinModifier(1)
                                    .setNormalizedHitPosition(1.0)
                                    .setNormalizedReticleSize(catchMessage.getHitPokemon() ? 1.95 + Math.random() * 0.05 : 1.0)
                                    .build();

            requestBuilder.setRequestMessage(newMessage.toByteString());
            envelopeBuilder.setRequests(i, requestBuilder.build());
        }

        i++;
    }

    RequestEnvelopeOuterClass.RequestEnvelope newEnvelope = envelopeBuilder.build();

    param.args[5] = ByteBuffer.wrap(newEnvelope.toByteArray());
    param.args[7] = newEnvelope.getSerializedSize();
}
```

Thx.

**Comment by FabianTerhorst** [comment]
Looks like you don´t sign the request? https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/util/Signature.java#L65

**Comment by rdegelo** [comment]
Yea.. I think this is the problem... 

To sign do I need sensor and device info?
Also current millis can be current system time?
For startTime, can I use any previous date?

Can I extract any of those values from the original envelope (authinfo also)?

Sorry for all of those questions.
Thanks a lot for your support.

**Comment by FabianTerhorst** [comment]
For signing you could use the device and sensor infos. There could protect you from a ban. The sensorinfos are very unknown right now. The deviceinfos can be found in DeviceInfo.DEFAULT. Im not sure whats happening when you provide a wrong timestamp. Normally its the time when you started the app. You should use the infos from the original one. Can you see with xposed the whole sensor infos? Whould be nice if you could see how there looks like.

**Comment by rdegelo** [comment]
It is probably handled by native code, but I`ll try to find something.
The sensorinfo can be extracted from the original envelope

The times are decrypted within the original envelope? Can't find it.

**Comment by rdegelo** [comment]
Also, seems like the gradle version is outdated, I can`t see setSessionHash.

Btw, what sessionHash stands for? and how I can compute this?

**Comment by FabianTerhorst** [comment]
session hash was unknown24.

**Comment by rdegelo** [comment]
I'm trying to sign it.

Gradle version is a little outdated, when will you update the gradle package?
Thxx!

**Comment by FabianTerhorst** [comment]
We are using gradle 2.14.1. 3.0 released a few hours ago.

**Comment by rdegelo** [comment]
Sorry, I meant the PokemonAPI package.

For instance, my version does not have sensorInfo (in signature util class), but development version does.

**Comment by FabianTerhorst** [comment]
you should use the dev branch always.

**Comment by rdegelo** [comment]
Hey Fabian, I'm using the maven package, and its not updated. So do I have to compile manually?

https://bintray.com/grover-c13/maven/PokeGOAPI/_latestVersion is 0.4.0 from Aug 8th

**Comment by FabianTerhorst** [comment]
@rdegelo yes you have to compile manually.

**Comment by rdegelo** [comment]
Hello... By signing the new envelope solved my problem.

The envelope size reduced a little bit, maybe because Im not adding sensor info yet.

Thx!

**Comment by FabianTerhorst** [comment]
The reduce is because of the sensor infos and because of the missing gps infos.
