### ISSUE TITLE
NearbyPokemon and CatchablePokemon not working

### ISSUE THREAD

**Issue by TarunPasumarthi** [Grover-c13/PokeGOAPI-Java#575]
I am always getting 0 when I am doing go.getMap().getCatchablePokemon() or go.getMap().getNearbyPokemon(). however go.getMap().getCatchablePokemons(); is working but its returning a collection of MapPokemons and I don't think there is a way to convert this to catchablePokemon and catch them. I am using the 4.0 version.

**Comment by TarunPasumarthi** [comment]
never mind. i figured it out

**Comment by mackenzieg** [comment]
@TarunPasumarthi what was your solution?

**Comment by TarunPasumarthi** [comment]
So after I do go.getMap().getNearbyPokemon() and get the MapPokemon, I pass that as the second arguemnent for the CatchablePokemon constructor, and that's it (the PokemonGo object being the first). You now have a CatchablePokemon object.

**Comment by TarunPasumarthi** [comment]
Collection<MapPokemon> catchablePokemon = go.getMap().getMapObjects().getCatchablePokemons();
                Set<CatchablePokemon> catchablePokemons = new HashSet<>();
                System.out.println("Pokemon in area:" + catchablePokemon.size());
                for(MapPokemon mp: catchablePokemon){
                    catchablePokemons.add(new CatchablePokemon(go, mp));
                    System.out.println(mp.getPokemonId().name());
                    System.out.println(mp.getLatitude()+","+mp.getLongitude());

```
            }
```
