### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pvanassen** [Grover-c13/PokeGOAPI-Java#576]
Files list GPL license but bintray lists Apache2 license. 
Pick one please.

**Comment by FabianTerhorst** [comment]
Bintray lists gpl-3.0. https://bintray.com/grover-c13/maven/PokeGOAPI/0.4.0

**Comment by pvanassen** [comment]
But the build gradle lists Apache
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/build.gradle#L138

**Comment by FabianTerhorst** [comment]
#578
