### ISSUE TITLE
Packaged API does not contain pokemon_names property file

### ISSUE THREAD

**Issue by meher19** [Grover-c13/PokeGOAPI-Java#583]
When i use jcenter dependecy, this file exists, but when i build myself the API the properties file is not included in the jar file.

I run this command to build the jar : 
`./gradlew build bundle`

**Comment by FabianTerhorst** [comment]
Whats the full name of the generated jar you use?

**Comment by AbandonedCart** [comment]
Judging by https://github.com/Grover-c13/PokeGOAPI-Java/issues/582 and this issue, it is safe to say something is corrupt in your local build. You may want to delete the clone and start fresh, making sure to follow the README carefully not to miss a step.

**Comment by FabianTerhorst** [comment]
Close this for now looks unrelated to this library.

**Comment by meher19** [comment]
The generated jar i used is : PokeGOAPI-0.4.0.jar

**Comment by AbandonedCart** [comment]
You want PokeGOAPI-library-all-0.4.0.jar
If you are using one that is hosted, it sounds like gradle is failing to retrieve it properly.

**Comment by meher19** [comment]
My build can't generate this jar, i followed readme instructions

**Comment by AbandonedCart** [comment]
Use the command `./gradlew :library:build`

**Comment by meher19** [comment]
my local build was corrupted for unknown reason, i deleted it and re-clone the projects now it's working, but i still having the same problem described here : https://github.com/Grover-c13/PokeGOAPI-Java/issues/582
