### ISSUE TITLE
Walking to location

### ISSUE THREAD

**Issue by silkgamers** [Grover-c13/PokeGOAPI-Java#586]
how to simulate a human walk to the coordinates of certain pokestop ?

**Comment by AbandonedCart** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/pull/561

**Comment by mackenzieg** [comment]
@silkgamers @LoungeKatt There are better ways of doing it such as my new implementation here:
[walking](https://github.com/mackenziejgoodwin/PokemonGoBot/blob/master/src/main/java/com/pokemongobot/actions/BotWalker.java#L59)
[running](https://github.com/mackenziejgoodwin/PokemonGoBot/blob/master/src/main/java/com/pokemongobot/actions/BotWalker.java#L95)
Note: walking step distance is usually 1 and running step distance is around 5.

**Comment by AbandonedCart** [comment]
I use a proprietary implementation, as noted on the PR I linked, but thanks.

**Comment by silkgamers** [comment]
thanks.
