### ISSUE TITLE
Need "redirect_uri" set "http://127.0.0.1:8080" for Android web view in GoogleUserCredentialProvider.java

### ISSUE THREAD

**Issue by procks** [Grover-c13/PokeGOAPI-Java#589]
I used Android webview for obtain authcode but I need "redirect_url" set to "http://127.0.0.1:8080". 
[GoogleAuthActivity](https://github.com/procks/PokeTool/blob/master/app/src/main/java/com/omkarmoghe/pokemap/views/GoogleAuthActivity.java#L47)

Now I used modified copy of [GoogleUserCredentialProvider](https://github.com/procks/PokeTool/blob/master/app/src/main/java/com/yuralex/poketool/GoogleUserCredentialProvider.java#L183)

I think it's simpliest way to obtain authcode on Android no need copy/paste...

**Comment by AbandonedCart** [comment]
You don't have to copy and paste. See https://github.com/Grover-c13/PokeGOAPI-Java/commit/4b166d028616f72bbbe4aced2056e7d58fcab80f#commitcomment-18437159

**Comment by procks** [comment]
I already solve copy/paste problem. I'll try this, but I think redirect_url better pass to overloaded constructor GoogleUserCredentialProvider.

**Comment by FabianTerhorst** [comment]
You can add a request interceptor to modify the outgoing request from the http client.
