### ISSUE TITLE
Is there any example for getting items at PokeStop?

### ISSUE THREAD

**Issue by chegola** [Grover-c13/PokeGOAPI-Java#590]
**Description:**
This is not an issue but question, is there any example for getting items at PokeStop?

**Steps to reproduce:**
1. Login supplied
2. Location supplied
3. If PokeStop is detected then get items

**Expected behavior:**
Items at PokeStop should be taken.

**Comment by FabianTerhorst** [comment]
a pokestop from the map objects has a loot method.

**Comment by FabianTerhorst** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/map/fort/Pokestop.java#L171
