### ISSUE TITLE
AsyncPokemonGoException 

### ISSUE THREAD

**Issue by Paul776** [Grover-c13/PokeGOAPI-Java#593]
Hello,

I have updated the lib to the latest version and now instead of the usual exception (LoginFailedException, RemoteServerException etc..) I always receive a AsyncPokemonGoException  that is wrapping the real exception. It is a bit of a pain to use try catch in this situation

**Comment by FabianTerhorst** [comment]
Can you post the full log?

**Comment by Paul776** [comment]
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
W/System.err:     at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:148)
W/System.err:     at xxxxx.MyAsynch.call(MyAsynch:81)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
W/System.err:     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
W/System.err:     at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
W/System.err:   ... 6 more
W/System.err: Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:9861)
W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
 W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:9861)
W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
 W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
W/System.err:     at rx.Observable.subscribe(Observable.java:9957)
W/System.err:     at rx.Observable.subscribe(Observable.java:9924)
 W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
W/System.err:   ... 8 more
W/System.err: Caused by: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
W/System.err:     at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:223)
W/System.err:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
W/System.err:   ... 1 more

**Comment by FabianTerhorst** [comment]
Your account is banned.

**Comment by Paul776** [comment]
Thanks for that... checkout again the issue

**Comment by FabianTerhorst** [comment]
When you use RxJava to catch the error is the same exception still there?

**Comment by Paul776** [comment]
The calling code is as simple as

try {
   pokemonGO.getMap().getCatchablePokemon();
} catch (LoginFailedException e) {
   e.printStackTrace()
} catch (Exception e) {
   e.printStackTrace()
}

In the log I gave you it is an example of ban but as you see it should have been a RemoteServerException not a AsyncPokemonGoException

An other example is when an AutInfo has an expired token and getCatchablePokemon is called I'm expecting a LoginFailedException to be thrown.. but instead it is a AsyncPokemonGoException 

This was not the case couple version before 0.4.0
