### ISSUE TITLE
Pokemon names in pokedex

### ISSUE THREAD

**Issue by francescoprisco** [Grover-c13/PokeGOAPI-Java#605]
When i try to get name of pokemon with this code
`
                GoogleAutoCredentialProvider provider = new GoogleAutoCredentialProvider(httpClient,USERNAME,PASSWORD);
                PokemonGo go= new PokemonGo(provider,httpClient);
                Log.d("num poke",go.getInventories().getPokebank().getPokemons().size()+"");
                List<Pokemon> poke =go.getInventories().getPokebank().getPokemons();
                for(int i =0;i<poke.size();i++)
                {
                  Log.d("nome poke",poke.get(i).getNickname());
                }
`
i get only pokemon name that i have changed i Original app of pokemon go
`08-16 17:38:20.831 13755-17178/it.intellibit.pokeevofree D/num poke: 181
08-16 17:38:20.836 13755-17178/it.intellibit.pokeevofree D/nome poke: Rainer
08-16 17:38:20.836 13755-17178/it.intellibit.pokeevofree D/nome poke: Sparky`

I need all pokemon name

**Comment by FabianTerhorst** [comment]
,poke.get(i).getPokemonName()

**Comment by francescoprisco** [comment]
There isn't this method!

**Comment by FabianTerhorst** [comment]
you also tried pokemon.getPokemonId().getNumber() ?

**Comment by AbandonedCart** [comment]
@opensource93 Don't get too worked up. It means you have to iterate through the pokedex and get each name individually to add to an array.

**Comment by francescoprisco** [comment]
poke.get(i).getPokemonId().name() this is a right method. Thanks all guys

**Comment by FabianTerhorst** [comment]
We coul maybe add a getName method that is returning the the nackname if he exists and when not the enum name.

**Comment by francescoprisco** [comment]
this would be a good thing
