### ISSUE TITLE
Can't perform Google Auth (invalid_grant)

### ISSUE THREAD

**Issue by Litarvan** [Grover-c13/PokeGOAPI-Java#609]
**Description:**
When I use the GoogleUserCredentialProvider (with a WebView on Android) i get a LoginFailedException with message : invalid_grant

(I verified, the good token is provided, but it does the same error even if the token is good or fake, if i type random things it does the same error)

**Steps to reproduce:**
1. Use the GoogleUserCredentialProvider on Android with a WebView with any token (real token or fake token, do the same error.

**Expected behavior:**
Should not throw an exception

**Actual behavior:**
Throw a LoginFailedException

**Stacktrace (If it's a crash):**
Can't provide sorry (can't print stacktrace in AsyncTask on Android). 

com.pokegoapi.exceptions.LoginFailedException: invalid_grant

**Version:**
0.4.0

Thanks for the help !

**Comment by AbandonedCart** [comment]
A new API key was most likely generated for the server.
Although usually that requires an app update, so have you verified the account isn't banned?

**Comment by Litarvan** [comment]
No my account isn't banned :/

**Comment by Animeshm77** [comment]
Same here

**Comment by Litarvan** [comment]
Any news ?

**Comment by vmarchaud** [comment]
@Litarvan Did you tried outside android, if its not working outside niantic must shutdown this auth method ? Btw you can setup a custom oauth redirection to local oauth server on android if i remember good.

**Comment by dustindevgroup** [comment]
@Litarvan , Are you getting something like this #661 ?

**Comment by Litarvan** [comment]
@vmarchaud Yes, it works outside android (wasn't excepting that) but not inside. I never used oauth so i don't really know what to do :/

@dustindevgroup Not really, i'm getting "invalid_grant" and not "invalid_request"

**Comment by Litarvan** [comment]
So this library can't be used with Google accounts on Android ? :'(

**Comment by Litarvan** [comment]
Is this fixed ?

**Comment by s7092910** [comment]
I'm cleaning up a lot of the issues that have been posted because there is going to be a reworking of the library.
