### ISSUE TITLE
New unused accounts error out on PokemonGo instance creation

### ISSUE THREAD

**Issue by mjmjelde** [Grover-c13/PokeGOAPI-Java#610]
**Description:**
I created a new PTC account and before even logging into the app on my phone tried to use the library to login.  This threw an error on creation of a PokemonGo instance.  I believe this is because until you accept the ToS, you can't use all the API calls (more specifically the settings calls).  Am trying to automated the tutorial process but this error causes problems

**Steps to reproduce:**
1. Create a PTC account
2. Create PokemonGo instance with new account

**Expected behavior:**
No errors thrown on PokemonGo instance creation.  Shouldn't do any API calls on instance creation except maybe login calls.

**Actual behavior:**
Error is thrown when Settings.updateSettings() is called from in the new PokemonGo(...) call

**Stacktrace (If it's a crash):**
http://pastebin.com/Jx6x7ufw

**Version:**
0.4.0 built from the Development branch

**Comment by jay8ee** [comment]
I'm seeing this same crash/stacktrace but when using Google credentials which have not been through the new account flow.

**Comment by FabianTerhorst** [comment]
#654

**Comment by FabianTerhorst** [comment]
We have reworked the login flow.
