### ISSUE TITLE
Why pokemon id return negative number? Is that UID?

### ISSUE THREAD

**Issue by vodoi1432** [Grover-c13/PokeGOAPI-Java#611]
**Description:**
pokemon id return a negative number, is that okay?

**Steps to reproduce:**

**Expected behavior:**
pokemon id is a nagative number

**Actual behavior:**
pokemon id is a nagative number
**Stacktrace (If it's a crash):**

**Version:**
0.4.0

**Comment by Grover-c13** [comment]
The pokemon ID is an unsigned long in the protobuf definitions, but java7 and below do not have an unsigned long type, so protobuf converts it to its signed counterpart.
