### ISSUE TITLE
Candy and stardust not update after power up? 

### ISSUE THREAD

**Issue by vodoi1432** [Grover-c13/PokeGOAPI-Java#613]
**Description:**
I relize that candy and stardust are not update after power pokemon. i dont want to login multiple times to update that values, it's slow and not necessary

**Version:**
0.4.0

**Comment by AbandonedCart** [comment]
Is this when using the hosted library or building from the repository?
Edit: Nevermind. It looks like none of the new methods handle it.

**Comment by FabianTerhorst** [comment]
You can force the inventory Update.

**Comment by vodoi1432** [comment]
thanks for your answer!
i just need to call:
go.getInventories().updateInventories();
go.getPlayerProfile().updateProfile();
after power up. But i think it should be automatically :)
