### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

### ISSUE THREAD

**Issue by Paul776** [Grover-c13/PokeGOAPI-Java#615]
Hey guys,

I'm using the API in android and occasionally I see this error in the bug reports (Sorry there is no full stack trace...)

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:233)
at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
at java.lang.Thread.run(Thread.java:818)

It doesn't show the calling method but in my app I only use new PokemonGO(..) and .getMap().getCactahblePokemon()

so it must be one of these two that throw this exception

Hope that this little stack trace can give you an idea

**Comment by AbandonedCart** [comment]
Are you sure it isn't when you iterate through the list? It looks like an attempt to get the second value from an array with only one value.

**Comment by Paul776** [comment]
The code is very simple like this. I'm iterating directly on the CatchablePokemon list

```
 List<CatchablePokemon> catchablePokemons = account.getPokemonGo().getMap().getCatchablePokemon();
          List<Pokemon> pokemons = new ArrayList<>();
          for (CatchablePokemon catchablePokemon : catchablePokemons) {
                 Pokemon pokemon = new Pokemon(); 
                 pokemon.setId(catchablePokemon.get....)
                 [fill the rest of my model]
                pokemons.add(pokemon)
          }
```

So the error must be coming form somewhere inside getCatchablePokemon

Note that a get this error maybe 4 or 5 times a day (on a 7k daily user base)

**Comment by AbandonedCart** [comment]
`List<Pokemon> pokemons = new ArrayList<>();` and `Pokemon pokemons = new Pokemon();` may be conflicting.
