### ISSUE TITLE
GoogleAutoCredentialProvider is no more working

### ISSUE THREAD

**Issue by meher19** [Grover-c13/PokeGOAPI-Java#616]
When i debug my app a problem occurs in the class Gpsoauth.java in this line : 
`return httpClient.newCall(request).execute();`
When i reach this line there is no triggered exception, but there is no response from the call, the debugger never goes to the next line.

**Comment by AbandonedCart** [comment]
Duplicate of existing issue https://github.com/Grover-c13/PokeGOAPI-Java/issues/582
