### ISSUE TITLE
Receiving AsyncPokemonGoException always from the same function call

### ISSUE THREAD

**Issue by nacheteam** [Grover-c13/PokeGOAPI-Java#618]
**Description:**
I have a function that tries to remove all pokemons listed in an ArrayList of pokemon IDs. The function looks like this:

```
public static void removeBadPokemons(PokemonGo go, String user, String password) throws LoginFailedException, RemoteServerException
{
  ArrayList<PokemonIdOuterClass.PokemonId> pokemons_to_remove;
  pokemons_to_remove = PokemonsToRemove.getRemovablePokemons();

  for(PokemonIdOuterClass.PokemonId p : pokemons_to_remove)
  {
    System.out.println("Removing " + p + "\n");
    go = refreshPokemonGo(new OkHttpClient(), user, password);
    transferPokemon(p, go);
  }

}
```

Where refreshPokemonGo is just a desperate try of avoiding the Async exception by creating a new PokemonGo Object and refreshing with it the last PokemonGo object. TransferPokemon looks like this:

```
public static void transferPokemon(PokemonIdOuterClass.PokemonId p, PokemonGo go) throws LoginFailedException, RemoteServerException
  {
    int max_cp=0;
    List<Pokemon> pokemons = go.getInventories().getPokebank().getPokemons();  
    boolean b=false;
    for(Pokemon pok : pokemons)
      if(pok.getPokemonId()==p)
      {
        b=true;
        break;
      }
    if(b)
    {
      for(Pokemon pokemon : pokemons)
      {
        if(pokemon.getPokemonId()==p)
          if(pokemon.getCp()>max_cp)
            max_cp=pokemon.getCp();
      }
      for(Pokemon pokemon : pokemons)
      {
        if(pokemon.getPokemonId()==p)
          if(pokemon.getCp()<max_cp)
          {
            ReleasePokemonResponseOuterClass.ReleasePokemonResponse.Result res = pokemon.transferPokemon();
            System.out.println("Removed: " + pokemon.getPokemonId()+ " cp: " + pokemon.getCp() + " ---> " + res);
          }
      }
    }
  }
```

It just removes the repeated pokemons that have less cp than the maximum one.

This error also appears when calling this function:

```
public static void incubateAndCheckEggs(PokemonGo go, PokemonGoView pkv) throws LoginFailedException, RemoteServerException
{
  List<HatchedEgg> hatched_eggs = go.getInventories().getHatchery().queryHatchedEggs();
  if(hatched_eggs.size()==0)
    System.out.println("There are no hatched eggs.\n");
  else
  {
    for(HatchedEgg e : hatched_eggs)
    {
      System.out.println("Egg hatched: " + e);
      GUI.HatchedEgg hte = new GUI.HatchedEgg(pkv, false);
      hte.setVisible(true);
    }
  }
  List<EggIncubator> incubators = go.getInventories().getIncubators();
  for(EggIncubator incubator : incubators)
  {
    if(!incubator.isInUse())
    {
      Set<EggPokemon> eggs = go.getInventories().getHatchery().getEggs();
      int km=0;
      EggPokemon egg = null;
      for(EggPokemon ep : eggs)
      {
        if(ep.getEggKmWalkedTarget()>km)
          egg=ep;
      }
      UseItemEggIncubatorResponseOuterClass.UseItemEggIncubatorResponse.Result incubate = egg.incubate(incubator);
      HatchingEgg he = new HatchingEgg(pkv, false);
      he.setHatchingInfo(String.valueOf(egg.getEggKmWalked()), String.valueOf(egg.getEggKmWalkedTarget()));
      he.setVisible(true);
      System.out.println("Result of incubation: " + incubate);
    }
  }
}
```

When I call this it always gives me Async error.

**Steps to reproduce:**
1. Just call removeBadPokemons function.
2. Call the checking eggs function.

**Expected behavior:**
Remove succesfully the pokemons.
Check the incubators.

**Actual behavior:**
It crashes.

**Stacktrace (If it's a crash):**

> Exception in thread "main" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
>   at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
>   at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:157)
>   at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:110)
>   at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:86)
>   at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:76)
>   at pokemongobot.PokemonGoFunctions.incubateAndCheckEggs(PokemonGoFunctions.java:427)
>   at pokemongobot.PokemonGoFunctions.catchThemAll(PokemonGoFunctions.java:272)
>   at pokemongobot.PokemonGoBot.main(PokemonGoBot.java:45)
> Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>   at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
>   at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
>   at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
>   at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
>   ... 7 more
> Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>   at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:111)
>   at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:88)
>   at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
>   at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
>   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
>   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
>   at rx.Observable.subscribe(Observable.java:9957)
>   at rx.Observable.subscribe(Observable.java:9924)
>   at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
>   ... 9 more
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>   at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
>   at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:298)
>   at java.lang.Thread.run(Thread.java:745)

**Version:**
0.4.0

**Comment by AbandonedCart** [comment]
That exception often happens when you make a new call before the required delay by the server, or when there is some other server response issue (ie. tutorial incomplete, banned, etc).

**Comment by nacheteam** [comment]
How much time do I need to sleep my calls just not to get this async?

**Comment by FabianTerhorst** [comment]
10 seconds
