### ISSUE TITLE
[Request] Expose EncounterKind in CatchablePokemon to be publicly readable.

### ISSUE THREAD

**Issue by duyngn** [Grover-c13/PokeGOAPI-Java#621]
I just saw encounterKind.... but it's all private to the CatchablePokemon class.  Can we have it be public readable?

**Comment by FabianTerhorst** [comment]
What´s the case when you need this enum?

**Comment by AbandonedCart** [comment]
I believe each encounter is handled differently (ie. DiskEncounter), but they are all tagged as CatchablePokemon. This is meant to replace the need for an isLured property.

**Comment by FabianTerhorst** [comment]
The async method is handling the right catch for the right type.

**Comment by AbandonedCart** [comment]
@duyngn probably isn't using async then. Either way, that is the case where it was needed.

**Comment by FabianTerhorst** [comment]
The async method is the same for synchronous 
https://github.com/Grover-c13/PokeGOAPI-Java/blob/72ca41cdc75e9cb40e85f5b63e800fa5187c495d/library/src/main/java/com/pokegoapi/api/map/pokemon/CatchablePokemon.java#L174

**Comment by AbandonedCart** [comment]
Question: `What´s the case when you need this enum?`
Answer: `This is meant to replace the need for an isLured property.`

**Comment by FabianTerhorst** [comment]
@duyngn Is there a reason to know if this pokemon is a lured pokemon?

**Comment by duyngn** [comment]
Hello and thank you for replying.  I am not trying to encounter the Pokemon or to catch it.  I am trying to distinguish it from regular spawns visually as it generally only has 3 minutes spawn time.(perhaps other clients can take additional action based on this distinction)  It also gives users the "peace of mind" that they aren't "missing" out on certain pokemon.(this is one of the worst fear for users of scanners)

I personally feel that such properties should be exposed for flexibility of categorization by consuming clients -- especially when the object already contains such property.

EDIT:  I am using getMap().getCatchablePokemon() -- which appears to be calling the Async version underneath.

**Comment by FabianTerhorst** [comment]
maybe an isLured():boolen method wouldn´t be that bad.

**Comment by duyngn** [comment]
Just noticed this got added.  Thanks!

EDIT: Just been sitting under a Lured pokestop and it's been working very reliably.
![screenshot_20160822-124214](https://cloud.githubusercontent.com/assets/5741896/17869438/1684f5ca-6868-11e6-9bd9-2161bd4e192d.png)
