### ISSUE TITLE
Pokemon.getMaxCpForPlayer():int returns invalid values

### ISSUE THREAD

**Issue by gionata-bisciari** [Grover-c13/PokeGOAPI-Java#622]
**Description:**
Pokemon.getMaxCpForPlayer():int returns values smaller than current pokemon's cp

**Steps to reproduce:**
1. Pokemon pokemon  = (A pokemon from the Pokebank powered up to maximum cp for current player level (you can see if it is at it's real maximum from official app cp bar));
2. pokemon.getMaxCpForPlayer()
3. pokemon.getCp()

**Expected behavior:**
The result of pokemon.getMaxCpForPlayer() should be greater or equals to pokemon.getCp() result

**Actual behavior:**
The result of pokemon.getMaxCpForPlayer() is less than pokemon.getCp() result
String format of the screen below: "CP:actualCP/maxCPForPlayer"
![622](https://cloud.githubusercontent.com/assets/15786737/17762027/95df9686-650c-11e6-8783-6d580775137a.jpg)

**Version:**
0.4.0

**Comment by FabianTerhorst** [comment]
this is fixed, right?

**Comment by gionata-bisciari** [comment]
If no one fixed it I think no
