### ISSUE TITLE
Update jcenter repository

### ISSUE THREAD

**Issue by pperle** [Grover-c13/PokeGOAPI-Java#626]
**Description:**
jcenter still has version 0.4.0 which is over 9 days old, please update

**Comment by FabianTerhorst** [comment]
@Grover-c13 has the api key to update. He could also publish it to oss sona type for snapshot build.

**Comment by FabianTerhorst** [comment]
We will release 0.4.1 after #650

**Comment by davinkevin** [comment]
Could be good to have it done from travis, which can automatically push tags to jcenter / another maven repository. 

In that case, every tag, everyone could publish pushing a tag. Or even more, you can publish nightlies with an automatic push everyday...

**Comment by AbandonedCart** [comment]
@chuparCh0pper It was more important to have complete features than to worry about the number of days between builds

@davinkevin As you may notice, many "issues" tend to be focused on implementation and supporting individual usage, so providing an ongoing stream of builds will only make it harder to identify and resolve them. It is better to have a formal release when the repository is stable than a large number of iterations that require tracking with hash numbers and could cause multiple reports for known issues.

Regardless, 0.4.1 has been published.
