### ISSUE TITLE
Unable To login using Google Account.

### ISSUE THREAD

**Issue by Animeshm77** [Grover-c13/PokeGOAPI-Java#630]
I am trying to login using google account like this :+1: 
      OkHttpClient httpClient = new OkHttpClient();

```
  GoogleCredentialProvider provider = new GoogleCredentialProvider(httpClient, listnr);
   go = new PokemonGo(provider, httpClient);
```

but nothing is happening no error no warning :(
Here is listener:
[ GoogleCredentialProvider.OnGoogleLoginOAuthCompleteListener listnr = new GoogleCredentialProvider.OnGoogleLoginOAuthCompleteListener() {
        @Override
        public void onInitialOAuthComplete(GoogleAuthJson googleAuthJson) {
            Log.d("Called", "onInitialOauthComplete " + googleAuthJson);
        }

```
    @Override
    public void onTokenIdReceived(GoogleAuthTokenJson googleAuthTokenJson) {
        Log.d("Called", "onTokenIdReceived " + googleAuthTokenJson);
    }
};
```

](url)

**Comment by FabianTerhorst** [comment]
The logcat isn´t related to this.

**Comment by FabianTerhorst** [comment]
you are running this on macos, windows, android, lunux....?

**Comment by Animeshm77** [comment]
@FabianTerhorst  android -jelly bean (API 17)

**Comment by Animeshm77** [comment]
Jelly bean

**Comment by FabianTerhorst** [comment]
android has still an bug that isn´t fixed at the dev branch.

**Comment by FabianTerhorst** [comment]
see #501

**Comment by Animeshm77** [comment]
@FabianTerhorst  Is there any way to login using google account in android ? ....PTC login works fine for me

**Comment by FabianTerhorst** [comment]
GoogleAutoCredentialProvider

**Comment by Animeshm77** [comment]
@FabianTerhorst GoogleAutoCredentialProvider is working fine on all APIs?

**Comment by FabianTerhorst** [comment]
@Animeshm77 i only tested it on api14+

**Comment by Animeshm77** [comment]
ok thanks a lot :)

**Comment by FabianTerhorst** [comment]
but maybe you get an error after the login because #501

**Comment by Animeshm77** [comment]
ok i will try and get back to you :)....please close 
this issue till than :)
