### ISSUE TITLE
Got a unexpected http code : 403 when loggin (account not banned)

### ISSUE THREAD

**Issue by vodoi1432** [Grover-c13/PokeGOAPI-Java#633]
**Description:**
I have a dynamic web project. It's okay if run on my pc with tomcat 7.0. Servlet can login pokemon as ptc, get info and send response to client. But when i  host it on openshift.  it can't login pokemon. 
I always receive a AsyncPokemonGoException: Unknown exception occurred. 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 403

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
http://pastebin.com/JwKExMYV

**Version:**
0.4.0

**Comment by FabianTerhorst** [comment]
Thats unrelated to this library. The niantic server doesn´t accept the connection.

**Comment by vodoi1432** [comment]
do you have any idea for me to make it work :(

**Comment by FabianTerhorst** [comment]
no sorry, i have never used tomcat 7.0.

**Comment by broach** [comment]
You're getting 403's because Niantic has IP blocked Openshift (entirely). 

https://github.com/cyraxx/pogobuf/wiki/Blocked-server-ISPs

**Comment by FabianTerhorst** [comment]
@broach Thanks for answering.
