### ISSUE TITLE
[Help] com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?

### ISSUE THREAD

**Issue by bolds07** [Grover-c13/PokeGOAPI-Java#638]
**Description:**
I've just a simple doubt and i'm sorry for disturbing for it but i couldn't find myself.
Sometimes when my program is running for a long time i get this exception, then i restart the program and everything works fine, what can i do to refresh the token without instantate a new PokemonGo?

i'm using only PtcCredentialProvider but i cant figure how to get authTicket from there.

**Expected behavior:**
a fresh authTicket

**Stacktrace (If it's a crash):**
com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?

**Comment by AbandonedCart** [comment]
I'm not sure that this token actually advertises the expiration time (not at a computer, so that needs verification), but you could either use that or a standard time of 15 minutes to attempt sending a new auth request through the object to obtain a new token.
