### ISSUE TITLE
getCatchablePokemon() and getWildPokemon() unexpected behavior

### ISSUE THREAD

**Issue by xae217** [Grover-c13/PokeGOAPI-Java#646]
**Description:**
When I call getCatchablePokemon() and getWildPokemon() at a certain coordinate, say (40.781549,-73.9650843646)
I get a set of pokemon, which is expected. However, when I make another right after on a point a couple of hundred meters away (40.781549,-73.9638913646) I get the exact same set of pokemon for the second point as well. 
When I only call the second point by itself I get an empty set of pokemon or a different set.
The problem occurs when I call two or more points in succession. 

**Steps to reproduce:**
1. [Step 1] Call getWildPokemon() at point A 
2. [Step 2] Call getWildPokemon() at point B (Note that i get the same set as in point A)
3. [Step 3] Call getWildPokemon() at point B (Get empty set or different pokemon)

**Expected behavior:**
I should be getting a different set of pokemon per point, provided that the points don't over lap.

**Actual behavior:**
I get the same set of pokemon for both points, but different sets if called separetly. 

**Version:**
Version 0.4.0

**Comment by FabianTerhorst** [comment]
the internal cache isn´t cleared after changing the location.

**Comment by FabianTerhorst** [comment]
#652

**Comment by xae217** [comment]
@FabianTerhorst How do I go about clearing the cache? 
Am I supposed to do this each time I use setLocation()?

**Comment by FabianTerhorst** [comment]
The cache is returning the last found Pokémon while waiting the time until next request.

**Comment by FabianTerhorst** [comment]
Can you check if this is a possible fix for your Problem.

**Comment by xae217** [comment]
@FabianTerhorst I don't think I'm following you. 
How do I access the cache?
I am currently creating a new map object every time I change location and then calling getMapObjects() on it. Is this an issue?
