### ISSUE TITLE
setLocation() doesn't count towards getKmWalked() (and not for eggs etc.)

### ISSUE THREAD

**Issue by cybran01** [Grover-c13/PokeGOAPI-Java#649]
**Description:**
When using setLocation() (over reasonably short distances with reasonable intervalls) it does NOT count towards walking distance, therefore is unusable for eggs etc. 
I tried simulating a walk with 4 m/s and 2 m/s both with setLocation() intervalls of 0.5 and 10 seconds.
Even though i "walked" a good amount of approximately a kilometer (multiple times, with different settings), no distance was added. (verified by the api getkmwalked and by using the android vm nox).
Is this a bug? or is there a function i dont know about, like moveplayer() or smth? is setLocation just called by the app at the beginning and the rest is done by that mystical move function or something?
I also called getLatitude and getLongitude to verify that the niantic serves keeps track of my position. (He does pretty well, even with relatively short intervalls.) 
I also used nox to check for a softban, but i can loot pkestops and cath pokemon just fine, so no ban.

**Steps to reproduce:**
1. Use setLocation() to move your player within reasonable speed/time/distance bounds
2. Stare in wonder as your walked distance doesnt change at all.

**Expected behavior:**
The "walked" distance should be added to your actual walked distance.

**Actual behavior:**
Well, it doesn't get added.

I dont know whether this is a bug or just a demonstration of pure stupidity on my side  ;)

**Comment by FabianTerhorst** [comment]
Set Location doesn't execute network requests. getMap getMap objects does.

**Comment by cybran01** [comment]
do you mean getLocation? so the location is only stored locally?

**Comment by FabianTerhorst** [comment]
The Location you setted is only used for the network requests that require a Location.

**Comment by cybran01** [comment]
oh i see :)
where can i get a list of methods that send my location to the serverside?
do only need to scan for pokemon, or do i have to encounter them, for example?

**Comment by FabianTerhorst** [comment]
Scan is using the Location.

**Comment by cybran01** [comment]
is there a command that can be called very frequently and sends my location?
i dont want to crash the niantic servers singlehanded ;)

**Comment by cybran01** [comment]
little update: i rewrote the code so is scans for catchable pokemon once in a while - and it works :))
so thanks a lot.
but one last question: what would be the most lightweigt api call that transmits the location?

**Comment by FabianTerhorst** [comment]
I think you can use the map object to scan for pokemons.

**Comment by cybran01** [comment]
thanks, but is that the most lightweigt option or is there a better one? i already figured that getcatchablepokemon just filters them out from a getmap call, so a changed that. but is there a better way did i already do whats possible to make it easy on the servers?

**Comment by FabianTerhorst** [comment]
You can look into the protos if you find a request for sending the location to the server, but i think the scan is the same as the normal app is doing.

**Comment by cybran01** [comment]
Ok, thanks
I will try that as soon as i am home again (even though there is no other way i would guess if the app sets server location only by getting map objects)
But thanks for your help ;)
