### ISSUE TITLE
How to use code for get pokestop

### ISSUE THREAD

**Issue by hanhmh1203** [Grover-c13/PokeGOAPI-Java#651]
**Description:**
[Short description of the issue observed. If this is a feature request you can modify the template as required.]

**Steps to reproduce:**
1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
[The version of the lib you used]

**Comment by FabianTerhorst** [comment]
api = new PokemonGo();

api.getMap().getMapObjects().getPokestops().

**Comment by hanhmh1203** [comment]
Thanks Pro @FabianTerhorst ,
Can you help me, how to touch on pokestop. ?

**Comment by hanhmh1203** [comment]
any update :)
