### ISSUE TITLE
DeviceInfo, SensorInfo? The user that need to set them?

### ISSUE THREAD

**Issue by Paul776** [Grover-c13/PokeGOAPI-Java#657]
I'm using the code from couple weeks ago (same day DeviceInfo.class was created)

I didn't look through all the code but does the DeviceInfo and SensorInfo are automatically populated by the API when missing?

Or is it to the user to set them manually?

My app has never set them, does this mean it has been sending null to both of them? Thus easy ban flag for niantic?

**Comment by ricechenghk** [comment]
hi, may I know what is the answer as my code is also from couple weeks ago?

**Comment by FabianTerhorst** [comment]
#650 we are working on this.
