### ISSUE TITLE
RemoteServerException

### ISSUE THREAD

**Issue by huzolee** [Grover-c13/PokeGOAPI-Java#666]
Hy!

I always get RemoteServerException when I try to login.

Login steps:
I go to there: com.pokegoapi.auth.GoogleUserCredentialProvider.LOGIN_URL in that way -->

private void redirectToGoogle() {
     getUI().getPage().open(new ExternalResource(GoogleUserCredentialProvider.LOGIN_URL).getURL(), "_blank");
    }
It will show me a window where I have to accept google things and I'm going to get a code.
After that I got the code to paste it a textfield.

private void loginWithGoogle() {
        try {
            final OkHttpClient okHttpClient = new OkHttpClient();
            final GoogleUserCredentialProvider provider = new GoogleUserCredentialProvider(okHttpClient);
            provider.login(authTextField.getValue());
...

AuthTextField contains the code properly what I got from google.
After that the provider.login() method will give me RemoveServerException in this section:

Response response = null;
        try {
            response = client.newCall(request).execute();
        } catch (IOException e) {<--here
            throw new RemoteServerException("Network Request failed to fetch tokenId", e);
        }

The response variable will be null because of the exception what is "Failed to connect to www.googleapis.com/2a00:1450:400d:806:0:0:0:200a:443"

Used version of PokeGoApi: 0.4.0 (lastest version)

I don't know what is the problem with it, but it worked for me earlier.

Thank you in advance for your help.

**Comment by iGio90** [comment]
```
                                Object reqObj = new FormBody.Builder()
                                        .add("code", code)
                                        .add("client_id", GoogleCredentialProvider.CLIENT_ID)
                                        .add("client_secret", GoogleCredentialProvider.SECRET)
                                        .add("redirect_uri", "http://127.0.0.1:9004")
                                        .add("grant_type", "authorization_code");
                                Request req = new Request.Builder()
                                        .url(GoogleCredentialProvider.OAUTH_TOKEN_ENDPOINT)
                                        .method("POST", ((FormBody.Builder) reqObj).build())
                                        .build();
                                Response response = new OkHttpClient().newCall(req).execute();

                                String r = response.body().string();
                                Utils.log(r);

                                Gson gson = new GsonBuilder().setPrettyPrinting().create();
                                JsonElement jelem = gson.fromJson(r, JsonElement.class);
                                JsonObject jobj = jelem.getAsJsonObject();

                                final String refreshToken = jobj.get("refresh_token").getAsString();
                                GoogleCredentialProvider sProvider = new GoogleCredentialProvider(new OkHttpClient(), refreshToken);
                                RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo sAuthInfo = sProvider.getAuthInfo();
```

save the refreshtoken and feed the provider with it later on

**Comment by FabianTerhorst** [comment]
or you can also use  GoogleAutoUserCredentialProvider.

**Comment by huzolee** [comment]
I tried on that way:

private void loginWithGoogle() {
        try {
            final OkHttpClient okHttpClient = new OkHttpClient();
            final GoogleAutoCredentialProvider provider = new GoogleAutoCredentialProvider(okHttpClient, usernameField.getValue(), passwordField.getValue());

and I also got an Exception:
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

Now I'm going to try iGio90's suggest.

**Comment by iGio90** [comment]
Yeah, try mine and close the issue =)

**Comment by FabianTerhorst** [comment]
This error is a missing permission to access certificates.

**Comment by FabianTerhorst** [comment]
Where are you running this code.

**Comment by huzolee** [comment]
It is called when I clicked on loginButton.

private void addListeners() {
        loginButton.addClickListener((final Button.ClickEvent event) -> {
            if (AccountType.google.equals(accountTypeChooser.getValue())) {
                loginWithGoogle();
            } else if (AccountType.ptc.equals(accountTypeChooser.getValue())) {
                loginWithPTC();
            }
        });
...

private void loginWithGoogle() {
        try {
            final OkHttpClient okHttpClient = new OkHttpClient();
            final GoogleAutoCredentialProvider provider = new GoogleAutoCredentialProvider(okHttpClient, usernameField.getValue(), passwordField.getValue());
            final String refreshToken = provider.getTokenId();

            if (refreshToken != null) {//sikeres bejelentkezés
                SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken("username", "password", Lists.newArrayList(new SimpleGrantedAuthority(ROLE_USER.name()))));

                final GoogleUserCredentialProvider googleUserCredentialProvider = new GoogleUserCredentialProvider(okHttpClient, refreshToken);
                final PokemonGo pokemonGo = new PokemonGo(googleUserCredentialProvider, okHttpClient);

                VaadinSession.getCurrent().setAttribute("pokemonGo", pokemonGo);
                getUI().getPage().setLocation(new ExternalResource(APP_URL).getURL());
            }
        } catch (final LoginFailedException | RemoteServerException e) {
            LOGGER.error(Arrays.toString(e.getStackTrace()));
        }
    }

It will call the provider.login(username,password) method where it tries to get the masterToken, but when it tries I got an exception what I mentioned.

private TokenInfo login(String username, String password)
			throws RemoteServerException, LoginFailedException {
		try {
			String masterToken = gpsoauth.performMasterLoginForToken(username, password, GOOGLE_LOGIN_ANDROID_ID);<--here

**Comment by huzolee** [comment]
It is called when I clicked on loginButton.

private void addListeners() {
        loginButton.addClickListener((final Button.ClickEvent event) -> {
            if (AccountType.google.equals(accountTypeChooser.getValue())) {
                loginWithGoogle();
            } else if (AccountType.ptc.equals(accountTypeChooser.getValue())) {
                loginWithPTC();
            }
        });
...

private void loginWithGoogle() {
        try {
            final OkHttpClient okHttpClient = new OkHttpClient();
            final GoogleAutoCredentialProvider provider = new GoogleAutoCredentialProvider(okHttpClient, usernameField.getValue(), passwordField.getValue());
            final String refreshToken = provider.getTokenId();

```
        if (refreshToken != null) {//sikeres bejelentkezés
            SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken("username", "password", Lists.newArrayList(new SimpleGrantedAuthority(ROLE_USER.name()))));
            final PokemonGo pokemonGo = new PokemonGo(provider, okHttpClient);
            VaadinSession.getCurrent().setAttribute("pokemonGo", pokemonGo);
            getUI().getPage().setLocation(new ExternalResource(APP_URL).getURL());
        }
    } catch (final LoginFailedException | RemoteServerException e) {
        LOGGER.error(Arrays.toString(e.getStackTrace()));
    }
}
```

It will call the provider.login(username,password) method where it tries to get the masterToken, but when it tries I got an exception what I mentioned.

private TokenInfo login(String username, String password)
            throws RemoteServerException, LoginFailedException {
        try {
            String masterToken = gpsoauth.performMasterLoginForToken(username, password, GOOGLE_LOGIN_ANDROID_ID);<--here

**Comment by huzolee** [comment]
iGio90 I tried your solution and it gives me the same exception as mine.

**Comment by iGio90** [comment]
can i check your code? do you have it up on a repo?

**Comment by FabianTerhorst** [comment]
you are using android? you have added the internet permission? you are using a different thread?

**Comment by huzolee** [comment]
It runs on tomcat as a webapp.(the container uses jdk1.8)
I have all kind of permission.

Yes, you can, if you give me somehow a bitbucket username. :D

**Comment by FabianTerhorst** [comment]
my bitbucket name is gtz

**Comment by huzolee** [comment]
I shared it.

**Comment by FabianTerhorst** [comment]
your truststore path is incorrect

**Comment by huzolee** [comment]
and how can I change it? where can I find that? :D
Did you run the project?

**Comment by FabianTerhorst** [comment]
i have never created a webapp for a tomcat. Its not related to this library. Its related to the http client.

**Comment by huzolee** [comment]
Thanks for your help.
I'm going to find out how to fix it. :)

**Comment by huzolee** [comment]
Thanks for your help again!

FabianTerhorst I had to change my path to -Djavax.net.ssl.trustStore=/usr/lib/jvm/jdk1.8.0_45/jre/lib/security/cacerts in tomcat VM options. It was misconfigured as you said earlier.
