### ISSUE TITLE
Clear cache ?

### ISSUE THREAD

**Issue by kilicool** [Grover-c13/PokeGOAPI-Java#677]
Hello,

What do we have to call or use when we change location to catch pokemons ?

I did notice that the first time it always work and the next time, even if it's just next to the first zone, it does not work :(

Thx

**Comment by chegola** [comment]
It works ok to me,  you can try by modifing CatchPokemonAtAreaExample by passing locations as parameters and see the result.

**Comment by FabianTerhorst** [comment]
You have still the issue with the latest version?

**Comment by dev111011** [comment]
I have same problem with getCatchablePokemon() version 0.4.0. When I try to scan in a list of locations around current locations, It usually returns empty array for all the next time after first time. I just tried to set delay time between 2 times, but this problem still appear.

**Comment by DaRealGunko** [comment]
Same for me. 
I get all pokemons for all locations I use, When I try it again, i get empty result.
