### ISSUE TITLE
CatchablePokemons isn't working for me.

### ISSUE THREAD

**Issue by Nickforall** [Grover-c13/PokeGOAPI-Java#68]
For some reason the size of CatchablePokemons is 0.

``` java
Collection<MapPokemonOuterClass.MapPokemon> catchablePokemons = this.api.getMap()
                    .getMapObjects(51.86177, 4.526361)
                    .getCatchablePokemons();
```

It worked fine before, but since I updated the API it's always an empty collection.

If I login on my phone, there are pokemon near that coordinate.

**Comment by mjmjelde** [comment]
It is working for me.  Are you sure there is CatchablePokemon around you?  CatchablePokemon are pokemon that are right next to you that you can encounter and catch.  This does not include all pokemon on the map.  You also do not need to specify a location in getMapObjects.  It is recommended that you set it on api.setLocation and call getMapObjects without any parameters

**Comment by Nickforall** [comment]
`api.setLocation(51.86177, 4.526361)`  and then calling getMapObjects works. If a method is not supposed to be used, make it deprecated or private please.

**Comment by guipenedo** [comment]
@Nickforall it's being made deprecated as we _write_

**Comment by vmarchaud** [comment]
They all call the same function, check the code.

**Comment by Nickforall** [comment]
> They all call the same function, check the code.

Explain to me why they don't work then.

**Comment by mjmjelde** [comment]
It doesn't work because of how the changes were made and an assumption that you could just pass any longitude or latitude you wanted without updating the api location as well.  This has been changed and methods depreciated in the #69
