### ISSUE TITLE
unk25

### ISSUE THREAD

**Issue by dgfitz** [Grover-c13/PokeGOAPI-Java#681]
https://www.reddit.com/r/pokemongodev/comments/4zla1f/did_anyone_figure_out_the_specifics_of_the_minor/d6xc8ba

**Comment by Paul776** [comment]
WIP

**Comment by dgfitz** [comment]
<3

**Comment by Grover-c13** [comment]
We do set uknown25?

.setUnknown25(7363665268261373700L);

**Comment by iGio90** [comment]
@Grover-c13 we are setting it since a couple of day. I also asked why we weren't doin it before and no one says a line :D.. it came from my pr of the signature but i checked all the branches and none put it inside

**Comment by iGio90** [comment]
close this, master branch is sending it!

**Comment by eraofchaos** [comment]
unknown25 = xxHash64("sha1 hash", 0x88533787);
sha1 hash is static string(including double qoutes) that exist inside client.
0.33.0 = "b8fa9757195897aae92c53dbcf8a60fb3d86d745"
0.35.0 = "0f15301fe1d0e824738ef5d93355e56a6fb910d4"

.setUnknown25 should be adapted to clientVersion each time...

We need to check minimal "clientVersion" from server to prevent communication with server...

**Comment by iGio90** [comment]
its not the clientVersion. It could be the sha1 hash of the git commit on the niantic library. Since we almost have no way to know this for sure, we will just hardcode the encrypted value on each update
