### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1 at com.pokegoapi.auth.PtcCredentialProvider.login

### ISSUE THREAD

**Issue by Paul776** [Grover-c13/PokeGOAPI-Java#682]
Doing nothing more (in a thread) than:
CredentialProvider credentialProvider = new PtcCredentialProvider(http, account.getUsername(), account.getPassword());

> java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
> at com.pokegoapi.auth.PtcCredentialProvider.login(PtcCredentialProvider.java:205)
> at com.pokegoapi.auth.PtcCredentialProvider.getAuthInfo(PtcCredentialProvider.java:261)
> at com.pokegoapi.api.PokemonGo.getAuthInfo(PokemonGo.java:122)
> at com.pokegoapi.main.RequestHandler.resetBuilder(RequestHandler.java:262)
> at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:173)
> at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
> at java.lang.Thread.run(Thread.java:818)

ANDROID_VERSION 6.0.1
BRAND   samsung

it is not bound to Android version. I see as well 4,5 and 6 having the same issue sometimes happens to getCatchablePokemon call as well.

**Comment by bolds07** [comment]
Man the problem is on your code, there is no array in this class, please use your own IDE to debug it

**Comment by FabianTerhorst** [comment]
#713
