### ISSUE TITLE
NPE when requesting currency player doesn't have

### ISSUE THREAD

**Issue by Gegy** [Grover-c13/PokeGOAPI-Java#690]
**Description:**
If the currencies map in PlayerProfile does not contain an amount for a certain currency, when it is requested via getCurrency a NPE is thrown.

**Stacktrace:**
java.lang.NullPointerException
    at com.pokegoapi.api.player.PlayerProfile.getCurrency(PlayerProfile.java:217)

**Version:**
Development branch of 8/27/16

**Comment by AbandonedCart** [comment]
The line number provided is https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/player/PlayerProfile.java#L217 which is currently unrelated to currency. I am assuming this is no longer an issue. If you find it is, please reopen it with the current error and line number so it can be revisited.

**Comment by Gegy** [comment]
I have not tested this on the latest code base yet, but the line I am referring to now is: https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/player/PlayerProfile.java#L241
