### ISSUE TITLE
How to pass an PokemonGO-Object from one activity to another

### ISSUE THREAD

**Issue by vodoi1432** [Grover-c13/PokeGOAPI-Java#693]
**Description:**
i want to share PokemonGO to another activity to avoid login again. it doesn't implement Parcelable or Serialization
**Version:**
0.4.0

**Comment by iGio90** [comment]
https://developer.android.com/training/basics/firstapp/index.html

**Comment by Paul776** [comment]
@vodoi1432 You shout NOT pass PokemonGO through each activity.

**Comment by iGio90** [comment]
@Paul776 delete it please :D
