### ISSUE TITLE
PokeDictionary.getDisplayName Not working on Android

### ISSUE THREAD

**Issue by Paul776** [Grover-c13/PokeGOAPI-Java#694]
Updated to the latest DEV code, PokeDictionary.getDisplayName(locale, id)  doesn't work (and the deprecated version neither). 

When debugging ResourceBundle getPokeBundle never returns. (it looks it tries to get the bundle and after a while throws a StackOverflow exception)

**Comment by FabianTerhorst** [comment]
What os you use?

**Comment by Paul776** [comment]
Android as in the title

(if you mean the os that built the jar = OSX)

**Comment by FabianTerhorst** [comment]
On Android you could use the String Resources for Translations. The Java bundle can't work on Android

**Comment by Paul776** [comment]
it worked perfectly up to your commit 16/08 (don't know which commit broke it after that)

(Im not using Android string stuff because I'm way to lazy to convert everything into Android res stuff)

**Comment by Paul776** [comment]
This doesn't seem to work on android
return ResourceBundle.getBundle(bundleBaseName, locale, **new ResourceBundle.Control() {
            @Override
            public Locale getFallbackLocale(String baseName, Locale locale) {
                return Locale.ENGLISH;
            }
        });**

removing it makes it work

**Comment by AbandonedCart** [comment]
Android may require the country locale, not the language locale. As per https://developer.android.com/reference/java/util/Locale.html US/UK are for the country, while ENGLISH is for the language.

**Comment by yutamago** [comment]
@Paul776 That's my fault and I'm getting it fixed right now. I can confirm the behaviour you mentioned, I just tested this on my device.

**Comment by yutamago** [comment]
Sorry for the inconvenience. I thought I would be fixing a future issue and instead I created one.
