### ISSUE TITLE
Error while catching pokemons 

### ISSUE THREAD

**Issue by Animeshm77** [Grover-c13/PokeGOAPI-Java#697]
I am getting an error while catching pokemons using this library (NOTE :MY ACCOUNT IS NOT BANNED)

Here is logcat:

08-28 13:17:19.584 27739-28193/com.bot.pokego W/System.err: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
08-28 13:17:19.585 27739-28193/com.bot.pokego W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
08-28 13:17:19.586 27739-28193/com.bot.pokego W/System.err:     at com.pokegoapi.api.map.pokemon.CatchablePokemon.useItem(CatchablePokemon.java:933)
08-28 13:17:19.587 27739-28193/com.bot.pokego W/System.err:     at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:563)
08-28 13:17:19.587 27739-28193/com.bot.pokego W/System.err:     at com.bot.pokego.services.ForeGroundService$5$1.doInBackground(ForeGroundService.java:641)
08-28 13:17:19.588 27739-28193/com.bot.pokego W/System.err:     at com.bot.pokego.services.ForeGroundService$5$1.doInBackground(ForeGroundService.java:611)
08-28 13:17:19.588 27739-28193/com.bot.pokego W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-28 13:17:19.590 27739-28193/com.bot.pokego W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
08-28 13:17:19.590 27739-28193/com.bot.pokego W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
08-28 13:17:19.591 27739-28193/com.bot.pokego W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
08-28 13:17:19.591 27739-28193/com.bot.pokego W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
08-28 13:17:19.591 27739-28193/com.bot.pokego W/System.err:     at java.lang.Thread.run(Thread.java:838)
08-28 13:17:19.591 27739-28193/com.bot.pokego W/System.err: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
08-28 13:17:19.592 27739-28193/com.bot.pokego W/System.err:     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
08-28 13:17:19.592 27739-28193/com.bot.pokego W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
08-28 13:17:19.592 27739-28193/com.bot.pokego W/System.err:     at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
08-28 13:17:19.593 27739-28193/com.bot.pokego W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
08-28 13:17:19.593 27739-28193/com.bot.pokego W/System.err:     ... 10 more
08-28 13:17:19.593 27739-28193/com.bot.pokego W/System.err: Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
08-28 13:17:19.594 27739-28193/com.bot.pokego W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
08-28 13:17:19.594 27739-28193/com.bot.pokego W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
08-28 13:17:19.594 27739-28193/com.bot.pokego W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
08-28 13:17:19.595 27739-28193/com.bot.pokego W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
08-28 13:17:19.595 27739-28193/com.bot.pokego W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:9861)
08-28 13:17:19.595 27739-28193/com.bot.pokego W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
08-28 13:17:19.595 27739-28193/com.bot.pokego W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
08-28 13:17:19.595 27739-28193/com.bot.pokego W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
08-28 13:17:19.596 27739-28193/com.bot.pokego W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
08-28 13:17:19.596 27739-28193/com.bot.pokego W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
08-28 13:17:19.596 27739-28193/com.bot.pokego W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
08-28 13:17:19.596 27739-28193/com.bot.pokego W/System.err:     at rx.Observable.subscribe(Observable.java:9957)
08-28 13:17:19.596 27739-28193/com.bot.pokego W/System.err:     at rx.Observable.subscribe(Observable.java:9924)
08-28 13:17:19.597 27739-28193/com.bot.pokego W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
08-28 13:17:19.597 27739-28193/com.bot.pokego W/System.err:     ... 12 more
08-28 13:17:19.597 27739-28193/com.bot.pokego W/System.err: Caused by: com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
08-28 13:17:19.597 27739-28193/com.bot.pokego W/System.err:     at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:223)
08-28 13:17:19.598 27739-28193/com.bot.pokego W/System.err:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
08-28 13:17:19.598 27739-28193/com.bot.pokego W/System.err:     ... 1 more

**Comment by Gegy** [comment]
How are you catching the Pokemon in-code?

**Comment by Animeshm77** [comment]
Here is the code:

List<CatchablePokemon> catchablePokemon = bot.getMap().getCatchablePokemon();
                        for (CatchablePokemon cpo : catchablePokemon) {
                            // You need to Encounter first.
                            Thread.sleep(25000);
                            EncounterResult encResult = cpo.encounterPokemon();

```
                        // if encounter was succesful, catch
                        if (encResult.wasSuccessful()) {
                            CatchOptions options = new CatchOptions(bot);
                            options.useRazzberries(true);
                            CatchResult result = cpo.catchPokemon(options);
                     //storing details after this ....
```

**Comment by AbandonedCart** [comment]
You are sleeping for 25 seconds after the encounter. It's probably timing out.

**Comment by Animeshm77** [comment]
removed sleep ! still same error.

**Comment by AbandonedCart** [comment]
Going from one extreme to the other will do that. Why not use a realistic delay?

**Comment by Animeshm77** [comment]
realistic delay means ?

**Comment by AbandonedCart** [comment]
[realistic](http://www.dictionary.com/browse/realistic) [delay](http://www.dictionary.com/browse/delay)

**Comment by Animeshm77** [comment]
i mean according to code ....not in terms of english @LoungeKatt

**Comment by AbandonedCart** [comment]
Thread.sleep(REALISTIC_DELAY);

**Comment by Animeshm77** [comment]
-_- can u please help with the issue.... .instead of taunting on me ?

**Comment by AbandonedCart** [comment]
I have provided an answer, but simply refuse to write the program for you. The API provides the methods and the rest is using common sense. The issue appears to be a lack of the latter.
