### ISSUE TITLE
LoginFailedException, RemoteServerException throwed for no reason

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#698]
there are some methods that throw LoginFailedException, RemoteServerException
for no reason, it's that correct?

just to give an example on EggIncubator.java

getKmCurrentlyWalked
getKmLeftToWalk
isInUse

**Comment by AbandonedCart** [comment]
No, there are some methods that can throw an unexpected exception and the cause is not always easily determined.

**Comment by FabianTerhorst** [comment]
we removed getStats() throw. These exceptions are not throwing anymore. #712
