### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by SwipeX** [Grover-c13/PokeGOAPI-Java#71]
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/MessageOrBuilder
at com.pokegoapi.auth.PTCLogin.login(PTCLogin.java:160)
```

**Comment by mjmjelde** [comment]
Using the latest master?  Have you build the gradle project at least once before trying to login?  This error is from protobuf not being build and included at runtime

**Comment by SwipeX** [comment]
To add: this is derived from using the jitpack build via gradle. @mjmfighter

**Comment by Aphoh** [comment]
@SwipeX Is this issue resolved?

**Comment by SwipeX** [comment]
Haven't encountered it lately.

**Comment by Aphoh** [comment]
Closing this issue then.
