### ISSUE TITLE
Your account may be banned exeption

### ISSUE THREAD

**Issue by Tempo95** [Grover-c13/PokeGOAPI-Java#715]
Description:
Hi. I want to clarify this problem with catching pokemon. You say it happens because is not do delay when catch pokemon. Where need do delay. When pokemon was catching? When encounter pokemon? And how much need delay, in order to not to get exeption.  Please answer, I am very concerned about this problem!

Steps to reproduce:
Simply catching pokemon code

Expected behavior:
pokemon catching

Actual behavior:
crash

Stacktrace (If it's a crash):
//piece
com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
//piece

Version:
0.4.0

**Comment by AbandonedCart** [comment]
Please update to the current library (version 0.4.1) to verify this is still an issue.

**Comment by weihung** [comment]
I think this is an issue. I also have exceptions.
com.pokegoapi.exceptions.RemoteServerException: Your account may be banned! please try from the official client.
Version 0.4.1

**Comment by wpgabriel** [comment]
I've had this exception happen to me when I try to catch with a ball I don't have. I switched which ball I used and it worked.

Delaying is a good idea, anyway, because your goal is to mimic human behavior as much as possible.

**Comment by Gegy** [comment]
Does this occur with the latest source? As wpgabriel mentioned, this is most likely caused by using a pokeball that is not in the inventory.
