### ISSUE TITLE
GoogleAutoCredentialProvider - NullPointerException

### ISSUE THREAD

**Issue by gionata-bisciari** [Grover-c13/PokeGOAPI-Java#716]
**Description:**
I can't login, it happens both if I use correct or wrong credentials and banned or not banned accounts.

**Login test used:**

```
import com.pokegoapi.api.PokemonGo;
import com.pokegoapi.auth.GoogleAutoCredentialProvider;
import com.pokegoapi.exceptions.LoginFailedException;
import com.pokegoapi.exceptions.RemoteServerException;

import okhttp3.OkHttpClient;

public class Main {

    public static void main(String[] args) throws LoginFailedException, RemoteServerException {
        OkHttpClient http = new OkHttpClient();
        GoogleAutoCredentialProvider authProvider = new GoogleAutoCredentialProvider(http, "myemail@gmail.com", "mypassword");
        PokemonGo go = new PokemonGo(http);
        go.login(authProvider);
    }
}
```

**Expected behavior:**
With correct credentials and not banned account it should login.

**Actual behavior:**
It throws a NullPointerException at this line:

```
GoogleAutoCredentialProvider authProvider = new GoogleAutoCredentialProvider(http, "mymail@gmail.com", "mypassword");
```

**Stacktrace:**

```
Exception in thread "main" java.lang.NullPointerException
    at svarzee.gps.gpsoauth.GpsoauthConfig.getProperties(GpsoauthConfig.java:19)
    at svarzee.gps.gpsoauth.GpsoauthConfig.<init>(GpsoauthConfig.java:13)
    at svarzee.gps.gpsoauth.Gpsoauth.<init>(Gpsoauth.java:18)
    at svarzee.gps.gpsoauth.Gpsoauth.<init>(Gpsoauth.java:24)
    at com.pokegoapi.auth.GoogleAutoCredentialProvider.<init>(GoogleAutoCredentialProvider.java:47)
    at Main.main(Main.java:12)
```

**Version:**
0.4.1

**P.S.:**
All parameters that I pass are not null:
- http is not null;
- username is not null;
- password is not null.

**Comment by FabianTerhorst** [comment]
Maybe the login was incorrect.

**Comment by gionata-bisciari** [comment]
What do you mean exactly with incorrect login?

**Comment by FabianTerhorst** [comment]
when email or password are wrong.

**Comment by gionata-bisciari** [comment]
But I wrote that it appens when I use correct credentials.

**Comment by FabianTerhorst** [comment]
I can´t reproduce the error and im always using this provider.

**Comment by FabianTerhorst** [comment]
This error is happening if he can´t access his config file. Maybe you don´t have file read write permissions?

**Comment by FabianTerhorst** [comment]
What os are you using?

**Comment by iGio90** [comment]
```
try (final InputStream stream = this.getClass().getClassLoader().getResourceAsStream("gpsoauth.properties")) {
```

this is the stack. Make sure you have gpsoauth.properties

**Comment by gionata-bisciari** [comment]
I'm on Windows 10 but I could login before changes to PokemonGo contructor

**Comment by FabianTerhorst** [comment]
@gionata-bisciari That doesn´t make sense.

**Comment by FabianTerhorst** [comment]
try it on a different system.

**Comment by gionata-bisciari** [comment]
ok, I'll try on ubuntu

**Comment by gionata-bisciari** [comment]
I tried on two other systems.
**Ubuntu:**
- It works fine.

**An other Windows 10:**
- It prints:

```
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
```

then it works.
(Yes it prints that 4 times I don't know why, same code and same jar library for all systems).

**Comment by FabianTerhorst** [comment]
and on macos?

**Comment by gionata-bisciari** [comment]
I can't try, I haven't got a mac.

**Comment by FabianTerhorst** [comment]
and on android?

**Comment by nguyenkhanh87** [comment]
I am new with Android & Java, trying to build something but failed on the first start.
I only try to login by ptc first. 

> public class PokeMonList extends AsyncTask<Void,Void,Boolean> {
>         private String userName;
>         private String passWord;
>         private String provider;
>         private String accessToken;
>         PokeMonList(String uName,String pWord,String aProvider,String aToken) {
>             userName = uName;
>             passWord = pWord;
>             provider = aProvider;
>             accessToken = aToken;
>         }
>         @Override
>         protected Boolean doInBackground(Void... params) {
>             OkHttpClient httpClient = new OkHttpClient();
>             PokemonGo go = new PokemonGo(httpClient);
>             try {
>                 go.login(new PtcCredentialProvider(httpClient, userName, passWord));
>                 System.out.println(go);
>             } catch (LoginFailedException | RemoteServerException e ) {
>                 e.printStackTrace();
>             }
>             return true;
>         }
>     }

Tried to run AsyncTask

> public PokeMonList pogo;
> pogo = new PokeMonList(ptcUsername,ptcPassword,provider,accessToken);
> pogo.execute();

Error I got

> FATAL EXCEPTION: Async HTTP Thread
>                  java.lang.NullPointerException: Attempt to invoke virtual method 'POGOProtos.Networking.Envelopes.SignatureOuterClass$Signature$ActivityStatus com.pokegoapi.api.device.ActivityStatus.getActivityStatus()' on a null object reference
>                                                                               at com.pokegoapi.api.PokemonGo.getActivitySignature(PokemonGo.java:353)
>                                                                               at com.pokegoapi.util.Signature.setSignature(Signature.java:57)
>                                                                               at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:179)
>                                                                               at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
>                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by AbandonedCart** [comment]
@nguyenkhanh87 that is a completely different issue that is explained / resolved in https://github.com/Grover-c13/PokeGOAPI-Java/issues/723

**Comment by nguyenkhanh87** [comment]
@LoungeKatt thank you very much.
