### ISSUE TITLE
Profile not updating?

### ISSUE THREAD

**Issue by bbb0x** [Grover-c13/PokeGOAPI-Java#727]
I created a simple test bot; placed him between 2 pokestops and all he does is checking every min if he can loot them, if yes it uses them.

I print the player XP before and after the loot and it always shows the same.
Only restarting gets me the new value.

Here the 2 functions I call before and after (updateplayer is called first) the loot:

```
    private void UpdatePlayer() throws RemoteServerException, LoginFailedException
    {
        if(profile == null){
        profile = go.getPlayerProfile();
        stats = profile.getStats();
        }
        else
        profile.updateProfile();
    }

    private void PrintStats()
    {

        int level = stats.getLevel();
        long experience = stats.getExperience();
        long toNext = stats.getNextLevelXp();


        MCLog.Log("Player level: "+level);
        MCLog.Log("XP: "+experience);
        MCLog.Log("To next Level: "+toNext);
    }

```

Both times, XP prints the same value. NextLevelXP too but I assume the meaning of that function is that it shows the entire XP a level needs, so it's fine.

**Comment by FabianTerhorst** [comment]
you have to call api.getPlayerProfile().updateProfile()

**Comment by FabianTerhorst** [comment]
When updateProfile doesn´t work this would be strange.

**Comment by bbb0x** [comment]
I tested 2 things but both didn't work:

```

        go.getPlayerProfile().updateProfile();
        profile = go.getPlayerProfile();
        stats = profile.getStats();

```

and

```
        profile = go.getPlayerProfile();
        profile.updateProfile();
        stats = profile.getStats();
```

Not sure, I'm more a C# guy so I'm new on Java anyway. Are these functions maybe maybe async that it jumps to my PrintStats before the update is finished?

**Comment by bbb0x** [comment]
Being busy with the issue for the last couple of hours and the solution was very weird.

```
`go.getInventories().updateInventories();`
```

This line fixed it, but shouldn't it be PlayerProfile and not Inventories that updates the stats? Updating the inventories in my update isn't wrong; but I wasn't at that point in my development yet to manage the inventories.

**Comment by FabianTerhorst** [comment]
The stats are inside the inventory api response. Thats the reason for this.
