### ISSUE TITLE
Request and Location Hashes Calculation

### ISSUE THREAD

**Issue by marceloueda** [Grover-c13/PokeGOAPI-Java#731]
Requests and location hashes are using 0x1B845238 as initial value: https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/util/Signature.java#L127

According to https://talk.pogodev.org/d/33-v0-35-new-initial-request/3 the correct value is 0x61656632 since 0.33.0. Tested against requests collected from 1.5.0 (iOS) and it seems accurate.

**Comment by Gegy** [comment]
Signature calculations have all changed now.
