### ISSUE TITLE
Wrong response from PokeGOApi?

### ISSUE THREAD

**Issue by SvnGpsk** [Grover-c13/PokeGOAPI-Java#738]
Hi,
After logging in with PTC (which seems to work), I tried to get some account info but Im getting wrong results.
My code:
-main class:

```

import com.pokegoapi.api.PokemonGo;

public class Pokemon {
    public static void main(String[] args) {
        LoginHandler loginHandler = new LoginHandler();
        PokemonGo go = loginHandler.login();

        double longitude = 50.108923;
        double latitude = 8.681821;
        double alt = 70;

        go.getPlayerProfile(); 
        go.setLocation(latitude, longitude, alt); 
        System.out.println(go.getPlayerProfile().getStats().getExperience());
    }
}
```

LoginHandler class:

```
import com.pokegoapi.api.PokemonGo;
import com.pokegoapi.auth.PtcCredentialProvider;
import com.pokegoapi.exceptions.LoginFailedException;
import com.pokegoapi.exceptions.RemoteServerException;
import okhttp3.OkHttpClient;

public class LoginHandler {
    public PokemonGo login() {

        OkHttpClient httpClient = new OkHttpClient();

        PokemonGo go = new PokemonGo(httpClient);
        try {
            go.login(new PtcCredentialProvider(httpClient, LoginCredentials.LOGIN ,LoginCredentials.PASSWORD ));
        } catch (LoginFailedException e1) {
            e1.printStackTrace();
        } catch (RemoteServerException e1) {
            e1.printStackTrace();
        }
        return go;
    }
}
```

Output is: 

> D/RequestHandler: Authenticated with static token
> 0

But should be the amount of experience, which isn't 0 in reality...

Is this a bug or am I using the API wrong?

**Version:**
0.4.1

**Comment by FabianTerhorst** [comment]
and when you call api.getInventories().updateInventories() before

**Comment by SvnGpsk** [comment]
That works! Thank you very much. Is there a documentary on what you need to call to use specific methods? because I'm not sure how I could have known that I need to call updateInventories() before I can use getExperience().

**Comment by FabianTerhorst** [comment]
That the update comes automatically is fixed with the latest commit. But when you catch a pokemon for example you have to call it. Its not documented right now.

**Comment by SvnGpsk** [comment]
Oh, okay. Thanks for the help again :)
