### ISSUE TITLE
Map#getMapObjectsAsync uses cache incorrectly

### ISSUE THREAD

**Issue by Gegy** [Grover-c13/PokeGOAPI-Java#739]
When Map#getMapObjectsAsync checks whether it should use the cache or not, it checks if cachedCatchable has any entries instead of checking if cachedMapObjects has any entries.

https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/api/map/Map.java#L335

**Comment by FabianTerhorst** [comment]
@LoungeKatt please fix your issue.

**Comment by FabianTerhorst** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/commit/910078b8e09528b38bae65e17b4304f0be7e54ed#diff-e356103bee63c77e4131618df05d6ff0R335

**Comment by gdespres** [comment]
Why verify cachedCatchable size ? PR #743 fix the issue.

**Comment by AbandonedCart** [comment]
@FabianTerhorst you verified and approved the code (via slack), claiming to understand it at the time. 

The explanation was provided at https://github.com/Grover-c13/PokeGOAPI-Java/pull/695/commits/910078b8e09528b38bae65e17b4304f0be7e54ed

On a side note, it is always good for people to look at a commit when it includes code that seems "misplaced" to verify there isn't some sort of explanation for it. This one included a note that allows following the code back to where the objects are filled to find that the object in question is a part of it.

**Comment by LoungeKatt** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/pull/695/commits/910078b8e09528b38bae65e17b4304f0be7e54ed
