### ISSUE TITLE
anybody give me a hand plaese..

### ISSUE THREAD

**Issue by n3wdev** [Grover-c13/PokeGOAPI-Java#741]
I can login to PokemonGO without asynctask in Eclipse
But in Android Studio i did it in asynctask but my app alway crash
can someone give me an example code to login with Android Studio please.. Thank you

**Comment by FabianTerhorst** [comment]
provide stacktrace please

**Comment by HEISEN3E2G** [comment]
this is my simple code to test but not work like i said

`public class MainActivity extends AppCompatActivity {
    OkHttpClient httpClient = new OkHttpClient();
    PokemonGo go = new PokemonGo(httpClient);
    PlayerProfile profile;
    TextView text1;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        text1=(TextView)findViewById(R.id.text1);
        new login().execute();
    
    }

    private class login extends AsyncTask<Void, Integer, String>  {
        protected void onPreExecute()  {

        }

        protected String doInBackground(Void... params)    {
            try {
                go.login(new PtcCredentialProvider(httpClient, "tsitpogo", "tsitpogo"));
                profile = go.getPlayerProfile();
            } catch (LoginFailedException e) {
                e.printStackTrace();
            } catch (RemoteServerException e) {
                e.printStackTrace();
            }
            String lv = profile.getPlayerData().getUsername();
            return lv+params;
        }


        protected void onPostExecute(String result)  {
            Toast.makeText(MainActivity.this,result,Toast.LENGTH_LONG).show();
        }
    }`

**Comment by n3wdev** [comment]
this is my simple code to test, but it's not work like i said.
what i missed?

`public class MainActivity extends AppCompatActivity {
    OkHttpClient httpClient = new OkHttpClient();
    PokemonGo go = new PokemonGo(httpClient);
    PlayerProfile profile;
    TextView text1;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        text1=(TextView)findViewById(R.id.text1);
        new login().execute();

```
}

private class login extends AsyncTask<Void, Integer, String>  {
    protected void onPreExecute()  {

    }

    protected String doInBackground(Void... params)    {
        try {
            go.login(new PtcCredentialProvider(httpClient, "tsitpogo", "tsitpogo"));
            profile = go.getPlayerProfile();
        } catch (LoginFailedException e) {
            e.printStackTrace();
        } catch (RemoteServerException e) {
            e.printStackTrace();
        }
        String user = profile.getPlayerData().getUsername();
        return user;
    }


    protected void onPostExecute(String result)  {
        Toast.makeText(MainActivity.this,result,Toast.LENGTH_LONG).show();
    }
}`
```

**Comment by Gegy** [comment]
Nobody can help you with out the stack trace.

**Comment by n3wdev** [comment]
these isn't error or exception, app just crash
![image](https://cloud.githubusercontent.com/assets/13644958/18193385/0f9ea8f8-7107-11e6-8666-5d0a69f9d514.png)
