### ISSUE TITLE
Errors using the API

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#745]
Hey, so I recently downloaded version 0.4.1 and added it as an external jar. I put the example code into my class, and i'm getting errors on:
- OkHttpClient
- PtcCredentialProvider
- InvalidProtocolBufferException
  and I think the root of the problem:

The type com.google.protobuf.CodedInputStream cannot be resolved. It is indirectly referenced from required .class files

Which is an error just at the top of my class, on the "p" for package line.

I'm pretty sure it's something with my build path or what i'm coding with, but i've downloaded everything it said to download.

I've simply download version 0.4.1 and added it as an external jar to my Java Project in Eclipse. Thanks!

**Comment by broach** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java#how-to-import

You've downloaded only the code for PokeGOAPI and do not have any of the dependencies. I would highly suggest using gradle or maven for your project to do the dependency management for you. If you don't want to do that, you either need to download and import all the dependencies manually, or clone the git repo and build the `PokeGOAPI-library-all-0.4.1.jar` which will include all the dependencies - you can then just import that single jar in your project.
