### ISSUE TITLE
getMapObjects returns 0 objects the majority of the time

### ISSUE THREAD

**Issue by Gegy** [Grover-c13/PokeGOAPI-Java#746]
getMapObjects returns 0 objects the majority of the time. I suspect this is partially related to #739, but this also occurs with getCatchablePokemon so there is most likely something else causing this.

**Comment by gdespres** [comment]
It's possible you don't wait 10 seconds (minimal time) between 2 calls ?

**Comment by Gegy** [comment]
I am waiting 10 seconds in-between the two calls.

**Comment by iGio90** [comment]
@pvanassen and @Paul776 should have the solution for this! They may suggest you that the blocking calls are not embedding the requests in the same envelope, instead, they are firing one by one all the requests with a new envelope (so, even when not needed, the library is signing all the requests and sending a new envelope every time). It may works, or return invalid calls.. but for sure your account will be banned in 2 days. #kappa

**Comment by iGio90** [comment]
if you want a solution for returning a valid getMapObject, just comment the login method in PokemonGo constructor. You will still face a ban within 2/3 days :)

**Comment by mjmjelde** [comment]
I might have uncovered the error earlier today for this when debugging my api.  The location hashes are wrong in the signature currently.  It should be using the accuracy and not altitude in the location hashs @iGio90

**Comment by pvanassen** [comment]
@iGio90 Why do you think I have a solution? I don't know if the signatures have been updated on this API already but this should be a trivial update.

**Comment by broach** [comment]
There's absolutely nothing wrong with getting map objects in the current Development branch. I updated to it this morning and it's working just fine.

**Comment by mjmjelde** [comment]
there is still a problem, but it is with the signature.  The following lines in Signature.java need to be updated to use accuracy and not altitude:

https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/util/Signature.java#L117
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/library/src/main/java/com/pokegoapi/util/Signature.java#L104

This is the problem I was having in my code.  Once changed, it all started working again.

**Comment by Gegy** [comment]
Just tested this, looks like fixing #739 fixes this issue.
