### ISSUE TITLE
getMapObjects

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#748]
**Description:**
When the getMapObjects, is greater than or equal to 8, the following message appears:

Caused by:. pokegoapi. exceptions. RemoteServerException: Your account may be banned. Please try from the official client.

**Example**

final int range = go.getMap().getMapObjects(8).getPokestops().size();

**Version:**
0.4.1

**Comment by Kurimatzu** [comment]
Up

**Comment by Gegy** [comment]
I'd imagine this isn't a problem with this API, but a limitation that Niantic has put in place.

**Comment by Gegy** [comment]
The API now handles `get_map_objects` requests
