### ISSUE TITLE
hatchEgg returns ERROR_POKEMON_ID_NOT_EGG

### ISSUE THREAD

**Issue by Gegy** [Grover-c13/PokeGOAPI-Java#756]
**Description:**
When using EggIncubator#hatchEgg on an egg being incubated, it returns ERROR_POKEMON_ID_NOT_EGG, although it was definitely an egg being hatched.

**Steps to reproduce:**
1. Incubate an egg
2. Move around until it is ready to hatch
3. Call EggIncubator#hatchEgg with the egg being hatched

**Expected behavior:**
I expected hatchEgg to return SUCCESS

**Actual behavior:**
hatchEgg returned ERROR_POKEMON_ID_NOT_EGG

**Version:**
0.4.1

**Comment by Gegy** [comment]
Testing a bit more, the Pokemon from the egg was received, it just returns the wrong result. Is there a way to get the Pokemon hatched from an egg?

**Comment by Gegy** [comment]
I think hatchEgg is just named / documented incorrectly, I see it is called from EggPokemon#incubate, so it looks like hatchEgg should also be renamed to incubate.

**Comment by Gegy** [comment]
I tried using Hatchery#queryHatchedEggs, but it returns 0 eggs even when an egg has hatched.

**Comment by wpgabriel** [comment]
Do you have some sample code? I'm able to hatch an egg just fine, but I can't seem to load a new one in. Here's my sample hatch code that seems to work.

```
Hatchery h = new Hatchery(L.go); //L.go is the api
Inventories inv = null;
try {
    inv = L.go.getInventories();
} catch (LoginFailedException | RemoteServerException e2) {
    e2.printStackTrace();
}

try {
    List<HatchedEgg> eggs = h.queryHatchedEggs();
    if(eggs != null && !eggs.isEmpty()){
        inv.updateInventories();
        for(HatchedEgg he : eggs){
            System.out.println("Hatched " + inv.getPokebank().getPokemonById(he.getId()).getPokemonId().name() + " | candy = " + he.getCandy() + " | stardust = " + he.getStardust());
        }
    }
} catch (RemoteServerException | LoginFailedException e1) {
    e1.printStackTrace();
}
```

**Comment by Gegy** [comment]
Does something need to be sent to request an egg hatch?

EDIT: Looks like incubator.hatchEgg needs to be called again to hatch the egg, but I'm still not getting any results from queryHatchedEggs.
