### ISSUE TITLE
getCatchablePokemon() Bug

### ISSUE THREAD

**Issue by paidaki** [Grover-c13/PokeGOAPI-Java#757]
**Description:**
If getCatchablePokemon() found 0 pokemon nearby, then cachedCatchable.size == 0, so any further calls to get MapObjects ( e.g. map.getGyms() ) will skip cache and will try to request new copy of MapObjects from the server, but the response will be empty because of the time limit (10s), which in turn will overwrite the "good" MapObjects.

**Steps to reproduce:**
account.go.setLocation(lat, lng, 1);  // Location without pokemon but with gyms or pokestops nearby
Map map = account.go.getMap();

map.getCatchablePokemon();
map.getGyms();
map.getMapObjects().getPokestops()

**Expected behavior:**
# cachablePokemon == 0
# gyms > 0
# pokestops > 0

**Actual behavior:**
# cachablePokemon == 0
# gyms == 0
# pokestops == 0

**Version:**
Commit 6333f96

**Comment by Gegy** [comment]
I think this is the same as #739
