### ISSUE TITLE
how to refresh token

### ISSUE THREAD

**Issue by Tempo95** [Grover-c13/PokeGOAPI-Java#760]
**Description:**
How to refresh token??

**Steps to reproduce:**
When try get data from server

**Expected behavior:**
Crash

**Actual behavior:**
Crash

**Stacktrace (If it's a crash):**
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?  

**Version:**
0.4.1 last

**Comment by yutamago** [comment]
When does it crash, immediately after login or after a while?
Can you login with the same refresh token after the crash?
Are you banned?

**Comment by Tempo95** [comment]
When i login, after 20 min my activity. I am not banned

**Comment by Tempo95** [comment]
I was wondering how do refresh token or clear token when i disconect. I have two options: 1) Refresh token when i login without disconect every 20 min or 2) Diconnect game and clear token with session and login again
