### ISSUE TITLE
How to get connection result ?

### ISSUE THREAD

**Issue by swapps** [Grover-c13/PokeGOAPI-Java#762]
Hi,

i'm using this to connect:

PokemonGo go = new PokemonGo(httpClient);
go.login(new PtcCredentialProvider(httpClient, username, password));

how can i know if the connection has been succesfull ?

is there any callback method ?

**Comment by broach** [comment]
If it doesn't throw an exception, it succeeded.

**Comment by swapps** [comment]
thanks
