### ISSUE TITLE
How to get Gym details using it's id

### ISSUE THREAD

**Issue by swapps** [Grover-c13/PokeGOAPI-Java#763]
Is it possible to get the current Gym information if i have his id ?

i have tried with 

FortDetails fort = MyApp.go.getMap().getFortDetails(id,lat,longi);

but i'm getting : 

com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred.

**Comment by wpgabriel** [comment]
I'm not sure about your direct question, but if you have the lat/long, then setLocation() and get the list of gyms within range of that location. It's not as efficient as getting what you want directly, but there shouldn't be so many gyms in a location that it becomes problematic.

```
double elevation = 500;
go.setLocation(lat, longi, elevation);
List<Gym> gyms = go.getMap().getGyms();
for(Gym gym : gyms){
    if(gym.getId().equals(id)){
        //Do what you want with the gym here
    }
}
```

**Comment by Gegy** [comment]
`Map.getMapObjects().getGym(id)` is now a thing
