### ISSUE TITLE
How to download Gym or Pokestop picture ?

### ISSUE THREAD

**Issue by swapps** [Grover-c13/PokeGOAPI-Java#764]
How is it possible to download Gym or Pokestop picture ?

Thanks

**Comment by BurakDev** [comment]
![image](https://cloud.githubusercontent.com/assets/3963184/18326684/51bb80d2-7547-11e6-8472-46c001cb0b41.png)

![image](https://cloud.githubusercontent.com/assets/3963184/18326697/62a30aa0-7547-11e6-8d97-75c3a9975dc5.png)

Pokestop and Gym icon !
