### ISSUE TITLE
freezes when recconect the game

### ISSUE THREAD

**Issue by Tempo95** [Grover-c13/PokeGOAPI-Java#765]
**Description:**
When i try recconect app freezes in create provider. On version 0.4.0 there is no such

**Steps to reproduce:**
1. disconect with this code:
   clietn - //PokemonGo api
   public void disconnect() {
         try {
             AuthInfo.Builder builder = client.getAuthInfo().toBuilder();
             builder.clearToken();
             builder.clearProvider();
             builder.clear();
         } catch (Exception e) {
             error(e);
         }
   
   client = null;
   }
2. Wait 5 minutes and connect with simply code

**Version:**
0.4.1

**Comment by R0g3r10LL31t3** [comment]
Hi,

I see this problem too.
Version: 0.41 (Last updated at 18/09)
Test: Connect, maintain updating loop 30s at 45s, calling getMapObjects and playerProfileUpdate(true);
Bug: After some hours, the STATUS 102 code is returning from N14nt1c S3rv3rs (replace letters).

LOG:

2016/09/18 11:58:36.393 DEBUG REQUEST [@Pokegoapi]
                              [m]st_id: 9000949199830486267
requests {
  request_type: GET_PLAYER
  request_message: "\n\b\n\002US\022\002en"
}
requests {
  request_type: CHECK_CHALLENGE
}
unknown6 {
  request_type: 6
  unknown2 {
    encrypted_signature: "O\216\362\365\255\004\020h\360_\270\210X\246p\354{\212\314\375\322\203\tz\360\275\310\313\277\334g\340~\002\275\363?\210\002\361\300\203\232#\357P(\313\365\361\241\371\335\364\275\001\335\231O\333a\023\261\3200\213{\314\241r\211L\300\372\247>??\267\022\217\353\S\304\3111\344?\366\216\265\365\336\0321\251\2570\350\377\372r\032\362\366\023\206bD\367 \3406\317\027\271\037.\347%\006\177\372\231\311\343\347\005\274C\266e\362>\207\260\361\3279\372Y\n\232m\327\0313m\a\320\v\253\370\271\256\254\307^\331H\341\364\231\022\234\375\212\f7A\316\260\313\263\242T\030\334RKE\351S\260\215x\315\3460\300B\331g\\257!\203\024eR\225\316k\272O`\3106\375\240~EvI\004\'\267&\263\323K\252\a\212\032\332\225q\3630u\340\317(\201\032\266\253+\354F\304cp\002W)\"\224\v\357qh\314{\223\210Z]\303A\276&\341g\276RP\005W&z\364S\316\r\270:\271\345\307\262\032\253\244)=\211 \311\016x]\345o`D\256\341\231i@\362\323\256\002 \033M\237\016\334\316I\202Wg5q\212\033\350\324\302\034\002,\263~S\250a\310\312\267\364\364,\024\344>\241\307\034_\341\254\216\336=\344\344m=\260\303\035\372\307\251\363\n\301\223\027se\224\v)\266\363\3529\345\344\237i\226]\331psQ\t\247CU\367\374N\355\2012b\236c\000\226\276V\232\313\327\031\231$\370\003nwUL\222\245>\252ii\226j\255\255^I\034B\272\022\253\277\342\314\277\237_o[\337MDuGG;\2473h\316\363\303\033\3672\211\261\307\277d\271\257\275 ?\345S\314\177\237\352z\363Om\246\000\n~cz1\314+\275\243\350\213\250]n\374!\225\036\3052\227\304km_\204\023L_\275\305r7\022\000\2177\bY\036\340\310\017\314b\322\331!V\206$m\314\020B\252+\251\3170|e\2475\275w\255"
  }
}
latitude: -22.96658813950045
longitude: -43.21973872952563
altitude: 685.0
auth_info {
  provider: "ptc"
  token {
    contents: "TGT-20822004-9eARzPpQ6AeMMbkKrFfEwOOKMBDiLfDJL0dc2AAUJpyQro1MVU-sso.pokemon.com"
    unknown2: 59
  }
}
ms_since_last_locationfix: 989
[/m]
2016/09/18 11:58:36.602 DEBUG REQUEST [@Pokegoapi]
                              [m]: RESPONSE
Response{protocol=http/1.1, code=200, message=OK, url=https://pgorelease.nianticlabs.com/plfe/401/rpc}
[/m]
2016/09/18 11:58:36.603 FATAL REQUEST [@Pokegoapi]
                              [m]: STATUS_CODE_102
Invalid Auth status code recieved, token not refreshed?  [/m]
2016/09/18 11:58:36.603 FATAL REQUEST [@Pokegoapi]
                              [m]: STATUS_CODE_102
Request{method=POST, url=https://pgorelease.nianticlabs.com/plfe/401/rpc, tag=null}[/m]
2016/09/18 11:58:36.603 FATAL REQUEST [@Pokegoapi]
                              [m]st_id: 9000949199830486267
requests {
  request_type: GET_PLAYER
  request_message: "\n\b\n\002US\022\002en"
}
requests {
  request_type: CHECK_CHALLENGE
}
unknown6 {
  request_type: 6
  unknown2 {
    encrypted_signature: "O\216\362\365\255\004\020h\360_\270\210X\246p\354{\212\314\375\322\203\tz\360\275\310\313\277\334g\340~\002\275\363?\210\002\361\300\203\232#\357P(\313\365\361\241\371\335\364\275\001\335\231O\333a\023\261\3200\213{\314\241r\211L\300\372\247>??\267\022\217\353\S\304\3111\344?\366\216\265\365\336\0321\251\2570\350\377\372r\032\362\366\023\206bD\367 \3406\317\027\271\037.\347%\006\177\372\231\311\343\347\005\274C\266e\362>\207\260\361\3279\372Y\n\232m\327\0313m\a\320\v\253\370\271\256\254\307^\331H\341\364\231\022\234\375\212\f7A\316\260\313\263\242T\030\334RKE\351S\260\215x\315\3460\300B\331g\\257!\203\024eR\225\316k\272O`\3106\375\240~EvI\004\'\267&\263\323K\252\a\212\032\332\225q\3630u\340\317(\201\032\266\253+\354F\304cp\002W)\"\224\v\357qh\314{\223\210Z]\303A\276&\341g\276RP\005W&z\364S\316\r\270:\271\345\307\262\032\253\244)=\211 \311\016x]\345o`D\256\341\231i@\362\323\256\002 \033M\237\016\334\316I\202Wg5q\212\033\350\324\302\034\002,\263~S\250a\310\312\267\364\364,\024\344>\241\307\034_\341\254\216\336=\344\344m=\260\303\035\372\307\251\363\n\301\223\027se\224\v)\266\363\3529\345\344\237i\226]\331psQ\t\247CU\367\374N\355\2012b\236c\000\226\276V\232\313\327\031\231$\370\003nwUL\222\245>\252ii\226j\255\255^I\034B\272\022\253\277\342\314\277\237_o[\337MDuGG;\2473h\316\363\303\033\3672\211\261\307\277d\271\257\275 ?\345S\314\177\237\352z\363Om\246\000\n~cz1\314+\275\243\350\213\250]n\374!\225\036\3052\227\304km_\204\023L_\275\305r7\022\000\2177\bY\036\340\310\017\314b\322\331!V\206$m\314\020B\252+\251\3170|e\2475\275w\255"
  }
}
latitude: -22.96658813950045
longitude: -43.21973872952563
altitude: 685.0
auth_info {
  provider: "ptc"
  token {
    contents: "TGT-20822004-9eARzPpQ6AeMMbkKrFfEwOOKMBDiLfDJL0dc2AAUJpyQro1MVU-sso.pokemon.com"
    unknown2: 59
  }
}
ms_since_last_locationfix: 989
[/m]

**Comment by R0g3r10LL31t3** [comment]
The app started at 09:27 and shutdown at 11:58.
- To reproduce, connect in the game and wait by longer hours. This is very hard to reproduce.

STARTED LOG:

2016/09/18 09:27:48.022 DEBUG REQUEST [@Pokegoapi]
                              [m]7\220?\264?\270\020_\330LJ%4\023H}I\337\314\344xv\200.\313,\262=\"Lp\235\'\023\207c\201\033\317\247\316\300|gAe\2552x\245`\347\t\363\006\347iyZ\345\351IN\273\367y\3134B\333\366\310\364\211v\222\337,\263QT\353c\350\355\241\321\276\334\355g0O\252q%\320\272\220\350\374X\202\226>\025\327\235\353B\272\\\217l\2200\021\r\313\037X\210\322\004y\222\3563|<N\336\232\263CD|\251%\225\225\355\233R\261\246\344Of\251\a~!v\204\027\244/y\005jV\312\207\336\371\346\216\213\373 Fo\316\373%\337\301\213\326\b\353\320\225\027\226\0371\353!\a\2659h\345\316\t\234IXrU\373\035\003Iylr\273~\0001\325\"g\261\271\230\233\251\037\300-t\354\372\\d\252\335\323\207W\'\207\324Q\357\344\233\206\340\037\306\262=\223\351\235H\"\006\221\t+k\253\360\036\323\360\332\344G=!\240\023\027\202\311\323\222\364\v\277=\023\310\203\035q\003p\205\230W\232\261\265\334\303\241j{\004!^\310\207\005\216\203#6\b@-\215U\272XyK\266\006\221e\344\"-5\256\355\265\032k\256\277\333\340\310\262{\274\203\325p\224b\034\202b\034\344\274\214\255\270$L}8c\234<\217\265\222(\360\321\366\023?^\b\261\240\a\226\363\341zU\001W\307\313>Is\351\260\024\017T\322\205U\341\2524\332\211HX5\266i\261\036D\253\254\177\363f2\3774A\325\037\3114c\222\333\n\35042A\211-)\r\304\242\277\214\r\320\241\005\212\2066U\200\326\261\256\250\035\353\214_\034z\304\246\205\362\213\337\306\264e\317a\206>]\006opI\310$\355R\227\206]\177`\223R\354\021\'\336\233\352\225\V\306\245\222c&mD^\375 &\022%\376\254F\367\230\273\347\b\354\266=\024-\177WTB_R\224\327G\201\220z\r\264\252zX\026\3476\006\246\252\256\344\240<\305\fSq\002\376\240c\376|f\216?\2657x+\204\250~\216D\356\022\247;f\255A\316V\034H\333-_\333\344\301.W\325:\332&\355{eq\326\bU\224R.\266\316\0366\366\274\026\300\324`}\037\377\v\331\"\240\240\236d_\260/\214\333\370\202\315\362\315\371\337\232\256$k\027\345Q\266\227\217\345[\216"
  }
}
latitude: NaN
longitude: NaN
altitude: NaN
auth_info {
  provider: "ptc"
  token {
    contents: "TGT-20822004-9eARzPpQ6AeMMbkKrFfEwOOKMBDiLfDJL0dc2AAUJpyQro1MVU-sso.pokemon.com"
    unknown2: 59
  }
}
ms_since_last_locationfix: 989
[/m]
2016/09/18 09:27:48.701 DEBUG REQUEST [@Pokegoapi]
                              [m]: RESPONSE
Response{protocol=http/1.1, code=200, message=OK, url=https://pgorelease.nianticlabs.com/plfe/rpc}
[/m]

**Comment by R0g3r10LL31t3** [comment]
@FabianTerhorst 
@LoungeKatt 
@iGio90

**Comment by AbandonedCart** [comment]
@R0g3r10LL31t3 There is no need to tag everyone when you don't get a reply within 24 hours. As collaborators, we already get email notifications for every single event without being impatient.

As you stated, _This is very hard to reproduce._
