### ISSUE TITLE
Build with gradle generate jar with duplicated files name

### ISSUE THREAD

**Issue by R0g3r10LL31t3** [Grover-c13/PokeGOAPI-Java#768]
Description
The final "PokeGOAPI-library-all-0.4.1.jar" generated with pokegoapi, pogoprotos and resources duplicate files. This problem occur since 0.4.0 version

Generated:
\PokeGOAPI-library-all-0.4.1.jar
+\devive
+\gym
+\inventory
+\map
+\player
+\pokemon
+\settings
+PokemonGo.class
+PokemonGo.class

Reproduce:
(on Windows 7)
1. git clone https://github.com/Grover-c13/PokeGOAPI-Java.git
2. git submodule update --init
3. gradlew :library:build
4. check generated jar files

Last Version Tested
0.4.1 (last commit)

**Comment by R0g3r10LL31t3** [comment]
![print](https://cloud.githubusercontent.com/assets/21255999/18359071/8ebc8170-75ce-11e6-9cac-e536a77cd9db.png)

**Comment by R0g3r10LL31t3** [comment]
Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
You are using Gradle 3.0:  This version of the protobuf plugin works with Gradle version 2.12+
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:library:extractIncludeProto
:library:extractProto
:library:generateProto
:library:compileJava
:library:processResources
:library:classes
:library:jar
:library:bundle
:library:javadoc
:library:javadocJar
:library:sourcesJar
:library:assemble
:library:checkstyleMain
:library:extractIncludeTestProto
:library:extractTestProto
:library:generateTestProto UP-TO-DATE
:library:compileTestJava UP-TO-DATE
:library:processTestResources UP-TO-DATE
:library:testClasses UP-TO-DATE
:library:checkstyleTest UP-TO-DATE
:library:test UP-TO-DATE
:library:check
:library:build

BUILD SUCCESSFUL

Total time: 1 mins 38.388 secs

**Comment by Gegy** [comment]
Have you tried clearing your build directory?
