### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MrPat** [Grover-c13/PokeGOAPI-Java#77]
What is this api licensed under? I'd like to use it but I need to know what all I can do with it first (e.g. commercial/noncommercial, etc.). I only ask because I couldn't find a License file or any other license notes anywhere. Thanks!

**Comment by FabianTerhorst** [comment]
Its against the tos from nintendo.

**Comment by FabianTerhorst** [comment]
So its not legal anyway to use it on the playstore.

**Comment by MrPat** [comment]
The TOS for Go? Players would be using the API at their own risk, and I don't think the Play Store would be concerned with the TOS for a game. Breaking the TOS could possibly result in a ban from Niantic but I don't think that would break any Play Store rules (or laws).

**Comment by Aphoh** [comment]
@MrPat Nintendo has made such a popular and important app that I don't think they would have ANY trouble getting any apps removed and maybe even any dev accounts banned.

**Comment by MrPat** [comment]
I hear you, but I think it might be worth a try. If not, though, I'd still like to know the license.

**Comment by Aphoh** [comment]
Because this library involves user passwords it might be a good idea to make it GPL or something that requires something more oss but I don't have much preference. We should probably wait until @Grover-c13 wakes up.

**Comment by FabianTerhorst** [comment]
@Aphoh gpl is a great idea. Its allowing commercial use, but also require all apps that are using this for commercial use to release the source code.

**Comment by MrPat** [comment]
Ok I'll check back later. By the way, you guys have done an amazing job! This is a great API to have while Go is still so buggy.

**Comment by Grover-c13** [comment]
Going with GPL  v3
