### ISSUE TITLE
Sometime getCatchablePokemon return empty 

### ISSUE THREAD

**Issue by dev111011** [Grover-c13/PokeGOAPI-Java#773]
**Description:**
I try to get nearby Pokemon by set location by mPokemonGo.setLocation(lat, longitude, alt) and mPokemonGo.getMap().getCatchablePokemon(), and sometime It return empty array but there are pokemons at scanned location.
So can anyone help to know how to scan multiple positions in a short time? I see the newest version of Pokemap for android can solve this problem, any suggestion?

**Comment by DaRealGunko** [comment]
Same here :+1:

**Comment by AbandonedCart** [comment]
If Pokemap is open source, you could compare the code and see how they go about it. Otherwise, it may be the delay you are using between requests. It is hard to diagnose how or why they don't show up without any errors.

**Comment by dev111011** [comment]
What minimum delay time should be? when i try with delay time more than 1s, app search better, but quite slow

**Comment by mjmjelde** [comment]
1 second?  its a 10 second delay minimum between each map call you do.  Anything before 10 seconds you won't get a valid response from the server

**Comment by dev111011** [comment]
@mjmfighter : thanks for your information. 10s is a long time for next searching :(

**Comment by AbandonedCart** [comment]
@dev111011 You can thank Niantic for being more concerned with preventing you from making a map than the actual user experience.

It appears this issue was the delay, so I am closing it. If you still experience the issue with a valid delay, you can reopen this one and add more details.
