### ISSUE TITLE
When i catching pokemon some time

### ISSUE THREAD

**Issue by Tempo95** [Grover-c13/PokeGOAPI-Java#774]
**Description:**
When i catch pokemon at area some time (20 - 30 min) i get a error when encounter: ERROR: ENCOUNTER_NOT_FOUND or ERROR: ENCOUNTER_ALREADY_HAPPEND. And later all pokemon escape or flee to me. Please help!

**Steps to reproduce:**
Catch pokemon at area some times

**Expected behavior:**
error

**Stacktrace (If it's a crash):**
ERROR: ENCOUNTER_NOT_FOUND or ERROR: ENCOUNTER_ALREADY_HAPPEND

**Version:**
0.4.1

**Comment by AbandonedCart** [comment]
Are you clearing the Pokemon from the list after you capture them or they flee?

**Comment by R0g3r10LL31t3** [comment]
Try to use a mirrored list with catchablePokemon FLED and FLEE, clean your mirrored list each new GetMapObjects newly. I am using this technique.
