### ISSUE TITLE
Eggs from Pokestops

### ISSUE THREAD

**Issue by wpgabriel** [Grover-c13/PokeGOAPI-Java#777]
**Description:**
I'm not receiving eggs from pokestops despite hatching many pokemon. I've used 5 of my 9 eggs and have hit a couple dozen pokestops during this time, and I haven't received an egg. I cannot tell if I'm using the Pokestop code wrong or if I've simply been that "unlucky." At this rate I'll be out of eggs pretty soon.

**Steps to reproduce:**

While walking around engaging pokemon, hatching eggs and getting pokestops, here is the code I roughly use to encounter the pokestop. I get everything else: pokeballs of various varieties, potions, revives, but since I've been using the api, no eggs.

```
Collection<Pokestop> stops = go.getMap().getMapObjects().getPokestops();
for(Pokestop stop : stops){
    if(stop.canLoot()){
        PokestopLootResult res = stop.loot();
        List<ItemAward> items = res.getItemsAwarded();
        for(ItemAward item : items){
            System.out.println(item.getItemId().name());
        }
        Thread.sleep(2500);
    }
}
```

**Version:**
0.4.0

**Comment by Gegy** [comment]
Eggs are not items. You can use res.toPrimitive().hasPokemonDataEgg() and res.toPrimitive().getPokemonDataEgg() to check and get the egg received.

**Comment by wpgabriel** [comment]
That makes sense, thank you for the guidance.
