### ISSUE TITLE
Fight in gym

### ISSUE THREAD

**Issue by Tempo95** [Grover-c13/PokeGOAPI-Java#778]
**Description:**
Pokemon not attack enemy pokemon on gym. But enemy pokemon attack my. And battle end with result TIMED_OUT

Exemple:
Defender: VENOMOTH [HP: 184/184 | ENERGY:80 | CP: 1142]
You: ARCANINE [HP: 40/136 | ENERGY:53 | CP: 2355]

**Steps to reproduce:**
Simple code for fight in gym

**Version:**
0.4.1

**Comment by bolds07** [comment]
I'm having similar issue,

trying to battle any gym and the battle.attack always return STATE_UNSET

i was looking to the method code and there is a -1 constant set to the target:

for (int i = 0; i < times; i++) {
            BattleAction action = BattleAction
                    .newBuilder()
                    .setType(BattleActionTypeOuterClass.BattleActionType.ACTION_ATTACK)
                    .setActionStartMs(api.currentTimeMillis() + (100 \* i))
                    .setDurationMs(500)
                    .setTargetIndex(-1)
                    .build();
            actions.add(action);
        }

is it okay? is anyone able to battle?
