### ISSUE TITLE
setLocation() 

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#780]
`go.setLocation(go.getLatitude() + 30 / 3.6 / 1000000, go.getLongitude() + 30 / 3.6 / 1000000, 1);
`

I want to move the character in 30 km/h for the pokestop, but this formula is not working properly.

Does anyone know another way to move a character to the pokestop 30 km/h?

**Comment by ghost** [comment]
#UP

**Comment by AbandonedCart** [comment]
The formula you posted will add 30 kilometers to both the latitude and longitude in a single step. This would only be accurate if the pokestop were exactly 30 kilometers in both directions and this was done 1 hour after the initial location is set.

You would want to calculate the distance to the pokestop, choose an interval, then move based on the distance you would cover in that interval at 30 km/h. It will likely be more than a single step.

**Comment by AbandonedCart** [comment]
An example (in words) would be that you wanted to move 10 kilometers in a single direction. If you were to move every minute, that would be .5 kilometers per minute. You would move .5 kilometers, wait a minute, and then move again for a total of 20 times.

**Comment by Gegy** [comment]
This can now be done with the Path class
