### ISSUE TITLE
Auto Login Google in 0.4.0?

### ISSUE THREAD

**Issue by kienphan75** [Grover-c13/PokeGOAPI-Java#781]
im still using version 0.4.0, so how do i auto login google account after first time?

**Comment by wpgabriel** [comment]
I use 0.4.0 as well, and I have found the GoogleAutoCredentialProvider works well with an app password on the Google Account (My Account -> Signing in to Google -> App Passwords -> Generate).

Once you have that, the GoogleAutoCredentialProvider class will take your username and app password directly, you don't need to worry about tokens or any other login steps.

Here's some stub code:

```
OkHttpClient http = new OkHttpClient();
CredentialProvider auth = new GoogleAutoCredentialProvider(http, username, password);
PokemonGo go = new PokemonGo(auth, http);
```

Hope that answers your question.

**Comment by AbandonedCart** [comment]
https://security.google.com/settings/security/apppasswords
Keep in mind, it requires 2 step verification to be enabled
