### ISSUE TITLE
Heal Stamina Pokemon

### ISSUE THREAD

**Issue by R0g3r10LL31t3** [Grover-c13/PokeGOAPI-Java#783]
Hello,

When I heal Pokemon, the stamina attribute isn't updated. Then, in next heal pokegoapi throw an exception with "Your account may be banned! please try from the official client.", status code 3.

Is possible add updating logic in heal or user item methods of the Pokemon class?

**Comment by R0g3r10LL31t3** [comment]
LOG:

2016/09/25 20:04:04.396 DEBUG REQUEST [@pokegoapi]
                              [m]: REQUEST_0829
requestEnvelope.toString()
status_code: 2
request_id: 9404254467067391095
requests {
  request_type: USE_ITEM_POTION
  request_message: "\be\021/\256\b\214Iu\317j"
}
unknown6 {
  request_type: 6
  unknown2 {
    encrypted_signature: "\303\303\335\347]\316\231\253\243Q\337\026Ty\243\354\352\356:\236\350E\357Gn\212n\n\"$\0228\322\316\205\304\331v.\026\034\270\370J\f\0250\347\367\235ZRo\315\216\033\333\263\316\337Gl7n\353\272_\230:a$\304\3366\263\337\355\0225\213\242\037\271\005i\211\312 P@\335\264M\211P\232\231\375\331^{\354\302 \231\n\3335_]\325\277K\ti\240\rz\\3276\337t\001K\340\337>?\2739lNP\003q\306\240f\222(J\226@\f\216\213\201\377\206\326\373\317\377\a7;\ft(\031\341F\244\270\210q\376\223}\017c\207k\357\244\r\233WH\320n\305\277\274\035\305\355\262\003\237S\335f\362=C\t(w\307\310N\321XT\315\363u\302(\037`\364\343lX\273\n\3654\244\254By~\321\367{\024\003\255\263\257X\003\202~S\316Y|W\207\362\256\334\206<\211\217C\242\223,\371\344|{\277 \346\210\303[%g\235p\277\273\332A[ _\177\235c\000\256\232\266ZtVj\f"
  }
}
latitude: -22.90527067999504
longitude: -43.17318435000573
altitude: 685.0
auth_ticket {
  start: "cT\350W\236OW\271\210\304\224\027\200\362\006\246\0061\335`L$`\"X\364\244\264\244\255\211\001\266\232Q\272\315,\273\342L\262\364\374-U)~;\207\004>.\305\263\210\336cS\223\314b\271\22620\t\005\363\244\2058\314E\267 >f}\236"
  expire_timestamp_ms: 1474845442088
  end: "\243\204n)L\344\266\375.\252\254\247\243\213>e"
}
ms_since_last_locationfix: 989
[/m]
2016/09/25 20:04:04.396 DEBUG REQUEST [@pokegoapi]
                              [m]: REQUEST_0829
httpRequest.toString()
Request{method=POST, url=https://pgorelease.nianticlabs.com/plfe/600/rpc, tag=null}[/m]
2016/09/25 20:04:05.038 DEBUG REQUEST [@pokegoapi]
                              [m]: RESPONSE_0829
httpResponse.toString()
Response{protocol=http/1.1, code=200, message=OK, url=https://pgorelease.nianticlabs.com/plfe/600/rpc}
[/m]
2016/09/25 20:04:05.039 DEBUG REQUEST [@pokegoapi]
                              [m]: RESPONSE_0829
responseEnvelop.toString()
status_code: 1
request_id: 9404254467067391095
unknown6 {
  response_type: 6
  unknown2 {
    unknown1: 1
  }
}
returns: "\b\001\020T"
[/m]
2016/09/25 20:04:05.390 DEBUG REQUEST [@pokegoapi]
                              [m]: REQUEST_0949
requestEnvelope.toString()
status_code: 2
request_id: 9404254467067391096
requests {
  request_type: USE_ITEM_POTION
  request_message: "\be\021/\256\b\214Iu\317j"
}
unknown6 {
  request_type: 6
  unknown2 {
    encrypted_signature: "\361\303B\025\341\356%C\324\232US\024\340R\270.#\304r:\206\347\231\335)da|\333\313\263&\375Jt\246&\004\341\301\237\331x`\364\222\350Gf\274\217\374d\321\201Q\016nk\215\005\316\256EY\222\365J\033\"\236L_\"\352\272g\"\314e\245\0012`XW\275\377\255\334\366u\264\212~\270\201\341\251\247\213\246\243\204\316\034\022tv3\022\025\f\335u\336\b\306W\235\200\210\a\350\324\225\001\266\205y \260\2369\352\tI\262Z\202\021`\036\341B\300\202\336\360\300\347\206x\310OO\374\263\335\332tX#)\233\032\225\333p-\374\fo\211\310G%\317\032$\332\352\305\334\f\207\"\326\212\232\025>\266\343KY)\001\330\247^G\024\366\b\342#\022\370m\271Cln\227\027\260\360\361Z\"\347\256\241r\212\233\f\3758\263\202?\177_\272^v\206\342\260i_\t\346\320\037&_\261/\2273q\332\343\321W\237vC\322\256v{\232Sj9\307~\210v~]?\327\3426\321\334\274\265\002S\315\360"
  }
}
latitude: -22.90527067999504
longitude: -43.17318435000573
altitude: 685.0
auth_ticket {
  start: "cT\350W\236OW\271\210\304\224\027\200\362\006\246\0061\335`L$`\"X\364\244\264\244\255\211\001\266\232Q\272\315,\273\342L\262\364\374-U)~;\207\004>.\305\263\210\336cS\223\314b\271\22620\t\005\363\244\2058\314E\267 >f}\236"
  expire_timestamp_ms: 1474845442088
  end: "\243\204n)L\344\266\375.\252\254\247\243\213>e"
}
ms_since_last_locationfix: 989
[/m]
2016/09/25 20:04:05.390 DEBUG REQUEST [@pokegoapi]
                              [m]: REQUEST_0949
httpRequest.toString()
Request{method=POST, url=https://pgorelease.nianticlabs.com/plfe/600/rpc, tag=null}[/m]
2016/09/25 20:04:05.793 DEBUG REQUEST [@pokegoapi]
                              [m]: RESPONSE_0949
httpResponse.toString()
Response{protocol=http/1.1, code=200, message=OK, url=https://pgorelease.nianticlabs.com/plfe/600/rpc}
[/m]
2016/09/25 20:04:05.794 DEBUG REQUEST [@pokegoapi]
                              [m]: RESPONSE_0949
responseEnvelop.toString()
status_code: 3
request_id: 9404254467067391096
unknown6 {
  response_type: 6
  unknown2 {
    unknown1: 1
  }
}
returns: ""
[/m]
2016/09/25 20:04:05.794 FATAL REQUEST [@pokegoapi]
                              [m]: STATUS_CODE_3_0949
Your account may be banned! please try from the official client.[/m]
2016/09/25 20:04:06.146 DEBUG REQUEST [@pokegoapi]
                              [m]: REQUEST_0650
requestEnvelope.toString()
status_code: 2
request_id: 9404254467067391097
requests {
  request_type: GET_PLAYER
  request_message: "\n\b\n\002US\022\002en"
}
requests {
  request_type: CHECK_CHALLENGE
}
unknown6 {
  request_type: 6
  unknown2 {
    encrypted_signature: "\367v\tR\306Q+%\002\320\336\237\266\365T\251\267\210\225\v\207\272\232Pe\203\324\255O/A_\275\357\003vx\036\017\003\334\312+\336.\230\230\2258\271\000\377\002;5\351\363\330\220EF.\245iO\347`q\370/\372#\005_\257J\371T\330~\235N\333\346\f\335\3070\345\272\005\341\202\265\336\254\270R}\337\314S`\207\374\271\202\207r\203S\262\360[%\266`\300\216B\324o\227\241\262\021A\273|`p\232\213@\264\333\234\310\372\277my\0046\245\245\272t\242\226\330\270\306\221\336\217\330\034\240\"\370\325\233\3318\r\213\321s\213\371\246\363\336l\214x:\270QFf\036\\355\215sPyK|\274L\231K\204\236}i\020\363\243?\005\251(\267\310\266wR\035r\245#\237T#sU\267\273<\374\303\036t\263+W\376\277\202\233aZ\261\340\021\360\vQ\260\375\"\261\313\002i@\323!*Y\272\352\253\t,\252j/\343/\036t\321\275s~\244\214\237\350\340\333sz\3661\236\311\223\275\214Uf:"
  }
}
latitude: -22.90527067999504
longitude: -43.17318435000573
altitude: 685.0
auth_ticket {
  start: "cT\350W\236OW\271\210\304\224\027\200\362\006\246\0061\335`L$`\"X\364\244\264\244\255\211\001\266\232Q\272\315,\273\342L\262\364\374-U)~;\207\004>.\305\263\210\336cS\223\314b\271\22620\t\005\363\244\2058\314E\267 >f}\236"
  expire_timestamp_ms: 1474845442088
  end: "\243\204n)L\344\266\375.\252\254\247\243\213>e"
}
ms_since_last_locationfix: 989
[/m]

**Comment by R0g3r10LL31t3** [comment]
The response to first heal can be empty (using default value). Then the new stamina isn't updated.

**Comment by R0g3r10LL31t3** [comment]
The response to powerUp method do not update stamina attribute.

**Comment by Gegy** [comment]
Can Pokemon without full stamina / health be powered up?
