### ISSUE TITLE
API 0.39 broken

### ISSUE THREAD

**Issue by leandrolimasi** [Grover-c13/PokeGOAPI-Java#784]
Hi,
It is still safe to use the api after the update api 0.39?
THIS API version has new encryptions!

**Comment by wpgabriel** [comment]
I would not use this API now that they forced the clients to 0.39. They're still letting 0.35 through--my scanners are still working--but now they know which accounts are are using APIs like this.

If and when someone is able to reverse engineer the new protos and this API links to those, then it will be okay to use again. But for now I believe that using this API is a sure fire way to get yourself banned soon.

**Comment by leandrolimasi** [comment]
tanks for reply,

bad news for all.
