### ISSUE TITLE
Auto get authcode from Google without copy - paste?

### ISSUE THREAD

**Issue by vodoi1432** [Grover-c13/PokeGOAPI-Java#785]
can somebody help me solve this prob?
im using ver 0.4.0.

**Comment by RebliNk17** [comment]
yes i can help you with that
solution: not getting to auth code at all
you this:
`GoogleAutoCredentialProvider provider = new GoogleAutoCredentialProvider(httpClient, username, password, new SystemTimeImpl());
PokemonGo go = new PokemonGo(httpClient);
go.setDeviceInfo(deviceInfo());
go.login(provider);`
