### ISSUE TITLE
Buddy Pokemon? 

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#786]
```
go.getPlayerProfile().updateProfile(go.getPlayerProfile().getPlayerData().toBuilder().setBuddyPokemon(BuddyPokemon.newBuilder().setId(pokemons.getPokemonId().ordinal()).build()).build());
```

Unfortunately, I just found this method to set Buddy Pokemon.

Another method?

(BuddyPokemon.newBuilder().SetId ()) , which id is this?

**Comment by Gegy** [comment]
Instead of using the Pokemon type ID (`pokemons.getPokemonId().ordinal()`), you should use `pokemons.getId();` as that is a unique ID for that particular Pokemon and not that type.

**Comment by ghost** [comment]
@gegy1000:
Thanks, it worked!
