### ISSUE TITLE
Can we know if a captcha is required ?

### ISSUE THREAD

**Issue by Timenote** [Grover-c13/PokeGOAPI-Java#787]
Hi, just a simple question, with this current version (0.4.1), can we know if a captcha is required ?

**Comment by Coalado** [comment]
Good question.

**Comment by Coalado** [comment]
Check the Player profile. keyword challenge

**Comment by ljk1291** [comment]
you can get the captcha from CheckChallenge

**Comment by DaRealGunko** [comment]
Sample code ?

**Comment by DaRealGunko** [comment]
I have retrieved captcha:

if(go?.hasChallenge){
   String captcha = go?.challengeURL
}
but if I solved it, it still generate new one ..

**Comment by RebliNk17** [comment]
Same here,  I am waiting for captcha to Come so ill check the new code

**Comment by DaRealGunko** [comment]
I think we need "verifyChallenge" ...

**Comment by Gegy** [comment]
`getChallengeURL`, `hasChallenge` and `verifyChallenge` are all available in the `PokemonGo` class now, along with `CaptchaSolveExample` to show how they can be used.
