### ISSUE TITLE
Api not work now?

### ISSUE THREAD

**Issue by Tempo95** [Grover-c13/PokeGOAPI-Java#788]
api not work?? All wait update?

**Comment by CasparChou** [comment]
#787 problem not solved yet , not just this api, every api/site in this world  just died .
unknown6 is working on reverse-engineering now .
[https://twitter.com/FastPokeMapCom/status/784475971084845056](https://twitter.com/FastPokeMapCom/status/784475971084845056)

**Comment by vagprogrammer** [comment]
Something new?

**Comment by CasparChou** [comment]
FastPokeMap is back,  API will work 

https://fastpokemap.se/beta/?forcerefresh

**Comment by chegola** [comment]
I am able to login but can't see any Pokemon even put the location that Pokemon are there by https://fastpokemap.se/beta/?forcerefresh. Do you guys got same issue?

**Comment by Animeshm77** [comment]
Fastpokemap developers realeased the decryption code ....please check .

**Comment by Gegy** [comment]
I think this can be closed now.
