### ISSUE TITLE
Do you plan to further work?

### ISSUE THREAD

**Issue by Tempo95** [Grover-c13/PokeGOAPI-Java#789]
Do you plan to further work on the api?

**Comment by yutamago** [comment]
The api lives and dies with the people who want to contribute.
Pokemon GO is slowly fading away and so are interested developers.

**Comment by aaiezza** [comment]
Sad reality indeed... So long wasted time.

**Comment by Tempo95** [comment]
there is just something you need to change the encryption mechanism. So much work to an empty? Correct a couple of files of all the ..

**Comment by yutamago** [comment]
@aaiezza I wouldn't call the time wasted. I learned a lot and it was fun while it lasted.
@Tempo95 You're always welcome to submit new changes. Fork the repository, get it working again and submit a PR.

I would still contribute if I weren't so extremely busy right now. Got a few parallel projects with similar deadlines going on, no time for playing hero.

**Comment by Gegy** [comment]
[This repository](https://github.com/POGO-Java/UK6) contains everything needed to get this API working again.

**Comment by Tempo95** [comment]
Prompt please: how to upgrade https://github.com/AeonLucid/POGOProtos aka submodule

**Comment by Tempo95** [comment]
i solved this, thanks

**Comment by 4ndro1d** [comment]
@gegy1000 could you include it osmehow? :X i can't get it to work. Doing an installation at a museum (LED facade showing pokeball and info about the gym) - and somehow they decided to put it live today T_T

**Comment by Gegy** [comment]
@4ndro1d #790

**Comment by Wolfsblvt** [comment]
So, @Tempo95, how did you actually actually updated the Protos?
I mean at the moment it is quite important with those base stat changes.

**Comment by Gegy** [comment]
Can this be closed, now that the API works again?
