### ISSUE TITLE
getCatchablePokemon()

### ISSUE THREAD

**Issue by ghost** [Grover-c13/PokeGOAPI-Java#792]
go.setLocation(40.71629,-73.9911473,1);
go.getMap().getCatchablePokemon().forEach(pokestop -> {
				try {
					System.out.println(pokestop.getLatitude());
				} catch (Exception e) {e.printStackTrace();};
			});

It's not working, does not return anything.
(using the latest commit.)

**Comment by Gegy** [comment]
I had this problem at one point too at one point. Updating the inventory before calling getCatchablePokemon seemed to fix it. 

EDIT:
Are you sure you are not soft-banned, in the wrong location, or in a place with no catchable Pokemon?

**Comment by ghost** [comment]
@gegy1000 

Yes, I'm in the right place (Central Park), and I'm not banned.

I put this:

go.getInventories().updateInventories ();

go.getMap().getMapObjects (7).getPokestops().forEach (pokestop-> {
try {
System.out. println (pokestop. getLatitude ());
} catch (Exception e) {e. printStackTrace ();};
});

The error continues.
I made this sample with pokestop, but with pokemon also continues.
(How to check the captcha? is that?)

**Comment by DaRealGunko** [comment]
go?.getMap()?.getCatchablePokemon()
is always empty for me too

**Comment by Gegy** [comment]
Does your account require the captcha to be solved?

**Comment by ghost** [comment]
@gegy1000 No, I checked the captcha.

**Comment by jhfeit** [comment]
@gegy1000 for me go.getMap().getCatchablePokemon() is also returning empty.
I already checked my account, and you're not asking for captcha.

**Comment by Gegy** [comment]
Are you using an altitude of 0?

**Comment by DaRealGunko** [comment]
Im using alt=350

**Comment by Gegy** [comment]
This may be your problem, currently using any altitude other than 0 receives no map objects. I am working on this.

EDIT: #796 should fix this issue

**Comment by jhfeit** [comment]
@gegy1000 I used altitude 0 and it continues returning empty data. I will update with your last commit and test.

**Comment by ghost** [comment]
@gegy1000 

go.setLocation(40.7828647 ,-73.9653551, 0);

Yes, it worked.

Thanks :)
