### ISSUE TITLE
expirationTime = -1

### ISSUE THREAD

**Issue by koffeeapps** [Grover-c13/PokeGOAPI-Java#797]
Expiration time for nearly all catchable pokemons is -1.
Anyone has an idea ?

![image](https://cloud.githubusercontent.com/assets/20814752/20242361/a6b81a10-a92b-11e6-9ff5-8cace66d2f68.png)

**Comment by jabbink** [comment]
noticed the same a few days ago. catching these works though, so I now check if the time is within boundaries or -1 and catch it then.
maybe the Protos broke something, or more likely: niantic broke

**Comment by Gegy** [comment]
This was an intended 'feature' from Niantic. The Pokemon only get valid despawn times when it goes below 90 seconds.
