### ISSUE TITLE
Update Hash function and protos 

### ISSUE THREAD

**Issue by vagprogrammer** [Grover-c13/PokeGOAPI-Java#802]
How can I update Hash function and protos. I'm using gradle version. 
I really need help, some one can help me? Thanks. 

**Version:**
0.4.1 gradle

**Comment by RebliNk17** [comment]
use git shell with this repository
run command "git submodule update --init"
let it finish
now run "./gradlew :library:build"
that is it
a file called pokeapi.library-all.....0.4.1.jar will be created with all protos and hash

**Comment by vagprogrammer** [comment]
Thanks in advance, but an error was ocurred, what is wrong?

![captura de pantalla 2016-11-18 a las 12 00 00](https://cloud.githubusercontent.com/assets/803683/20440821/3d60557c-ad87-11e6-8a04-79f13f2c5304.png)

I just clone the repo like: 
git clone https://github.com/Grover-c13/PokeGOAPI-Java.git 
then: 
"git submodule update --init"
then
"./gradlew :library:build"

**Comment by vagprogrammer** [comment]
I found the error. Now all is working, thanks
