### ISSUE TITLE
[2 problems] I want to not catch a pokemon and Captcha

### ISSUE THREAD

**Issue by RebliNk17** [Grover-c13/PokeGOAPI-Java#803]
1) I want to **not** catch a pokemon i've encountered.
i tried to set probability with CatchOptions to 0
0 pokeballs, 0 razberrys and it is still catching it.
how do i stop that?

2) I made a popup window in java to solve the captcha.
when i solve it do i need to to anything after?
because it still asking me for captcha...

I use the most updated PokeGOAPI-Java

thank you very much :-)

**Comment by DaRealGunko** [comment]
Same for me, what I need to do after solving captcha ?

**Comment by DaRealGunko** [comment]
I think we need "verifyChallenge" ...

**Comment by RebliNk17** [comment]
Where do you find that verifychallenge?

**Comment by DaRealGunko** [comment]
So far I found out, you need to check challenge, if return true, solve captcha from check challenge url and send result using verifyChallenge. But verifyChallenge is not implemented here yet, so I will wait ...

**Comment by RebliNk17** [comment]
There is updateChallenge, but what do i send with it?

**Comment by Gegy** [comment]
`verifyChallenge` has been implemented in the latest commit, and an example of usage can be found in the `SolveCaptchaExample`

**Comment by RebliNk17** [comment]
Thank you very much gegy.
im closing this issue.
for the first question, i have found a bypass.
thanks 👍
