### ISSUE TITLE
What with gym battle

### ISSUE THREAD

**Issue by Tempo95** [Grover-c13/PokeGOAPI-Java#804]
constantly arises TIMED_OUT

**Comment by Gegy** [comment]
#252

**Comment by Tempo95** [comment]
this is old information. Problem not in it.

**Comment by Gegy** [comment]
The problem is still with the Battle class in general

**Comment by Tempo95** [comment]
i know. But I do not understand what exactly. Battle starts correctly, but at the first turns action get result = TIMED_OUT and battle is ending

**Comment by Tempo95** [comment]
I think this is related with api function currentTime(). Before 0.35 battle work great. But now always get TIMED_OUT.
