### ISSUE TITLE
Error getting CP with getCpAfterEvolve() and getMaxCpFullEvolveAndPowerupForPlayer()

### ISSUE THREAD

**Issue by vagprogrammer** [Grover-c13/PokeGOAPI-Java#812]
Some one can help me please.

1)There a problem when i try to get the Cp after evolution or the maximum CP of any pokemon, the error is: 
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
  I get the same error for getCpAfterFullEvolve() and getMaxCpFullEvolveAndPowerupForPlayer().

2)How can I know the Cp after evolve Eevee and it is posible to know what pokemon can get after evolve (Flareon, Vaporeon, Jolteon)         

Note: I used the last commited changes of the Api. Thanks in advance.

**Comment by RebliNk17** [comment]
for 1 Show code, probebly you are running on an empty loop, we need to see code.
for 2, i don't think we can, i have tried it already.

**Comment by Gegy** [comment]
#813 should fix this, although it now requires you to pass the desired pokemon evolution id to the method, as multiple evolutions can happen for a single pokemon. (Eevee)

You can get all evolutions of a Pokemon with the Evolutions class

**Comment by vagprogrammer** [comment]
@gegy1000

How can i get the Highest Pokemon. 

![captura de pantalla 2016-12-06 a las 6 31 35 p m](https://cloud.githubusercontent.com/assets/803683/20949991/5281dd0e-bbe2-11e6-9e26-cd5b82806740.png)

For example to CHARMANDER the Highest Pokemon should be CHARIZARD, but when I call Evolutions.getHighest(pokemon.getPokemonId()); I ever get an empty list,

**Comment by Gegy** [comment]
Looks like this is a bug with the Evolutions#getHighest method, I'll fix this.

**Comment by vagprogrammer** [comment]
Thank you so much!

**Comment by Gegy** [comment]
Fixed in latest commit.
