### ISSUE TITLE
How to collect candy from pokemon buddy?

### ISSUE THREAD

**Issue by nok044** [Grover-c13/PokeGOAPI-Java#814]
Is this function implemented?

**Comment by RebliNk17** [comment]
I am currently try to figure out how it is working and implement a listener for that
but there is a mathod that get pokebuddycandys

**Comment by Gegy** [comment]
`PokemonListener#onBuddyFindCandy` is what you'll want to use. Buddies can also be gotten and set from the PlayerProfile class.
