### ISSUE TITLE
Somebody correct Battle.java please

### ISSUE THREAD

**Issue by Tempo95** [Grover-c13/PokeGOAPI-Java#816]
Api have problem with gym battle.
Battle **begins good**. But after first attack action battle ends with result =  **TIMED_OUT**.
The problem is most likely in time. Maybe method api **getCurrentTime()** return wrong time.
I can not deal with this problem because I tried different options for change but I did not succeed.
Please, who now how or may do this, help me.

**Comment by Gegy** [comment]
This is related to #252, I think only one issue is necessary, if the battle is fixed, both of these issues will likely be fixed together.
