### ISSUE TITLE
Question: How to get the Moves of each pokemon.

### ISSUE THREAD

**Issue by vagprogrammer** [Grover-c13/PokeGOAPI-Java#821]
**Description:**
I am looking for a way to access the data of the movements of each pokemon. Now I can only access to the name of the movement through a call to:

PokemonMoveOuterClass.PokemonMove mMove1 = pokemon.getMove1();
Log.i(TAG, "Move1: " + mMove1.name());

or

PokemonMoveOuterClass.PokemonMove mMove2 = pokemon.getMove2();
Log.i(TAG, "Move2: " + mMove2.name());

My question is: How can I access to other Movement info? (Speed, movement power, etc) 

**Version:**
I'm using the last commited changes of the API. Thanks in advance!

**Comment by Gegy** [comment]
`PokemonMoveMetaRegistry` is likely what you are looking for.

**Comment by vagprogrammer** [comment]
Hi @gegy1000 , I hope you are very well, with the new api update, I can not access to the movements of each Pokemon. How can I do that?

**Comment by Gegy** [comment]
`PokemonMeta.getMoveSettings`
