### ISSUE TITLE
getNearbyPokemon() return Empty.

### ISSUE THREAD

**Issue by shion1118** [Grover-c13/PokeGOAPI-Java#824]
**Description:**
getNearbyPokemon() alyways return empty. getMapObjects() also empty. 
go.getPlayerProfile().getPlayerData().getUsername() is Working ! (Maybe API is working)

**Code:**
```
go.setLocation(35.668865, 139.6985487, 0.0);
List<NearbyPokemon> pokemon = go.getMap().getNearbyPokemon();
System.out.println("Pokemon in area: " + pokemon.size());
```

**Comment by Gegy** [comment]
Could you possibly be banned / soft-banned? What version of the API are you using? The latest on the Development branch?

Also, I'm assuming you did call `go.login` before the given code.

**Comment by Animeshm77** [comment]
You need to solve captcha @Shion1118 .....login using pokemon go official app, solve captcha and than retry.

**Comment by shion1118** [comment]
@gegy1000 This account can play PokemonGO on ios. API version is 0.4.1.
**Code:**
```
OkHttpClient httpClient = new OkHttpClient();
PokemonGo go = new PokemonGo(httpClient);
go.login(new PtcCredentialProvider(httpClient, USERNAME, PASSWORD));
```

**Comment by Gegy** [comment]
You must compile from the latest source from the Development branch.

**Comment by shion1118** [comment]
@Animeshm77 Im using PTC account that can play PokemonGO on ios. Maybe, this account is solved captcha.

**Comment by shion1118** [comment]
@gegy1000 It Works! Thanks!!
