### ISSUE TITLE
Trying to locate Pokemon with CatchPokemonAtAreaExample, but never shows any

### ISSUE THREAD

**Issue by scprotz** [Grover-c13/PokeGOAPI-Java#829]
I just loaded up the .jar file into an eclipse project.  I copied over the CatchPokemonAtAreaExample.  I created a brand new account on club.pokemongo.net (and authenticated it).

I picked a location that I know has many pokemon around it always (it is a big gym). I ran the app but it comes back with nothing in the area.  Let it run for a few minutes.

I then turned off the app, logged in on a regular device with the same account.  I have a charmander (default) and my name is a random string of characters (guess I never set these before starting bot).
I looked at the gym (I'm physically at the gym).  5 pokemon were there.

Logged out of device and tried again with the app.  Still no pokemon.

Any ideas what I'm missing here?

I'm using the latest 041 API code.  I can submit code if that helps, but it is same as in API other than changed username/password.

**Comment by clangdev** [comment]
I you changed nothing but username/password, then you did not set your desired location successfully.
Could you please post your code?

**Comment by scprotz** [comment]
@clangdev Thanks for looking. Here is the sample code with my 2 changes (my credentials and the location I'm using - in Switzerland)

`/**
	 * Catches a pokemon at an area.
     * @param args args
	 */
	public static void main(String[] args) {
		OkHttpClient http = new OkHttpClient();
		RequestEnvelopeOuterClass.RequestEnvelope.AuthInfo auth = null;
		PokemonGo go = new PokemonGo(http);
		try {
			go.login(new PtcCredentialProvider(http, ExampleLoginDetails.LOGIN,
					ExampleLoginDetails.PASSWORD));
			//or google
			//new PokemonGo(GoogleCredentialProvider(http,listner));
			//Subsiquently
			//new PokemonGo(GoogleCredentialProvider(http,refreshtoken));
			// set location
			go.setLocation(46.212935, 6.145413, 0);

			List<CatchablePokemon> catchablePokemon = go.getMap().getCatchablePokemon();
			System.out.println("Pokemon in area:" + catchablePokemon.size());

			for (CatchablePokemon cp : catchablePokemon) {
				// You need to Encounter first.
				EncounterResult encResult = cp.encounterPokemon();
				// if encounter was succesful, catch
				if (encResult.wasSuccessful()) {
					System.out.println("Encounted:" + cp.getPokemonId());
					CatchOptions options = new CatchOptions(go);
					options.useRazzberry(true);
					CatchResult result = cp.catchPokemon(options);
					System.out.println("Attempt to catch:" + cp.getPokemonId() + " " + result.getStatus());
				}

			}

		} catch (LoginFailedException | NoSuchItemException | RemoteServerException e) {
			// failed to login, invalid credentials, auth issue or server issue.
			Log.e("Main", "Failed to login or server issue: ", e);

		}
	}`

I have also tried it wrapping the code ('get'ing the map and inspecting for catchable pokemon) in a while loop and inspecting every 1000 millis.  No luck with that either.

**Comment by scprotz** [comment]
One other thing.  I logged in with a real client and was forced to 'captcha' (I didn't even know PoGo had captcha option).  Could this be caused by the examples?

**Comment by clangdev** [comment]
Just tested your code.
Got the following console output after modifying the login credentials:

> D/RequestHandler: Authenticated with static token
> Pokemon in area:6
> Encounted:RATTATA
> V/CatchablePokemon: Pokemon caught/or flee
> Attempt to catch:RATTATA CATCH_SUCCESS
> Encounted:RATTATA
> V/CatchablePokemon: Pokemon caught/or flee
> Attempt to catch:RATTATA CATCH_SUCCESS
> Encounted:ZUBAT
> V/CatchablePokemon: Pokemon caught/or flee
> Attempt to catch:ZUBAT CATCH_SUCCESS
> Encounted:WEEDLE
> V/CatchablePokemon: Pokemon caught/or flee
> Attempt to catch:WEEDLE CATCH_SUCCESS
> Encounted:VENONAT
> V/CatchablePokemon: Pokemon caught/or flee
> Attempt to catch:VENONAT CATCH_SUCCESS
> Encounted:WEEDLE
> V/CatchablePokemon: Pokemon caught/or flee
> Attempt to catch:WEEDLE CATCH_SUCCESS

I guess that you get no reply because of unsolved captcha? Maybe you take a look at the CaptchaExample https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/sample/src/main/java/com/pokegoapi/examples/SolveCaptchaExample.java
Your code is ok.

**Comment by scprotz** [comment]
Thanks,

The Captcha was the issue.  Why is it that captcha appears on the API and not on the real client.  Is the API not matching the client perfectly?

**Comment by clangdev** [comment]
I noticed you already discovered my issue where I would like to find out more about that, too.
Good you found the cause for your problem.

**Comment by Gegy** [comment]
I'd recommend you build your own jar from the latest API source instead of using 0.4.1.

**Comment by scprotz** [comment]
I've built my own from source and works fine.  The Captcha issue still exists (get captcha when using the API).  I'll consider this closed and keep an eye on the captcha thread.
