### ISSUE TITLE
Error running gradlew :library:build

### ISSUE THREAD

**Issue by kotiansukesh** [Grover-c13/PokeGOAPI-Java#831]
**Steps to reproduce:**
1. Open terminal (Using Windows 10)
2. Clone the project "https://github.com/sukeshkotiang/PokeGOAPI-Java"
3. Run "git submodule update --init"
4. Run "gradlew :library:build"

**Result:**
Lot of errors.

**Stack Trace:**
http://pastebin.com/kVVK4eRa

I hope this is enough information.

**Comment by RebliNk17** [comment]
move the folder to c:/a 
or d:/d
first short folder name, and all the files of the api inside...
then run 3-4 again

**Comment by kotiansukesh** [comment]
Thanks man, this worked for me.
