### ISSUE TITLE
How do i implement walk from one location to another?

### ISSUE THREAD

**Issue by kotiansukesh** [Grover-c13/PokeGOAPI-Java#834]
**Description:**
I've been trying to implement walk, and i'm not able to understand what to do next.

**Below is the code i've written**
double startLat = 37.80898;
double startLon = -122.41588;
double endLat = 37.807595;
double endLon = -122.420763;

Point startPoint = new Point(startLat, startLon);
Point endPoint = new Point(endLat, endLon);

Path walkPath = new Path(startPoint, endPoint, 5);
walkPath.start(go);

**Comment by RebliNk17** [comment]
easy,
follow this example:
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/sample/src/main/java/com/pokegoapi/examples/TravelToPokestopExample.java

**Comment by kotiansukesh** [comment]
Sorry didn't notice that example there. Thank you 👍
