### ISSUE TITLE
Can't seem to drop a potion (when I get too many)

### ISSUE THREAD

**Issue by scprotz** [Grover-c13/PokeGOAPI-Java#836]
Fairly obvious but, I'm trying to drop a potion (keep my total around 75).

Here is my sample method:
`Item potions = go.getInventories().getItemBag().getItem(ItemId.ITEM_POTION);
		Item superpotions = go.getInventories().getItemBag().getItem(ItemId.ITEM_SUPER_POTION);
		Item hyperpotions = go.getInventories().getItemBag().getItem(ItemId.ITEM_HYPER_POTION);
		Item maxpotions = go.getInventories().getItemBag().getItem(ItemId.ITEM_MAX_POTION);

		if (maxpotions.getCount() > POTION_LIMIT)
		{
			maxpotions.setCount(POTION_LIMIT);
			hyperpotions.setCount(NONE);
			superpotions.setCount(NONE);
			potions.setCount(NONE);
		}
		else if (maxpotions.getCount() + hyperpotions.getCount() > POTION_LIMIT)
		{
			hyperpotions.setCount(POTION_LIMIT - maxpotions.getCount());
			superpotions.setCount(NONE);
			potions.setCount(NONE);
		}
		else if (maxpotions.getCount() + hyperpotions.getCount() + superpotions.getCount() > POTION_LIMIT)
		{
			superpotions.setCount(POTION_LIMIT - maxpotions.getCount() - hyperpotions.getCount());
			potions.setCount(NONE);
		}
		else if (maxpotions.getCount() + hyperpotions.getCount() + superpotions.getCount() + potions.getCount() > POTION_LIMIT)
		{
			potions.setCount(POTION_LIMIT - maxpotions.getCount() - hyperpotions.getCount() - superpotions.getCount());
		}`
On the console it 'says' it dropped it, but if i log back into a real client, no potions dropped. 

Any ideas why it isn't actually dropping the potions?

**Comment by Gegy** [comment]
`setCount` only updates the count client-side. You'll want to use `ItemBag#removeItem`

**Comment by scprotz** [comment]
Works.  Thanks.
