### ISSUE TITLE
Missing PokemonFamilyId for Smoochum(Jynx)

### ISSUE THREAD

**Issue by scprotz** [Grover-c13/PokeGOAPI-Java#837]
I got some Smoochum pokemon and tried to check their family (Jynx) but it comes back as NullPointerException (guessing it hasn't been added to Protobuf yet).

**Comment by Gegy** [comment]
What version of the API are you using?

**Comment by scprotz** [comment]
I downloaded and built from github just a couple days ago, but using the default that gradle built (PokeGOAPI-library-all-0.4.1.jar).

**Comment by clangdev** [comment]
Could you please post a snippet where you try to query the family?

**Comment by scprotz** [comment]
`private static void listPokemon(PokemonGo go) throws RemoteServerException, CaptchaActiveException, LoginFailedException
	{
		List<Pokemon> pokemons = go.getInventories().getPokebank().getPokemons();

		for (Pokemon p : pokemons)
		{
			String id = p.getPokemonId().toString();

			try
			{
				if (p.getPokemonId() == PokemonId.SMOOCHUM)
				{
					System.out.println("Family of smoochum: " + p.getPokemonFamily());
				}
			}
			catch (Exception e)
			{
				System.out.println("Problem with: " + id);
				e.printStackTrace();
			}
		}
	}`

This throws a Java NPE  (I do have 2 smoochums in my inventory)

**Comment by Gegy** [comment]
Does this still occur?
