### ISSUE TITLE
Gym Battle is not working !!

### ISSUE THREAD

**Issue by Animeshm77** [Grover-c13/PokeGOAPI-Java#839]
Defender doesnt get swapped after first defender pokemon ...it shows new defender as MISSINGNO.
and battler never ends.

**Comment by Gegy** [comment]
Will need to make a MITM log of a battle with multiple defenders.

**Comment by scprotz** [comment]
I tried to use the sample application a (build on Jan 5) and got the same issue.  Is this still a problem?  It would be nice to have bot that can gym battle.

Is there some way to set up a MITM the inspect the traffic to see what the client is saying to the server or would we have to sign up for some kind of hosted hash to do that now?

**Comment by Gegy** [comment]
No, you don't have to sign up for anything, but you'd have to put in a lot of work to remove the certificate pinning.

**Comment by bobkubista** [comment]
Any progress on this? How can I help on this one?

**Comment by Animeshm77** [comment]
Issue is not solved yet !! reopen it please.

**Comment by RebliNk17** [comment]
Will fix it soon. We now have all the details we need to fix it

**Comment by oujinlong** [comment]
is it fix now?
