### ISSUE TITLE
LegacyHashProvider VS PokeHashProvider

### ISSUE THREAD

**Issue by gdespres** [Grover-c13/PokeGOAPI-Java#842]
**Description:**

Will "LegacyHashProvider" implementation continue to work or will need to proceed to PokeHashProvider implementation.

What's the difference ?

**Version:**
0.4.1

**Comment by Gegy** [comment]
`LegacyHashProvider` runs the free, local hasher, while `PokeHashProvider` requires a paid key and is done on the pokehash servers. `LegacyHashProvider` is using the 0,45 hash, which is outdated, so if you use it Niantic knows you are not a real player and have no problem with banning that account. `PokeHashProvider` runs on the latest 0.51 hash, which could result in a 100% drop in captchas if done right and if using it, Niantic can not know you are not a real player.

**Comment by gdespres** [comment]
Thanks ;-)
