### ISSUE TITLE
Can't remove pokemon from pokedex after successful encounter

### ISSUE THREAD

**Issue by scprotz** [Grover-c13/PokeGOAPI-Java#843]
So I am using the CatchPokemonAtAreaExample.  I tried to add a small bit of code to look through the pokedex and remove it after a successful encounter, but it appears the Pokemon is not yet in the pokedex at that point.

How do I remove a pokemon after a successful encounter (I caught it)?   Should I cache the pokemon id somewhere and then try later? 

if I try the following, the pokemon isn't found:

`Pokemon p = go.getInventories().getPokebank().getPokemonById(encResult.getPokemonData().getId());
`

(This assumes a CATCH_SUCCESS)

Thanks

**Comment by RebliNk17** [comment]
Are you using the gradle to import 0.4.1? 
If so, that is why... 0.4.1 is a very old jar which not sending requests as needed...

**Comment by scprotz** [comment]
I built using gradle (and it appears to be 0.4.1 jar).  How do a I build a newer jar with support?

**Comment by RebliNk17** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/blob/Development/README.md

**Comment by scprotz** [comment]
So i updated to 0.4.7.  Still same issue.  When I use the encResult.getPokemonData().getId() and search the pokebank, it is still returning a null.  Any other suggestions?

**Comment by scprotz** [comment]
Just one more comment.  I actually tested, and at the point of capture, the pokemon has not been entered into the pokebank (so no real way to 'remove' them from the pokebank).  Is this just an Async issue where I need to wait a bit for the pokemon to make it into the pokebank before removing them?

**Comment by scprotz** [comment]
Yeah, so this must just be a timing issue.  I stored the encResult.getPokemonData in a List while I'm catching pokemon.  Later, after setting a location point again, I check the pokebank for those pokemon based on their PokemonData and they are there, so I remove them at that point.

I'll leave this one up for a bit in case someone has a better solution, otherwise will close it after a day.

**Comment by scprotz** [comment]
Closing this issue.  It appears you must wait after encounter to do the transfer (as stated in the above comment).  My recommendation is to just store the PokemonData in a list and later just search through pokebank and 'transfer' any pokemon you don't wont from the list.
