### ISSUE TITLE
Getting 3 captcha URLs on startup.  Which is the right one?

### ISSUE THREAD

**Issue by scprotz** [Grover-c13/PokeGOAPI-Java#844]
So, even though my bot acts very 'human-like' most of the time, after a while, I eventually trigger a captcha.  Sometimes the JavaFX scene that hosts the captcha URL doesn't fire (seems like a bug from the example code or a problem with JavaFX), but on those occasions when I restart my bot, I get 3 captchas back-to-back.  I wrote a simple snippet to test this, and on just a basic auth, I get 3 captchas.  Is there a way to limit it to one? I'm still trying to read through the code to understand where the captchas are being triggered.  Here is my sample code to recreate (with a bot that has been 'captcha-ed'

`		// Set up OkHTTP to talk to Pokemon Server //
		OkHttpClient http = new OkHttpClient();

		// Create a pokemon go player called 'go' //
		PokemonGo go = new PokemonGo(http);

		go.addListener(new LoginListener()
		{
			@Override
			public void onLogin(PokemonGo api)
			{
				System.out.println("Successfully logged in!");
			}

			@Override
			public void onChallenge(PokemonGo api, String challengeURL)
			{
				System.out.println("Captcha received! URL: " + challengeURL);
			}
		});

		// Create a set of username and password //
		CredentialProvider auth = new PtcCredentialProvider(http, USERNAME, PASSWORD);
		go.login(auth);`

**Comment by Gegy** [comment]
I see you're on an older version of the API, try build from the latest source-code and see if the problem still occurs.

**Comment by scprotz** [comment]
Thanks.  I checked and my source was 2 weeks old.  What a difference 2 weeks makes.

**Comment by scprotz** [comment]
Moving this to a new thread:

I changed to the new version of the API but am getting this very regularly:

com.pokegoapi.exceptions.RemoteServerException: A bad request was sent!
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:244)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:366)
	at java.lang.Thread.run(Thread.java:745)


Any ideas?

**Comment by Gegy** [comment]
As the name suggests, you are sending bad requests to server. From which messages are these being thrown?
