### ISSUE TITLE
Updated to new API on Jan 5.  Getting RemoteServerException

### ISSUE THREAD

**Issue by scprotz** [Grover-c13/PokeGOAPI-Java#845]
After running my bot for about 5 minutes I get the following:

I changed to the new version of the API but am getting this very regularly:

`com.pokegoapi.exceptions.RemoteServerException: A bad request was sent!
at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:244)
at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:366)
at java.lang.Thread.run(Thread.java:745)
`
Any ideas?

There doesn't seem to be a way to recover from it because the exception is trapped inside the API and doesn't get surfaced to my code.  Any ideas?

I just rebuilt my jar last night (Jan 5) with the current snapshot in github.

**Comment by scprotz** [comment]
Ok, so a way to handle it - the new API does throw the RemoteServerException (just not obvious).  I just wrapped the whole app in a try/catch and essentially restarted the auth/login if it happens. seems to work ok.

**Comment by RebliNk17** [comment]
That's not the answer for that.
Try and catch are for exceptions that you want to receive.
but the "RemoteServerException: A bad request was sent!" is something that you don't want!
Maybe you caught that exception but the problem still occur,
some request is sent not in the correct way...
