### ISSUE TITLE
Cannot access to captcha link at second time in one login

### ISSUE THREAD

**Issue by vokhanhhuy** [Grover-c13/PokeGOAPI-Java#848]
Description
It seems we cannot open the Captcha link more than 1 time in LoginListener. Firstly, I make a GET request to Captcha URL, then get and send GoogleKey(data-sitekey) to other service for resolving Captcha and get back the Token, then I'll use that Token for api.verifyChallenge(Token) function.When i call api.verifyChallenge(Token) function, it hangs forever without any behaviors.
I have tried to open that link with WebView instead of calling api.verifyChallenge(Token) function after making a GET request to Captcha URL, a blank page appeared.

Any explanation or recommendation?

Version: 0.4.1 latest code from Development branch up to now

Thanks.

**Comment by RebliNk17** [comment]
Yes. There are few problems with the listener,  I've found that today. I will Debug it maybe next week and send PR. 
I fixed it on my project but I had to change lots of things to fit my project...
