### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by extsoft** [Grover-c13/PokeGOAPI-Java#849]
**Description:**
Unable to log in.

**Steps to reproduce:**

1. I try to execute the following code:
```
            OkHttpClient httpClient = new OkHttpClient();
            PokemonGo go = new PokemonGo(httpClient);
            go.login(new GoogleUserCredentialProvider(httpClient, "token"));
            return go.getInventories().getPokebank().getPokemons();
```

**Expected behavior:**
Have a list of pokemons.

**Actual behavior:**
Got Exception.

**Stacktrace (If it's a crash):**
```
Exception in thread "main" java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at POGOProtos.Enums.PokemonIdOuterClass$PokemonId.getNumber(PokemonIdOuterClass.java:1239)
	at com.pokegoapi.api.inventory.Pokedex.add(Pokedex.java:41)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:160)
	at com.pokegoapi.api.PokemonGo.fireRequestBlockOne(PokemonGo.java:212)
	at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:168)
	at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:164)
```

**Version:**
    `compile 'com.pokegoapi:PokeGOAPI-library:0.4.1'`

**Comment by RebliNk17** [comment]
which version are you using?

**Comment by extsoft** [comment]
version is 0.4.1

**Comment by RebliNk17** [comment]
That is the problem.
0.4.1 is an old jar
Compile using the updates files this github.
read instructions in the ReadMe.

**Comment by extsoft** [comment]
@RebliNk17 thank you! Will try.

**Comment by Gegy** [comment]
Did you try this, is this still occurring?

**Comment by 94929** [comment]
@RebliNk17 What is the most recent version of the API? It seems that 0.4.1 is the most latest one according to the readme.md.

> [ ![Download](https://api.bintray.com/packages/grover-c13/maven/PokeGOAPI/images/download.svg) ](https://bintray.com/grover-c13/maven/PokeGOAPI/_latestVersion)

**Comment by extsoft** [comment]
It isn't relevant anymore.

**Comment by Gegy** [comment]
You should build from the latest source.

**Comment by 94929** [comment]
@gegy1000 Thanks for your reply, I will try that :)
