### ISSUE TITLE
checkpoint checkin

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#85]
Hello,

i am having trouble on understanding how i can checkin on a particular checkpoint that i found on map.

can someone point me on the right direction?

Also, there is a place with docs, like a wiki or such?

**Comment by jabbink** [comment]
https://github.com/jabbink/PokemonGoBot/blob/master/src/main/kotlin/ink/abb/pogo/scraper/Main.kt#L221
