### ISSUE TITLE
No way to "logout" without shutting down the app

### ISSUE THREAD

**Issue by scprotz** [Grover-c13/PokeGOAPI-Java#850]
Maybe I missed this somewhere, but I am trying to figure out how to log out (or at least shut down all the processes related to the PokeGOAPI) when I'm done with a task, but still keep the App up and running.

Any ideas on this on how to perform a logout?  I'll try to run it through the debugger - I'm guessing there is some hidden thread that is in a nice while loop and not exiting.

**Comment by RebliNk17** [comment]
I don't think that there is an option for that.

**Comment by RebliNk17** [comment]
It is possible now.
`go#exit();`
will do what you want
