### ISSUE TITLE
Got 2 (very long) bans from the bot today using lightly modified examples.

### ISSUE THREAD

**Issue by scprotz** [Grover-c13/PokeGOAPI-Java#852]
Not sure if anyone else has run across this, but 2 accounts I use regularly were banned last night/early this morning.  They were doing the following loop:  walk a path between pokestops (based on pokestop sample), wait for update, check pokemon/catch all pokemon (based on sample), clean up inventory (some of my own code, but very simple inventory checks).

Not asking anyone to fix it, but just to see if others are experiencing this since the new update came out...and yes, I'm still using LegacyHashProvider with most current codebase as of last week.

**Comment by RebliNk17** [comment]
They could be banned from previous use...

**Comment by Gegy** [comment]
They were probably banned because this API is still using 0.51, or possibly you were using 0.45.

**Comment by clangdev** [comment]
One of my accounts got banned, too. Don't know exacty since when, but I discovered it yesterday (sunday) and I believe I last logged in succesfully on friday.
I used my bot the last time in the beginning of last week (monday?). I took care of not updating my original client to 0.53, but looks like.. it had no use.
I used API 0.51 with HASH-Key.
Mailed Niantic support for an unban request. let's see what happens.

**Comment by scprotz** [comment]
I'm just letting mine sit.  My ban was about 24 hours before I originally posted (so now 2 days).  Let me know how your unban goes.  I checked and my accounts still exist on pokemon trainer club.  Just can't log in with them to the game, or if it does log in, gives me the infamous "failed to get game data from the server" message.  Someone on a forum elsewhere suggested that they could be either ready for a perma-ban and just waiting for the sweep, or they might get unbanned after some time period (like 3 days).  After 3 days, I may request an unban.

**Comment by Gegy** [comment]
@scprotz which hash were you using?

**Comment by clangdev** [comment]
I was using 150RPM Hash advertised on this site: https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

**Comment by Gegy** [comment]
If you used it since 0.53 was forced, that explains the problem. Your app should check the minimum required version, and not run if you are on a lower version than the forced version.

**Comment by clangdev** [comment]
Honestly, I am not sure and I don't know the datetime when 0.53 was forced.
Would be nice if the API could check for the minimum required version :-)

**Comment by scprotz** [comment]
@gegy1000 as stated above, I was still using the Legacy (I think it is 0.47 but worked fine other than lots of captchas).  Accounts still blocked today.  Guessing they are perma-banned, but no indication from Niantic that this is so.
