### ISSUE TITLE
token refresh exception on login

### ISSUE THREAD

**Issue by bobkubista** [Grover-c13/PokeGOAPI-Java#855]
**Description:**
When I try to login using the latest sources, I get a LoginFailedException

**Steps to reproduce:**

1. Login using LegacyHashProvider and PTC login

**Expected behavior:**
logged in

**Actual behavior:**
LoginFailedException thrown

**Stacktrace (If it's a crash):**
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?

**Version:**
latest self compiled sources, not changed

**Comment by robisaks** [comment]
Possibly related, but when I attempt to login using LegacyHashing it never returns.

I call the following
`HashProvider hasher = new LegacyHashProvider();`
`api.login(new PtcCredentialProvider(http, username, password), hasher);`
`Log.i("TEST", "setLocation");`

It logs
`D/RequestHandler: Authenticated with static token`

But never reaches setLocation.

edit: I should also mention, that it seems to work once, on a fresh account, but then successive attempts to login don't return.
