### ISSUE TITLE
Please add support for latest pokehash api (0.55)

### ISSUE THREAD

**Issue by clangdev** [Grover-c13/PokeGOAPI-Java#857]
As far as i can see there is still only pokehash api 0.51 supported, but 0.55 is released already.
Please add support for latest (paid) hash service.

Edit: Just noticed https://github.com/gegy1000/PokeGOAPI-Java has already done the work. thank you very very much. 

Hopefully captchas will be gone by this update.

**Comment by Gegy** [comment]
https://github.com/Grover-c13/PokeGOAPI-Java/commit/0d611b746b11f1ddff6c9a7a5f3e0b56d16c3b22
