### ISSUE TITLE
Build from source (Update to 0.55) failed

### ISSUE THREAD

**Issue by vagprogrammer** [Grover-c13/PokeGOAPI-Java#858]
Hi everyone! some one can help me please.

Description:
I can't build from source with the last API changes (Update to 0.55)

Steps to reproduce:
* Clone the repo and cd into the folder
* git submodule update --init
* ./gradlew :library:build

Then i get this error:

![captura de pantalla 2017-02-10 a las 10 56 04 a m](https://cloud.githubusercontent.com/assets/803683/22836089/b2bb4eb8-ef80-11e6-8fc0-90b47fa5a425.png)

![captura de pantalla 2017-02-10 a las 10 56 19 a m](https://cloud.githubusercontent.com/assets/803683/22836098/ba544fb2-ef80-11e6-853a-1fb38ce159c8.png)

Thanks in advance.

**Comment by Gegy** [comment]
Just merged a fix.
