### ISSUE TITLE
catch pokemon doesn't work

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#86]
Hello,

i have try this little piece of code to try to catch pokemon on my area.
distance return meters of distance from go.getLat/lon to pokemon.getLat/long with all
the supposed radiant sin cos stuff.

i check that the pokemon it's close to the current location, but catchResult return always fail.
on log i can see some json running around (probably a sleep will be better)

it's not working right now or i am doing something of wrong?

```
 Collection<CatchablePokemon> pokemons = go.getMap().getCatchablePokemon();
            for (CatchablePokemon pokemon : pokemons) {
                if (distance(go,pokemon) <0.5) {
                    for (int i = 0;i<10;i++) {
                        CatchResult r = pokemon.catchPokemon();
                        if (r.isFailed())
                        {
                            dbg("fail");
                        }
                    }
                }
            }

```

**Comment by jabbink** [comment]
You have to encounter the Pokemon first, or you are soft banned.

https://github.com/jabbink/PokemonGoBot/blob/master/src/main/kotlin/ink/abb/pogo/scraper/Main.kt#L186
