### ISSUE TITLE
Cannot update nearby pokemons

### ISSUE THREAD

**Issue by 94929** [Grover-c13/PokeGOAPI-Java#862]
**Description:**
After changing current location of the player, it doesn't seem to update catchable pokemons nearby.

**Steps to reproduce:**

1. Changed current location of the player(i.e. from home to dest location).
2. Tried to get nearby pokemons by 'go.getMap().getMapObjects().getPokemon()'.

**Expected behavior:**
[What should happen?]

1. 'go.getMap().getMapObjects().getPokemon()' should return Set\<CatchablePokemon\> which represent nearby pokemons.

**Actual behavior:**
[What actually happens]

1. It does return Set<CatchablePokemon> but contains pokemons in previous location(home location) not updated location(dest location).

**Version:**
[The version of the lib you used]
0.4.1

**Comment by RebliNk17** [comment]
it update every 10 seconds.
also i hope your are not using the gradle version...

**Comment by 94929** [comment]
@RebliNk17 Thanks for your reply, and yes I waited for 15 seconds after I changed my location but still no luck.

**Comment by RebliNk17** [comment]
which version?

**Comment by 94929** [comment]
@RebliNk17 Jar version 0.4.1. Btw is there any issue with gradle version?

**Comment by RebliNk17** [comment]
what jar?
jar that you created?

**Comment by 94929** [comment]
@RebliNk17 The jar created with 'build from source' in readme.md. I just followed 'build from source' instruction there.

**Comment by RebliNk17** [comment]
Ok, it should work, i don't know why it's happening to you...
maybe @gegy1000 will know.
The gradle version is out-dated...

**Comment by 94929** [comment]
@RebliNk17 Thanks for your support. I have one last question. Is PokeGOAPI-library-all-0.4.1.jar up-to-date?

**Comment by Gegy** [comment]
`go.getMap().awaitUpdate()`

**Comment by 94929** [comment]
@gegy1000 I tried 'go.getMap().awaitUpdate()' and 'TimeUnit.SECONDS.sleep(15)' but none of them worked :(

**Comment by 94929** [comment]
Actually the issue happens irregulary, sometimes work(updates nearby Pokemons at new location) and sometimes don't.
