### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by jeremys18** [Grover-c13/PokeGOAPI-Java#872]
I'm using ver. 0.4.1 and have been able to log in before but now I can't. When I try it throws an "Unknown Exception". Am I doing this right?

I have a refresh token and use this to log in:

OkHttpClient httpClient = new OkHttpClient();
GoogleProvider = new GoogleUserCredentialProvider(httpClient);
pokemonGo = new PokemonGo(httpClient);
pokemonGo.login(new GoogleUserCredentialProvider(httpClient, access));

And when that fails I ask the user to reauth. the app with a new google token and log in using:

GoogleProvider.login(access);
pokemonGo = new PokemonGo(httpClient);
pokemonGo.login(GoogleProvider);
return GoogleProvider.getRefreshToken();

I would expect if the first failed the second would pass since I'm using a brand new token but instead it throws an exception for both.

I'm not doing anything fancy. I simply want to log in using the refresh token, so I don't have to ask for auth. every time, and get a list of the users current pokemon. That's it. No gameplay, nothing. Just get their pokemon info.

Here's the stack trace:

W/System.err: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
W/System.err:     at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
W/System.err:     at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:103)
W/System.err:     at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:88)
W/System.err:     at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:160)
W/System.err:     at com.pokemongotrader.js.pokemongotrader.MyPokemonActivity$LoginAndSetRefreshToken.doInBackground(MyPokemonActivity.java:248)
W/System.err:     at com.pokemongotrader.js.pokemongotrader.MyPokemonActivity$LoginAndSetRefreshToken.doInBackground(MyPokemonActivity.java:226)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
W/System.err:     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
W/System.err:     at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
W/System.err:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
W/System.err: 	... 12 more
W/System.err: Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
W/System.err:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
W/System.err:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
W/System.err:     at rx.Observable.subscribe(Observable.java:9957)
W/System.err:     at rx.Observable.subscribe(Observable.java:9924)
W/System.err:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
W/System.err: 	... 14 more
W/System.err: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
W/System.err:     at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
W/System.err:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
W/System.err: 	... 1 more

**Comment by Gegy** [comment]
We are currently working on fixing this. For now, your best option is to build from my fork where things are partially working.

**Comment by Gegy** [comment]
Login is now properly working on my fork.
