### ISSUE TITLE
Support for newly implemented berries in CatchOptions (0.57.2)

### ISSUE THREAD

**Issue by Gegy** [Grover-c13/PokeGOAPI-Java#879]
The current CatchOptions only support razzberries, but should also support usage of pinap and nabab berries.

**Comment by RebliNk17** [comment]
The current catchOptions shouldn't have support razzberry in the first place...
RazzBerry should be thrown by ``catchablePokemon.throwrazzBerry()`` and not by the catchOptions.
Will commit something later today.
