### ISSUE TITLE
Any way to check whether Client API version is compatible to minimum accepted server version?

### ISSUE THREAD

**Issue by clangdev** [Grover-c13/PokeGOAPI-Java#882]
Hi all,
just a question if there is any way to check if current used Java-Api is compatible with PoGo Server verision.
Any way to check that before starting queries with outdated/forbidden API and risking a ban?

Regards,
Christian

**Comment by Raventy** [comment]
Send a HTTP GET request to https://pgorelease.nianticlabs.com/plfe/version

It will response 0.57.2

**Comment by clangdev** [comment]
Thank you. 
Looks like the way to go. Would it be an option to integrate this check to the api?
But therefore we would need the minimum API-Version, not the current.

**Comment by Raventy** [comment]
Although not very accurate, we may make use of the version # in PokeHashProvider.java for API version checking:

// This means 0.55
private static final int VERSION = 5500;
