### ISSUE TITLE
[Discussion] The parameters to generate CATCH_MISSED when catching pokemon

### ISSUE THREAD

**Issue by Raventy** [Grover-c13/PokeGOAPI-Java#884]
Currently, the default CatchOptions are optimized that would produce "CATCH_SUCCESS", "CATCH_ESCAPE" and "CATCH_FLEE", I wonder what are the settings that would produce a "CATCH_MISSED"?

Say if I accentially touch the screen, the pokeball rolls out but does not touch the wild pokemon, it should be a "CATCH_MISSED" right? I want to reproduce this programmatically.

**Comment by RebliNk17** [comment]
Currently you can't. The ball always hit the pokemon. 
I am working on a new catch system.

**Comment by Raventy** [comment]
RebliNk17 Thank you for your prompt reply.

**Comment by RebliNk17** [comment]
You shouldn't have close this.
this is still something that need to be done.

**Comment by s7092910** [comment]
Reopened

**Comment by RebliNk17** [comment]
@s7092910 I have a temporary new catch system (until api 2.0 will be out) push it here or to gegys repo?

**Comment by s7092910** [comment]
@RebliNk17 gegys repo

**Comment by Gegy** [comment]
A new catch system has been implemented, see the CatchPokemonAtAreaExample for further details.
