### ISSUE TITLE
API version 0.57.4 no longer works today on 2017-03-07

### ISSUE THREAD

**Issue by tommywuhaojie** [Grover-c13/PokeGOAPI-Java#887]
Niantic has updated their API again which caused login problem even with valid hash key with api end point api/v127_4/hash

I am using repo from https://github.com/gegy1000/PokeGOAPI-Java

![error](https://cloud.githubusercontent.com/assets/12468911/23687513/b2240c96-0363-11e7-854e-5abb698f46e0.PNG)

**Comment by s7092910** [comment]
API 0.57.4 hashing and static values hasn't been implemented yet.

Closed as issue #885 is for updating the library to use the 0.57.4 hashing and static values.
