### ISSUE TITLE
Failed build from source.

### ISSUE THREAD

**Issue by BaronNox** [Grover-c13/PokeGOAPI-Java#888]
**Description:**
Gradle failed to build from source on win10 on UNIX I got no errors:
For users who want to import the api into Eclipse IDE, you'll need to :

I.
    build once : ./gradlew :library:build
    Right click on the project
    Select Build path > Configure Build Path > Source > Add Folder
    Select library/build/generated/source/proto/main/java
    Finish
II.  
    Clone the repo and cd into the folder
    git submodule update --init
    ./gradlew :library:build
    you should have the api jar in library/build/libs/PokeGOAPI-library-all-0.X.X.jar
        (0.X.X refers to the version number provided in the JAR filename, ie. 0.3.0)

**Steps to reproduce:**

1. Run the instructions from https://github.com/Grover-c13/PokeGOAPI-Java under build from src

**Expected behavior:**
No crash.

**Actual behavior:**
For I: http://pastebin.com/nhdg0ue6
For II: Crash
**Stacktrace (If it's a crash):**
For I: http://pastebin.com/nhdg0ue6
For II: Execution failed for task ':library:generateProto'.
> java.io.IOException: Cannot run program "C:\Users\BaronNox\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.0.0-beta-3\71e76cad4f9b30aab172c44035d343c5bab47815\protoc-3.0.0-beta-3-windows-x86_64.exe": CreateProcess error=206, The filename or extension is too long
**Version:**
0.4.1

**Comment by marcelohenrique** [comment]
That problem was solved to me when I executed "git submodule update --init" command.

**Comment by Gegy** [comment]
You need to put the API folder closer to your root directory, because windows has a filename length limit.

**Comment by RebliNk17** [comment]
Or install python, 
https://www.python.org/
Follow the installation screen and search for "Disable command line char limits" or something like that, and make sure it's checked.

**Comment by BaronNox** [comment]
I built it on my UNIX machine in the meantime where it worked without problems.
Thanks for the answers though :)
