### ISSUE TITLE
The Pokebank is not updated after catching a pokemon

### ISSUE THREAD

**Issue by szgyula0923** [Grover-c13/PokeGOAPI-Java#896]
The Pokebank is not updated after catching a pokemon.
A week ago it worked...
Try out the example (CatchPokemonAtAreaExample.java)

**Comment by oujinlong** [comment]
use updateInteventories after catching

**Comment by RebliNk17** [comment]
Or even better
just send Ninatic a message that you are using a 3rd party application...
it will be easier...

updateInteventories after catching a pokemon is a RED FLAG!!

use update inventory listener....


You should never send a Common request as a regular request... so just don't do that...

**Comment by szgyula0923** [comment]
even after updateInventories does not work, i need relog to update...

RebliNk17: Thx for help...

**Comment by szgyula0923** [comment]
It work again lol??? :D
