### ISSUE TITLE
from where can i pull a build?

### ISSUE THREAD

**Issue by davidgwking** [Grover-c13/PokeGOAPI-Java#909]
It looks like the most recent release on jcenter is 0.4.1.

Unless I'm mistaken, this looks like an outdated build (the version that I pulled doesn't even support hashing). Is there a more recent repository push available?

**Comment by Gegy** [comment]
Yes, you will need to build from the API source

**Comment by AbandonedCart** [comment]
Once the version number is updated, a new build can be pushed.
