### ISSUE TITLE
Duplicate file exception

### ISSUE THREAD

**Issue by coder04** [Grover-c13/PokeGOAPI-Java#924]
Hi whenever i try to run my app i get this error

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK AUTHORS
	File1: C:\Program Files\Android\Android Studio\gradle\m2repository\com\android\tools\external\lombok\lombok-ast\0.2.3\lombok-ast-0.2.3.jar
	File2: C:\Program Files\Android\Android Studio\gradle\m2repository\com\android\tools\external\lombok\lombok-ast\0.2.3\lombok-ast-0.2.3.jar

**Comment by AbandonedCart** [comment]
Your app has a duplicate file in APK AUTHORS. 
There are two copies of lombok-ast-0.2.3.jar in your project.
Find out why you have two and remove one.

Closing this, since it's unrelated to the library.
