### ISSUE TITLE
Cannot Login via oAuth - HashException

### ISSUE THREAD

**Issue by halsafar** [Grover-c13/PokeGOAPI-Java#926]
com.pokegoapi.exceptions.request.RequestFailedException: com.pokegoapi.exceptions.request.HashException: Could not verify your authentication details (2)!

Do we really need a legit Hashing service just to login?  I only ever intend to issue a login and get the Pokebank, nothing more.  Is this no longer possible.  I've been out of the loop for 9 months.

**Comment by Gegy** [comment]
Yes, every request requires a signature with hashes.
