### ISSUE TITLE
#937

### ISSUE THREAD

**Issue by sonvuhung** [Grover-c13/PokeGOAPI-Java#937]

**Comment by Gegy** [comment]
Should be resolved with #938, can you test this?

**Comment by Tommy-Emmanuel** [comment]
@gegy1000 : I tested but #938 gradle build **FAIL**! Please recheck or guide me build. Thanks.

"FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':library'.
> No signature of method: org.gradle.api.internal.tasks.DefaultTaskInputs.source() is applicable for argument types: (com.google.protobuf.gradle.ProtobufSourceDirectorySet_Decorated) values: [main Proto source]
  Possible solutions: collect(), use([Ljava.lang.Object;)"

**Comment by sonvuhung** [comment]
#938 works! Thank you very much 👍
