### ISSUE TITLE
getMapObjects doesn't return all objects (pokestop)

### ISSUE THREAD

**Issue by ramarro123** [Grover-c13/PokeGOAPI-Java#95]
it's correct to do

while (true) {
go.setLocation(lat, long, h);
go.getMap().getMapObjects(1);
lat+=SOMETHING;
long+=SOMETHING;
}

i am not getting all the results from getPokestops, and i am sure of that cos i am testing on the same area :)

**Comment by Grover-c13** [comment]
There is a caching & last update check to reduce the request, try setUseCache and setTrackUpdate to false and see how it goes

**Comment by Grover-c13** [comment]
Any updates @ramarro123

**Comment by ramarro123** [comment]
in a short while :) 

to test this one i have to go outside ;) hehehe

**Comment by ramarro123** [comment]
work for me, tnx!
