### ISSUE TITLE
API doesn't work

### ISSUE THREAD

**Issue by arao99** [Grover-c13/PokeGOAPI-Java#954]
**Description:**
I couldn't use this API.
I'm unconfident about how to use this API, so I'll tell you commands I did.
If it was wrong, please tell me how to use this API.

**Steps to reproduce:**
$ git clone git@github.com:Grover-c13/PokeGOAPI-Java.git
$ cd PokeGOAPI-Java
$ git submodule update --init
$ ./gradlew :library:build
$ vi build.gradle
and add...
```
dependencies {
  compile fileTree(include: ['PokeGOAPI-library-all-*.jar'], dir: '!!MY_PATH!!/PokeGOAPI-Java/library/build/libs')
}
```
$ vi sample/src/main/java/com/pokegoapi/examples/ExampleConstants.java
and add...
```
public static final String LOGIN = "MY_POKEMON_ID";
public static final String PASSWORD = "MY_POKEMON_PASSWORD";
...
public static final String POKEHASH_KEY = "!!MY_POKEHASH_KEY!!";
```
$ gradle sample:run

**Actual behavior:**
```
D/RequestHandler: Authenticated with static token
E/Main: An exception occurred while running example: 
com.pokegoapi.exceptions.request.RequestFailedException: com.pokegoapi.exceptions.request.HashException: Failed to perform PokeHash request
```

**Version:**
0.4.1

Thank you.

**Comment by Furtif** [comment]
api is off sorry
