### ISSUE TITLE
Failed to perform PokeHash request Error

### ISSUE THREAD

**Issue by badbones69** [Grover-c13/PokeGOAPI-Java#957]
**Description:**
I keep getting a strange error when trying to load the API and login.

**Steps to reproduce:**
I saved the refresh token to a data file so thats what the get string is.
Code:
https://pastebin.com/yUS1C8eA

**Stacktrace (If it's a crash):**
https://pastebin.com/euwCQaiE

**Version:**
Build version from 11/11/18.

**Comment by Furtif** [comment]
all right 👍 hash is still off..

**Comment by badbones69** [comment]
@Furtif Is it an issue on my end or yours as it still shows for me with the newest pull I just did today.
