### ISSUE TITLE
Does this library still working?

### ISSUE THREAD

**Issue by vagprogrammer** [Grover-c13/PokeGOAPI-Java#958]
**Description:**
Hello everyone :) 
Is just a question, I have been followed this library for a long time and i have noticed that is frecuently update, but I'm not sure if we can still using it, currentñy there is not an API hashing service that allow us to use it, so is there any reason to have this library updated? 

**Version:**
The last version updated

cc @Grover-c13 @gegy1000 @Furtif

**Comment by AbandonedCart** [comment]
Is there any reason not to have it updated?

**Comment by vagprogrammer** [comment]
@AbandonedCart Currently there is no way to use it, so why keep it updated? I'm not sure if if there is way to use it, if yes i really want to know it.

**Comment by AbandonedCart** [comment]
@vagprogrammer The library is presented as a means to understand the inner workings of the service, but use of it violates the terms of service. While the "added bonus" of being useful as a third party means to interact with the service may not always be possible, updating eliminates any possibility that there would be a delay when functionality returns. So, to better phrase the point of my question, is there some detriment to you by updating it?

Also, there is no need to tag the entire team to reply to one person directly. All contributors are automatically notified of every post, in addition to any other visitors that subscribe or reply.

**Comment by AbandonedCart** [comment]
Since it appears there is not an actual issue here, I am going to close this one as "discussion"
