### ISSUE TITLE
Nearby pokemons all at 200 meters ?

### ISSUE THREAD

**Issue by Paul776** [Grover-c13/PokeGOAPI-Java#97]
Trying the API and when I check the nearByPokemon it always says they are 200 meters away. Which is wrong as I can clearly a catchable poker just next to me.

Is this a bug of the server or the API ?

**Comment by mjmjelde** [comment]
From last I heard this is a bug in the server.  This is why when actually playing the game, the radar always shows 3 steps for all pokemon.

**Comment by vmarchaud** [comment]
If you use the method getCatchablePokemons() you might found pokemon that are defined as wild pokemons (3 steps in the apps) that you can capture with the client but not with the official game.

**Comment by jabbink** [comment]
NearbyPokemon are not in reach. Catchable pokemon are `CatchablePokemon` and `MapPokemon`.

And to (presumably) reduce server cpu load, they removed actual calculations of the `distance` and set it to `200m`.

**Comment by Paul776** [comment]
Thanks for the responses!

So with the current state of the API is there a way to retrieve the coordinate of pokemon that are not at reach?
(Im seeing couple of website project where it displays pokemon way further that the "catchable" area
How is that done? Is actually just the Catchable list ?

**Comment by mjmjelde** [comment]
Those website projects just change the location of the player and retrieves the catchable pokemon.  There really isn't a way other than that to get pokemon outside the reachable area

**Comment by Paul776** [comment]
Perfect  thanks
