### ISSUE TITLE
Google login without user intervention

### ISSUE THREAD

**Issue by jabbink** [Grover-c13/PokeGOAPI-Java#98]
Someone extracted a valid OAuth signature

https://github.com/AHAAAAAAA/PokemonGo-Map/blob/develop/pogom/pgoapi/auth_google.py#L33

**Comment by mmastika** [comment]
I believe it's just missing &access_type=offline in GoogleLogin.java:48, will test it tomorrow, whoops this is for the 30 mins issue?

**Comment by KyleBoyer** [comment]
Was there resolution on this? I know that the Python Pokemon Go bot manages to login without having to visit google.com/device at all.

**Comment by Grover-c13** [comment]
Yes, they use a gpsoauth library (google play services library), that "pretends" to be a phone logging into the server. There is no port to java currently and us doing it would be mean we would need to include a better crypto package to sign passwords, which adds overhead. I tried to port the library over today but could not get the password signing right.

**Comment by Aphoh** [comment]
I believe with the oauth callbacks this issue has been resolved.
